### ISSUE TITLE
report

### ISSUE THREAD

**Issue by ciceronero** [dragokas/hijackthis#10]
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/1534904/HiJackThis.log)

**Comment by dragokas** [comment]
Hi, ciceronero !

Thank you for the log.
Do you need any assistance?

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Comment by dragokas** [comment]
No answer for 10 days. Closed.
If you need to re-open your case, please, ask in PM to one of VIRUSNET members.
