### ISSUE TITLE
Stuttering computer when running heavy programs and games (Help wanted)

### ISSUE THREAD

**Issue by CobaltXXX** [dragokas/hijackthis#103]
I recently began having a problem where my computer would "stutter" when doing nothing and playing games. It was completely fine until I brought it back from a LAN party. I tried re-seating my graphics card, ram, cords, etc. Nothing fixed this issue, virus scanner didn't pick up anything, speccy didn't see any problems. I was recommended HijackThis to see if there were any problems. I don't know how to decipher these logs. Any help would be appreciated!
[hijackthis3.txt](https://github.com/dragokas/hijackthis/files/5111857/hijackthis3.txt)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog, and write what problems remained.
