### ISSUE TITLE
This task was not found by hijack

### ISSUE THREAD

**Issue by MrM40** [dragokas/hijackthis#104]
I get a very strange error in my evet log, that a program called "WSQLBackup.exe" is tried to be executed:

Event log:
```
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: WSQLBackup.exe
P2: 0.0.0.0
P3: 5be769ed
P4: KERNELBASE.dll
P5: 10.0.17763.615
P6: b6cb145b
P7: e0434352
P8: 0000000000039129
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7B9A.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_WSQLBackup.exe_db3ee4c422338eb677d1245efeb1a6fa4a31b639_0f345cdc_34ae7aee

Analysis symbol: 
Rechecking for solution: 0
Report Id: e57a9123-c7a3-4ed1-b16c-fe855b2630a1
Report Status: 4196
Hashed bucket: 
Cab Guid: 0
```

Something is trying to execute this program every 20 minute.
Tried searching for "WSQLBackup.exe" in registry but no hit.

It is a .Net program I've created myself and a ran it few times on this computer and then deleted the files (not installed, just potable).

Also tried to restart. Where and how can it be registered? Can it be registered in registry after all  in other ways than ascii/UTF, e.g base64 or something else?
Very strange.
Remembers Hijack from the old days and thought it could find it :-/

**Comment by dragokas** [comment]
Interesting.
Maybe, it is run indirectly. I can't tell you more without log.

Download and run Process Monitor from:
https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

 - Via Filter menu, select "Process Name" is "WSQLBackup.exe" (without quotes) => Add => Apply => OK.
 - Wait till the process has caught.
 - Double-click any record in Process Monitor:
1) Select "Process" tab => in "Path" field you can see where is your ghost application is actually located :)
2) next, remember the number in "Parent PID" field.
 - Press menu Filter => Filter, select the previously created rule => Remove, and let's create new rule:
 - "PID" is X, where X is a number, you remembered in step 2 => Add => Apply => OK.

You should see the name of process, responsible for the launching of your ghost :)

Please, come back to tell us about results ^^

**Comment by MrM40** [comment]
I don't think it will catch it.
First of all "WSQLBackup.exe" doesn't exist, has been delete long time ago.
Secondly I expect the process which is trying to execute it are closed immediately.
The question is rather, where is this task registered? 
One could imagine it was located in a Schedule Task but haven't been able to find it.

**Comment by MrM40** [comment]
What a paint to seach schedule tasks (which are both registered in registry and xml files in "c:\windows\tasks" and "c:\windows\system32\tasks".
You cannot use the console tool `findstr` as it doesn't support unicode.
So I had to:

1. Download  [sysinternals](https://docs.microsoft.com/en-us/sysinternals/downloads/strings) **strings** (which can read the  files)
2. Copy content of all task-files to one text-file:
    `strings -s "C:\Windows\System32\Tasks\*.*" > "c:\temp\Tasks.txt"`   
3. Open the file `"c:\temp\Tasks.txt"`  and do a manual search

But `WSQLBackup.exe` was not to be found :-(

**Comment by dragokas** [comment]
If WSQLBackup.exe doesn't exist, how do you able to see its crashing in event log.

Can you provide an export of your event log?

**Comment by dragokas** [comment]
It is possible that the process is located in another place such as when you publish it with VS.
Even if it doesn't exist at all, you can setup Process Monitor to catch run attempt:
Enter the rule: "Path" "contains" "WSQLBackup"

**Comment by MrM40** [comment]
Ahhh, nice, good idea! I'll try that :-)

**Comment by MrM40** [comment]
Unfortunately I don't get any hits :-(
The event show these detailts:

```
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: WSQLBackup.exe
P2: 0.0.0.0
P3: 5be769ed
P4: KERNELBASE.dll
P5: 10.0.17763.615
P6: b6cb145b
P7: e0434352
P8: 0000000000039129
```
I wonder if I could use any of these information to track down the source-process of the event. 
E.g. "P8: 0000000000039129" could be a process ID, but unfortunately it doesn't seem to be the case.

Got this form on of the saved report files (C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_WSQLBackup.exe_db3ee4c422338eb677d1245efeb1a6fa4a31b639_0f345cdc_cab_0c2295d4\WER9578.tmp.xml):
```
<cmd nm="event">
          <arg nm="cat" val="crash64" />
          <arg nm="app" val="WSQLBackup.exe" />
          <arg nm="appver" val="0.0.0.0" />
          <arg nm="applink" val="5be769ed" />
          <arg nm="mod" val="KERNELBASE.dll" />
          <arg nm="modver" val="10.0.17763.615" />
          <arg nm="modlink" val="b6cb145b" />
          <arg nm="ecode" val="e0434352" />
          <arg nm="offset" val="0000000000039129" />
          <arg nm="appsessionguid" val="00000f10-0002-002e-ef7f-81a40160d601" />
          <arg nm="targetappid" val="W:00062dabe808de30128b88d5ea218279cd6d0000ffff!0000d30f4b4c53f7c10b446f0dbb5c3be91b59231d16!WSQLBackup.exe" />
          <arg nm="targetappver" val="2018/11/10:23:29:49!0!WSQLBackup.exe" />
          <arg nm="targetasid" val="3797" />
          <arg nm="isfatal" val="1" />
          <arg nm="userimpactvector" val="0" />
        </cmd>
```

**Comment by MrM40** [comment]
Okay, I'll just reboot the server tonight....

**Comment by dragokas** [comment]
Attach Process Monitor log. I will look.
(File => Save => Format PML => OK)

**Comment by MrM40** [comment]
The mystery seem to be solved, although I still don't understand what really was going on.
Some weeks ago this application crashed, no big deal, and apparently Windows created a crash report and dump (some memory dump or whatever) in the folder C:\ProgramData\Microsoft\Windows\WER\ReportQueue\...
And for some reason Windows recreate this dump and crash-report about every 20-30 minutes, based on the previous files in the folder, and also create the mentioned event log.
After I deleted the files in this folder (reports and dump file) it all stopped! So there never was  a process or task after all, that's why I could find in the process monitor either. Weird!

**Comment by dragokas** [comment]
Glad to see it is solved. Anyway, if a similar problem will occur, you know how to identify it now.

Good luck.

**Comment by MrM40** [comment]
Yea, and sorry for the "noise"
I actually got a similar event log regarding a language pack, also looping, solved the same way.
I've create a StackExchange Superuser question/answer with both examples. Just for info.
