### ISSUE TITLE
Someone granted access to my network

### ISSUE THREAD

**Issue by ghost** [dragokas/hijackthis#105]
I have a 1GB plan with Vodafone. A few weeks ago I started to lose speed even when using Netflix, which never happened before.
When I tested my speed I reached 80Mbs download and 50Mbs upload. **That's not even 10% of my contracted speed.**

I called Vodafone support who changed my modem, password, etc. Days later support made some changes to my modem configuration and restarted it. They informed me that **5 devices (2 iPhones, 2 laptops and 1 unknown device)** were connected to my network.

I don't own iPhones and all my devices are named after me which makes identification easy. 
I changed all the passwords again, including the password that gives access to the modem settings. 

**In my Temp folder there is another folder called "frozen-genpy-27" which I can't delete even with the system administrator account.** 

I scanned the PC and nothing was found. 
[CollectionLog-2020.09.02-18.23.zip](https://github.com/dragokas/hijackthis/files/5163831/CollectionLog-2020.09.02-18.23.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

Did you install Brave Browser by yourself?
Even if so, uninstall it and also uninstall IObit Uninstaller 10.

Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by ghost** [comment]
Hi,

Yes, I installed Brave Browser and IObit too
Brave and IObit uninstalled
[AdwCleaner[S01].txt](https://github.com/dragokas/hijackthis/files/5167757/AdwCleaner.S01.txt)

**Comment by Sandor-Helper** [comment]
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by ghost** [comment]
Please see the logs attached.
[Addition.txt](https://github.com/dragokas/hijackthis/files/5168340/Addition.txt)
[FRST.txt](https://github.com/dragokas/hijackthis/files/5168341/FRST.txt)

**Comment by Sandor-Helper** [comment]
Log FRST.txt is not complete. Please get it again and before do this temporarily switch off any antivirus.
Also uninstal newly installed SUPERAntiSpyware, it is PUP.

**Comment by ghost** [comment]
Here you are
[Addition.txt](https://github.com/dragokas/hijackthis/files/5168734/Addition.txt)
[FRST.txt](https://github.com/dragokas/hijackthis/files/5168735/FRST.txt)

**Comment by Sandor-Helper** [comment]
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CreateRestorePoint:
GroupPolicy: Restriction ? <==== ATTENTION
AlternateDataStreams: C:\WINDOWS\system32\Drivers\wsddfac.sys:X5ZN8aGXs4 [2410]
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by ghost** [comment]
Done!
Anything else?

**Comment by Sandor-Helper** [comment]
> Program will create (Fixlog.txt). Attach it to the next post

Did you get it?

**Comment by ghost** [comment]
Ah! Sorry, I forgot to attach the log.
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/5177957/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
Is there any changes in your system?
There ara some corrections you have to made manually:
In the IE properties clean all of the IE restricted site and IE trusted site.
Not sure that this will solve the problem, but all these records are malicious.

Here link with details how to do this - https://support.microsoft.com/en-us/help/17479/windows-internet-explorer-11-change-security-privacy-settings

**Comment by ghost** [comment]
I have a Vodafone's technician coming over this Wed to check my internet. They sent me an App to my mobile phone that I will be warned if any alien device connect to my network. My Wi-Fi 5Ghz speed is 40MBps only and using cable too. 

So definitely, something is using my internet or there is some problem with the telephone cables because 40MBps is not 10% of my contracted speed.

**Comment by dragokas** [comment]
If you turn off wi-fi completely in the router settings and try to connect to the router directly by cable, will the speed become faster?

**Comment by ghost** [comment]
I tried but no. The speed connection today don't go above than 40Mbps.

**Comment by dragokas** [comment]
If you go to Device Manager - Network adapters - Select your ethernet device - Properties - Advanced - Speed & Duplex. What value is selected there?
![netw_speed](https://user-images.githubusercontent.com/19956568/92307194-30737b80-ef9d-11ea-8abb-a6f732ec6e3d.jpg)

How did you check the speed? Did you try another browser, e.g. Firefox? Try it and verify speed on this site: https://speed.cloudflare.com/ when you are connected via cable.

During the test, open Task Manager - Performance - Ethernet, wait a little bit after the tests are finished, and show us the screenshot of that window.

![eth](https://user-images.githubusercontent.com/19956568/92307257-a1b32e80-ef9d-11ea-89f8-662ec4269a72.jpg)

You don't have HiJackThis log in your collection for some reason. Can you make it separately:
Download https://dragokas.com/tools/HiJackThis_test.zip
Run, press "Do a scan and save a logfile" and attach HiJackThis.log

**Comment by ghost** [comment]
Here you are
[hijackthis.log](https://github.com/dragokas/hijackthis/files/5178335/hijackthis.log)

![image](https://user-images.githubusercontent.com/70641063/92309107-7da21e00-ef9a-11ea-98e6-867b17105f08.png)

**Comment by ghost** [comment]
Ah! About the first picture is the same settings in your pic Auto Negotiation

**Comment by Sandor-Helper** [comment]
Chrome:  63.0.3239.108 - it's a very old version. You should update it to actual one.

> How did you check the speed? Did you try another browser, e.g. Firefox?

Did you try already?

**Comment by ghost** [comment]
My Chrome shows updated.
![image](https://user-images.githubusercontent.com/70641063/92310583-ee9c0280-efa7-11ea-8cdf-89379723e4b9.png)

I check my speed using the websites fast.com provided by Netflix or speedtest.net by Oakla

**Comment by Sandor-Helper** [comment]
OK, Chrome version is actual now. Did you checked speed in [another browser, e.g. Mozilla Firefox already](https://github.com/dragokas/hijackthis/issues/105#issuecomment-687619307)?

**Comment by dragokas** [comment]
++ also, make one more HiJackThis log again.

**Comment by ghost** [comment]
Yes I checked speed using other browsers. Technician is coming to change my modem. They think could be that. 
HiJackThis log attached
[hijackthis.txt](https://github.com/dragokas/hijackthis/files/5183465/hijackthis.txt)

**Comment by dragokas** [comment]
Please, help us to improve our diagnostic tools by searching chrome version in registry. To do this, download:
http://download.bleepingcomputer.com/farbar/MiniRegTool64.zip

- [x] Run it
- [x] Copy and paste the following text in field:
```
85.0.4183.83
```
- [x] Mark option **Search**.
- [x] Press key **Go**

Wait a while, and attach **Result.txt** to your message.
