### ISSUE TITLE
HiJackThis

### ISSUE THREAD

**Issue by sergioend** [dragokas/hijackthis#106]
[CollectionLog-2020.09.24-17.51.zip](https://github.com/dragokas/hijackthis/files/5277408/CollectionLog-2020.09.24-17.51.zip)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Describe your problem in detail.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog, and write what problems remained.
