### ISSUE TITLE
Persistant Virus or Malware on Windows 10 Laptop.

### ISSUE THREAD

**Issue by joEEaLLan** [dragokas/hijackthis#107]
I've been attempting to get rid of whatever "IT" is without any luck. This is a fresh install of Windows 10 Home on a ASUS L406MA laptop. Any help will be appreciation in advance.

Logfile of HiJackThis Fork by Alex Dragokas v.2.9.0.18

Platform:  x64 Windows 10 (Home), 10.0.18363.592 (ReleaseId: 1909), Service Pack: 0
Time:      25.09.2020 - 22:17 (UTC-04:00)
Language:  OS: English (0x409). Display: English (0x409). Non-Unicode: English (0x409)
Elevated:  Yes
Ran by:    shool	(group: Administrator) on DESKTOP-15MBBIC, FirstRun: yes

Edge:    11.0.18362.476
Internet Explorer: 11.0.18362.1
Default: "C:\Windows\system32\LaunchWinApp.exe" "%1" (Microsoft Edge)

Boot mode: Normal
Scan mode: Additional; Environment variables

Environment variables:

[System]
ComSpec = C:\Windows\System32\cmd.exe
DriverData = C:\Windows\System32\Drivers\DriverData
OS = Windows_NT
Path = C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH
PATHEXT = .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE = AMD64
PSModulePath = C:\Windows\system32\WindowsPowerShell\v1.0\Modules
TEMP = C:\Windows\TEMP
TMP = C:\Windows\TEMP
USERNAME = SYSTEM
windir = C:\Windows
NUMBER_OF_PROCESSORS = 2
PROCESSOR_LEVEL = 6
PROCESSOR_IDENTIFIER = Intel64 Family 6 Model 122 Stepping 1, GenuineIntel
PROCESSOR_REVISION = 7a01

[User]
Path = C:\Users\shool\AppData\Local\Microsoft\WindowsApps;
TEMP = C:\Users\shool\AppData\Local\Temp
TMP = C:\Users\shool\AppData\Local\Temp
OneDrive = C:\Users\shool\OneDrive

[Current process]
ALLUSERSPROFILE = C:\ProgramData
APPDATA = C:\Users\shool\AppData\Roaming
CommonProgramFiles = C:\Program Files (x86)\Common Files
CommonProgramFiles(x86) = C:\Program Files (x86)\Common Files
CommonProgramW6432 = C:\Program Files\Common Files
COMPUTERNAME = DESKTOP-15MBBIC
ComSpec = C:\Windows\System32\cmd.exe
DriverData = C:\Windows\System32\Drivers\DriverData
HOMEDRIVE = C:
HOMEPATH = \Users\shool
LOCALAPPDATA = C:\Users\shool\AppData\Local
LOGONSERVER = \\DESKTOP-15MBBIC
NUMBER_OF_PROCESSORS = 2
OneDrive = C:\Users\shool\OneDrive
OS = Windows_NT
Path = C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Users\shool\AppData\Local\Microsoft\WindowsApps
PATHEXT = .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE = x86
PROCESSOR_ARCHITEW6432 = AMD64
PROCESSOR_IDENTIFIER = Intel64 Family 6 Model 122 Stepping 1, GenuineIntel
PROCESSOR_LEVEL = 6
PROCESSOR_REVISION = 7a01
ProgramData = C:\ProgramData
ProgramFiles = C:\Program Files (x86)
ProgramFiles(x86) = C:\Program Files (x86)
ProgramW6432 = C:\Program Files
PSModulePath = C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC = C:\Users\Public
SystemDrive = C:
SystemRoot = C:\Windows
TEMP = C:\Users\shool\AppData\Local\Temp
TMP = C:\Users\shool\AppData\Local\Temp
USERDOMAIN = DESKTOP-15MBBIC
USERDOMAIN_ROAMINGPROFILE = DESKTOP-15MBBIC
USERNAME = shool
USERPROFILE = C:\Users\shool
windir = C:\Windows
__COMPAT_LAYER = Installer

Special folders:

3D Objects = C:\Users\shool\3D Objects
AccountPictures = C:\Users\shool\AppData\Roaming\Microsoft\Windows\AccountPictures
Administrative Tools = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Administrative Tools
AppData = C:\Users\shool\AppData\Roaming
AppDataDesktop = C:\Users\shool\AppData\Local\Desktop
AppDataDocuments = C:\Users\shool\AppData\Local\Documents
AppDataFavorites = C:\Users\shool\AppData\Local\Favorites
AppDataProgramData = C:\Users\shool\AppData\Local\ProgramData
AppMods = C:\Users\shool\AppMods
Application Shortcuts = C:\Users\shool\AppData\Local\Microsoft\Windows\Application Shortcuts
CD Burning = C:\Users\shool\AppData\Local\Microsoft\Windows\Burn\Burn
Cache = C:\Users\shool\AppData\Local\Microsoft\Windows\INetCache
Camera Roll = C:\Users\shool\Pictures\Camera Roll
CameraRollLibrary = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Libraries\CameraRoll.library-ms
Captures = C:\Users\shool\Videos\Captures
Common Administrative Tools = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools
Common AppData = C:\ProgramData
Common Desktop = C:\Users\Public\Desktop
Common Documents = C:\Users\Public\Documents
Common Programs = C:\ProgramData\Microsoft\Windows\Start Menu\Programs
Common Start Menu = C:\ProgramData\Microsoft\Windows\Start Menu
Common Start Menu Places = C:\ProgramData\Microsoft\Windows\Start Menu Places
Common Startup = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp
Common Templates = C:\ProgramData\Microsoft\Windows\Templates
CommonDownloads = C:\Users\Public\Downloads
CommonMusic = C:\Users\Public\Music
CommonPictures = C:\Users\Public\Pictures
CommonRingtones = C:\ProgramData\Microsoft\Windows\Ringtones
CommonVideo = C:\Users\Public\Videos
Contacts = C:\Users\shool\Contacts
Cookies = C:\Users\shool\AppData\Local\Microsoft\Windows\INetCookies
CredentialManager = C:\Users\shool\AppData\Roaming\Microsoft\Credentials
CryptoKeys = C:\Users\shool\AppData\Roaming\Microsoft\Crypto
Desktop = C:\Users\shool\Desktop
Development Files = C:\Users\shool\AppData\Local\DevelopmentFiles
Device Metadata Store = C:\ProgramData\Microsoft\Windows\DeviceMetadataStore
DocumentsLibrary = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Libraries\Documents.library-ms
Downloads = C:\Users\shool\Downloads
DpapiKeys = C:\Users\shool\AppData\Roaming\Microsoft\Protect
Favorites = C:\Users\shool\Favorites
Fonts = C:\Windows\Fonts
GameTasks = C:\Users\shool\AppData\Local\Microsoft\Windows\GameExplorer
History = C:\Users\shool\AppData\Local\Microsoft\Windows\History
ImplicitAppShortcuts = C:\Users\shool\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\ImplicitAppShortcuts
Libraries = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Libraries
Links = C:\Users\shool\Links
Local AppData = C:\Users\shool\AppData\Local
Local Documents = C:\Users\shool\Documents
Local Downloads = C:\Users\shool\Downloads
Local Music = C:\Users\shool\Music
Local Pictures = C:\Users\shool\Pictures
Local Videos = C:\Users\shool\Videos
LocalAppDataLow = C:\Users\shool\AppData\LocalLow
LocalizedResourcesDir = C:\Windows\resources\0409
MusicLibrary = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Libraries\Music.library-ms
My Music = C:\Users\shool\Music
My Pictures = C:\Users\shool\Pictures
My Video = C:\Users\shool\Videos
NetHood = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Network Shortcuts
OEM Links = C:\ProgramData\OEM Links
OneDrive = C:\Users\shool\OneDrive
OneDriveCameraRoll = C:\Users\shool\OneDrive\Pictures\Camera Roll
OneDriveDocuments = C:\Users\shool\OneDrive\Documents
OneDriveMusic = C:\Users\shool\OneDrive\Music
OneDrivePictures = C:\Users\shool\OneDrive\Pictures
Original Images = C:\Users\shool\AppData\Local\Microsoft\Windows Photo Gallery\Original Images
Personal = C:\Users\shool\Documents
PhotoAlbums = C:\Users\shool\Pictures\Slide Shows
PicturesLibrary = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Libraries\Pictures.library-ms
Playlists = C:\Users\shool\Music\Playlists
PrintHood = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Printer Shortcuts
Profile = C:\Users\shool
ProgramFiles = C:\Program Files (x86)
ProgramFilesCommon = C:\Program Files (x86)\Common Files
ProgramFilesCommonX86 = C:\Program Files (x86)\Common Files
ProgramFilesX86 = C:\Program Files (x86)
Programs = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
Public = C:\Users\Public
PublicAccountPictures = C:\Users\Public\AccountPictures
PublicGameTasks = C:\ProgramData\Microsoft\Windows\GameExplorer
PublicLibraries = C:\Users\Public\Libraries
Quick Launch = C:\Users\shool\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch
Recent = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Recent
Recorded Calls = C:\Users\shool\Recorded Calls
RecordedTVLibrary = C:\Users\Public\Libraries\RecordedTV.library-ms
ResourceDir = C:\Windows\resources
Ringtones = C:\Users\shool\AppData\Local\Microsoft\Windows\Ringtones
Roamed Tile Images = C:\Users\shool\AppData\Local\Microsoft\Windows\RoamedTileImages
Roaming Tiles = C:\Users\shool\AppData\Local\Microsoft\Windows\RoamingTiles
SampleMusic = C:\Users\Public\Music\Sample Music
SamplePictures = C:\Users\Public\Pictures\Sample Pictures
SampleVideos = C:\Users\Public\Videos\Sample Videos
SavedGames = C:\Users\shool\Saved Games
SavedPictures = C:\Users\shool\Pictures\Saved Pictures
SavedPicturesLibrary = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Libraries\SavedPictures.library-ms
Screenshots = C:\Users\shool\Pictures\Screenshots
SearchHistoryFolder = C:\Users\shool\AppData\Local\Microsoft\Windows\ConnectedSearch\History
SearchTemplatesFolder = C:\Users\shool\AppData\Local\Microsoft\Windows\ConnectedSearch\Templates
Searches = C:\Users\shool\Searches
SendTo = C:\Users\shool\AppData\Roaming\Microsoft\Windows\SendTo
Start Menu = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Start Menu
Startup = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\StartUp
System = C:\Windows\system32
SystemCertificates = C:\Users\shool\AppData\Roaming\Microsoft\SystemCertificates
SystemX86 = C:\Windows\SysWOW64
Templates = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Templates
ThisPCDesktopFolder = C:\Users\shool\Desktop
User Pinned = C:\Users\shool\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned
UserProfiles = C:\Users
UserProgramFiles = C:\Users\shool\AppData\Local\Programs
UserProgramFilesCommon = C:\Users\shool\AppData\Local\Programs\Common
VideosLibrary = C:\Users\shool\AppData\Roaming\Microsoft\Windows\Libraries\Videos.library-ms
Windows = C:\Windows

Running processes:
  PID | Path
   1  C:\Program Files\WindowsApps\Microsoft.SkypeApp_14.35.152.0_x64__kzf8qxf38zg5c\SkypeApp.exe
   1  C:\Program Files\WindowsApps\Microsoft.SkypeApp_14.35.152.0_x64__kzf8qxf38zg5c\SkypeBackgroundHost.exe
   1  C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2008.9-0\MsMpEng.exe
   1  C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2008.9-0\NisSrv.exe
   1  C:\Users\shool\Desktop\HiJackThis\HiJackThis.exe
   1  C:\Windows\ImmersiveControlPanel\SystemSettings.exe
   1  C:\Windows\System32\ApplicationFrameHost.exe
   1  C:\Windows\System32\DriverStore\FileRepository\dal.inf_amd64_d52c63e0e1c02c96\jhi_service.exe
   1  C:\Windows\System32\DriverStore\FileRepository\dptf_cpu.inf_amd64_4a3ae74cfa6c37d6\esif_uf.exe
   1  C:\Windows\System32\ELANFPService.exe
   5  C:\Windows\System32\MicrosoftEdgeCP.exe
   1  C:\Windows\System32\MicrosoftEdgeSH.exe
   2  C:\Windows\System32\RtkAudUService64.exe
   6  C:\Windows\System32\RuntimeBroker.exe
   1  C:\Windows\System32\SearchIndexer.exe
   1  C:\Windows\System32\SecurityHealthService.exe
   1  C:\Windows\System32\SgrmBroker.exe
   2  C:\Windows\System32\WUDFHost.exe
   4  C:\Windows\System32\Windows.WARP.JITService.exe
   1  C:\Windows\System32\audiodg.exe
   1  C:\Windows\System32\browser_broker.exe
   2  C:\Windows\System32\csrss.exe
   1  C:\Windows\System32\ctfmon.exe
   2  C:\Windows\System32\dllhost.exe
   1  C:\Windows\System32\dwm.exe
   2  C:\Windows\System32\fontdrvhost.exe
   1  C:\Windows\System32\lsass.exe
   1  C:\Windows\System32\services.exe
   1  C:\Windows\System32\sihost.exe
   1  C:\Windows\System32\smartscreen.exe
   1  C:\Windows\System32\smss.exe
   1  C:\Windows\System32\spoolsv.exe
  67  C:\Windows\System32\svchost.exe
   1  C:\Windows\System32\taskhostw.exe
   1  C:\Windows\System32\wininit.exe
   1  C:\Windows\System32\winlogon.exe
   1  C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe
   1  C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
   1  C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe
   1  C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe
   1  C:\Windows\explorer.exe

O10 - Broken Internet access because of LSP provider 'C:\Windows\system32\vsocklib.dll' missing
O17 - DHCP DNS 1: 192.168.1.254
O17 - DHCP DNS 2: 75.153.176.1
O23 - Service R2: ELAN Service - (ELANFPService) - C:\Windows\System32\ELANFPService.exe (size: 197360 bytes, MD5: 53D1B621F766DC04AC12145365345F98)
O23 - Service R2: Intel(R) Dynamic Application Loader Host Interface Service - (jhi_service) - C:\Windows\System32\DriverStore\FileRepository\dal.inf_amd64_d52c63e0e1c02c96\jhi_service.exe (size: 648080 bytes, MD5: EF3A4EFF84A61BF41115907B2959FE0A)
O23 - Service R2: Intel(R) Dynamic Tuning service - (esifsvc) - C:\Windows\System32\DriverStore\FileRepository\dptf_cpu.inf_amd64_4a3ae74cfa6c37d6\esif_uf.exe (size: 2141064 bytes, MD5: 3EDB6BE675F6352104C1D7A53B267524)
O23 - Service R2: Realtek Audio Universal Service - (RtkAudioUniversalService) - C:\Windows\System32\RtkAudUService64.exe (size: 971256 bytes, MD5: A04ECCAC5F3BCEEDD99A1073BFE294B9)
O23 - Service S2: Intel(R) TPM Provisioning Service - C:\Windows\System32\DriverStore\FileRepository\iclsclient.inf_amd64_3004658ee4d7fe24\lib\TPMProvisioningService.exe (size: 787216 bytes, MD5: B081DE44B5A573988628B659348D906E)
O23 - Service S3: Intel(R) Capability Licensing Service TCP IP Interface - C:\Windows\System32\DriverStore\FileRepository\iclsclient.inf_amd64_3004658ee4d7fe24\lib\SocketHeciServer.exe (size: 858888 bytes, MD5: CD87E642568839B3BE43DBB4C78F4E79)
O23 - Driver R3: ASUS Touch Service - (AsusPTPDrv) - C:\Windows\System32\drivers\AsusPTPFilter.sys (size: 108232 bytes, MD5: 33E238D261ECBB503777194AB4416836)
O23 - Driver R3: Intel(R) Serial IO SPI Driver v2 - (iaLPSS2_SPI) - C:\Windows\System32\drivers\iaLPSS2_SPI.sys (size: 153488 bytes, MD5: D5C36DF200C06FA7FD058A505A92CABF)
O23 - Driver R3: Intel(R) Serial IO UART Driver v2 - (iaLPSS2_UART2) - C:\Windows\System32\drivers\iaLPSS2_UART2.sys (size: 300432 bytes, MD5: F8C5DD19D9D2693BEE6F849771E1F6FC)
O23 - Driver R3: Intel(R) Trusted Execution Engine Interface - (MEIx64) - C:\Windows\System32\drivers\TeeDriverW8x64.sys (size: 263808 bytes, MD5: 5B137B3F6A3199932F835DFF4C66ED2D)
O23 - Driver R3: Realtek PCIE Card Reader - PER - (RTSPER) - C:\Windows\System32\drivers\RtsPer.sys (size: 995416 bytes, MD5: 289A93671B10F83E5D3096DC5937ACCA)
O23 - Driver R3: Service for Realtek HD Audio (WDM) - (IntcAzAudAddService) - C:\Windows\system32\drivers\RTKVHD64.sys (size: 6988072 bytes, MD5: 2B00372242FD2857A94C55F7281F488F)
O23 - Driver R3: dptf_acpi - C:\Windows\System32\DriverStore\FileRepository\dptf_acpi.inf_amd64_5989fd2721678bab\dptf_acpi.sys (size: 77192 bytes, MD5: F6A4005CEB6FD7E8500D871A3B158046)
O23 - Driver R3: dptf_cpu - C:\Windows\System32\DriverStore\FileRepository\dptf_cpu.inf_amd64_4a3ae74cfa6c37d6\dptf_cpu.sys (size: 74120 bytes, MD5: 2E034D188092D6DCAE2CC35BA326F684)
O23 - Driver R3: esif_lf - C:\Windows\System32\DriverStore\FileRepository\dptf_cpu.inf_amd64_4a3ae74cfa6c37d6\esif_lf.sys (size: 408456 bytes, MD5: 7935DCF2D0CA9FCEA22FBBB7A0442B86)
O23 - Driver R: (no name) - C:\Windows\System32\Drivers\dump_dumpsd.sys (file missing)

--
End of file - Time spent: 41.5 sec. - 30526 bytes, CRC32: FFFFFFFF. Sign: 僾䏯

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  *   Please, describe in more details, what signs you reveal the presence of a virus?

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog, and write what problems remained.
