### ISSUE TITLE
PB de fichiers Qt_temp trés importants et a plusieurs endroits

### ISSUE THREAD

**Issue by christiangueritauld** [dragokas/hijackthis#108]
Tout est dans le titre
PC Windows 10
doit-on s'inquiéter de la présence de tels fichiers .?
Merci

**Comment by dragokas** [comment]
Hi and welcome.
Unfortunately, we can only provide assistance in the English language.
I didn't understand the title. Can you describe it in more detail?
Also, why have you labeled it as a "bug" in HiJackThis?

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.

If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in detail.
