### ISSUE TITLE
Hacker got access to my computer. I have 0 clue how he's doing it.

### ISSUE THREAD

**Issue by Giamo23** [dragokas/hijackthis#109]
Sometime ago I noticed that someone has access to my computer and can literally use every aspect of it. That scared me quite a lot. I uses Hijackthis to creat a logfil. Unfortunately I have no idea which processes are evil and which are not. Its my first time dealing with something like this.
Thnaks for your help!
[HiJackThis3.log](https://github.com/dragokas/hijackthis/files/5397721/HiJackThis3.log)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in more detail, what specific signs of hacking are you seeing.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip), prepare new CollectionLog, and write what problems remained.
