### ISSUE TITLE
blu

### ISSUE THREAD

**Issue by Blufoxes** [dragokas/hijackthis#11]
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/1539612/HiJackThis.log)

**Comment by dragokas** [comment]
Hi, Blufoxes !

Thank you for the log.
Do you need any assistance?

To make improvement in our program, please, [create registry export](https://www.laptopmag.com/articles/create-reg-file-for-registry-hacks) for this key:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers`

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Comment by dragokas** [comment]
No answer for 10 days. Closed.
If you need to re-open your case, please, ask in PM to one of VIRUSNET members.
