### ISSUE TITLE
potential malicious website manipulated my Windows 10 Home PC - how to find out what it did?

### ISSUE THREAD

**Issue by OneElectronics** [dragokas/hijackthis#110]
1. What did you done before the problem occurs: I had been web-surfing with firefox, and had stress and had been so silly to click in a strange forum to find a children's book on a link, that promised a pdf from this book, the link had begun with "csanzupa.site/de/... download ...", and after clicking, nothing happened, but I was quite afraid,
that now I obviously opened some door for malware. It had been a very suspicious site, it told it is safe in large letters ... and so on.

Then I made a scan with bitdefender (found nothing) under windows 10,
but norton power eraser told me, that something was wrong in my windows 10 registry.
I wanted to go back to a previous windows restore point, but I was very surprised, that only two from the past were listed, and I tried to activate both, but after rebooting windows, it came up the message:
"unable to restore registry"/registry maybe locked by antivirus program, but had I disabled bitdefender.

1b) I tried to do a scan with antivirus rescue dvd, but scan crashed without comment at 7% or 16% scan duration.

1c) I made a scan with ESET rescue USB stick, it told that "windows", "skype", etc. is locked and can not be analyzed.
A lot of windows system archives seem to be damaged
(see log file of ESET scan)
It found not really a threat (some old unwanted applications from chip.de installers),
but a lot of damaged or locked files ... I don't know, if it is true or a bug in ESET ?

1d) for reasons of security, I pulled off the wlan usb dongle before running "autologger.exe",
if you need a second scan with acitivated internet connection, please tell me.

1e) during running autologger internet explorer asked to enable a java script,
(screenshot attached)
should I have accepted or declined this? During the first and only autologger run,
I had clicked nothing, so neither accept nor decline.

2. What programs (browsers) affected by the problem: ________________
Windows 10 Home, 64 bit, Firefox

3. Steps to reproduce: _________________
previous windows restore points can not be activated

some online tools like google scanner tell, that the site "csanzupa.site/de" is clean,
but total virus scanner tells in one case, that it is suspicious (elevated exposure, no https, etc.).

3a) How to analyze a suspicious site, what it does? In this case 

3b) More important: How to be sure, that my Windows 10 PC is still ok and not infected with any malware, etc.

3c) Should I try to reinstall windows (with keeping my data) or do a complete reinstallation to be sure?

file:///media/jo/FLASHDEVICE/ESET_scan_log.txt
file:///media/jo/FLASHDEVICE/add_on_java_ie.JPG
file:///media/jo/FLASHDEVICE/CollectionLog-2020.10.19-20.10.zip
file:///media/jo/FLASHDEVICE/ESET_history.txt

**Comment by OneElectronics** [comment]
I can not see the attached files... had they been uploaded or not ... ?

**Comment by Sandor-Helper** [comment]
Hello and welcome,

No, files are not uploaded. Please, first try to upload only CollectionLog.zip again.

**Comment by OneElectronics** [comment]
upload dialogue opens, but then nothing happens here with my reserve "PC" "raspberry pi" ... maybe I will need more trials for uploading ...

**Comment by OneElectronics** [comment]
[CollectionLog-2020.10.19-20.10.zip](https://github.com/dragokas/hijackthis/files/5411323/CollectionLog-2020.10.19-20.10.zip)
![add_on_java_ie](https://user-images.githubusercontent.com/73078247/96639955-c03d7100-1322-11eb-80d5-42d53b30d90d.JPG)
[ESET_history.txt](https://github.com/dragokas/hijackthis/files/5411330/ESET_history.txt)
[ESET_scan_log.txt](https://github.com/dragokas/hijackthis/files/5411333/ESET_scan_log.txt)

now it seems to work on Windows 10 PC (in safe mode) ... strange, with raspbian pi upload did not work with firefox.

**Comment by Sandor-Helper** [comment]
I repeat, we need CollectionLog.zip created by Autologger.

**Comment by OneElectronics** [comment]
Yes, it is attached in the first line of my comment above. I even tried to re-download it from github here as check, and it is really uploaded. Please see above, the first line. Then a snapshot, then ESET log files. Thank you very much.

**Comment by Sandor-Helper** [comment]
Sorry, I missed it :-)

Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by OneElectronics** [comment]
Good evening, thank you very much for your advices.
Here is the log of AdwCleaner, that I had zipped.
[AdwCleaner[S00].zip](https://github.com/dragokas/hijackthis/files/5418170/AdwCleaner.S00.zip)

**Comment by Sandor-Helper** [comment]
You could delete (put in quarantine) only
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Booking.com.lnk

Suspicious files
C:\Users\admin\Desktop\..\Downloads\OSFMOUNT - CHIP-INSTALLER.EXE
C:\Users\admin\Desktop\..\Downloads\WIN32 DISK IMAGER - CHIP-INSTALLER.EXE
are by your choice.

Check and inspect Preinstalled Software. If some of it you don't use, uninstall it via Control Panel - Applications.

Do one more investigation.
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by OneElectronics** [comment]
Good morning, thanks again.
Unintentionally I downloaded the german version of FRST,
so hopefully the logs are ok for you.

[Addition.txt](https://github.com/dragokas/hijackthis/files/5420590/Addition.txt)
[FRST.txt](https://github.com/dragokas/hijackthis/files/5420591/FRST.txt)

**Comment by Sandor-Helper** [comment]
> german version of FRST

No problem.

I do not see any more malicious records in logs.
Are there any problems left?

**Comment by OneElectronics** [comment]
Thank you very much, my question 3c) very above remain: Du you recommend to reinstall windows completely (to be sure nothing hidden is left), or only try to recover windows while own data aee kept (maybe also malware is kept then?), or shall I try again to switch back to windows system restore point ... and ESET scan tells about a lot of damaged windows archives ... better reinstall completely?
and question 3a) is it necessary to try to find out what this website did or does (shall I go in direction of analysis with sandbox? But I have completely no experience)
Best regards!

**Comment by Sandor-Helper** [comment]
> 3c) Should I try to reinstall windows (with keeping my data) or do a complete reinstallation to be sure?

It is not necessary. Keep the system and the antivirus up to date. Do not download nothing from suspicious sites.



> 3a) How to analyze a suspicious site, what it does?

This requires certain skills. And if you need to visit this site often, you need to contact with site's administration.
Analizing logs from your system doesn't show any serious malware (or adware) problems.

**Comment by OneElectronics** [comment]
Thank you very much, I'll donate to your team. Hopefully you'll also get some amount.
