### ISSUE TITLE
Outlook doesn't open and virus programs will not install

### ISSUE THREAD

**Issue by kgloverfl** [dragokas/hijackthis#111]
Welcome!
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Are you in the right place?

  * Do you need assistance in PC cure from viruses?
  * Or would you like to report a bug or propose a feature for HiJackThis?

If yes, see the next step.

### Step 2: Show us the required logs (for PC cure):

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](http://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

  * Describe your problem in details:
Outlook quit opening.  Would just sit at loading screen.  Tried creating new database, tried repairing database, went through all Microsoft suggestions.  Updated Windows. Kaspersky Security Cloud errored out when trying to download and install.  Last month, my Amazon account was hacked even with 2FA enabled.  The rep I spoke to at Amazon wouldn't give me many details but said that my 2FA was not enabled but when I went to log in, I had to always enter a OTC.  The rep hinted around that there may have been another user set up on my account.  The same day, I received an email from Capital One, whom I had a credit card with, saying that they needed more information before they could approve my Walmart credit account.  I did not apply for one so I called and canceled my Capital One account completely.  Strange things like this have seemed to happen for the last month so I suspect that my computer(s) are compromised.  I have another work computer on the same network that I suspect is also compromised and will submit a separate report for it tomorrow.
I just noticed also that a lot of updates failed to update today, such as .NET Framworks 3.5 and 4.8, Security update for Adobe Flash Player and Cumulative Update for Windows 10 version 1903.

1. What did you done before the problem occurs: _Tried to install Kaspersky_Security Cloud. Updated Windows. Ran TrendMicro Housecall_____________
2. What programs (browsers) affected by the problem: _Outlook mostly and the installation of Kaspersky.  Windows randomly close or quit responding, such as Control Panel/Mail (Micorsoft Outlook 2016)/Mail setup_______________
3. Steps to reproduce: Start Outlook
[CollectionLog-2020.10.20-00.19.zip](https://github.com/dragokas/hijackthis/files/5406072/CollectionLog-2020.10.20-00.19.zip)

_________________

**Comment by Sandor-Helper** [comment]
Hello and welcome,

Our advise is not to use third party optimizers like **System Mechanic**. Uninstall it as well.
I see ZAM Guard Driver running. It is part of Zemana Anti Malware. Try to install is again [from here](https://www.zemana.com/antimalware) and then uninstall.
After that try to install Kaspersky.

Do additional scan:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by kgloverfl** [comment]
Uninstalled System Mechanic
Ran Zemana quick scan, no threats found.  Will run full scan after I send this message.
Kaspersky installed.  Quick scan ran, no threats found.  Will run a full scan after Zemana 
Tried opening Outlook and it was successful - odd that System Mechanic seems to have caused that.  I was certain that I installed System Mechanic to try to clean up the system because I couldn't open Outlook.
Closed Outlook and ran Farbar.  Log files attached.

Thank you for the quick response
[FRST.txt](https://github.com/dragokas/hijackthis/files/5408941/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/5408942/Addition.txt)

**Comment by Sandor-Helper** [comment]
Good to hear good news!
You can now uninstall Zemana AntiMalware. One antivirus is enough for system.

**Comment by kgloverfl** [comment]
After running a full scan, it found a dozen issues.  While fixing them, it crashed.  Running a full Kaspersky scan now

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, describe what problems remained.
