### ISSUE TITLE
PC overheating

### ISSUE THREAD

**Issue by Felix699** [dragokas/hijackthis#112]
Hi, it's been about 2 months that my pc is overheating in every situation. This affects performance, not only when I use it for gaming but in other situations as well. The fans start and adjust to the temperature but never manage to drop it below 91-92C when I play and 68C when I study. I downloaded HiJackThis to try to figure out if there are any programs that are running without my knowledge. I ask for help in identifying, in the log file, which ones are potentially harmful. Thanks for help, and sorry for my english
[CollectionLog-2020.10.23-12.12.zip](https://github.com/dragokas/hijackthis/files/5428826/CollectionLog-2020.10.23-12.12.zip)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Felix699** [comment]
> Hi,
> If you need our assistance:
> 
> * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
> * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)
> 
> **Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**
> 
> **Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Felix699** [comment]
I have corrected

**Comment by Sandor-Helper** [comment]
Hello,

I haven't find any malicious records in logs.
There are too many preinstalled soft from Asus. Check them and uninstall useless ones.
It is good idea to install drivers from its vendor's site, so program Driver Easy 5.6.14 should be also uninstalled.
Then start PC in [safe mode](https://support.microsoft.com/en-us/windows/start-your-pc-in-safe-mode-in-windows-10-92c27cff-db89-8644-1ce4-b3e5e56fe234) and check - is there also overheating occurs?
Tell us the result.

**Comment by Felix699** [comment]
Thanks a lot for helping. I've deleted all usleess programs. If i boot system in normal mode, overheating problems are not solved. But, in safe mode, the fans do not start. I guess that there is a program that cause the problem. I've checked in Task Manager if there are processes using CPU,GPU etc but ther aren't. Thanks again for help

**Comment by Sandor-Helper** [comment]
Now do a [clean boot](https://support.microsoft.com/en-us/help/929135/how-to-perform-a-clean-boot-in-windows) and try to find out which one of program is fault.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
