### ISSUE TITLE
FILTERING results in HijackThis + (UN)SELECT ALL button

### ISSUE THREAD

**Issue by mauriciogracia** [dragokas/hijackthis#114]
Let's provide a FILTER on the found results of HijackThis with a (UN)SELECT ALL button

When the FILTER is applied it will only show the lines that match that pattern, this combined with the (UN)SELECT ALL button for the current results will allow you to FIX all the results that say "file missing" or when you are looking for a specific process or file name.

Here is a very crude prototype
https://user-images.githubusercontent.com/2321661/97818444-7896dd80-1c70-11eb-8520-ce066d06902c.png

**Comment by dragokas** [comment]
![filt](https://user-images.githubusercontent.com/19956568/107257392-47823200-6a43-11eb-880b-3f2d8677b165.png)

Introduced in v2.10.0.5 beta (Nightly build).
