### ISSUE TITLE
PC random BS and console popup on windows startup.

### ISSUE THREAD

**Issue by Cza214** [dragokas/hijackthis#117]
Hi. From few days i have problem with bluescreens and im not sure what cause it and from 3 weeks or more im not sure ho long i have problem with cscript.exe and cmd.exe that popup on windows startup.
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/5503452/HiJackThis.log)

BlueScreens are Nsy.sys and pcpip.sys with code KMODE_EXCEPTION_NOT_HANDLED
UPDATED LOGS:
[CollectionLog-2020.11.06-22.09.zip](https://github.com/dragokas/hijackthis/files/5503531/CollectionLog-2020.11.06-22.09.zip)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

I didn't find any malicious records in log.
Try to run system in [safe mode](https://support.microsoft.com/en-us/windows/start-your-pc-in-safe-mode-in-windows-10-92c27cff-db89-8644-1ce4-b3e5e56fe234) and watch - is it also fall in bluescreen?
Tell us result.

**Comment by Cza214** [comment]
I will test that tumorrow one more problem that i have is sometimes 10x per day malware is showing out connection to push tr xyz trojan chrome.exe i tried to scan by ADWcleaner, malware and avast nothing found

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip), prepare new CollectionLog, and write what problems remained.
