### ISSUE TITLE
Suspicious activity on my pc and accounts, scanned and removed malware several times. Finally ran hijackthis and was recommended to seek your guidance.

### ISSUE THREAD

**Issue by KingMonkeyDevil** [dragokas/hijackthis#119]
[hijackthis.log](https://github.com/dragokas/hijackthis/files/5588827/hijackthis.log)

this is the associated file containing the list of programs it found suspicious. Im not current knowledgeable enough to know if a file is spyware or just suspiciously named so i didnt want to trust my instincts and simply read through and remove what may be essential files that happen to look suspect to me. I am curious though if there are giveaways.

**Comment by KingMonkeyDevil** [comment]
it may be inaccurate due to being run on 64 bit system, i imagine thats where the mass of missing files is from

**Comment by dragokas** [comment]
that is a very old version of hijackthis.

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

  * Describe your problem in detail.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip), prepare new CollectionLog, and write what problems remained.
