### ISSUE TITLE
2017-12-11

### ISSUE THREAD

**Issue by Montegrillo** [dragokas/hijackthis#12]

**Comment by dragokas** [comment]
Hi, Montegrillo !

Thank you for joining the section of VIRUSNET team support.

Tell us if you need any assistance in PC cure.
Assistance is provided free of charge in our free time.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Comment by dragokas** [comment]
No answer for 10 days. Closed.
If you need to re-open your case, please, ask in PM to one of VIRUSNET members.
