### ISSUE TITLE
Windows 10 freezes when doing a rightclick + harddisk at 100%  active time + speed issues

### ISSUE THREAD

**Issue by bamboocha9** [dragokas/hijackthis#120]
Hi there! 
I used HijackThis and followed the instructions - now i'm here. 
Thank you for taking your time and trying to help strangers with their computer-problems.  
My PC slows down when doing a rightclick in "MyComputer" on harddisks for example. I also found out, that one of my harddisks goes to "active time" 100% a few minutes after starting the pc  or when i try to open a file. 
Today, the explorer even crashed for short, when doing a rightclick .
Yesterday i installed a SSD because i thought it was a problem with my HDD. But it'ts actually the same. 
I also got the feeling, the the speed in games dropped a bit.
The machine i use: i7 4770K, 16GB DDR3 1600 MHZ, GTX 770 2GB.
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/5598228/HiJackThis.log)

Thank you for your help in advance!! 
Kind Regards, 
Mario

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by bamboocha9** [comment]
[CollectionLog-2020.11.25-19.23.zip](https://github.com/dragokas/hijackthis/files/5598573/CollectionLog-2020.11.25-19.23.zip)

here is the collectionlog. 
thank you!

**Comment by Sandor-Helper** [comment]
Hi,
Additionally:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by bamboocha9** [comment]
Here you go. Thank you! 
[AdwCleaner[C00].txt](https://github.com/dragokas/hijackthis/files/5602600/AdwCleaner.C00.txt)

**Comment by Sandor-Helper** [comment]
You're already clean everything, ok.

Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by bamboocha9** [comment]
thank you for your amazingly fast support. 
[Addition.txt](https://github.com/dragokas/hijackthis/files/5602728/Addition.txt)
[FRST.txt](https://github.com/dragokas/hijackthis/files/5602729/FRST.txt)

**Comment by Sandor-Helper** [comment]
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CreateRestorePoint:
HKU\S-1-5-21-2608480102-3873841244-244810575-1000\...\MountPoints2: {45d0b316-a428-11ea-8fef-001a7dda7109} - "J:\HiSuiteDownLoader.exe" 
HKU\S-1-5-21-2608480102-3873841244-244810575-1000\...\MountPoints2: {4896f590-f659-11e8-8f0b-bcee7b8bd25c} - "M:\setup.exe" 
GroupPolicy: Beschränkung ? <==== ACHTUNG
AS: Spybot - Search and Destroy (Disabled - Out of date) {A16C3F68-9280-E053-1818-342707FECF4D}
bl (HKLM-x32\...\{2A075BB4-E976-4278-BF3F-E5C6945D84C0}) (Version: 1.0.0 - Your Company Name) Hidden
ph (HKLM-x32\...\{185F9795-9663-4F13-9EF9-307A282ADB5A}) (Version: 1.0.0 - Your Company Name) Hidden
TuneUp Utilities 2014 (de-DE) (HKLM-x32\...\{EA594E28-547D-4FB5-AED8-3628EFB1474D}) (Version: 14.0.1000.340 - TuneUp Software) Hidden
ShellIconOverlayIdentifiers: [00asw] -> {472083B0-C522-11CF-8763-00608CC02F24} =>  -> Keine Datei
AlternateDataStreams: C:\Users\Admin\Cookies:KAU8SdGBYDd1JZJwNsgNhNj [2328]
AlternateDataStreams: C:\ProgramData\TEMP:373E1720 [118]
FirewallRules: [{483A9113-F30B-4ECD-92B8-B81423058D00}] => (Allow) LPort=54925
FirewallRules: [{0F0A3DB6-0E71-4D1F-886B-4EEAB6C3F1C8}] => (Allow) LPort=2869
FirewallRules: [{4E85EF21-5290-4A5B-A466-1176FADE62D9}] => (Allow) LPort=1900
FirewallRules: [{8F188E1C-DE65-4728-8AB4-0498FF5CB139}] => (Allow) LPort=5556
FirewallRules: [{582A63D9-F14C-467D-A05E-604F5C953191}] => (Allow) LPort=5558
StandardProfile\AuthorizedApplications: [C:\Program Files (x86)\Spybot - Search & Destroy 2\SDTray.exe] => Enabled:Spybot - Search & Destroy tray access
StandardProfile\AuthorizedApplications: [C:\Program Files (x86)\Spybot - Search & Destroy 2\SDFSSvc.exe] => Enabled:Spybot-S&D 2 Scanner Service
StandardProfile\AuthorizedApplications: [C:\Program Files (x86)\Spybot - Search & Destroy 2\SDUpdate.exe] => Enabled:Spybot-S&D 2 Updater
StandardProfile\AuthorizedApplications: [C:\Program Files (x86)\Spybot - Search & Destroy 2\SDUpdSvc.exe] => Enabled:Spybot-S&D 2 Background update service
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

In Programs list you'll see previously hidden

> bl
> ph
> TuneUp Utilities 2014 (de-DE)

Unistall them.

**Comment by bamboocha9** [comment]
i hope i did this right:
i copied the code above and pasted it into FRST.
Then i pressed FIX button.

I uninstalled bl and ph
TunUp Utliites is greyed out to be uninstalled. i can't click anything.
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/5604625/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
Try to force uninstall them using [Geek Uninstaller](http://www.geekuninstaller.com/geek.zip)

**Comment by bamboocha9** [comment]
done!
edit: Right-Click on Volume "D" (for example) still causes a freeze for a few minutes

**Comment by Sandor-Helper** [comment]
Start system in [safe mode](https://support.microsoft.com/en-us/windows/start-your-pc-in-safe-mode-in-windows-10-92c27cff-db89-8644-1ce4-b3e5e56fe234) and check - is in that mode right-click getting same thing?

**Comment by bamboocha9** [comment]
did a restart - and it works!! thank you so much for your help!

**Comment by Sandor-Helper** [comment]
Clarify please - is it now OK in normal mode (not in safe mode)?

**Comment by bamboocha9** [comment]
no. i did a restart after uninstalling tune up with geek uninstaller.
is there a possibility to donate some bucks for you?

**Comment by bamboocha9** [comment]
oh no! i just tried the rightclick again. now the explorer freezes again :(
edit: after the crash it works faster again
gonna try safe mode

**Comment by Sandor-Helper** [comment]
> gonna try safe mode

Yes, try it and check - is rightclicking also freezes in safe mode?

**Comment by bamboocha9** [comment]
hi! i tried safemode with networking and it still freezes.
i think it happens the first time after boot that the explorer freezes. 
after restarting explorer it works.

**Comment by Sandor-Helper** [comment]
In that case I'm afraid that problem is caused by hardware, i.e. hard drive, memory etc.
[Get SMART](https://crystalmark.info/redirect.php?product=CrystalDiskInfoInstaller) from your hard drive and show its screen.

**Comment by bamboocha9** [comment]
[CrystalDiskInfo_20201130091713.txt](https://github.com/dragokas/hijackthis/files/5614568/CrystalDiskInfo_20201130091713.txt)
oof. i already changed partition D from Disk 01 to disk 04 because i thought i would be the disk itself -no difference.
thank you! 
after the frist freeze when rightklicking everything works fine.

**Comment by Sandor-Helper** [comment]
My specialization in this area is not good enough, so try to solve this at other profile forums.
I can surely say that problem is not virus depended and your system is clean in that meaning.

**Comment by bamboocha9** [comment]
okay. thank you tough for your help!

**Comment by bamboocha9** [comment]
hi there! 
yesterday i used the tool "ShellExView" do cure my pc! i downloaded this tool already last week, but couldn't handle it. i read about it yesterday and now my pc works again. 
there was a dead/missing shell-extension. it was like when i did a rightklick my pc tried to find the missing one, but couldnt do so. this tool shows the suspicous ones that might be dead/missing. when i disabled them, my pc startet working fluently again.
but thank you too so much for your time and help!!

**Comment by Sandor-Helper** [comment]
Thanks for the information.


> this tool shows the suspicous ones that might be dead/missing

Do you remember what it was exactly?
