### ISSUE TITLE
Malware and other Security Threats

### ISSUE THREAD

**Issue by demansanaallan** [dragokas/hijackthis#121]
Hi Secs Team,

Good day...I never had thought that an irrelevant person would be infested by God knows what.  I have tried asking all over the place...I think those I had consulted are just playing around, but for some reason almost all of them can not do anything.  I finally decided to go with the Open Source Foundation (Source Forge)...At least now I am able to use my old computer and had given my cheap but little bit newer than this infested other laptop that is bigger than a desktop...

I had a simple joy in life and this is thingking myself to be at least an average guy in doing things.  Words can't express and besides I think it is not even professional that soemthing should come out of my mouth against those who ever they are although some of the tools both from opern source and portableapps (freeware/sorftware--GNULicense Soft/Apps) showed therir indentity already.  I guess they are just worried about something...

Kindly help...If any of my personal information can help imporve anythign related to Security and safety (especially of the public) I don't have anything that I can not share.

I will wait for the next instruction....

God bless.

Regards,
Allan

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip), prepare new CollectionLog, and write what problems remained.
