### ISSUE TITLE
schtasks.exe

### ISSUE THREAD

**Issue by jffabian2** [dragokas/hijackthis#122]
When I turn off the computer, a message appears that the application did not start correctly and the error 0xc0000142 appears
with the name schtasks.exe
also sometimes conhost.exe appears with error 0xc000012d

It happens to me that the task manager applications are closed while they are in progress.
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/5661317/HiJackThis.log)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

  * Are there any other signs of infection, excepting the crashes of some applications?

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by jffabian2** [comment]
[avz_log.txt](https://github.com/dragokas/hijackthis/files/5661384/avz_log.txt)

**Comment by dragokas** [comment]
This is the wrong file. See: Collection-[Date].zip

**Comment by jffabian2** [comment]
[CollectionLog-2020.12.08-13.27.zip](https://github.com/dragokas/hijackthis/files/5661528/CollectionLog-2020.12.08-13.27.zip)

**Comment by jffabian2** [comment]
is this file right?

**Comment by jffabian2** [comment]
[Uploading CollectionLog-2020.12.08-13.27.zip…]()

**Comment by Sandor-Helper** [comment]
Hello,

Please find this file

> C:\ProgramData\RealtekHDUpdater\realtekdrv.exe

Upload it to www.virustotal,com copy link to result and paste it to your next post here.

**Comment by jffabian2** [comment]
the link doesn't work for me and I can't find RealtekHDUpdater in the folder

**Comment by jffabian2** [comment]
My accounts are being stolen, I think you are controlling my computer, I give it to restore.?

**Comment by Sandor-Helper** [comment]
> I give it to restore.?

Lets try to fix it first.

Close all running programs, **temporarily** unload antivirus and other protecting software.

[Run a script in AVZ](https://github.com/dragokas/hijackthis/wiki/AVZ:-How-to-execute-script) (File - Run script):

```
begin
 QuarantineFile('C:\ProgramData\RealtekHDUpdater\realtekdrv.exe', '');
 CreateQurantineArchive(GetAVZDirectory + 'quarantine.zip');
end.

```

File **quarantine.zip** from extracted AVZ folder please send using [this form](http://www.oszone.net/virusnet/) or (if archive size exceeds the 8 MB) to this mailbox: **quarantine at safezone.cc** (change _at_ to _@_) and specify your forum link in e-mail subject and password: **virus** in message body.

**Comment by jffabian2** [comment]
[Uploading quarantine.zip…]()

**Comment by jffabian2** [comment]
I am afraid, I lost two accounts, where I no longer receive password recovery emails, like they changed my email, and the antivirus threw me that there were threats in a win32 folder with a Trojan

**Comment by jffabian2** [comment]
![image](https://user-images.githubusercontent.com/75695787/101600974-aedb2180-39c1-11eb-8a91-c46b544813ba.png)

**Comment by jffabian2** [comment]
They are controlling my computer, it has already extracted some things, how can I do?

**Comment by Sandor-Helper** [comment]
OK, this file was already deleted by Windows Defender.

Now please run Autologger again, get new CollecionLog.zip and attach it to your next post.

**Comment by jffabian2** [comment]
the problem is that this file is deleted by windows and then the same threat puts me again

**Comment by jffabian2** [comment]
has already notified me several times

**Comment by jffabian2** [comment]
windows has already removed it about 20 times

**Comment by Sandor-Helper** [comment]
Do new CollectionLog and we'll try to fix it.

**Comment by jffabian2** [comment]
[Uploading CollectionLog-2020.12.09-02.29.zip…]()

**Comment by Sandor-Helper** [comment]
This is just link to previous post. Drag and drop zip file itself like you did before.

**Comment by jffabian2** [comment]
[CollectionLog-2020.12.09-02.29.zip](https://github.com/dragokas/hijackthis/files/5664505/CollectionLog-2020.12.09-02.29.zip)

**Comment by Sandor-Helper** [comment]
Close all running programs, **temporarily** unload antivirus and other protecting software.

[Run a script in AVZ](https://github.com/dragokas/hijackthis/wiki/AVZ:-How-to-execute-script) (File - Run script):

```
begin
 ExecuteFile('net.exe', 'stop tcpip /y', 0, 15000, true);
 ClearQuarantineEx(true);
 TerminateProcessByName('c:\programdata\realtekhdupdater\realtekdrv.exe');
 QuarantineFile('C:\ProgramData\RealtekHDUpdater\realtekdrv.exe', '');
 QuarantineFile('c:\windows\syswow64\schtasks.exe', '');
 DeleteSchedulerTask('Realtek Updater');
 DeleteFile('C:\ProgramData\RealtekHDUpdater\realtekdrv.exe', '64');
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1001', 1);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1004', 3);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1201', 3);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1804', 1);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '2201', 3);
 CreateQurantineArchive(GetAVZDirectory + 'quarantine.zip');
ExecuteSysClean;
 ExecuteWizard('SCU', 2, 3, true);
RebootWindows(true);
end.

```

Computer will _reboot_. 



File **quarantine.zip** from extracted AVZ folder please send using [this form](http://www.oszone.net/virusnet/) or (if archive size exceeds the 8 MB) to this mailbox: **quarantine at safezone.cc** (change _at_ to _@_) and specify your forum link in e-mail subject and password: **virus** in message body.



For _third_ diagnostics please run AutoLogger again. 
Attach new CollectionLog to your post.

**Comment by jffabian2** [comment]
[quarantine.zip](https://github.com/dragokas/hijackthis/files/5664620/quarantine.zip)

**Comment by jffabian2** [comment]
[CollectionLog-2020.12.09-02.55.zip](https://github.com/dragokas/hijackthis/files/5664642/CollectionLog-2020.12.09-02.55.zip)

**Comment by Sandor-Helper** [comment]
[Fix in HijackThis](https://github.com/dragokas/hijackthis/wiki/HJT:-How-to-'Fix-it'):
```
O22 - Task: GPU Tweak II - D:\GPUTweakII.exe (file missing)
O22 - Task: Realtek Updater - C:\ProgramData\RealtekHDUpdater\realtekdrv.exe (file missing)
```

After that:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by jffabian2** [comment]
[FRST.txt](https://github.com/dragokas/hijackthis/files/5664763/FRST.txt)

**Comment by jffabian2** [comment]
[Addition.txt](https://github.com/dragokas/hijackthis/files/5664764/Addition.txt)

**Comment by Sandor-Helper** [comment]
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CreateRestorePoint:
HKU\S-1-5-21-538785442-3372959813-2752330216-1001\...\Run: [Chromium] => "c:\users\fabián\appdata\local\chromium\application\chrome.exe" --auto-launch-at-startup --profile-directory="Default" --restore-last-session
HKU\S-1-5-21-538785442-3372959813-2752330216-1001\...\MountPoints2: {d0a764b6-9f27-11ea-b68c-b42e99d6cfa7} - "E:\HiSuiteDownLoader.exe" 
GroupPolicy: Restricción ? <==== ATENCIÓN
Policies: C:\ProgramData\NTUSER.pol: Restricción <==== ATENCIÓN
HKLM\SOFTWARE\Policies\Mozilla\Firefox: Restricción <==== ATENCIÓN
S3 GPUZ-v2; \??\C:\Users\FABIN~1\AppData\Local\Temp\GPUZ-v2.sys [X] <==== ATENCIÓN
Folder: C:\ProgramData\RealtekHDUpdater
2020-12-03 10:50 - 2020-12-09 02:50 - 000000000 _RSHD C:\ProgramData\RealtekHDUpdater
ShellIconOverlayIdentifiers: [00asw] -> {472083B0-C522-11CF-8763-00608CC02F24} =>  -> Ningún archivo
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by jffabian2** [comment]
Now I'm going to rest a moment, I'll answer you soon

**Comment by jffabian2** [comment]
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/5667817/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
What now with your problem?

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
