### ISSUE TITLE
Webmail spams / Is my PC has ads / infected or non desirable processes / software

### ISSUE THREAD

**Issue by kripskroll** [dragokas/hijackthis#123]
Logfile of HiJackThis Fork by Alex Dragokas v.2.9.0.26

Platform:  x64 Windows 10 (Pro), 10.0.19041.685 (ReleaseId: 2004), Service Pack: 0
Time:      21.12.2020 - 14:46 (UTC+01:00)
Language:  OS: French (0x40C). Display: French (0x40C). Non-Unicode: French (0x40C)
Elevated:  No
Ran by:    miche	(group: Limited User) on DESKTOP-BOISSET, FirstRun: yes

Chrome:  87.0.4280.88
Firefox: 81.0.0.7565
Edge:    11.0.19041.546
Internet Explorer: 11.0.19041.1
Default: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --single-argument %1 (Google Chrome)

Boot mode: Normal

Running processes:
Number | Path
   1  C:\Program Files (x86)\Geneatique2012\Genea2012.exe
  18  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
   1  C:\Program Files\Common Files\Intel\WirelessCommon\RegSrvc.exe
   1  C:\Program Files\DellTPad\ApMsgFwd.exe
   1  C:\Program Files\DellTPad\ApntEx.exe
   1  C:\Program Files\DellTPad\Apoint.exe
   1  C:\Program Files\DellTPad\hidfind.exe
   1  C:\Program Files\Intel\WiFi\bin\EvtEng.exe
   1  C:\Program Files\Intel\WiFi\bin\ZeroConfigService.exe
   1  C:\Program Files\WindowsApps\Microsoft.Windows.Photos_2020.20110.11001.0_x64__8wekyb3d8bbwe\Microsoft.Photos.exe
   1  C:\Program Files\WindowsApps\Microsoft.WindowsMaps_10.2011.6.0_x64__8wekyb3d8bbwe\Maps.exe
   1  C:\Program Files\WindowsApps\Microsoft.WindowsStore_12011.1001.1.0_x64__8wekyb3d8bbwe\WinStore.App.exe
   1  C:\Program Files\WindowsApps\Microsoft.XboxGamingOverlay_5.420.11102.0_x64__8wekyb3d8bbwe\GameBar.exe
   1  C:\Program Files\WindowsApps\Microsoft.XboxGamingOverlay_5.420.11102.0_x64__8wekyb3d8bbwe\GameBarFTServer.exe
   1  C:\Program Files\WindowsApps\Microsoft.YourPhone_1.20112.68.0_x64__8wekyb3d8bbwe\YourPhone.exe
   1  C:\Program Files\WindowsApps\Microsoft.ZuneVideo_10.20112.10111.0_x64__8wekyb3d8bbwe\Video.UI.exe
   2  C:\Users\miche\Desktop\HiJackThis\HiJackThis.exe
   2  C:\WINDOWS\System32\Wbem\WmiPrvSE.exe
   1  C:\WINDOWS\System32\Wbem\unsecapp.exe
   1  C:\WINDOWS\system32\MoUsoCoreWorker.exe
   1  C:\WINDOWS\system32\SearchFilterHost.exe
   1  C:\WINDOWS\system32\SearchIndexer.exe
   1  C:\WINDOWS\system32\SearchProtocolHost.exe
   1  C:\WINDOWS\system32\SecurityHealthService.exe
   1  C:\WINDOWS\system32\SgrmBroker.exe
   1  C:\WINDOWS\system32\WUDFHost.exe
   2  C:\WINDOWS\system32\csrss.exe
   1  C:\WINDOWS\system32\dasHost.exe
   2  C:\WINDOWS\system32\dllhost.exe
   1  C:\WINDOWS\system32\dwm.exe
   2  C:\WINDOWS\system32\fontdrvhost.exe
   1  C:\WINDOWS\system32\lsass.exe
   1  C:\WINDOWS\system32\msdtc.exe
   1  C:\WINDOWS\system32\services.exe
   1  C:\WINDOWS\system32\smss.exe
   1  C:\WINDOWS\system32\spoolsv.exe
   1  C:\WINDOWS\system32\sppsvc.exe
  85  C:\WINDOWS\system32\svchost.exe
   1  C:\WINDOWS\system32\wininit.exe
   1  C:\WINDOWS\system32\winlogon.exe
   1  C:\WINDOWS\system32\wlanext.exe
   1  C:\Windows\ImmersiveControlPanel\SystemSettings.exe
   1  C:\Windows\System32\ApplicationFrameHost.exe
  11  C:\Windows\System32\RuntimeBroker.exe
   1  C:\Windows\System32\SettingSyncHost.exe
   1  C:\Windows\System32\audiodg.exe
   2  C:\Windows\System32\conhost.exe
   1  C:\Windows\System32\ctfmon.exe
   1  C:\Windows\System32\oobe\UserOOBEBroker.exe
   1  C:\Windows\System32\sihost.exe
   1  C:\Windows\System32\smartscreen.exe
   1  C:\Windows\System32\taskhostw.exe
   1  C:\Windows\SystemApps\Microsoft.LockApp_cw5n1h2txyewy\LockApp.exe
   1  C:\Windows\SystemApps\Microsoft.Windows.Search_cw5n1h2txyewy\SearchApp.exe
   1  C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe
   1  C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\InputApp\TextInputHost.exe
   1  C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe
   1  C:\Windows\explorer.exe
   1  DDVCollectorSvcApi.exe
   1  DDVDataCollector.exe
   1  DDVRulesProcessor.exe
   1  DSAPI.exe
   1  DSAService.exe
   1  DSAUpdateService.exe
   1  GoogleCrashHandler.exe
   1  GoogleCrashHandler64.exe
   1  GoogleUpdate.exe
   1  HidMonitorSvc.exe
   1  Memory Compression
   1  MicrosoftEdgeUpdate.exe
   1  MsMpEng.exe
   1  NisSrv.exe
   1  Registry
   1  ServiceShell.exe
   1  SupportAssistAgent.exe
   1  SurSvc.exe
   1  TiWorker.exe
   1  TrustedInstaller.exe
   1  armsvc.exe

O1 - Hosts: ::1 localhost
O2 - HKLM\..\BHO: IEToEdge BHO - {1FD49718-1D00-4B19-AF5F-070AF6D5D54C} - C:\Program Files (x86)\Microsoft\Edge\Application\87.0.664.66\BHO\ie_to_edge_bho_64.dll
O4 - HKCU\..\RunOnce: [Delete Cached Standalone Update Binary] = C:\WINDOWS\system32\cmd.exe /q /c del /q "C:\Users\miche\AppData\Local\Microsoft\OneDrive\StandaloneUpdater\OneDriveSetup.exe"
O4 - HKCU\..\RunOnce: [Delete Cached Update Binary] = C:\WINDOWS\system32\cmd.exe /q /c del /q "C:\Users\miche\AppData\Local\Microsoft\OneDrive\Update\OneDriveSetup.exe"
O4 - HKCU\..\RunOnce: [Uninstall 20.169.0823.0008\amd64] = C:\WINDOWS\system32\cmd.exe /q /c rmdir /s /q "C:\Users\miche\AppData\Local\Microsoft\OneDrive\20.169.0823.0008\amd64"
O4 - HKCU\..\RunOnce: [Uninstall 20.169.0823.0008] = C:\WINDOWS\system32\cmd.exe /q /c rmdir /s /q "C:\Users\miche\AppData\Local\Microsoft\OneDrive\20.169.0823.0008"
O4 - HKLM\..\Run: [Apoint] = C:\Program Files\DellTPad\Apoint.exe
O4 - HKLM\..\Run: [HotKeysCmds] = C:\WINDOWS\system32\hkcmd.exe
O4 - HKLM\..\Run: [IgfxTray] = C:\WINDOWS\system32\igfxtray.exe
O4 - HKLM\..\Run: [Persistence] = C:\WINDOWS\system32\igfxpers.exe
O4 - HKLM\..\Run: [VX3000] = C:\WINDOWS\vVX3000.exe
O17 - DHCP DNS 1: 192.168.1.1
O22 - Task (.job): (disabled) CreateExplorerShellUnelevatedTask.job - (no file)
O22 - Task (.job): (disabled) Microsoft_Hardware_Launch_vVX3000_exe.job - (no file)
O23 - Service R2: "Alps HID Monitor Service"		; Service Name - (ApHidMonitorService) - C:\Program Files\DellTPad\HidMonitorSvc.exe
O23 - Service R2: Adobe Acrobat Update Service - (AdobeARMservice) - C:\Program Files (x86)\Common Files\Adobe\ARM\1.0\armsvc.exe
O23 - Service R2: Dell Client Management Service - (DellClientManagementService) - C:\Program Files (x86)\Dell\UpdateService\ServiceShell.exe
O23 - Service R2: Dell Data Vault Collector - (DDVDataCollector) - C:\Program Files\Dell\DellDataVault\DDVDataCollector.exe
O23 - Service R2: Dell Data Vault Processor - (DDVRulesProcessor) - C:\Program Files\Dell\DellDataVault\DDVRulesProcessor.exe
O23 - Service R2: Dell Data Vault Service API - (DDVCollectorSvcApi) - C:\Program Files\Dell\DellDataVault\DDVCollectorSvcApi.exe
O23 - Service R2: Dell Hardware Support - C:\Program Files\Dell\SupportAssistAgent\PCDr\SupportAssist\6.0.7106.1428\DSAPI.exe
O23 - Service R2: Dell SupportAssist - (SupportAssistAgent) - C:\Program Files\Dell\SupportAssistAgent\bin\SupportAssistAgent.exe
O23 - Service R2: Intel(R) Driver & Support Assistant - (DSAService) - C:\Program Files (x86)\Intel\Driver and Support Assistant\DSAService.exe
O23 - Service R2: Intel(R) PROSet/Wireless Event Log - (EvtEng) - C:\Program Files\Intel\WiFi\bin\EvtEng.exe
O23 - Service R2: Intel(R) PROSet/Wireless Registry Service - (RegSrvc) - C:\Program Files\Common Files\Intel\WirelessCommon\RegSrvc.exe
O23 - Service R2: Intel(R) PROSet/Wireless Zero Configuration Service - (ZeroConfigService) - C:\Program Files\Intel\WiFi\bin\ZeroConfigService.exe
O23 - Service R2: Intel(R) System Usage Report Service SystemUsageReportSvc_QUEENCREEK - (SystemUsageReportSvc_QUEENCREEK) - C:\Program Files\Intel\SUR\QUEENCREEK\SurSvc.exe
O23 - Service R3: Intel(R) Driver & Support Assistant Updater - (DSAUpdateService) - C:\Program Files (x86)\Intel\Driver and Support Assistant\DSAUpdateService.exe
O23 - Service S2: Service Google Update (gupdate) - (gupdate) - C:\Program Files (x86)\Google\Update\GoogleUpdate.exe /svc
O23 - Service S3: Adobe Flash Player Update Service - (AdobeFlashPlayerUpdateSvc) - C:\WINDOWS\SysWOW64\Macromed\Flash\FlashPlayerUpdateService.exe
O23 - Service S3: Energy Server Service queencreek - (ESRV_SVC_QUEENCREEK) - C:\Program Files\Intel\SUR\QUEENCREEK\x64\esrv_svc.exe "--AUTO_START" "--start" "--start_options_registry_key" "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\ESRV_SVC_QUEENCREEK\_start"
O23 - Service S3: Google Chrome Elevation Service - (GoogleChromeElevationService) - C:\Program Files (x86)\Google\Chrome\Application\87.0.4280.88\elevation_service.exe
O23 - Service S3: Intel(R) Content Protection HECI Service - (cphs) - C:\WINDOWS\SysWow64\IntelCpHeciSvc.exe
O23 - Service S3: Intel(R) SUR QC Software Asset Manager - (Intel(R) SUR QC SAM) - C:\Program Files\Intel\SUR\QUEENCREEK\Updater\bin\IntelSoftwareAssetManagerService.exe
O23 - Service S3: Mozilla Maintenance Service - (MozillaMaintenance) - C:\Program Files (x86)\Mozilla Maintenance Service\maintenanceservice.exe
O23 - Service S3: Service Google Update (gupdatem) - (gupdatem) - C:\Program Files (x86)\Google\Update\GoogleUpdate.exe /medsvc
O23 - Service S3: User Energy Server Service queencreek - (USER_ESRV_SVC_QUEENCREEK) - C:\Program Files\Intel\SUR\QUEENCREEK\x64\esrv_svc.exe "--run_as_user_process" 
O23 - Service S3: Wireless PAN DHCP Server - (MyWiFiDHCPDNS) - C:\Program Files\Intel\WiFi\bin\PanDhcpDns.exe

Debug information:

- 21.12.2020 14:46:03 - LoadFileToStream - #0 LastDllError = 5 (Accès refusé.) CreateFile C:\WINDOWS\Tasks\CreateExplorerShellUnelevatedTask.job 
- 21.12.2020 14:46:03 - ParseJob. Unable to open file: C:\WINDOWS\Tasks\CreateExplorerShellUnelevatedTask.job - #0 LastDllError = 0
- 21.12.2020 14:46:03 - LoadFileToStream - #0 LastDllError = 5 (Accès refusé.) CreateFile C:\WINDOWS\Tasks\Microsoft_Hardware_Launch_vVX3000_exe.job 
- 21.12.2020 14:46:03 - ParseJob. Unable to open file: C:\WINDOWS\Tasks\Microsoft_Hardware_Launch_vVX3000_exe.job - #0 LastDllError = 0

--
End of file - Time spent: 9,8 sec. - 19976 bytes, CRC32: FFFFFFFF. Sign: �

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

  * Describe your problem in detail.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by kripskroll** [comment]
Thanks for your help
