### ISSUE TITLE
Multiple start-up errors involving Local Management Service service failing to start

### ISSUE THREAD

**Issue by BrutishRogue** [dragokas/hijackthis#127]
Need help.  Tried resolving alone for many moons with no luck.  Multiple start-up errors causing system to not work normally. 
The Intel(R) Management and Security Application Local Management Service service failed to start due to the following error: The system cannot find the file specified.
DCOM got error "2" attempting to start the service LMS with arguments "" in order to run the server:
{80C25488-192B-4DE2-8150-5B2D2A2F835E}
The following boot-start or system-start driver(s) failed to load: uezndl

and more.  Any suggestions?

**Comment by dragokas** [comment]
Hi,
We only deal with malware-related issues. It is not likely the case.
For resolving general operating system or hardware issues, we suggest asking for help on the forums, like:
 - https://www.tenforums.com
 - https://www.eightforums.com
 - https://www.sevenforums.com/
 - https://answers.microsoft.com/
 - http://www.geekstogo.com/forum/forum/41-operating-systems/

Good luck to you.

**Comment by BrutishRogue** [comment]
Thank you.
