### ISSUE TITLE
Floxif - cant seem to get rid of

### ISSUE THREAD

**Issue by juic3b0x** [dragokas/hijackthis#128]
I have recently been infected with the floxif malware and have been unsuccessful at removing it completely. Any help would be great. Thank you.
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/5825671/HiJackThis.log)

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by juic3b0x** [comment]
I apologize for not fully reading the directions. I have completed the directions now. 
[CollectionLog-2021.01.17-03.57.zip](https://github.com/dragokas/hijackthis/files/5825836/CollectionLog-2021.01.17-03.57.zip)

**Comment by Sandor-Helper** [comment]
How do you know this is

> floxif malware

?
And what problems you're experienced now?

I advise to remove PUP antivirus programs like:

> SpyHunter 5
> SUPERAntiSpyware

You have installed Malwarebytes version 4.1.0.56. Do a complete scan and save results to text file. Attach it to your next post.

**Comment by juic3b0x** [comment]
I had initially ran Malwarebytes on 1/13/2021 and thats when it said I had the floxif malware infection. Since then I have been trying to remedy the situation to no avail. It really enjoys infecting my dlls and other exes to stay alive. I appreciate the help. I have attached the initial quick scan report as well as a current complete scan per request. Thank you.

[Malwarebytes-Results-1-13-2021.txt](https://github.com/dragokas/hijackthis/files/5826966/Malwarebytes-Results-1-13-2021.txt)


[complete-scan-Malwarebytes-Results-1-17-2021.txt](https://github.com/dragokas/hijackthis/files/5826978/complete-scan-Malwarebytes-Results-1-17-2021.txt)

**Comment by Sandor-Helper** [comment]
Four detected files in File section are false positives in my opinion. You can leave it.
Do you have some troubles using system like slowing down, freezing or something else after cleaning by Malwarebytes?

Additionally:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by juic3b0x** [comment]
I do not have any slowing down really, some freezing but I have 16GB RAM, and i7 in this laptop so it doesn't really see slow downs that go unnoticed.

[FRST.txt](https://github.com/dragokas/hijackthis/files/5828509/FRST.txt)

[Addition.txt](https://github.com/dragokas/hijackthis/files/5828510/Addition.txt)

**Comment by Sandor-Helper** [comment]
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
SystemRestore: On
CreateRestorePoint:
AppInit_DLLs-x32: C:\PROGRA~1\COMMON~1\System\symsrv.dll => No File <==== ATTENTION
GroupPolicy: Restriction ? <==== ATTENTION
GroupPolicyScripts\User: Restriction <==== ATTENTION
Policies: C:\ProgramData\NTUSER.pol: Restriction <==== ATTENTION
Task: {26EED4F9-1930-487B-9DA6-BA618BAAC82E} - \Lenovo\ImController\Plugins\LenovoSystemUpdatePlugin_WeeklyTask -> No File <==== ATTENTION
Task: {4BAF2577-BA97-4267-86B2-75995DAFB00F} - \Lenovo\ImController\Lenovo iM Controller Scheduled Maintenance -> No File <==== ATTENTION
Task: {6D3BF2CF-AEFF-4EDB-A581-20A75B509800} - \Lenovo\ImController\Lenovo iM Controller Monitor -> No File <==== ATTENTION
Task: {C1DBFFA7-08B0-4CB5-8DEE-50C5E7B44933} - \Lenovo\ImController\TimeBasedEvents\ec3012cd-42f3-41b5-9d96-e78d12083a77 -> No File <==== ATTENTION
Task: {DB1F4551-A97A-4CE2-9907-1CFE0B98FA5B} - \Lenovo\ImController\TimeBasedEvents\f7d6d7d3-2214-4b20-94d7-b7094f2ad63a -> No File <==== ATTENTION
Task: {F7BBD67B-765D-4011-BDB8-DB74FD06C803} - \Lenovo\ImController\TimeBasedEvents\97c91a66-bb53-4ae2-affd-95141b14361f -> No File <==== ATTENTION
FirewallRules: [{AB4AD4AB-EE71-4FDD-9801-59A28137DC47}] => (Allow) C:\Program Files\SUPERAntiSpyware\SUPERAntiSpyware.exe => No File
FirewallRules: [{547B163F-470E-4F37-A120-5BC1F33A5762}] => (Allow) C:\Program Files\SUPERAntiSpyware\SUPERAntiSpyware.exe => No File
FirewallRules: [{7DF97F88-F7D2-40A1-9D37-5C17C501C857}] => (Allow) C:\Program Files\SUPERAntiSpyware\SSUpdate64.exe => No File
FirewallRules: [{F1BDE79A-DC99-456F-AA63-19BC2CA02AFB}] => (Allow) C:\Program Files\SUPERAntiSpyware\SSUpdate64.exe => No File
FirewallRules: [{C02BBE17-8D38-440D-B8EA-BA35EE1FEE9A}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\SpyHunter5.exe => No File
FirewallRules: [{7AF26F9C-8860-4023-8550-99390BC849C9}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\SpyHunter5.exe => No File
FirewallRules: [{7BFD7D3C-2E9B-4243-AE65-488B8DC23007}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\SpyHunter5.exe => No File
FirewallRules: [{A41FB485-843D-484A-A9BE-9D56DDB79F6D}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\SpyHunter5.exe => No File
FirewallRules: [{365727BE-4CA8-4844-8315-BED708675E24}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\ShMonitor.exe => No File
FirewallRules: [{072CBE45-EBBB-4E13-99B0-3485411D858B}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\ShMonitor.exe => No File
FirewallRules: [{A7014CF1-4346-4385-B747-98486C421310}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\ShMonitor.exe => No File
FirewallRules: [{D1779FD5-68C9-4FBC-96DF-CF278A51A3B4}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\ShMonitor.exe => No File
FirewallRules: [{14250446-57AC-4035-A2FF-668C33773D41}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\ShKernel.exe => No File
FirewallRules: [{52443DCD-BF05-4EC8-973C-447F526B60D2}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\ShKernel.exe => No File
FirewallRules: [{4C267033-5E11-43C2-B618-0CE583DFAE90}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\ShKernel.exe => No File
FirewallRules: [{3A2FA7BD-37B7-4D17-95B8-A53C45FE8A7C}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\ShKernel.exe => No File
FirewallRules: [{E9501173-9091-4234-A5DE-67C45E09DF07}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\Native.exe => No File
FirewallRules: [{6CB70151-49EC-40C2-B782-E61D9179FACC}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\Native.exe => No File
FirewallRules: [{9313F3C4-3BBB-4D02-BCA3-9655ABB47C79}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\Native.exe => No File
FirewallRules: [{35BCEA95-79B5-4E68-9A59-D644566AD400}] => (Allow) C:\Program Files\EnigmaSoft\SpyHunter\Native.exe => No File
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by juic3b0x** [comment]
Sorry for the delay.. Just ran the fix and attached is the log.
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/5842266/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
OK. Now if all is going well:
Rename FRST.exe (FRST64.exe) to **uninstall.exe** and run it. PC will reboot.
Other tools you can simply delete.

Keep your system and antivirus updated.
Other vulnerabilities you can check with [SecurityCheck](https://safezone.cc/resources/security-check-by-glax24.25/download). It is conveniently to run it with `SecurityCheck.exe -! /htmllog` parameter.
