### ISSUE TITLE
HijackThis help

### ISSUE THREAD

**Issue by dontreadme** [dragokas/hijackthis#130]
Everytime i search something on Google Chrome, Avast pops up and it says: "We've safely aborted connection on servscrpt.de because it was infected with URL:blacklist

So i read on an other forum to run HijackThis and save the log and send it to this forum. So can anybody help me which ones i need to fix/delete?
[hijackthis.log](https://github.com/dragokas/hijackthis/files/5832863/hijackthis.log)

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip), prepare new CollectionLog, and write what problems remained.
