### ISSUE TITLE
Very slow computer: infected?

### ISSUE THREAD

**Issue by Bertcaus** [dragokas/hijackthis#133]
Hello, this is my first help request. HiJack This (log attached) highlighted an item: 
02-32 - HKLM..BHO: ITEoEdge BHO ........ ie_to_edge_bho.dll which could possibly create problems.

The PC is an HP Envy Recline 23 (all-in-one) with an Intel Core i5-4570T CPU @ 2.9 GHz, 8GB of RAM and a SeageSSHD of 1 TB,  which is very slow even from the startup with a lot of disk activity (the activity LED is almost permanently lit) and also after logging in (Microsoft Account with PIN) it takes a lot of time to open for example Thunderbird e-mail or any other program with the same disk activity. I have been searching already for a long time to find a cause (hard - and software) but with no result. The OS is MS Windows 10 Pro 20H2 (dutch version).
Thanks for helping me out.
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/6010835/HiJackThis.log)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed due to duplication of: https://github.com/dragokas/hijackthis/issues/134
