### ISSUE TITLE
AdwCleaner results for issue 133

### ISSUE THREAD

**Issue by Bertcaus** [dragokas/hijackthis#135]
Welcome!
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Are you in the right place?

  * Do you need assistance in PC cure from viruses?
  * Or would you like to report a bug or propose a feature for HiJackThis?

If yes, see the next step.

### Step 2: Show us the required logs (for PC cure):

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](http://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

  * Describe your problem in details:

1. What did you done before the problem occurs: _________________
2. What programs (browsers) affected by the problem: ________________
3. Steps to reproduce: _________________
Hello,

Do I really have to create a new issue every time I respond? Isn't there another way to respond? Sorry if I am missing something.
I uninstalled the programs you asked: O&O software are trusted (payed) programs I've be using for years (from time to time there is a new version). DirverFix was only installed recently for troubleshooting: the problem already existed. I still see a trace in the logfile even after uninstallation of DriverFix and a reboot (this was necessary for Diskimage).
Thanks again.
[AdwCleaner[S00].txt](https://github.com/dragokas/hijackthis/files/6017481/AdwCleaner.S00.txt)

**Comment by dragokas** [comment]
Why did you create a new topic?
You have to answer in the same case: https://github.com/dragokas/hijackthis/issues/134
This topic will be closed. Please, duplicate your response in the appropriate place.
