### ISSUE TITLE
Requesting Help to clean out my computer

### ISSUE THREAD

**Issue by ghost** [dragokas/hijackthis#136]
Hi there, I followed a forum about clearing duplicate tasks in the task manager using HiJackThis. My Disk is always running at 100% and i think im have malware that is difficult to remove. So I followed the instructions on the page. I would very much appreciate any help and time anyone is willing to give.
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/6026423/HiJackThis.log)
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/6026426/HiJackThis.log)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip), prepare new CollectionLog, and write what problems remained.
