### ISSUE TITLE
svchost.exe

### ISSUE THREAD

**Issue by ortobruenn** [dragokas/hijackthis#138]
after every restart my pc takes a lot of time to be rdy. For 10 minutes my HDD is on 100%
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/6031027/HiJackThis.log)

**Comment by dragokas** [comment]
Hi,
We only deal with malware-related issues. It is not likely the case.
For resolving general operating system or hardware issues, we suggest asking for help on the forums, like:
 - https://www.tenforums.com
 - https://www.eightforums.com
 - https://www.sevenforums.com/
 - https://answers.microsoft.com/
 - http://www.geekstogo.com/forum/forum/41-operating-systems/

If you are sure it can be malware-related, and you still need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

  * Describe your problem in detail (like, why you think it is a malware, did you download and install something potentially dangerous recently etc.).

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip), prepare new CollectionLog, and write what problems remained.
