### ISSUE TITLE
Assistance Request

### ISSUE THREAD

**Issue by Sei-lus** [dragokas/hijackthis#139]
Hello,

I need to request help because I was careless recently. I had this computer for 1 year and a half, I did a clean install of W10 about 1 week ago (W10 20H2), and it was running fine before the clean install, after the clean install and even right now. But I did some senseless actions recently.

Please note that in this post I will link to multiple URLs and I will mark them if I think they are unsafe. But regardless, please be careful even if I'm not pointing to some major evil sources, just some possible adware.

I got interested about the idea of customizing my laptop with Rainmeter and eventually found a nice program that modifies W10 themes. The name is UXThemePatcher. I always run everything via Virus Total and I also try to find other users input about if the tool is trustworthy in Reddit, Deviantart or the like. (r/software, r/windows10, and the like... not some random part of reddit) and I felt confident due to the fact that the site show no add or anything like that ON my firefox settings but was told by someone at discord that the site is shady.

**Site where I downloaded from and probable malware/adware site**
https://uxthemepatcher.com/
Virus Total from the file that I downloaded from the site and installed (1 time with windows defender enabled and 1 with all antivirus protection disabled):
https://www.virustotal.com/gui/file/29bd905b2c7f0c1dfb26a52b61fd323271179b025e7d46b6fb6b130ab7f66968/detection

Real site of the tool: UltraUXThemePatcher
https://mhoefs.eu/software_uxtheme.php?lang=en
Virus Total of original tool:
https://www.virustotal.com/gui/file/826186b0c1aa55646dfd2d7699a05192d78f7f0b76413a6525effa894cf83bf2/detection

Log from Revo Uninstaller Pro (I was monitoring the first time I ran the .exe, but I don't know how to export the log out of the proprietary .ruel log file of Revo... But this may be helpful)
[Log from Revo Uninstaller.zip](https://github.com/dragokas/hijackthis/files/6085766/Log.from.Revo.Uninstaller.zip)

I spent 4 hours researching if I should install the file I installed, but literally 15 minutes after I did I found the true site of the author of the tool. I immediately did a system restore to about 10 hours before I installed the possible malware. Then I used Disk Cleanup to deleted every cache Windows allow, then deleted AppData/Local/Temp folder, then deleted every remnant I found via me searching and using the Revo log of registries, folder and files changes, and I ran a full system scan with Windows Defender.

I have 2 SSD drives, and I partitioned like this with the hopes in the case I ever mess in the future, I limit where the viruses travel to.
![image](https://user-images.githubusercontent.com/57790936/110010396-2943e500-7d16-11eb-9374-a4a6148c4631.png)

I don't have network folders or other devices to propagate malware to.

I'm about to run HijackThis but I wanted to start getting attention to this thread.

Edit: I also tried to use the "Behavior" tab of Virus Total to the best of my ability to try, track and reverse everything the program did in my pc.

**Comment by Sei-lus** [comment]
So I followed the recommendations of another thread of what to log.

Ran AutoLogger-test.exe twice. Once with Windows Defender ON and one OFF (I wanted to make sure not to mess again like I did with the program I installed before)

Antivirus ON (Just in case it is useful):
[CollectionLog-2021.03.04-14.29 (Antivirus ON).zip](https://github.com/dragokas/hijackthis/files/6085890/CollectionLog-2021.03.04-14.29.Antivirus.ON.zip)
Antivirus OFF:
[CollectionLog-2021.03.04-14.35.zip](https://github.com/dragokas/hijackthis/files/6085891/CollectionLog-2021.03.04-14.35.zip)

HijackThis Log (Antivirus OFF):
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/6085896/HiJackThis.log)

Thanks for considering to help me, and I'll be waiting for a reply. I'm worried about malware that may be hidden (either because after 2 years of computer use there may be malwares that resist clean installs, or move with my user data backups (I mean photos, word files, etc) or because the system restore is not exactly perfect and I may still be in danger from UXThemePatcher)

Yes, although incredible cumbersome... I would be willing to clean install again so feel free to give me all your recommendations.

**Comment by Sandor-Helper** [comment]
Hello and welcome,

File **CheckBrowserLnk.log** from

> ...\AutoLogger\CheckBrowserLnk 

drag and drop onto [ClearLNK tool](http://dragokas.com/tools/ClearLNK.zip).

http://dragokas.com/tools/move.gif

Its report should be look like **ClearLNK-< Date >.log**. Attach it to your next post.

This will delete orphan file links.

All other logs looks fine, i.e. I didn't find any malicious traces.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip), prepare new CollectionLog, and write what problems remained.
