### ISSUE TITLE
Memory can not be read... DayZ

### ISSUE THREAD

**Issue by MrTatiTunes** [dragokas/hijackthis#140]
memory error in game maybe there are some more programs interfering with it :
![MEM ERROR](https://user-images.githubusercontent.com/30302908/110214931-da758700-7e9e-11eb-90a5-b38cc80ce1b8.JPG)

**Comment by MrTatiTunes** [comment]
This error happens on varies of memory ranges.

**Comment by dragokas** [comment]
Hi,
We only deal with malware-related issues. It is not likely the case.
For resolving general operating system or hardware issues, we suggest asking for help on the forums, like:
 - https://www.tenforums.com
 - https://www.eightforums.com
 - https://www.sevenforums.com/
 - https://answers.microsoft.com/
 - http://www.geekstogo.com/forum/forum/41-operating-systems/

If you are sure it can be malware-related, and you still need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

  * Describe your problem in detail (like, why you think it is a malware, did you download and install something potentially dangerous recently etc.).

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by MrTatiTunes** [comment]
Thanks
I had searched for this issue and found this:
https://forum.pcformat.pl/Instrukcja-spod-0x00aef9c6-odwoluje-sie-do-pamieci-pod-adresem-0x000000000-t
