### ISSUE TITLE
Systeem Waarschuwing!

### ISSUE THREAD

**Issue by enschot** [dragokas/hijackthis#143]
After yesterday windows whit Systeem waarschuwing appaers on my screen

Most of the thime when i open firefox explorer

Need help to remove this annoying window

no screenshot available on this moment

thanks in advance
Frans

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by enschot** [comment]
Van: Sandor-Helper ***@***.*** 
Verzonden: woensdag 24 maart 2021 11:47
Aan: dragokas/hijackthis ***@***.***>
CC: enschot ***@***.***>; Author ***@***.***>
Onderwerp: Re: [dragokas/hijackthis] Systeem Waarschuwing! (#143)

 

Hi,
If you need our assistance:

*	Read carefully: How to make a request for help in the PC cure section <https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F> 
*	Attach 'Collection-[Date].zip' log created by AutoLogger <https://tools.safezone.cc/drongo/test/AutoLogger-test.zip> 

Please, note that only members of VIRUSNET-Association <https://github.com/VIRUSNET-Association>  are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!

Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using this form <https://safezone.cc/donate/>  or you can leave feedback in Guestbook <https://github.com/dragokas/hijackthis/issues/47> .

**Comment by dragokas** [comment]
**enschot**, what is it?

**Comment by enschot** [comment]
![Capture](https://user-images.githubusercontent.com/5345052/112366424-1438f100-8cd9-11eb-9d80-d6bb6d0a039a.PNG)
This is a picture from my virus problem

[CollectionLog-2021.03.24-14.38.zip](https://github.com/dragokas/hijackthis/files/6199597/CollectionLog-2021.03.24-14.38.zip)
What you mean with **what is it?**
Log file is include again, also report 1 and 2
[report1.log](https://github.com/dragokas/hijackthis/files/6199609/report1.log)
[report2.log](https://github.com/dragokas/hijackthis/files/6199612/report2.log)

thanks in advance

**Comment by Sandor-Helper** [comment]
> This is a picture from my virus problem

Are these notifications appears even when all browsers closed?
Try to turn off notifications regarding [this instruction](https://support.microsoft.com/en-us/windows/change-notification-settings-in-windows-10-ddcbbcd4-0a02-f6e4-fe14-6766d850f294).

**Comment by enschot** [comment]
Hi Sandor,

I have switched-off all notifications, and it looks that my problem is solved.
I think I saw this annoying window only when I started firefox.
When all windows closed I not see this, but I not fully sure about.
Is it necessary to switch-off all the notifications, or can I also switch-off the notification that course this window?

Thanks in advance

**Comment by Sandor-Helper** [comment]
> it looks that my problem is solved

Great!


> or can I also switch-off the notification that course this window?

Right. It's not necessary to switch-off all the notifications. It is by your choice.
