### ISSUE TITLE
Pls check this Logfile Bitdefender blocked gitcdn.link from chrome.exe

### ISSUE THREAD

**Issue by itayfun** [dragokas/hijackthis#144]
Logfile of HiJackThis Fork (Beta) by Alex Dragokas v.2.10.0.6

Platform:  x64 Windows 10 (Pro), 10.0.19042.868 (ReleaseId: 2009), Service Pack: 0
Time:      30.03.2021 - 16:33 (UTC+02:00)
Language:  OS: German (0x407). Display: German (0x407). Non-Unicode: German (0x407)
Elevated:  Yes
Ran by:    XXXXXXXXXXXXX	(group: Administrator) on XXXXXXXXXXXXX, FirstRun: no

Chrome:  89.0.4389.90
Edge:    11.0.19041.844
Internet Explorer: 11.789.19041.0
Default: "C:\Program Files\Google\Chrome\Application\chrome.exe" --single-argument %1 (Google Chrome)

Boot mode: Normal

--
End of file - Time spent: 5,1 sec. - 43524 bytes, CRC32: FFFFFFFF. Sign: ᱘

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

  * Describe your problem in detail.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by itayfun** [comment]
I can`t create an Autmatic Log Creator cause if i start the programm it says 'Pls downloaded the last version' and the programm closed.

My english is also not good so pls forgive me

**Comment by dragokas** [comment]
Sorry, I gave you an outdated link.
Please, use this one: [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip)

**Comment by itayfun** [comment]
[CollectionLog-2021.03.30-18.32.zip](https://github.com/dragokas/hijackthis/files/6230637/CollectionLog-2021.03.30-18.32.zip)

**Comment by Sandor-Helper** [comment]
Hello,

Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by dragokas** [comment]
Also, please update the safe database. See the [instruction here](https://github.com/dragokas/hijackthis/wiki/AVZ:-How-to-update-safe-files%3F).

**Comment by itayfun** [comment]
[AdwCleaner[S01].txt](https://github.com/dragokas/hijackthis/files/6248836/AdwCleaner.S01.txt)

**Comment by itayfun** [comment]
From where i can get AVZ ?

**Comment by dragokas** [comment]
You already have it in \AutoLogger\AV\av_z.exe

**Comment by Sandor-Helper** [comment]
Also show us file AdwCleaner[C00].txt please.

**Comment by itayfun** [comment]
[AdwCleaner[C00].txt](https://github.com/dragokas/hijackthis/files/6248957/AdwCleaner.C00.txt)

**Comment by Sandor-Helper** [comment]
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by itayfun** [comment]
[FRST.txt](https://github.com/dragokas/hijackthis/files/6248998/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/6248999/Addition.txt)

**Comment by itayfun** [comment]
That is the LOG what i did with AVZ
https://rapidgator.net/file/3ba5d7bbf7556f622094111516a21311/virusinfo_files_ITAYFUN-GAMING.zip.html

**Comment by Sandor-Helper** [comment]
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CreateRestorePoint:
HKLM\SOFTWARE\Policies\Microsoft\Windows Defender: Beschränkung <==== ACHTUNG
Policies: C:\ProgramData\NTUSER.pol: Beschränkung <==== ACHTUNG
HKLM\SOFTWARE\Policies\Microsoft\Edge: Beschränkung <==== ACHTUNG
HKU\S-1-5-21-3020197095-1575548706-597192262-1001\SOFTWARE\Policies\Microsoft\Edge: Beschränkung <==== ACHTUNG
FirewallRules: [{3D129DB4-B6A4-480A-A2B5-9428F55CE61A}] => (Allow) LPort=32682
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by itayfun** [comment]
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/6249277/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
One fix at a time was enough ))
Please clarify: is AV detection appears only when Chrome is running? Is it appears when you surfing in MS Edge?

**Comment by itayfun** [comment]
i only use Chrome MS Edge is deactivated

**Comment by Sandor-Helper** [comment]
I'm not asking you to use it, only to check to see what can we do to solve the problem (if it still occurs).

**Comment by itayfun** [comment]
I think we can close the Issue, cause Adwcleaner find the problem and fixed it
