### ISSUE TITLE
Invasive ads x appearing in Chrome on top of my Google search results 

### ISSUE THREAD

**Issue by FrancescoReviso** [dragokas/hijackthis#146]
Everytime I use Google search to look for information in my Chrome web browser, the correct results are shown just for a fraction of second and then replaced by a bunch of invasive and misleading ads x search results. 
I checked my Chrome extensions and I coulnd't find any of them that might be affected by a malware, I used Malwarebytes to inspect my machine and it couldn't find any malware
[CollectionLog-2021.04.12-15.56.zip](https://github.com/dragokas/hijackthis/files/6297235/CollectionLog-2021.04.12-15.56.zip)

**Comment by Sandor-Helper** [comment]
Hello and welcome,

Please update the safe database. See the [instruction here](https://github.com/dragokas/hijackthis/wiki/AVZ:-How-to-update-safe-files%3F).

Next:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
