### ISSUE TITLE
Can't delete file from descop

### ISSUE THREAD

**Issue by Animal8111** [dragokas/hijackthis#147]
Hi there, i got problems with file which i can't delete. These are my logs.
[CollectionLog-2021.04.21-17.51.zip](https://github.com/dragokas/hijackthis/files/6352296/CollectionLog-2021.04.21-17.51.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

 - What exactly is the file name?

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Animal8111** [comment]
File name is: 178-the-common-puffer-tetraodon-turgidus-179-the-small-globe-fish-acanthosoma-catinatum-180-the-hairy-balloon-fish-diodon-pilosus-181-the-unspoted-balloon-fish-d-fuliginosus-still-image-prints-1842-1844-de-kay-james-e-james-ellsworth-1792-1851-2CTC6TA
My son has downolad this from some page. Im a newbie-if there are some other issues that You can see-please help. Thanks in advance.

**Comment by Sandor-Helper** [comment]
Hi,
Please additionally:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by Animal8111** [comment]
Hi, 
here's my log
[AdwCleaner[S03].txt](https://github.com/dragokas/hijackthis/files/6357935/AdwCleaner.S03.txt)

**Comment by Sandor-Helper** [comment]
Via Control panel - Programs - uninstall following
`TotalAV`

Next:
Start AdwCleaner again, press Scan. Do not check preinstalled sofware and press Quarantine.
PC should be restarted.
At the end of the cleaning log will be found at:
C:\AdwCleaner\Logs\AdwCleaner[Cxx].txt (where x is any digit).
Attach it to your next post here.

Then:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by Animal8111** [comment]
Here's Adw log
[AdwCleaner[S04].txt](https://github.com/dragokas/hijackthis/files/6358371/AdwCleaner.S04.txt)

**Comment by Animal8111** [comment]
here's Adw log
[AdwCleaner[S04].txt](https://github.com/dragokas/hijackthis/files/6358432/AdwCleaner.S04.txt)

**Comment by Animal8111** [comment]
And there are FRST logs
[FRST.txt](https://github.com/dragokas/hijackthis/files/6358445/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/6358446/Addition.txt)

**Comment by Sandor-Helper** [comment]
You've attached AdwCleaner log with "S" letter, but I need another one with "C" letter.

**Comment by Animal8111** [comment]
Sorry, here's with c
[AdwCleaner[C04].txt](https://github.com/dragokas/hijackthis/files/6358461/AdwCleaner.C04.txt)

**Comment by Sandor-Helper** [comment]
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
SystemRestore: On
CreateRestorePoint:
GroupPolicy: Ograniczenia ? <==== UWAGA
Policies: C:\ProgramData\NTUSER.pol: Ograniczenia <==== UWAGA
HKLM\SOFTWARE\Policies\Mozilla\Firefox: Ograniczenia <==== UWAGA
AV: Total AV (Disabled - Out of date) {B185458D-38B3-A010-10F7-3D378DAA6032}
bl (HKLM-x32\...\{2A075BB4-E976-4278-BF3F-E5C6945D84C0}) (Version: 1.0.0 - Your Company Name) Hidden
ph (HKLM-x32\...\{185F9795-9663-4F13-9EF9-307A282ADB5A}) (Version: 1.0.0 - Your Company Name) Hidden
CMD: del "\\?\C:\Users\CP24\Desktop\178-the-common-puffer-tetraodon-turgidus-179-the-small-globe-fish-acanthosoma-catinatum-180-the-hairy-balloon-fish-diodon-pilosus-181-the-unspoted-balloon-fish-d-fuliginosus-still-image-prints-1842-1844-de-kay-james-e-james-ellsworth-1792-1851-2CTC6TA.jpg "
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

In Control Panel - Program list - you'll see two previously hidden programs. 
```
bl
ph
```
Uninstall them.

**Comment by Animal8111** [comment]
I did what You asked.
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/6358766/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
Please wait for tomorrow, I'll try to get rid of this long name deletion.

**Comment by Animal8111** [comment]
I appreciate Your help. Thanks

**Comment by Sandor-Helper** [comment]
Lets do it another way:
Download and install [7z archiver](https://www.7-zip.org/).
Add this file with long name to 7z archive (right click on file - 7-zip - add to archive...), give short name to archive and ceck "Delete files after compression"
http://prntscr.com/11wt0t5

After that you can simply delete archive file.

**Comment by Animal8111** [comment]
Hi, i did it that way and it actually helped!!! File dissapeared.  Thanks a LOT.  If you need some digital drawing feel free to email me-i can make portrait from picture, or enything you wish. Best regards.
