### ISSUE TITLE
Chrome starting slowly

### ISSUE THREAD

**Issue by Sevroneth** [dragokas/hijackthis#148]
Recently I noticed that Chrome is starting very slowly when loading the home page (about 5-6 seconds). Before was nearly instant. I tried different solutions, but none worked. So I suspect some malware could be the problem. Here's the log.
[CollectionLog-2021.04.28-17.23.zip](https://github.com/dragokas/hijackthis/files/6392975/CollectionLog-2021.04.28-17.23.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

Uninstall PUP:

> Wise Registry Cleaner 10.1.4

Then:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by Sevroneth** [comment]
here's the log as you asked.
[AdwCleaner[S04].txt](https://github.com/dragokas/hijackthis/files/6401456/AdwCleaner.S04.txt)

**Comment by Sandor-Helper** [comment]
Attach also this file - AdwCleaner[C02].txt

Next:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
