### ISSUE TITLE
Slow laptop - Possible Malware

### ISSUE THREAD

**Issue by Therealcazza** [dragokas/hijackthis#149]
Hi
My laptop has been laggy for a few weeks now so I ran HJT just now. That in itself had a problem when trying to run it (screenshot attached). I tried the workaround suggested but that also failed saying I didn't have the rights to save the file.
I deleted around 10 R1 lines plus one R0 but as you can see some still came back when I reran it so I decided I needed to ask for help.
I appreciate any advice that you have.

![HJT](https://user-images.githubusercontent.com/83494670/116777462-bdf06800-aa65-11eb-98b0-1990362444fa.jpg)
[hijackthis.log](https://github.com/dragokas/hijackthis/files/6409273/hijackthis.log)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip)

  * Describe your problem in detail.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Therealcazza** [comment]
My apologies. I've attached the file.
Many thanks
[CollectionLog-2021.05.01-17.50.zip](https://github.com/dragokas/hijackthis/files/6409971/CollectionLog-2021.05.01-17.50.zip)

**Comment by Sandor-Helper** [comment]
Hello,

Please uninstall
`Lenovo App Explorer`

Then:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by Therealcazza** [comment]
[AdwCleaner[S00].txt](https://github.com/dragokas/hijackthis/files/6410126/AdwCleaner.S00.txt)

**Comment by Sandor-Helper** [comment]
Do not touch Peinstalled soft (leave it unchecked)
Run AdwCleaner again, press Scan and then Quarantine.
Clean log should be here - C:\AdwCleaner\Logs\AdwCleaner[Cxx].txt
Attach it to your next post.

Next:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by Therealcazza** [comment]
Hi
Sorry I'm a bit confused about the preinstalled software part so I've attached screenshots showing the status of Adware as I ran it.
The other logs are attached too.
Many thanks
[AdwCleaner[C01].txt](https://github.com/dragokas/hijackthis/files/6411116/AdwCleaner.C01.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/6411117/Addition.txt)
[FRST.txt](https://github.com/dragokas/hijackthis/files/6411119/FRST.txt)
![ADW scan](https://user-images.githubusercontent.com/83494670/116809443-f95a6780-ab35-11eb-9a96-b76f81976f56.jpg)
![ADW scan1](https://user-images.githubusercontent.com/83494670/116809446-fb242b00-ab35-11eb-992b-c20fba74de7e.jpg)
![ADW scan2](https://user-images.githubusercontent.com/83494670/116809447-fcedee80-ab35-11eb-849a-1c7de00ed231.jpg)

**Comment by Sandor-Helper** [comment]
Better way to uninstall Preinstalled SW is through the Parameters - Apps, but you've already cleaned it via AdwCleaner. Well, no prolem.

Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CreateRestorePoint:
HKLM\SOFTWARE\Policies\Mozilla\Firefox: Restriction <==== ATTENTION
HKLM\SOFTWARE\Policies\Google: Restriction <==== ATTENTION
Task: {71B9154A-6F88-4EB6-B69D-AD122F83996E} - \Lenovo\ImController\TimeBasedEvents\ef29e4dd-a211-4748-829d-9fd7b9fd9091 -> No File <==== ATTENTION
Task: {AA867CF9-5A64-4732-B70C-A30173C399BD} - \Lenovo\ImController\TimeBasedEvents\33c29c54-96aa-4869-945b-d5d958d8f1dc -> No File <==== ATTENTION
Task: {AA9C4CCF-BB08-4D90-A1BF-5619444560AB} - \Lenovo\ImController\TimeBasedEvents\e544db5f-e0df-40f3-aeab-7bf961e19842 -> No File <==== ATTENTION
Task: {C8C73586-A981-4E83-A90E-D74A15F61108} - \Lenovo\ImController\Lenovo iM Controller Scheduled Maintenance -> No File <==== ATTENTION
Task: {D30232B8-70AB-45FA-96C9-A593BCF94A44} - \Lenovo\ImController\TimeBasedEvents\162bca6d-28de-4a56-a7ba-63300fea8b1c -> No File <==== ATTENTION
Task: {F808A976-135A-43C3-843F-9B6F98262670} - \Lenovo\ImController\Lenovo iM Controller Monitor -> No File <==== ATTENTION
Task: {F951449C-401C-40B0-8DA5-ED771EBC2A5C} - \Lenovo\ImController\Plugins\LenovoSystemUpdatePlugin_WeeklyTask -> No File <==== ATTENTION
AV: Malwarebytes (Disabled - Up to date) {23007AD3-69FE-687C-2629-D584AFFAF72B}
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by Therealcazza** [comment]
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/6411237/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
Is it better now?

**Comment by Therealcazza** [comment]
Yes, a definite improvement. Thank you so much! Are you able to tell me what might have caused this?

**Comment by Sandor-Helper** [comment]
We cleaned adware and did a deep clean of temp files.

Run AdwCleaner again. In Settings tab scroll down to Remove AdwCleaner and press Remove button.

Rename FRST.exe (FRST64.exe) to **uninstall.exe** and run it. PC will reboot.
All othe tools and its folders can be sipmly deleted manually.

**Comment by Therealcazza** [comment]
Hi, I uninstalled FRST but adware wouldn't highlight the option to remove it. No worries. All is sorted and running great again. I can't thank you enough :)
