### ISSUE TITLE
Unidentified cause of high CPU core temperature

### ISSUE THREAD

**Issue by uhs-uhs** [dragokas/hijackthis#150]
Hi, 
I wonder if anyone here can have any idea what's wrong with my HP ZBook 15.
While running just 1 app (e.g. net browser) or sometimes even no apps running, the temperature of all 4 cores goes up over 80-90 deg celcius. Fans go crazy. CPU performance in span of 0-20%. 
This overheats is an everyday phenomenon. Very rarely temp looks normal (~39deg C while no app running / 50-60deg C while apps are running) and there is no association between this rare events and my activity on PC. 
I couldn't identify any settings related causes, so I suspect some malicious activity. 
Thanks in advance for any help.
[CollectionLog-2021.05.01-12.29.zip](https://github.com/dragokas/hijackthis/files/6409414/CollectionLog-2021.05.01-12.29.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

I didn't find any malicious traces in logs. 
Lets do this checking - start system in [Safe mode](https://support.microsoft.com/en-us/windows/start-your-pc-in-safe-mode-in-windows-10-92c27cff-db89-8644-1ce4-b3e5e56fe234) and try to analyze: will it also rise the temperature?

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
