### ISSUE TITLE
IsWinServiceFileName

### ISSUE THREAD

**Issue by spyrosmas** [dragokas/hijackthis#151]
Click on "Do a system scan only" I get error 
![image](https://user-images.githubusercontent.com/18444690/116826195-7b30ac00-ab9b-11eb-9ed8-a1f93c8d28b3.png)

**Comment by spyrosmas** [comment]
test version 2.10.0.7 dos not have this problem.

**Comment by dragokas** [comment]
Wait for pushing an update to a stable branch.
