### ISSUE TITLE
Hijacked from unknown source

### ISSUE THREAD

**Issue by diskvideos** [dragokas/hijackthis#153]
[CollectionLog-2021.05.06-18.53.zip](https://github.com/dragokas/hijackthis/files/6436372/CollectionLog-2021.05.06-18.53.zip)
For some reason, my browsers (Chrome, FF, Edge) start to go to ad-websites when clicking somewhere.

Is there anybody out there who might be able to help?

All the best
DV

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

Additional please:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by diskvideos** [comment]
Thank you!
Here you go.
[AdwCleaner[S00].txt](https://github.com/dragokas/hijackthis/files/6444317/AdwCleaner.S00.txt)

**Comment by Sandor-Helper** [comment]
Run AdwCleaner again, scan and at the end of it press **Quarantine**.
Log will be found at:
**C:\AdwCleaner\Logs\AdwCleaner[Cxx].txt** (where x is any digit).
Attach it to your next post here.

Next:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by diskvideos** [comment]
Thank you so much for your time!

Here are the requested files:

[FRST.txt](https://github.com/dragokas/hijackthis/files/6446404/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/6446405/Addition.txt)
[AdwCleaner[S03].txt](https://github.com/dragokas/hijackthis/files/6446399/AdwCleaner.S03.txt)


So, just to add that:
Apparently it also has something to do with my synchronised Chrome-Profile.
As far as I can tell, I am able to quarantine all the files and the browser works nicely, once I sync my Chrome-profile, it all starts again :-|

**Comment by Sandor-Helper** [comment]
Wondershare Helper Compact 2.6.0 - seems like PUP. If you do not install it by yourself, uninstall via Control Panel - Apps.

1. Switch off sync in Chrome by [this instruction](https://forums.malwarebytes.com/topic/258886-chrome-secure-preferences-detection-always-returns/). Instead of 9-th step do following:
2. 
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CreateRestorePoint:
IFEO\LogTransport2.exe: [Debugger] 0
GroupPolicy: Beschränkung ? <==== ACHTUNG
Policies: C:\ProgramData\NTUSER.pol: Beschränkung <==== ACHTUNG
CHR HomePage: Default -> hxxp://www.istartsurf.com/?type=sy&ts=1434904038&z=1c24e775961f05af1061c78g7z9c2z6t0eez3e3ccb&from=smt&uid=SAMSUNGXMZMPC256HBGJ-000_S0YKNEAC503854
AlternateDataStreams: C:\ProgramData\TEMP:054B9966 [136]
AlternateDataStreams: C:\Users\hase\Desktop\2012-08-21 i didnt sign up for that shit white.jpg:com.dropbox.attributes [168]
AlternateDataStreams: C:\Users\hase\Desktop\20130212 - have a mice day.jpg:com.dropbox.attributes [424]
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by diskvideos** [comment]
So, I did all that.
Switched off the sync and did everything from the list, including the malwarebytes scan & quarantine.
Didn't turn the sync back on.

Here is the filre requested:
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/6447205/Fixlog.txt)

Thank you!

**Comment by Sandor-Helper** [comment]
Ok, turn it on and tell us what will be.

**Comment by diskvideos** [comment]
Looks good!
No problems so far!

Thank you so much for your time and patience!

All the best
DV

**Comment by Sandor-Helper** [comment]
Good!

Rename FRST.exe (FRST64.exe) to **uninstall.exe** and run it. PC will reboot.

Run AdwCleaner again. In Settings tab scroll down to Remove AdwCleaner and press Remove button.

All other cureing tools and folders could be simply deleted.

**Comment by diskvideos** [comment]
Apparently, we're back at it again :(
Malewarebytes finds the following problems on a regular basis:

[malware.txt](https://github.com/dragokas/hijackthis/files/6463746/malware.txt)


Although I quarantine them, they get back after a while.

DV

**Comment by Sandor-Helper** [comment]
Repeat again instruction from Malwarebytes and pay attention to last point:

> If you use Chrome to log in to **any** Google service from **any** other computer, please follow these steps before turning on Chrome sync on those computers as well.

Also check default Search systems - place in browser's address this:
`chrome://settings/searchEngines`
and press Enter

**Comment by diskvideos** [comment]
That did the trick, thank you!
Apparently, I wasn't logged out on all other computers!

Thanks!

**Comment by Sandor-Helper** [comment]
Great! Gool luck!
