### ISSUE TITLE
How to get rid of O1 - Hosts: 127.0.0.1 and follow by many website name

### ISSUE THREAD

**Issue by MindnSoul** [dragokas/hijackthis#154]
Please help to get rid of O1 - Hosts: 127.0.0.1 and follow by many website names
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/6546738/HiJackThis.log)

Thank you in advance.

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download)
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by MindnSoul** [comment]
[CollectionLog-2021.05.27-23.05.zip](https://github.com/dragokas/hijackthis/files/6555361/CollectionLog-2021.05.27-23.05.zip)

**Comment by Sandor-Helper** [comment]
Close all running programs, **temporarily** unload antivirus and other protecting software.

[Run a script in AVZ](https://github.com/dragokas/hijackthis/wiki/AVZ:-How-to-execute-script) (File - Run script):

```
begin
 ExecuteFile('net.exe', 'stop tcpip /y', 0, 15000, true);
 ClearQuarantineEx(true);
 TerminateProcessByName('C:\ProgramData\conhost.exe');
 QuarantineFile('C:\ProgramData\conhost.exe', '');
 QuarantineFile('C:\Users\MindnSoul\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\conhost.exe', '');
 QuarantineFile('C:\Users\MindnSoul\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\conhost.exe.manifest', '');
 QuarantineFile('C:\Users\MindnSoul\Start Menu\Programs\Startup\conhost.exe', '');
 DeleteSchedulerTask('AVG\Overseer');
 DeleteSchedulerTask('Skype');
 DeleteFile('C:\Program Files (x86)\IObit\IObit Uninstaller\UninstallExplorer.dll', '64');
 DeleteFile('C:\ProgramData\conhost.exe', '');
 DeleteFile('C:\ProgramData\conhost.exe', '32');
 DeleteFile('C:\ProgramData\conhost.exe', '64');
 DeleteFile('C:\Users\MindnSoul\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\conhost.exe', '');
 DeleteFile('C:\Users\MindnSoul\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\conhost.exe', '64');
 DeleteFile('C:\Users\MindnSoul\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\conhost.exe.manifest', '64');
 DeleteFile('C:\Users\MindnSoul\Start Menu\Programs\Startup\conhost.exe', '');
 DelBHO('{10921475-03CE-4E04-90CE-E2E7EF20C814}');
 RegKeyParamDel('HKEY_CURRENT_USER', 'Software\Microsoft\Windows\CurrentVersion\Run', 'CXTVVAVSU4', '32');
 RegKeyParamDel('HKEY_CURRENT_USER', 'Software\Microsoft\Windows\CurrentVersion\Run', 'CXTVVAVSU4', '64');
ExecuteSysClean;
 ExecuteRepair(13);
 ExecuteWizard('SCU', 2, 3, true);
RebootWindows(true);
end.

```

Computer will _reboot_. 

After reboot run that script:

```
begin
CreateQurantineArchive(GetAVZDirectory+'quarantine.zip'); 
end.
```

File **quarantine.zip** from extracted AVZ folder please send using [this form](http://www.oszone.net/virusnet/) or (if archive size exceeds the 8 MB) to this mailbox: **quarantine at safezone.cc** (change _at_ to _@_) and specify your forum link in e-mail subject and password: **virus** in message body.



For _secondary_ diagnostics please run AutoLogger again. 
Attach new CollectionLog to your post.

**Comment by MindnSoul** [comment]
Can't translate this

![image](https://user-images.githubusercontent.com/84851850/119995901-4aa42c80-bff8-11eb-90d4-ae1f18e910bb.png)

**Comment by dragokas** [comment]
It says the wrong file name is attached.

**Comment by Sandor-Helper** [comment]
Nevertheless continue with new CollectionLog.zip by Autologger.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
