### ISSUE TITLE
Redirects in internet browser to ojrq.net

### ISSUE THREAD

**Issue by Mattis88** [dragokas/hijackthis#155]
Hey everyone,

I think my browser got hijacked, judging by seemingly random redirects to www.ojrq.net on random Google links.
I can't find anything myself and anti-malware solutions that I have tried didn't find anything either.

Here is the log file. I had to exclude a big chunk of it (see the three dots) because through my HOSTS file I redirect a lot of stuff to 0.0.0.0. With that part the log was too long to be posted as it exceeded 65536 characters.
I guess that chunk can be ignored though. My HOSTS file wasn't modified since the last time I created it and I couldn't find anything added to it.

[log deleted]

Thanks for taking a look!
Mathias

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Mattis88** [comment]
[CollectionLog-2021.05.31-19.46.zip](https://github.com/dragokas/hijackthis/files/6571694/CollectionLog-2021.05.31-19.46.zip)
It's attatched now.

**Comment by Sandor-Helper** [comment]
Hello,


> my browser got hijacked

You mean Chrome?

Additional, please:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
