### ISSUE TITLE
Please Help me! 

### ISSUE THREAD

**Issue by Capitanbetter** [dragokas/hijackthis#159]
I have problems with my pc. This is a Log file

[Log is deleted]

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download)
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Plus, describe in details what kind of problem you're experienced?

**Comment by Capitanbetter** [comment]
The problem is this: when I click to open an application or even just the browser, hundreds of windows of the same program open at the same time, I tried to do all the various virus scans but practically nothing comes out.

**Comment by Capitanbetter** [comment]
> Salve,
> se avete bisogno della nostra assistenza:
> 
> * Leggi [attentamente: Come fare una richiesta di aiuto nella sezione cura pc](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
> * Allega registro 'Collection-[Date].zip' creato da [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download)
> 
> **Si prega di notare che solo i membri [di VIRUSNET-Association](https://github.com/VIRUSNET-Association) sono autorizzati a rispondere agli argomenti di cura del PC. Ignorare eventuali suggerimenti forniti da altri utenti, inclusi i PM !!!**
> 
> **L'assistenza è fornita gratuitamente nel nostro tempo libero. Se hai trovato utile il nostro aiuto, puoi ringraziarci con qualsiasi importo utilizzando [questo modulo](https://safezone.cc/donate/) o puoi lasciare un feedback in [Guestbook.](https://github.com/dragokas/hijackthis/issues/47)**

Yes Thanks! I'm new here

**Comment by Sandor-Helper** [comment]
OK, waiting for CollectionLog.zip attached to your next post.

**Comment by Capitanbetter** [comment]
[
[CollectionLog-2021.07.28-16.23.zip](https://github.com/dragokas/hijackthis/files/6893824/CollectionLog-2021.07.28-16.23.zip)
](url)

**Comment by Sandor-Helper** [comment]
Uninstall PUPs (potentially unwanted progs):

> RogueKiller version 15.0.8.0
> WinZip 25.0
> Wise Registry Cleaner 10.4.1

Next:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by Capitanbetter** [comment]
ok done! 

Oh by the way, besides the multiple windows and programs that open, I noticed that on internet browsers the "send" command on the numeric keypad no longer works.

I attach the log below



# Malwarebytes AdwCleaner 8.3.0.0
# -------------------------------
# Build:    06-29-2021
# Database: 2021-06-29.1 (Local)
# Support:  https://www.malwarebytes.com/support
#
# -------------------------------
# Mode: Scan
# -------------------------------
# Start:    07-28-2021
# Duration: 00:00:09
# OS:       Windows 10 Home
# Scanned:  31978
# Detected: 0


***** [ Services ] *****

No malicious services found.

***** [ Folders ] *****

No malicious folders found.

***** [ Files ] *****

No malicious files found.

***** [ DLL ] *****

No malicious DLLs found.

***** [ WMI ] *****

No malicious WMI found.

***** [ Shortcuts ] *****

No malicious shortcuts found.

***** [ Tasks ] *****

No malicious tasks found.

***** [ Registry ] *****

No malicious registry entries found.

***** [ Chromium (and derivatives) ] *****

No malicious Chromium entries found.

***** [ Chromium URLs ] *****

No malicious Chromium URLs found.

***** [ Firefox (and derivatives) ] *****

No malicious Firefox entries found.

***** [ Firefox URLs ] *****

No malicious Firefox URLs found.

***** [ Hosts File Entries ] *****

No malicious hosts file entries found.

***** [ Preinstalled Software ] *****

No Preinstalled Software found.


AdwCleaner[S00].txt - [13667 octets] - [28/07/2021 12:36:42]
AdwCleaner[C00].txt - [6787 octets] - [28/07/2021 12:37:00]
AdwCleaner[S01].txt - [7330 octets] - [28/07/2021 20:56:06]
AdwCleaner[C01].txt - [8129 octets] - [28/07/2021 20:56:28]

########## EOF - C:\AdwCleaner\Logs\AdwCleaner[S02].txt ##########

**Comment by Capitanbetter** [comment]
I also noticed that when I try to move any folder (holding down the left mouse button) it opens it countless times

**Comment by Capitanbetter** [comment]
in addition when I click on the x to close the folder opens me others in bursts

**Comment by Sandor-Helper** [comment]
Rather than insert contents of log in message, please attach logs via drag & drop.
I'd like to see AdwCleaner[C00].txt and AdwCleaner[C01].txt logs.


> it opens it countless times

Seems that this is mouse problem. Try to find and use another known good one.

Additionally:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
