### ISSUE TITLE
Browser Hijack Software Scanner

### ISSUE THREAD

**Issue by pilarchip** [dragokas/hijackthis#16]
Welcome !
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Are you in the right place?

  * Do you need assistance in PC cure from viruses?
  * Or would you like to report a bug or propose a feature for HiJackThis?

If yes, see the next step.

### Step 2: Show us required logs (for PC cure):

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details:

1. What did you done before the problem occurs: _________________
2. What programs (browsers) affected by the problem: ________________
3. Steps to reproduce: _________________

**Comment by pilarchip** [comment]
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/1629157/HiJackThis.log)
WHen I enter a "search string in the Chrome browser and press enter instead of google opening and showing me a list of links I get a list of links from yahoo search. The same thing happens when I open google.com. It seems like only chrome, although I seldom use firefox. Both are the latest versions.

The steps to reproduce are just as I have described above.

**Comment by dragokas** [comment]
Hi, pilarchip!

I see you closed the ticket. Do you need further assistence?
If so, please, prepare CollectionLog, as described in [this instruction.](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

**Comment by dragokas** [comment]
No answer for 10 days. Closed.
If you need to re-open your case, please, ask in PM to one of VIRUSNET members.
