### ISSUE TITLE
Windows 10 crashing and not booting automatically after processor upgrade

### ISSUE THREAD

**Issue by GTavoxD** [dragokas/hijackthis#160]
Hello!,

This is my first time posting an issue on github, so let me explain it.

First of all i got a lot of issues on booting my pc, i need to manually press F11 or going directly to BIOS to choose the bootable device (even if priorities changed on BIOS), also i got some PC crashes causing reboot after upgrading processor I9 10900KF to 11900K on MSI Z490 Godlike MOBO

Some other affections are:
* Lower FPS per example, Warzone from AVG 130-140 to 90-110
* Visually lagging animations while using windows (moving windows, etc.)

I hope someone can help me, Thanks!

**Comment by GTavoxD** [comment]
[CollectionLog-2021.08.18-15.34.zip](https://github.com/dragokas/hijackthis/files/7010923/CollectionLog-2021.08.18-15.34.zip)

**Comment by Sandor-Helper** [comment]
Hello and welcome!

I didn't find any malicious traces in logs so far. Lets get more logs:

Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by GTavoxD** [comment]
> Hello and welcome!
> 
> I didn't find any malicious traces in logs so far. Lets get more logs:
> 
> Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.
> 
> **Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.
> 
> * Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
> * Press **Scan** button.
> * It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
> * Please attach the logs back here.



> Hello and welcome!
> 
> I didn't find any malicious traces in logs so far. Lets get more logs:
> 
> Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.
> 
> **Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.
> 
> * Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
> * Press **Scan** button.
> * It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
> * Please attach the logs back here.

[Addition.txt](https://github.com/dragokas/hijackthis/files/7014775/Addition.txt)
[FRST.txt](https://github.com/dragokas/hijackthis/files/7014776/FRST.txt)

**Comment by Sandor-Helper** [comment]
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
SystemRestore: On
CreateRestorePoint:
HKU\S-1-5-21-3317686729-3182039643-497015630-1001\...\MountPoints2: {10068910-7b6f-11eb-93d4-e45e3701ba66} - "F:\DVDSetup.exe" 
HKU\S-1-5-21-3317686729-3182039643-497015630-1001\...\MountPoints2: {298922bd-9872-11eb-9412-806e6f6e6963} - "E:\WD Drive Unlock.exe" autoplay=true
GroupPolicy\User: Restriction ? <==== ATTENTION
CHR HomePage: Default -> hxxp://www.mystartsearch.com/?type=sy&ts=1439660043&z=e29b0d078a9d9f8d1f2b086gazdc2teqawft0taw1c&from=cmi&uid=WDCXWD5000AADS-00S9B0_WD-WCAV9012231422314
FirewallRules: [{35CAE67A-A5F2-48C3-A80F-FB675348E82A}] => (Allow) LPort=57209
FirewallRules: [{CACC3E18-E35C-480A-9FCB-160F81FF46EB}] => (Allow) LPort=57209
FirewallRules: [{3DE7B1DC-DCFA-4E31-9B0B-FDE50BCCEE44}] => (Allow) LPort=3074
FirewallRules: [{25C88012-D4B0-4D2D-97E8-14586E742A87}] => (Allow) LPort=27036
FirewallRules: [{73B38605-3671-4464-80F5-05F39EEFB4C2}] => (Allow) LPort=32682
FirewallRules: [{3E97D711-9A69-447E-979F-20D0782C6786}] => (Allow) LPort=32682
FirewallRules: [{CC497B24-F402-46F7-99CC-521DF9E3653F}] => (Allow) LPort=26822
cmd: sfc /scannow
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by GTavoxD** [comment]
> Temporarily turn off any antivirus.
> Highlight following code:
> 
> ```
> Start::
> SystemRestore: On
> CreateRestorePoint:
> HKU\S-1-5-21-3317686729-3182039643-497015630-1001\...\MountPoints2: {10068910-7b6f-11eb-93d4-e45e3701ba66} - "F:\DVDSetup.exe" 
> HKU\S-1-5-21-3317686729-3182039643-497015630-1001\...\MountPoints2: {298922bd-9872-11eb-9412-806e6f6e6963} - "E:\WD Drive Unlock.exe" autoplay=true
> GroupPolicy\User: Restriction ? <==== ATTENTION
> CHR HomePage: Default -> hxxp://www.mystartsearch.com/?type=sy&ts=1439660043&z=e29b0d078a9d9f8d1f2b086gazdc2teqawft0taw1c&from=cmi&uid=WDCXWD5000AADS-00S9B0_WD-WCAV9012231422314
> FirewallRules: [{35CAE67A-A5F2-48C3-A80F-FB675348E82A}] => (Allow) LPort=57209
> FirewallRules: [{CACC3E18-E35C-480A-9FCB-160F81FF46EB}] => (Allow) LPort=57209
> FirewallRules: [{3DE7B1DC-DCFA-4E31-9B0B-FDE50BCCEE44}] => (Allow) LPort=3074
> FirewallRules: [{25C88012-D4B0-4D2D-97E8-14586E742A87}] => (Allow) LPort=27036
> FirewallRules: [{73B38605-3671-4464-80F5-05F39EEFB4C2}] => (Allow) LPort=32682
> FirewallRules: [{3E97D711-9A69-447E-979F-20D0782C6786}] => (Allow) LPort=32682
> FirewallRules: [{CC497B24-F402-46F7-99CC-521DF9E3653F}] => (Allow) LPort=26822
> cmd: sfc /scannow
> EmptyTemp:
> Reboot:
> End::
> ```
> 
> Copy highlighted text (right click - Copy).
> Run FRST (FRST64) as Administrator.
> Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.
> 
> PC will reboot.

[Fixlog.txt](https://github.com/dragokas/hijackthis/files/7015004/Fixlog.txt)

**Comment by GTavoxD** [comment]
After restart i still keep getting black screen boot loop with MOBO Codes 67 and A2. I need to keep pressing F11 on startup to manually select boot device.

**Comment by dragokas** [comment]
Hi,
it seems your PC problem is hardware-related.
We only deal with malware-related issues. It is not likely the case.
For further assistance, we recommend you to ask for help on the forums that provide help in resolving general operating system and hardware issues, like:
 - https://www.tenforums.com
 - https://www.eightforums.com
 - https://www.sevenforums.com/
 - https://answers.microsoft.com/
 - http://www.geekstogo.com/forum/forum/41-operating-systems/
