### ISSUE TITLE
help me computer is slow but taskmanager shows nothing 

### ISSUE THREAD

**Issue by Barknwoof** [dragokas/hijackthis#161]
umm my pc is clearly new, but recently my mouse clicks arent registering as well like 1/3rd of click register but the same mouse works flawlessly in other pc and taskmanager shows 100% while startup and then goes down to 6 or 7 percent 
[CollectionLog-2021.08.30-18.44.zip](https://github.com/dragokas/hijackthis/files/7076919/CollectionLog-2021.08.30-18.44.zip)

**Comment by Sandor-Helper** [comment]
Hello and welcome,

Do you know this folder and file?
> D:\Windows stuff\TaskbarX\TaskbarX.exe

And did you install this prog by yourself?
> ScpToolkit

Try to run Windows in [safe mode](https://support.microsoft.com/en-us/windows/start-your-pc-in-safe-mode-in-windows-10-92c27cff-db89-8644-1ce4-b3e5e56fe234) and see - will the mouse behave the same?

**Comment by Barknwoof** [comment]
thanks forur reply but i found out the root of the problem after resetting
my pc, it was caused by an app called "Modern Flyouts" hogging up all the
ram and cpu usage, the minute i installed it again on my reinstalled pc it
started to do the same thing again so.... dont install modern flyouts from
the microsoft store. scp toolkit is a playstation controller setup
application and i did install it myself and i do know bout the taskbarx
