### ISSUE TITLE
Hijack Log: please help

### ISSUE THREAD

**Issue by sem38x** [dragokas/hijackthis#162]

**Comment by sem38x** [comment]
[log is removed]

**Comment by sem38x** [comment]
[log is removed]

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip)

  * Describe your problem in detail.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by sem38x** [comment]
I downloaded and installed a program where I had to change a reg file, after that my email and my steam account were accessed by a third party. I think I have a trojan or virus but my anti-virus programs do not recognize anything because I think it is crypted

**Comment by sem38x** [comment]
x

**Comment by sem38x** [comment]
Download Link: https://www.xup.in/dl,11328011/CollectionLog-2021.09.17-19.08.zip/
Delete Link: https://www.xup.in/kill,11328011,539d0e374f/

**Comment by dragokas** [comment]
The log you provided is inaccessible.
Please, attach it directly to your post.

![image](https://user-images.githubusercontent.com/19956568/133829778-f255a511-f548-4d49-8c00-abc6d7a33d0c.png)

**Comment by sem38x** [comment]
[CollectionLog-2021.09.17-19.08.zip](https://github.com/dragokas/hijackthis/files/7187411/CollectionLog-2021.09.17-19.08.zip)

**Comment by sem38x** [comment]
the programm that i had installed was adobe i deleted this files 

  1  C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\acrotray.exe
   1  C:\Program Files (x86)\Common Files\Adobe\ARM\1.0\armsvc.exe
   1  C:\Program Files (x86)\Common Files\Adobe\AdobeGCClient\AGMService.exe
   1  C:\Program Files (x86)\Common Files\Adobe\AdobeGCClient\AGSService.exe

is there are any more suspicious files?

**Comment by Sandor-Helper** [comment]
Hello,

I didn't find any malicious traces in logs.


> my email and my steam account were accessed by a third party

You have to change passwords and use 2FA where it is possible.
Do not use several antiviruses at the same time. Now I see:
```
Malwarebytes version 4.4.5.130
McAfee LiveSafe
TotalAV
```

Leave just one.

One more check will be good:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
