### ISSUE TITLE
Virustotal.com detection in prebuilt binary

### ISSUE THREAD

**Issue by Hunanbean** [dragokas/hijackthis#165]
Virustotal.com  Cyren detects W32/Rozena.D.gen!Eldorado in the precompiled binary linked to from this page.

Of course i assume a false positive, but an explanation would be appreciated.

Thank you

**Comment by dragokas** [comment]
Hi.
We don't provide explanations.
Please, report about false positive to Cyren.
Here are all the required links and conditions: https://safezone.cc/threads/kuda-soobschit-o-lozhnom-srabatyvanii-antivirusa.23501/
And thanks for informing us.
Best regards.

**Comment by dragokas** [comment]
Solved.
