### ISSUE TITLE
Virus hijacked google account via browser

### ISSUE THREAD

**Issue by ltolstoy** [dragokas/hijackthis#166]
I have an issue with my Win 10 laptop, Chrome v90 browser. I start receiving emails that somebody is changing my  gmail password, etc. I run some cleaning software before, it erased some viruses , but my hosts file (reported as modified by DrWeb CureIt antivirus) located in 
C:\Windows\System32\drivers\etc\hosts file has this line (which re-appears even after I delete it manually):
c127.0.0.1       CF-LRC-141A-JW.LSCS.prv # LMS GENERATED LINE
and also WIndows->Settings shows "Some settings are managed by your organization" while I don't have any accounts in "Access Work or School". So I think that something was not cleaned completely.
Please suggest.
[CollectionLog-2021.11.10-15.26.zip](https://github.com/dragokas/hijackthis/files/7516350/CollectionLog-2021.11.10-15.26.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

I didn't find any malicious traces in logs so far. Just several orphan links.

Click on **CheckBrowserLnk.log** from folder 
`C:\downloads\antivirusi\Autologger\AutoLogger\CheckBrowserLnk` 
drag and drop it onto [ClearLNK](https://dragokas.com/tools/ClearLNK.zip).
Like this:
https://dragokas.com/tools/move.gif

You'll get **ClearLNK-<Date>.log**. Attach it to your next post.

Second - lets take more logs:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by ltolstoy** [comment]
Thank you for the answer, @Sandor-Helper. 
Here are logs you requested.

[ClearLNK-2021.11.11_08.48.58.log](https://github.com/dragokas/hijackthis/files/7521585/ClearLNK-2021.11.11_08.48.58.log)
[FRST.txt](https://github.com/dragokas/hijackthis/files/7521587/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/7521588/Addition.txt)

**Comment by Sandor-Helper** [comment]
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CreateRestorePoint:
HKLM\SOFTWARE\Policies\Microsoft\Windows Defender: Restriction <==== ATTENTION
GroupPolicy: Restriction ? <==== ATTENTION
Policies: C:\ProgramData\NTUSER.pol: Restriction <==== ATTENTION
HKLM\SOFTWARE\Policies\Mozilla\Firefox: Restriction <==== ATTENTION
Task: C:\Windows\Tasks\{50C925ED-D5D8-C8F7-685C-25C3265BDEED}.job => C:\Users\HP-owner\AppData\Local\Mepat\updtask.exe <==== ATTENTION
Hosts:
FirewallRules: [TCP Query User{4889A7DE-FFAB-4099-A08C-D58C5490BFE2}C:\downloads\transmissionportable\app\transmission\transmission-qt.exe] => (Allow) C:\downloads\transmissionportable\app\transmission\transmission-qt.exe => No File
FirewallRules: [UDP Query User{1C13667A-1620-4DE8-84A9-DCB42DADECBF}C:\downloads\transmissionportable\app\transmission\transmission-qt.exe] => (Allow) C:\downloads\transmissionportable\app\transmission\transmission-qt.exe => No File
FirewallRules: [{8FE291E9-AD25-4659-AEEF-3E85EFA69117}] => (Allow) C:\Program Files (x86)\Steam\Steam.exe => No File
FirewallRules: [{674DE509-A623-4966-9F37-EB8BA66FAF0D}] => (Allow) C:\Program Files (x86)\Steam\Steam.exe => No File
FirewallRules: [{5EE178A3-8B05-47C8-9F95-01E4F31974D7}] => (Allow) C:\Program Files (x86)\Steam\bin\cef\cef.win7\steamwebhelper.exe => No File
FirewallRules: [{64764239-9142-4A88-840E-701E14DCB9C7}] => (Allow) C:\Program Files (x86)\Steam\bin\cef\cef.win7\steamwebhelper.exe => No File
FirewallRules: [TCP Query User{B8255797-C071-443F-A737-9D7FAA2450F6}C:\downloads\transmissionportable\app\transmission\transmission-qt.exe] => (Allow) C:\downloads\transmissionportable\app\transmission\transmission-qt.exe => No File
FirewallRules: [UDP Query User{321DAEB0-F9F4-474C-8B27-30397CE629B9}C:\downloads\transmissionportable\app\transmission\transmission-qt.exe] => (Allow) C:\downloads\transmissionportable\app\transmission\transmission-qt.exe => No File
FirewallRules: [{49303428-D972-4DC6-A57B-D8C2200DE128}] => (Allow) C:\Program Files (x86)\AnyDesk\AnyDesk.exe => No File
FirewallRules: [{5F831CFA-B1BA-4BCD-8625-EF06CC921FB3}] => (Allow) C:\Program Files (x86)\AnyDesk\AnyDesk.exe => No File
FirewallRules: [{105DED3B-C8DB-4B93-BBA4-74220B98E32C}] => (Allow) C:\Program Files (x86)\AnyDesk\AnyDesk.exe => No File
FirewallRules: [{4C39A268-E372-4FB5-BCD6-6CABCA8D4A69}] => (Allow) C:\Program Files (x86)\AnyDesk\AnyDesk.exe => No File
FirewallRules: [{AAF80E81-8F1B-4F6B-82C3-23FF5F3C58DF}] => (Allow) C:\Program Files (x86)\AnyDesk\AnyDesk.exe => No File
FirewallRules: [{8A798295-19F4-4EC7-B3A2-646072445A8C}] => (Allow) C:\Program Files (x86)\AnyDesk\AnyDesk.exe => No File
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

Main antivirus in the system is Avast, so uninstall Bitdefender Agent will be good idea.

**Comment by ltolstoy** [comment]
Thank you for the answer, @Sandor-Helper.
Here is log you requested, again. I just uninstalled Bitdefender Agent.
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/7528569/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
Thank you for the log. Is Hosts file changed now?

> I start receiving emails that somebody is changing my gmail password, etc.

It'll be good to enable 2FA where it is possible.

**Comment by ltolstoy** [comment]
Sure, I enabled 2FA where this option is available. It's kind of late, but any way it is useful, in a long run (less convenient, but more secure). My host file still changes, the same line
`127.0.0.1       CF-LRC-141A-JW.LSCS.prv # LMS GENERATED LINE`
is there... My laptop has LMS executable in `C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\LMS`, just not sure why would it change host file (if it really is the program that does it and not a virus effect).
Also, WIndows->Settings->General still shows "Some settings are managed by your organization"  notification on the top.

**Comment by Sandor-Helper** [comment]
Please delete old and create new FRST.txt and Addition.txt logs by FRST and attach them to your next post.

**Comment by Sandor-Helper** [comment]
> if it really is the program that does it and not a virus effect

Seems that you are right. Here what I "googled":
`LMS generates this line when there is a mismatch between the OS FQDN and the Intel® ME FQDN. This can happen, for example, when you swap hard drives between computers.`

**Comment by ltolstoy** [comment]
Thank you for the answer, @Sandor-Helper. 
I read about LMS.exe and uninstalled it (i.e  Active Management Technology by Intel), looks like Win10 can work without it pretty well.
So now hosts file doesn't have this line, and it doesn't re-appear after reboot.
Now the only suspicious thing left is this
WIndows->Settings->General still shows "Some settings are managed by your organization" notification on the top.
Actually, I can't change Control Panel\System and Security\System\Advanced system settings ->Computer Name tab->Network ID-> Join a Domain or Workgroup window -> "This is a home computer; it's not a part of a business network".
After reboot it goes back to "This computer is part of a business network; I use it to connect to other computers at work" option. 
May be there is something else, deeper, but I don't notice.
[FRST.txt](https://github.com/dragokas/hijackthis/files/7547568/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/7547569/Addition.txt)

**Comment by Sandor-Helper** [comment]
Thank you for the logs. Nothing suspicious.
Lets deal with antivirus.
Temporarily unistall Avast and all its components. After that clean system with its [special tool](https://files.avast.com/files/eng/aswclear.exe) in Safe mode.
In logs I see traces of BitDefender. Here [the tool](https://www.bitdefender.com/files/KnowledgeBase/file/BitDefender_Uninstall_Tool.exe) to clean it. You can use it in Normal mode. 
And at last clean traces of Malwarebytes by its [own tool](https://downloads.malwarebytes.com/file/mbst).
After that cleaning see if mentioned message gone.

**Comment by ltolstoy** [comment]
Thank you for the answer, @Sandor-Helper.
Hm, it looks like this message is gone now!
Thanks a lot!

**Comment by Sandor-Helper** [comment]
Glad to hear it.

Rename FRST.exe (FRST64.exe) to **uninstall.exe** and run it. PC will reboot.
Other tools and folders you can simply delete. But before that please check the vulnerabilities.
Download [SecurityCheck](https://tools.safezone.cc/glax24/SecurityCheck/SecurityCheckH.zip), unzip it and run. It will scan your system and get the html report with probable things needed to update.

**Comment by ltolstoy** [comment]
Done.
SecurityCheck scan suggests to update Windows to 21H2. I have 2016 LTSB at the moment.
