### ISSUE TITLE
Suspicious HiJackThis entries

### ISSUE THREAD

**Issue by devinmcmanus** [dragokas/hijackthis#17]
Hi everybody,
First off, I'm running an older Windows 7 machine (purchased over 5 years ago). As expected, it's slowed down over time. Recently, it's moving at a snails pace. I decided to run a quick HiJackThis scan just to see if anything fishy was going on and found at least one entry that seemed a little off. Any help would be much appreciated.

[CollectionLog-2018.01.23-05.41.zip](https://github.com/dragokas/hijackthis/files/1655526/CollectionLog-2018.01.23-05.41.zip)

**Comment by Sandor-Helper** [comment]
Hello and welcome,

I didn't find any malicious record in logs, but lets do a couple of things:

1. Uninstall
`Spybot - Search & Destroy`
via Control Panel - Uninstall a program

2. Start system in Safe Mode and do an observation - is it running faster?

**Comment by dragokas** [comment]
No answer for 10 days. Closed.
If you need to re-open your case, please, send new message into this topic.
