### ISSUE TITLE
Windows update 8.1 it's no working . Malware action.

### ISSUE THREAD

**Issue by dandjro** [dragokas/hijackthis#171]
I think my PC has malware.
Windows update doesn't work.
When trying to upgrade to windows 10 I get an error.

Attached is the HijackThis log and also a file that comes out when I click Advanced Firewall Settings. Instead of opening the advanced configuration window, this file wf.msc is opened.
[WF.zip](https://github.com/dragokas/hijackthis/files/7869330/WF.zip)

I am also attaching a snippet of the firewall screen where I have the problem that I do not have full control: "For security, the system administrator manages certain settings."
![Firewall configuracion avanzada](https://user-images.githubusercontent.com/97730018/149493238-60163950-0faf-4cb6-af18-643470a7701e.PNG)

Thanks

[HiJackThis.log](https://github.com/dragokas/hijackthis/files/7869293/HiJackThis.log)

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download)
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
