### ISSUE TITLE
Check PC

### ISSUE THREAD

**Issue by Giovy2497** [dragokas/hijackthis#172]
Hi, Last week my pc didn't turn off so I make log to check the pc
[CollectionLog-2022.02.22-12.22.zip](https://github.com/dragokas/hijackthis/files/8116356/CollectionLog-2022.02.22-12.22.zip)
.

**Comment by Sandor-Helper** [comment]
Hello and welcome!

I didn't see a serious issues so far, but there are some kind of adware and unwanted progs wich we will clean in next few steps.

1. Please go to Parameters -> Programs and uninstal potentially unwanted

> Bonjour
> Defraggler
> Driver Booster 8
> SUPERAntiSpyware
> Wondershare Helper Compact 2.5.2

Restart your PC after that.

2. Run HiJackThis from this location:

E:\Download\Chrome\AutoLogger\AutoLogger\HiJackThis\HiJackThis.exe
Choose "Do a system scan only"
Mark only these records:

> R1 - HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings: [ProxyOverride] = *.local
> O1 - Hosts: Reset contents to default
> O15 - Trusted Zone: http://webcompanion.com

And press **Fix selected**.

Restart your PC once again.

3. Lets grab more logs.

Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
