### ISSUE TITLE
Suspision of hacking netflix account

### ISSUE THREAD

**Issue by CoolEdgY** [dragokas/hijackthis#176]
Hi all, 

So I saw today that I had a new user created in my netflix account. 
I quickly looked into Netflix's history and saw over the last couple of weeks that there had been users from China and other places over the world that had been using the account. 
I don't even know anyone in China - so I'm very sure that this is some time of hacking.

I have two computers and a friend I share the netflix account with.
I have already changed the password and forced all devices to log out.

But I feel I still need to do a full security sweep. 

I did a virus check - nothing found. 

But i'm still very suspicious, and haven't found out how exactly they got into the account. 

I'm logging a HiJackthis log from my main computer and would love to hear if you see anything suspicious. 

[hijackthis.log](https://github.com/dragokas/hijackthis/files/8255497/hijackthis.log)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
