### ISSUE TITLE
Mark everything found for fixing after check doesn't work

### ISSUE THREAD

**Issue by ghost** [dragokas/hijackthis#18]
Hi,

Everything is in the title!!
Mark everything found for fixing after check doesn't work in admin exe launch or not.

Windows 10 Pro 10 build 16299  

Thanks a lot for your work dragokas.

ps : I use Hijackthis only to check new entry at computer startup and detect normal/abnormal setup since last session. This software do the job very well.

Best regards,

**Comment by dragokas** [comment]
v2.8.0.1 - bug is confirmed. Will be fixed soon. Thanks for reporting.

**Comment by ghost** [comment]
Great happy to help your software robustness...

**Comment by dragokas** [comment]
Fixed in 2.8.0.2.
Test version available by the link: https://dragokas.com/tools/HiJackThis_test.zip

**Comment by ghost** [comment]
Thanx, work for me.
