### ISSUE TITLE
System laging some time, strange browsing, no smooth network

### ISSUE THREAD

**Issue by PSYOLOT** [dragokas/hijackthis#180]
Describe the cure

1.    System is not runing straight all the way
2.    Firefox browsing, useing google search
3.    when you click on the search result, you are redirected to an absurd website, the back button takes you to bing.de
    during gaming counter-strike 1.6 (old FPS egoshooter)online i get micro lags
3.    doing chat talk over ip Discord, sometimes partners voice is lagging. only i hear the lag not the other ones.
4.    many errors at windows event viewer - Administrative events
5.    ms Edge isn´t runing perfektly

issue more detail:

1.    how to explain.... i guess is to full of rubbish. evan crash down on sleepmode and evan get stock on reboot infrequent.
2.    if i´m browsing on mozilla firefox by useing google research and klicking one of the searcresults it transfares me to n unaspected site infrequently. and if then i do use the back button i get transfare to n bing.de result.
3.    online gaming get micro lags and doesn´t run smoothly constantly.
    voice chating with Discord: i don´t hear the partner continuously when chatting. but the other clients in chanel didn´t have this problems. by the way, my voice is not laging at all.
4.    earn many errors to see in Administrative events. for example:

ERROR: kernal eventtraceing: The PerfDiag Logger session terminated due to the following error: 0xC0000188.

ERROR: Aplication hang : The msedge.exe version 96.0.1054.62 program has stopped interacting with Windows and has been closed. Check the problem history in the Security and Maintenance Control Panel to find more information about the problem.
Process ID: 2964
Start time: 01d84c4da29d113d
Termination time: 4294967295
Application path: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Report ID: 121246ac-4881-4ddc-b497-a2ddb0e0eaa0
Full name of the faulty package:
Relative Application ID of the faulty package:
Crash type: Top level window is idle
Expected behavior

ERROR: kernal eventtraceing: The following error occurred when starting session 'Microsoft.Windows.Remediation': 0xC0000035.

ERROR: Windows updateclient : Installation Error: Installation of the following update failed with error 0x80240017: Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.363.99.0)

ERROR: kernal eventtraceing: The PerfDiag Logger session terminated due to the following error: 0xC0000188.

ERROR: kernal eventtraceing: Failed to set properties for provider {8444a4fb-d8d3-4f38-84f8-89960a1ef12f}. Error: 0xC0000001

evan Aplicatin errors:

ERROR: Aplication error : Faulting application name: nmap.exe, version: 7.0.70.0, timestamp: 0x603367c4
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1620, timestamp: 0xa3eae062
Exception code: 0xc06d007e
Error offset: 0x0012b922
Faulting process ID: 0x15c0
Faulting application start time: 0x01d84c4711a84516
Faulting application path: C:\Program Files (x86)\Trend Micro\DRScanner\sdk\nmap\nmap.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 5f58ccd6-f33f-4d73-ba51-5754b996a3f9
Full name of the faulty package: (empty no text here)
Application ID relative to the faulty package: (empty no text here)

ERROR: Aplication error : Faulting application name: Origin.exe, version: 10.5.111.50299, timestamp: 0x6215c00d
Faulting module name: Qt5Core.dll, version: 5.8.0.0, timestamp: 0x5cfe7d03
Exception code: 0xc0000005
Error offset: 0x0009d9ab
Faulting process ID: 0x32e0
Faulting application start time: 0x01d84b9606cec0e5
Faulting application path: C:\Program Files (x86)\Origin\Origin.exe
Faulting module path: C:\Program Files (x86)\Origin\Qt5Core.dll
Report ID: 71e58845-826e-4818-90a3-58bd896aff6d
Full name of the faulty package:
Application ID relative to the faulty package:

and so on!

5. if i´ll open ms Edge browser i can´t restore last session. an issue window pops up.(screenshot popupMSedge)

Desktop (please complete the following information):

    OS: windows 10
    HJT Version 2.10.0.17
   Browser: Mozilla Firefox 99.0 plugins Ghostery; uBlock Origin: i don´t care about cookies

Additional context
i hope there are not to many garbage in the windows REG

my english isn´t that good, plz be indulgent with me and google translate

you can see i´m fare a way to be computer expert. i use windows mostly to playing arround doing daily stuff. i do use macOS most of my life.
so it would be so helpfull get some tips from u guys.
Please forgive me if i can´t answare right away consistently, my working periods are not consistent
![POPUPmsEDGE](https://user-images.githubusercontent.com/4714613/162861201-3a850af9-54ae-418f-be03-7ed9a3bebf77.png)
[CollectionLog-2022.04.12-03.16.zip](https://github.com/dragokas/hijackthis/files/8468819/CollectionLog-2022.04.12-03.16.zip)
.

**Comment by Sandor-Helper** [comment]
Hello and welcome!

Please go to Parameters -> Apps select and uninstall

> Bonjour

Even if you use an Apple applications, you don't need it.

Next:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by PSYOLOT** [comment]
-bonjour uninstalled
-adwcleaner 3 files in quarantai
[AdwCleaner[C04].txt](https://github.com/dragokas/hijackthis/files/8498052/AdwCleaner.C04.txt)
[AdwCleaner[C03].txt](https://github.com/dragokas/hijackthis/files/8498053/AdwCleaner.C03.txt)
[AdwCleaner[S03].txt](https://github.com/dragokas/hijackthis/files/8498054/AdwCleaner.S03.txt)
n

**Comment by Sandor-Helper** [comment]
OK, thanks for the logs.
Lets go further.

Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by PSYOLOT** [comment]
[FRST.txt](https://github.com/dragokas/hijackthis/files/8504726/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/8504727/Addition.txt)
n

**Comment by Sandor-Helper** [comment]
Bonjour - is still pesist in applications list. Please uninstall it.
If it don't uninstalled usual way, try to force uninstall using [Geek Uninstaller](http://www.geekuninstaller.com/geek.zip)

Next:

Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CreateRestorePoint:
HKLM\SOFTWARE\Policies\Microsoft\Windows Defender: Beschränkung <==== ACHTUNG
Policies: C:\ProgramData\NTUSER.pol: Beschränkung <==== ACHTUNG
HKLM\SOFTWARE\Policies\Google: Beschränkung <==== ACHTUNG
HKLM\SOFTWARE\Policies\Microsoft\Edge: Beschränkung <==== ACHTUNG
FF user.js: detected! => C:\Users\schre\AppData\Roaming\Mozilla\Firefox\Profiles\n2ha0ya6.default-release\user.js [2022-04-15]
2022-04-16 22:25 - 2022-04-16 22:25 - 000000000 ____D C:\Program Files\Bonjour
2022-04-16 22:25 - 2022-04-16 22:25 - 000000000 ____D C:\Program Files (x86)\Bonjour
AlternateDataStreams: C:\Users\schre\Anwendungsdaten:00e481b5e22dbe1f649fcddd505d3eb7 [394]
AlternateDataStreams: C:\Users\schre\AppData\Roaming:00e481b5e22dbe1f649fcddd505d3eb7 [394]
C:\Windows\Temp\*.*
C:\WINDOWS\system32\*.tmp
C:\WINDOWS\syswow64\*.tmp
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by PSYOLOT** [comment]
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/8505193/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
Please do one more scan.

Download [Malwarebytes v.4](https://downloads.malwarebytes.com/file/mb-windows). Install and run.
(Use free version).
Run Scan and wait untill it ends.

Press "Save to text (*.txt)". Name log as you wish, "scan" for exapmle.
Attach log to your next post.

**Comment by PSYOLOT** [comment]
after first scan, 810 items found, next step : put quarantain; saved in log
[MBAMSERVICE.LOG](https://github.com/dragokas/hijackthis/files/8548429/MBAMSERVICE.LOG)

**Comment by PSYOLOT** [comment]
there was no save as. i hope is okay?

**Comment by PSYOLOT** [comment]
i´m sorry, windows did n update yesturday 
Kumulatives Update KB5012117 vom 12. April 2022 für .NET Framework 3.5 und 4.8 unter Windows 10 Version 20H2, Windows Server Version 20H2, Windows 10 Version 21H1 und Windows 10 Version 21H2

**Comment by Sandor-Helper** [comment]
> after first scan, 810 items found, next step : put quarantain; saved in log [MBAMSERVICE.LOG](https://github.com/dragokas/hijackthis/files/8548429/MBAMSERVICE.LOG)

Please do another scan now in Malwarebytes, save result log in text format and attach it.

**Comment by PSYOLOT** [comment]
[scan.txt](https://github.com/dragokas/hijackthis/files/8550232/scan.txt)

**Comment by Sandor-Helper** [comment]
You did something wrong.
When scan is finished you could see something like this (it in Russian)
![Screenshot_11](https://user-images.githubusercontent.com/31479044/165268312-b65b9b94-73e2-466e-8baa-7f641212248b.png)
Red arrow point to Save button and you should choose **Text file**.

**Comment by Sandor-Helper** [comment]
Here the explanation from Malwarebytes itself
https://support.malwarebytes.com/hc/en-us/articles/360038479194-View-Reports-and-History-in-Malwarebytes-for-Windows-v4

**Comment by PSYOLOT** [comment]
ok i ´ll try that if i´m back. coz i´ve to trevel untill 11.05. 
is that okay to continue at 11.05?

**Comment by PSYOLOT** [comment]
ok i ´ll try that if i´m back. coz i´ve to trevel untill 11.05. 
is that okay to continue at 11.05
[scan.txt](https://github.com/dragokas/hijackthis/files/8567795/scan.txt)
?

**Comment by Sandor-Helper** [comment]
Sure it's okay.
The log is correct now and Malwarebytes find nothing suspisious.

When you have enough time lets get another scan:

Download [Microsoft Safety Scanner](https://go.microsoft.com/fwlink/?LinkId=212732) and run it.

In the **Scan Options** choose **FULL scan**.

Have much patience, scan could get several hours. Wait till it ends.
Find log named **MSERT.log** in this folder C:\Windows\debug\msert.log

Attach it to your next post.

**Comment by PSYOLOT** [comment]
[msert.log](https://github.com/dragokas/hijackthis/files/8600896/msert.log)

**Comment by Sandor-Helper** [comment]
All is clean here also.

`if i´m browsing on mozilla firefox`

Try to do a [default reset of Mozilla](https://support.mozilla.org/ru/kb/sbros-firefox-lyogkoe-reshenie-bolshinstva-problem)

**Comment by PSYOLOT** [comment]
okay, thank u very much. thx 4 doing support us!
cU
