### ISSUE TITLE
hijackthis log help

### ISSUE THREAD

**Issue by gaucho1978** [dragokas/hijackthis#181]
which lines should i remove from my pc?
this is my log:
[myLog.txt](https://github.com/dragokas/hijackthis/files/8502025/myLog.txt)

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download)
(It include HiJackThis.log as well).
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by gaucho1978** [comment]
Instructions about  where to upload log file Is not clear. A automatic suggestion should be displayed, as it was in the past. 
about my log: I fixed all records then i uninstalled all programs, External antivirus included. It works better now.

**Comment by Sandor-Helper** [comment]
Attach CollectionLog.zip staight to you next post (same as you did with your HiJack log).

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
