### ISSUE TITLE
HiJackThis Analysis Third Party Access to PC?

### ISSUE THREAD

**Issue by paulahelp** [dragokas/hijackthis#186]
Hello, entries in a database are repeatedly changed from my PC, although I do not access this database. I therefore suspect unauthorised access to my PC by malware that activates online connections in the background.
Does the HiJackThis-log file show automatic access to the Internet? Or other sources of error?

Thx for your help
Paulahelp

[hijackthis.log](https://github.com/dragokas/hijackthis/files/8748461/hijackthis.log)

**Comment by paulahelp** [comment]
And here are the autologger files
[CollectionLog-2022.05.22-01.15.zip](https://github.com/dragokas/hijackthis/files/8748497/CollectionLog-2022.05.22-01.15.zip)

Thx for your help.
paulahelp

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

I didn't find any signs of infection, but find such system records as:

> Message: Volume "E:" (\Device\HarddiskVolume6) muss offline geschaltet werden, um eine vollständige chkdsk-Prüfung auszuführen. Führen Sie "CHKDSK /F" lokal über die Befehlszeile oder "REPAIR-VOLUME <Laufwerk:>" lokal oder remote über PowerShell aus.
> Message: Volume "D:" (\Device\HarddiskVolume5) muss offline geschaltet werden, um eine vollständige chkdsk-Prüfung auszuführen. Führen Sie "CHKDSK /F" lokal über die Befehlszeile oder "REPAIR-VOLUME <Laufwerk:>" lokal oder remote über PowerShell aus.

Please do offerred disk check for both D and E disks.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
