### ISSUE TITLE
Hosts file entries no longer show

### ISSUE THREAD

**Issue by Boxersteavee** [dragokas/hijackthis#187]
**Describe the bug**
I help in a community who help with technical Minecraft problems. We use HiJackThis to find malicious programs or modifications to the system that can cause issues. Recently we noticed that the hosts file contents is no longer being shown even when it is modified.

**To Reproduce**
1. Add a few hosts file entries
2. Run HJT
3. Look through the log file'
4. Observe lack of hosts file entries

**Expected behavior**
Hosts file contents show, allows easy diagnostics and we can immediately notify the user to clear their hosts file.

**Desktop (please complete the following information):**
 - OS: windows 8.1 and windows 10, unsure about windows 11.
 - HJT Version: v.2.10.0.17

**Additional context**
Unsure if this was intentional or not. If it was, please understand that it was a really useful feature. If not then it was probably something in windows changed.

**Comment by dragokas** [comment]
Confirmed. Making fix...
Thanks for the info.

**Comment by dragokas** [comment]
Fixed in latest commit 2.10.0.18
https://github.com/dragokas/hijackthis/commit/f8d249307196bc52b628716b0d754339b02dcfb6

**Comment by Boxersteavee** [comment]
How do we direct users to this version? Or do we have to wait for next release?

**Comment by Boxersteavee** [comment]
Also the nightly build link on the readme.md file redirects to invalid ssl

**Comment by dragokas** [comment]
> Also the nightly build link on the readme.md file redirects to invalid ssl

Hmm, that's a new issue.

> How do we direct users to this version? Or do we have to wait for next release?

For now, you can use this link:
https://raw.githubusercontent.com/dragokas/hijackthis/devel/binary/HiJackThis.exe

**Comment by dragokas** [comment]
SSL problem is now fixed.

Do you have any other issues left?

**Comment by Boxersteavee** [comment]
Nope, all good. Thanks!
