### ISSUE TITLE
Pc software and chrome browser unable to gain access to internet except when I use Microsoft Edge then I can access websites

### ISSUE THREAD

**Issue by theuser707** [dragokas/hijackthis#189]
Sometimes the problem fixes itself (meaning all softwares and chrome browser on my pc is able to gain access) then it comes back again. Sometimes when the internet comes back and I use chrome I can only access youtube and google all other sites would time out when I tried to access it.
[CollectionLog-2022.09.14-15.13.zip](https://github.com/dragokas/hijackthis/files/9563669/CollectionLog-2022.09.14-15.13.zip)

**Comment by Sandor-Helper** [comment]
Hello,

I didn't see any obvious signs of infection so far.
Lets do some minor cleaning.

Please uninstall unwanted or obsolete software:

> Adobe Flash Player 32 PPAPI
> Bonjour

Start HiJackThis that version:
C:\Users\Tellus\Downloads\AutoLogger\AutoLogger\HiJackThis\**HiJackThis.exe**
Press "Do a system scan only" button then checkmark only following:

```
O22 - Tasks: NahimicTask32 - C:\Windows\System32\..\SysWOW64\NahimicSvc32.exe $(Arg0) $(Arg1) $(Arg2) $(Arg3) $(Arg4) $(Arg5) $(Arg6) $(Arg7) (file missing)
O22 - Tasks_Migrated: gxx speed launcher - C:\Program Files (x86)\Garena\Garena\Garena.exe -silentlaunch -gxxsvclaunch (file missing)
O22 - Tasks_Migrated: MSIAfterburner - D:\MSI Afterburner\MSIAfterburner.exe /s (file missing)
O22 - Tasks_Migrated: NahimicTask32 - C:\Windows\System32\..\SysWOW64\NahimicSvc32.exe $(Arg0) $(Arg1) $(Arg2) $(Arg3) $(Arg4) $(Arg5) $(Arg6) $(Arg7) (file missing)
```
And press "Fix checked".
Restart your PC and get more logs:

Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by theuser707** [comment]
[FRST.txt](https://github.com/dragokas/hijackthis/files/9565379/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/9565380/Addition.txt)
[CollectionLog-2022.09.14-18.22.zip](https://github.com/dragokas/hijackthis/files/9565431/CollectionLog-2022.09.14-18.22.zip)

Not sure if its a coincidence but when i turn off my windows virus & threat protection especially the option real-time protection my chrome works again and softwares on my pc could access internet.

**Comment by Sandor-Helper** [comment]
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CloseProcesses:
SystemRestore: On
CreateRestorePoint:
RemoveProxy:
HKLM\SOFTWARE\Policies\Microsoft\Windows Defender: Restriction <==== ATTENTION
Policies: C:\ProgramData\NTUSER.pol: Restriction <==== ATTENTION
CHR HKLM\...\Chrome\Extension: [miockbgloklamfiklogjaohlgekodeok]
CHR HKLM\...\Chrome\Extension: [obhdbhpjhfncnelcpknkffpdmpdcjpep]
CHR HKU\S-1-5-21-2998282684-778249462-2140900864-1001\SOFTWARE\Google\Chrome\Extensions\...\Chrome\Extension: [miockbgloklamfiklogjaohlgekodeok]
CHR HKU\S-1-5-21-2998282684-778249462-2140900864-1001\SOFTWARE\Google\Chrome\Extensions\...\Chrome\Extension: [obhdbhpjhfncnelcpknkffpdmpdcjpep]
CHR HKLM-x32\...\Chrome\Extension: [miockbgloklamfiklogjaohlgekodeok]
CHR HKLM-x32\...\Chrome\Extension: [obhdbhpjhfncnelcpknkffpdmpdcjpep]
S3 avgTap; C:\WINDOWS\System32\drivers\avgTap.sys [54888 2021-06-29] (AVG Technologies CZ, s.r.o. -> The OpenVPN Project)
ContextMenuHandlers1: [IObitUnstaler] -> {836AB26C-2DE4-41D3-AC24-4C6C2699B960} => C:\Program Files (x86)\IObit\IObit Uninstaller\IUMenuRight.dll -> No File
ContextMenuHandlers4: [IObitUnstaler] -> {836AB26C-2DE4-41D3-AC24-4C6C2699B960} => C:\Program Files (x86)\IObit\IObit Uninstaller\IUMenuRight.dll -> No File
ContextMenuHandlers6: [IObitUnstaler] -> {836AB26C-2DE4-41D3-AC24-4C6C2699B960} => C:\Program Files (x86)\IObit\IObit Uninstaller\IUMenuRight.dll -> No File
AlternateDataStreams: C:\ProgramData\acxoweqj.wmy:0BB963D514 [2586]
AlternateDataStreams: C:\ProgramData\agent.1641829198.bdinstall.v2.bin:0841BC41C0 [2586]
AlternateDataStreams: C:\ProgramData\agent.1661432732.10892.v2.bin:702C52A35F [2586]
AlternateDataStreams: C:\ProgramData\agent.1661432732.18848.v2.bin:690B2404E9 [2586]
AlternateDataStreams: C:\ProgramData\agent.1661432732.20292.v2.bin:BCCE7CC418 [2586]
AlternateDataStreams: C:\ProgramData\agent.1661432749.bdinstall.v2.bin:25BCEF01AA [2586]
AlternateDataStreams: C:\ProgramData\agent.1661433364.bdinstall.v2.bin:72BBB2D225 [2586]
AlternateDataStreams: C:\ProgramData\agent.1661433543.bdinstall.v2.bin:CE9DC51A9A [2586]
AlternateDataStreams: C:\ProgramData\agent.1661433881.bdinstall.v2.bin:67A427490B [2586]
AlternateDataStreams: C:\ProgramData\agent.1661865938.bdinstall.v2.bin:AB6674301C [2586]
AlternateDataStreams: C:\ProgramData\agent.1661866193.11372.v2.bin:997F6B944B [2586]
AlternateDataStreams: C:\ProgramData\agent.1661866225.bdinstall.v2.bin:0FDF5ED84C [2586]
AlternateDataStreams: C:\ProgramData\aoichsbw.dxd:706605E356 [2498]
AlternateDataStreams: C:\ProgramData\apwpcnbs.xoh:811133FC4C [2498]
AlternateDataStreams: C:\ProgramData\aqflgalw.vij:617E38A201 [2586]
AlternateDataStreams: C:\ProgramData\conxtjoh.tep:EA8FDEB4D4 [10]
AlternateDataStreams: C:\ProgramData\crlbffib.kyt:902DFC8994 [2498]
AlternateDataStreams: C:\ProgramData\cygosldi.mvv:63EB76EBCE [2586]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\desktop.ini:B1DA6C571C [2586]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Access.lnk:A1B76439FE [2586]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Application Manager.lnk:1BABAD356A [2586]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Premiere Pro CC 2015.lnk:003D3A3976 [2586]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\AltServer.lnk:53AA82DA28 [2586]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Apple Software Update.lnk:B026C77744 [2586]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\desktop.ini:41964AA945 [2586]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Epic Games Launcher.lnk:BE32D07BC5 [2586]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Excel.lnk:B96E9B8455 [2586]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Firefox.lnk:980850BA8A [2586]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk:8096E45125 [2586]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Notepad++.lnk:159ADC9AA1 [10]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\NZXT CAM.lnk:AB04221C49 [10]
AlternateDataStreams: C:\Users\Public\Shared Files:VersionCache [7968]
AlternateDataStreams: C:\Users\Tellus\Application Data:00e481b5e22dbe1f649fcddd505d3eb7 [394]
AlternateDataStreams: C:\Users\Tellus\AppData\Roaming:00e481b5e22dbe1f649fcddd505d3eb7 [394]
StartBatch:
  pushd c:\windows\system32
  bcdedit.exe /set {default} recoveryenabled yes
  net stop bits
  net stop cryptSvc
  net stop wuauserv
  net stop msiserver
  netsh winsock reset catalog
  netsh int ipv4 reset reset.log
  netsh int ipv6 reset reset.log
  ipconfig /release
  ipconfig /renew
  ipconfig /flushdns
  ipconfig /registerdns
  net start bfe
  net start bits
  net start cryptSvc
  net start eventsystem
  net start msiserver
  net start rpcss
  net start sdrsvc
  net start trustedinstaller
  net start vss
  net start winmgmt
  net start wuauserv
  netsh winhttp reset proxy
  bitsadmin /list /allusers
  bitsadmin /reset /allusers
EndBatch:
StartPowershell:
Set-MpPreference -DisableAutoExclusions $true -Force
set-mppreference -mapsreporting basic -Force
set-mppreference -DisableRealtimeMonitoring $false -Force
set-mppreference -DisablePrivacyMode $true -Force
set-mppreference -DisableIOAVProtection $false -Force
set-mppreference -CheckForSignaturesBeforeRunningScan $true -Force
set-mppreference -PUAProtection enabled -Force
Update-MpSignature
Get-MpComputerStatus
get-mppreference
EndPowershell:
CreateRestorePoint:
exportkey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Exclusions
exportkey: hkcu\software\classes\ms-settings\shell\open\command
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by theuser707** [comment]
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/9580097/Fixlog.txt)

Found out what was the problem, it's not a coincidence that when i turn off my windows defender real time protection my pc and chrome is able to gain access to internet other than youtube and google. Could this be a virus that's forcing me to turn off windows real time defender?

**Comment by Sandor-Helper** [comment]
OK, lets get another one scan with Microsoft Safety Scanner.

Make sure you have exit all running programs.
Download [Microsoft Safety Scanner](https://go.microsoft.com/fwlink/?LinkId=212732) and run it.

In **Scan Options** choose **FULL scan**.

Get a lot of patience because the scan can take several hours depending of amount of files and speed of your PC. Wait for the end of scan,
Log named **MSERT** should be found in this folder - C:\Windows\debug\msert.log

Please attach it to your next message.

**Comment by theuser707** [comment]
[msert.log](https://github.com/dragokas/hijackthis/files/9584800/msert.log)

**Comment by Sandor-Helper** [comment]
That run was good

> Found HackTool:Win32/DefenderControl!MSR and Removed!
> Found VirTool:Win32/DefenderTamperingRestore and Removed!

Is your issue still persist?

**Comment by txllus** [comment]
the scan deleted a software that i used to turn of the windows defender control , im not sure if that was the issue but i have windows defender turned off rn and everything is running fine

**Comment by theuser707** [comment]
the scan deleted a software that i used to turn of the windows defender control , im not sure if that was the issue but i have windows defender turned off rn and everything is running fine

**Comment by Sandor-Helper** [comment]
Was that software named dControl.exe?
If so, be very careful using that kind of soft.

You could now rename FRST64.exe to uninstall.exe and run it. This will delete all files and folders created by FRST.

To check system' safety download, unzip and run [Security Check by glax24](https://www.safezone.cc/resources/security-check-by-glax24.25/)
Run it with [-! /htmllog] parameter, i.e. like this:
`C:\Users\Tellus\Desktop\SecurityCheck.exe -! /htmllog`

After a while you'll get html log which show you most necessary links.

**Comment by theuser707** [comment]
yeah, it's called dControl.exe, I specifically downloaded it to turn off the windows anti-virus. everything is updated and working fine as of now,  not sure about my pc not having an anti-virus tho as I always used the one on default windows.

**Comment by Sandor-Helper** [comment]
Glad we could help.
Take care and stay safe.
