### ISSUE TITLE
Malware help - Bitwarden/Google accounts compromised

### ISSUE THREAD

**Issue by yamlaf** [dragokas/hijackthis#194]
Welcome!
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Show us the required logs (for PC cure only):

  * Read carefully: "How to make a request for help in the PC cure section":
https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by "AutoLogger" tool:
http://tools.safezone.cc/drongo/test/AutoLogger-test.zip

[report1.log](https://github.com/dragokas/hijackthis/files/10136078/report1.log)
[report2.log](https://github.com/dragokas/hijackthis/files/10136079/report2.log)
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/10136082/HiJackThis.log)
(https://github.com/dragokas/hijackthis/files/10136077/CollectionLog-2022.12.01-20.43.zip)

### Step 2: Describe your problem in details:

1. What did you done before the problem occurs: 
I tried downloading a macro recorder software to automate some of my work however this was infected with malware. This took over access of my Google, Amazon, Google Wallet, Bitwarden, Facebook and Twitter accounts. My Facebook and Twitter accounts are now suspended and I have appealed them. I have contacted Google as a payment was made to create a Google Ads account and purchase advertisement. This was charged from my credit card. I have since cancelled and requested a replacement of all my cards as listed on my Google Wallet.
I received a further security breach alert despite changing my Google account password. I wonder if this is because my Bitwarden password was still known and I did not have 2FA enabled. So, I have now enabled 2FA on my Bitwarden account. I have not yet gone through the process of changing all 500+ of my passwords stored - as I would prefer to avoid this if at all possible.

I have run MalwareBytes, RKill to clean my PC and I am not getting any malware alerts now. But, I wanted to be sure by checking these logs that in fact there is nothing else being detected by AutoLogger. I am quite distressed and would like to resolve this as quickly as possible. 

Any help would be most appreciated. Thank you

3. What programs (browsers) affected by the problem
Google Chrome
Note I have not noticed any other abnormal pop ups or changes to my desktop.

4. Steps to reproduce: Tbc
6. Expected behavior: To achieve some kind of guarantee that my system is now restored and there is no chance of further compromise. I have no way to be sure that my 500+ passwords have not been exported and are now being circulated/used.
7. If applicable, add screenshots to help explain your problem.

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

Do you create these files at your Desktop by yourself?

> C:\Users\Admin\Desktop\sleep.bat
> C:\Users\Admin\Desktop\wake.bat
> C:\Users\Admin\Desktop\Script.vbs

After your answer there will be more steps to do.

Please uninstall outdated

> Adobe Flash Player 32 ActiveX
> Adobe Flash Player 32 PPAPI

**Comment by yamlaf** [comment]
[CollectionLog-2022.12.02-08.48.zip](https://github.com/dragokas/hijackthis/files/10139546/CollectionLog-2022.12.02-08.48.zip)
[report1.log](https://github.com/dragokas/hijackthis/files/10139547/report1.log)
[report2.log](https://github.com/dragokas/hijackthis/files/10139548/report2.log)

Hi
Yes I created those 3 files you mentioned. They are for sleeping and waking my machine as well as resetting my internet adapter. I have deleted them in any case. I will also uninstall those 2 programmes.

I have re run and attached AutoLogger after completing these steps.

Thanks

**Comment by Sandor-Helper** [comment]
Thanks for the explanation. I didn't ask to delete those files, I only wanted to make sure that you know about them. But it is no harm so far.

Run HiJackThis from that location:
C:\Users\Admin\Desktop\Malware\AutoLogger\AutoLogger\HiJackThis\HiJackThis.exe
Check only following:
```
O7 - TroubleShooting: (EV) HKCU\..\Environment: [TEMP] = (not exist)
O7 - TroubleShooting: (EV) HKCU\..\Environment: [TMP] = (not exist)
O7 - TroubleShooting: (EV) HKLM\..\Environment: [PATHEXT] = .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
O22 - Tasks: (disabled) Sleep - C:\Users\Admin\Desktop\sleep.bat (file missing)
O22 - Tasks: (disabled) Wake - C:\Users\Admin\Desktop\wake.bat (file missing)
O22 - Tasks: tplink - C:\Users\Admin\Desktop\Script.vbs (file missing)
```
and press Fix button.
Restart your PC and get me more logs please:

Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by yamlaf** [comment]
Thank you.

I have checked and removed those items from HiJackThis.exe and restarted my PC.
Find attached the new logs FRST.txt Addition.txt

[Addition.txt](https://github.com/dragokas/hijackthis/files/10140262/Addition.txt)
[FRST.txt](https://github.com/dragokas/hijackthis/files/10140263/FRST.txt)

**Comment by Sandor-Helper** [comment]
Temporarily turn off any antivirus.

Highlight following code:

```
Start::
CloseProcesses:
SystemRestore: On
CreateRestorePoint:
GroupPolicy: Restriction ? <==== ATTENTION
GroupPolicy\User: Restriction - Chrome <==== ATTENTION
Policies: C:\Users\Admin\NTUSER.pol: Restriction <==== ATTENTION
Policies: C:\ProgramData\NTUSER.pol: Restriction <==== ATTENTION
U4 nxdm; no ImagePath
U4 nxpcap; no ImagePath
U4 nxsshd; no ImagePath
U4 nxtun; no ImagePath
U4 nxusbd; no ImagePath
U4 nxusbh; no ImagePath
U4 nxusbs; no ImagePath
2022-11-28 20:03 - 2022-11-23 17:14 - 000000072 _____ C:\Users\Admin\AppData\LocalLow\7UT985QCiUeQ
2022-11-28 20:03 - 2022-11-23 17:14 - 000000070 _____ C:\Users\Admin\AppData\LocalLow\95JVrRUYVPcy
2022-11-28 20:03 - 2022-11-23 17:14 - 000000067 _____ C:\Users\Admin\AppData\LocalLow\X9bWE1Yvn8fv
2022-11-28 20:03 - 2022-10-02 20:06 - 000004146 _____ C:\Users\Admin\AppData\LocalLow\Ir3WVBMWOExr
swMSM (HKLM-x32\...\{612C34C7-5E90-47D8-9B5C-0F717DD82726}) (Version: 12.0.0.1 - Adobe Systems, Inc) Hidden
AlternateDataStreams: C:\Windows\System32:tdsrset.gfc [5846]
AlternateDataStreams: C:\Users\Admin:Heroes & Generals [38]
AlternateDataStreams: C:\Users\Admin\Application Data:6699d3ee8dd9cf775caae782c8f44f03 [394]
AlternateDataStreams: C:\Users\Admin\AppData\Roaming:6699d3ee8dd9cf775caae782c8f44f03 [394]
AlternateDataStreams: C:\Users\Admin\AppData\Local\Temp:$DATA​ [34]
AlternateDataStreams: C:\Users\Public\AppData:CSM [458]
FirewallRules: [{D1A3BC1D-0DD2-4712-919B-C59EAF5E460A}] => (Allow) LPort=3389
FirewallRules: [{4F2B6FB4-654B-42CE-8D92-2074396584AD}] => (Allow) LPort=3389
ExportKey: HKLM\SOFTWARE\Microsoft\Windows Defender\Exclusions
EmptyTemp:
Reboot:
End::
```

Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

In the program list find

> swMSM

that was hidden earlier and unistall it.

**Comment by yamlaf** [comment]
Thank you. Completed.

Fixlog.txt attached
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/10140583/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
OK, good run.

You have Malwarebytes version 4.5.18.226 installed.
Please do a full scan, save report to text file and attach it to your next post.

**Comment by yamlaf** [comment]
Malwarebytes report attached. The scan showed no problems though I did add a folder to the allow list before scanning where I have a programme called PhraseExpress which includes a 'keygen' that I used many months ago to help register the programme for full functionality which I downloaded from [link](https://www.mazterize.com/phraseexpress.html). I do not believe this to be the culprit but I can try deleting it if you suggest it and re-scanning.
[MalwareBytes.txt](https://github.com/dragokas/hijackthis/files/10140770/MalwareBytes.txt)

**Comment by Sandor-Helper** [comment]
Mentioned site you gave me link to have very [bad reputation](https://www.virustotal.com/gui/url/2a8693a338db790aca8fef6b85c7d95859587a9400521683bd1501e54498b705). So it is good idea to unistall a prog gotten from there.

Ok, we've made some changes so I propose to watch for issue for some time and then give us a note.

**Comment by yamlaf** [comment]
Many thanks - now uninstalled. I will report back in due course.

**Comment by yamlaf** [comment]
Just to update you - all good so far. I will keep MalwareBytes in its free state to protect me in the meantime as I would hate to go through this again. Thank you for all your help.
