### ISSUE TITLE
can I get an analysis please of this hijack this log?

### ISSUE THREAD

**Issue by f7ancis** [dragokas/hijackthis#196]
recently my DNS was resetting itself to local host.
I wondered if any of the services running were malware and causing this
[hijackthis.log](https://github.com/dragokas/hijackthis/files/10212125/hijackthis.log)

**Comment by dragokas** [comment]
Hi,
sorry, we missed this case.
If you still need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
