### ISSUE TITLE
been CryptoShufflered... i think

### ISSUE THREAD

**Issue by kosherdaddy** [dragokas/hijackthis#198]
hiya,

I believe that I have been a victim of CryptoShuffler because right after I copied the address of the company to send my bitcoin to, the malware replaced it with another address, and I sent to there. I found out when the vendor asked me whose address this payment was going to because not his did the bomb finally explode in my head. by process of elimination and meticulously going through all the all the steps I took to make the payment, and finally doing another transaction did I see it for myself. 
The steps were
1. I highlighted the correct bitcoin address. I oppressed control c' to copy it. 
2. When I clicked onto the recipient box and pressed control v to paste- where I pressed control V. it should have pasted the address I copied right before. 
3. but it came out with a string of numbers that did not belong to anyone I have sent money to in the last 3 years. 
4. The number belonged to a scammer I had encountered 3 years ago. I not only did he defraud me he had also put this for then i would use the Coinbase next. 
5. I did not think to recheck the address again when i pasted it nor did i check it again it was emailed. Which is why this malware is so simple yet so brutal. It is inserted right before the sending and after you are at the mercy of the exchange. 
By the timer, i realized what had happened, the bitcoin transfer was confirmed and left. I have used Malwarebytes, Adware and  Spyshelter, ZHP Cleaner and all they found was little.  I am still trying desperately to get Coinbase to agree to accept my claim as under the Coinbase Account Protection but i am short of the criteria of me being a Coinbase One account, they are not helpful. Either way i have lost over USD500 usd money i saved up to use for purchase something very vital for my very elderly parents. I just wanna know where this MF is located on my PC and remove it. So eveyone out there, i am out of options and need your esteemed help. I am the necessary logs. To start out with. Please tell me if I need to collect more extra information and please direct what I need to do to fix this. Thank you very much.

**Comment by dragokas** [comment]
Hi,
If you still need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by kosherdaddy** [comment]
yes i am collating all the logs now. and yes, i desperately need help. i did not know this would be posted yet. but will attach the files. thank you again

**Comment by kosherdaddy** [comment]
[](url)
[info.txt](https://github.com/dragokas/hijackthis/files/10304973/info.txt)
[log.txt](https://github.com/dragokas/hijackthis/files/10304974/log.txt)
[Check_Browsers_LNK.log](https://github.com/dragokas/hijackthis/files/10304975/Check_Browsers_LNK.log)
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/10304976/HiJackThis.log)

**Comment by kosherdaddy** [comment]
am i missing anything? sorry but i am new at this

**Comment by kosherdaddy** [comment]
[info.txt](https://github.com/dragokas/hijackthis/files/10305319/info.txt)
[log.txt](https://github.com/dragokas/hijackthis/files/10305320/log.txt)
[Check_Browsers_LNK.log](https://github.com/dragokas/hijackthis/files/10305321/Check_Browsers_LNK.log)
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/10305323/HiJackThis.log)

**Comment by kosherdaddy** [comment]
Completed the next round of logs - CollectionLog-2022.12.27-02.11
[info.txt](https://github.com/dragokas/hijackthis/files/10305410/info.txt)
[log.txt](https://github.com/dragokas/hijackthis/files/10305411/log.txt)
[virusinfo_syscheck.zip](https://github.com/dragokas/hijackthis/files/10305412/virusinfo_syscheck.zip)
[Check_Browsers_LNK.log](https://github.com/dragokas/hijackthis/files/10305413/Check_Browsers_LNK.log)
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/10305414/HiJackThis.log)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

**Comment by Sandor-Helper** [comment]
Hello,

Close all running programs, **temporarily** unload antivirus and other protecting software.

[Run a script in AVZ](https://github.com/dragokas/hijackthis/wiki/AVZ:-How-to-execute-script) (File - Run script):

```
begin
 ExecuteFile('net.exe', 'stop tcpip /y', 0, 15000, true);
 QuarantineFile('C:\Users\raphi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\AntiAlexa.exe', '');
 QuarantineFile('C:\Users\raphi\Start Menu\Programs\Startup\AntiAlexa.exe', '');
 DeleteFile('C:\Users\raphi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\AntiAlexa.exe', '');
 DeleteFile('C:\Users\raphi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\AntiAlexa.exe', '64');
 DeleteFile('C:\Users\raphi\Start Menu\Programs\Startup\AntiAlexa.exe', '');
ExecuteSysClean;
 ExecuteWizard('SCU', 2, 3, true);
RebootWindows(true);
end.

```

Computer will _reboot_. 


For _secondary_ diagnostics please run AutoLogger again. 
Attach new CollectionLog to your post. You can attach whole zip file.

**Comment by kosherdaddy** [comment]
[CollectionLog-2022.12.28-08.44.zip](https://github.com/dragokas/hijackthis/files/10313169/CollectionLog-2022.12.28-08.44.zip)

done.

**Comment by Sandor-Helper** [comment]
That was good run, thank you.
Next step:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by kosherdaddy** [comment]
[Addition.txt](https://github.com/dragokas/hijackthis/files/10327079/Addition.txt)
[FRST.txt](https://github.com/dragokas/hijackthis/files/10327080/FRST.txt)

**Comment by kosherdaddy** [comment]
files attached as instructed. thanks, and awaiting further instructions .

Happy new year  x

**Comment by Sandor-Helper** [comment]
VdhCoApp 1.6.3 - this prog is known as unwanted so it's better to uninstall it.

Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CloseProcesses:
SystemRestore: On
CreateRestorePoint:
HKLM\SOFTWARE\Microsoft\Windows Defender: [DisableAntiSpyware] Restriction <==== ATTENTION
HKLM\SOFTWARE\Microsoft\Windows Defender: [DisableAntiVirus] Restriction <==== ATTENTION
GroupPolicy: Restriction - Edge <==== ATTENTION
GroupPolicyUsers\S-1-5-21-608727093-2089158493-2326368293-1001\User: Restriction <==== ATTENTION
Policies: C:\ProgramData\NTUSER.pol: Restriction <==== ATTENTION
CHR Notifications: Profile 7 -> hxxps://best.aliexpress.com; hxxps://czjmh.atthewon.buzz; hxxps://de.aliexpress.com; hxxps://getarrectlive.com; hxxps://help.coinbase.com; hxxps://mewe.com; hxxps://sg.mail.yahoo.com; hxxps://thepiratebay.org; hxxps://twitter.com; hxxps://web.skype.com; hxxps://www.desertcart.ae; hxxps://www.diy.com; hxxps://www.facebook.com; hxxps://www.flyscoot.com; hxxps://www.hakii.com; hxxps://www.instagram.com; hxxps://www.manomano.co.uk; hxxps://www.onbuy.com; hxxps://www.reddit.com; hxxps://www.singaporeair.com; hxxps://www.techopedia.com
AV: ESET Security (Enabled - Up to date) {89B55CC4-3881-78B2-11E2-479AE0371896}
AlternateDataStreams: C:\ProgramData\TEMP:CB0AACC9 [152]
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

You have Malwarebytes installed. Please do a full scan, save report to the text file and attach it to your next message.

Thanks and Happy New year!

**Comment by kosherdaddy** [comment]
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/10327216/Fixlog.txt)
[311222 malwarebye scan report.txt](https://github.com/dragokas/hijackthis/files/10327239/311222.malwarebye.scan.report.txt)

**Comment by kosherdaddy** [comment]
all attached as asked.

**Comment by Sandor-Helper** [comment]
adaware antivirus - please uninstall this program as well. It is also PUP software.
Then you should delete (place in quarantine) all things that Malwarebytes found.

After that please check and tell us - is your issue still persist?

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.

**Comment by kosherdaddy** [comment]
Dear team,

thank you so much for all your help and I do sincerely apologise for not being in contact for the last 10 days. to be to be honest, I do not know whether the threat is still there or not because I was only able to find it at one time. I can only say that. I have done everything when you have asked an I have Cleaned as much as I can. If there's any further problems, I will definitely create a new collection log and I will create a new entry. Thank you again for all your help and your encouragement. I sincerely thank you for being a source of great comfort to me especially after h having this horrible episode.

Sincerely
RFM

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
