### ISSUE TITLE
been CryptoShufflered... i think 

### ISSUE THREAD

**Issue by kosherdaddy** [dragokas/hijackthis#199]
Hello everyone,

Sadly I  been a victim of this malware or something similar. I have done the logs of. The third run of this. Attaching it. Hoping that someone will make sense of this and tell me if I'm clear of it and what I need to do further? To make sure that this type of malware. It's no longer my computer. Im going to give the context of this from previous messages when I first got into this forum:

About one week ago, I sent Bitcoin to a vendor only to find out it did not reach the destination. The address where to send a Bitcoin had been changed. After rechecking with the vendor and cross-checking all the information I had. I realized that the address in which I sent the money was to be used about 2 to 3years ago. I was scammed then. But why would I use a Bitcoin address that I've not used for three years which was logged only in my Bitcoin wallet. There is no such information located anywhere in my PC that I know of. I only ever copied the address from the vendor. And soon it became clear. After another short experiment, which I did. Did I see my own device? How a number? Which I can copy. Turn to a different address in an extremely easy and straightforward way that one would have never noticed Until it was too late. these are the steps and sequence of events that happened-

1. I bought bitcoin on Coinbase and then was preparing to transfer to the vendor using his bitcoin wallet. I highlighted his 
2. bitcoin wallet address. I pressed control c' to copy it.
3. Then control v to paste- in the meantime just before pasting, the malware had switched the address. 
which was the same scammer that robbed me 3 years ago. Like most victims, unfortunately,  I did not double check the numbers and I went ahead with the transfer. I did not think for a moment that it could happen. 
4. It was too late by the vendor. I checked the address and realized it wasn't his, and after a process of elimination, a simple test that I did showed me exactly What is malware did. 

I have used Malwarebytes, Adware and Spyshelter, ZHP Cleaner and all they found was little. I am still trying desperately to get Coinbase to agree to accept my claim as under the Coinbase Account Protection but i am short of the criteria of me being a Coinbase One account, they are not helpful. Either way i have lost over USD500 usd money i saved up to use for purchase something very vital for my very elderly parents. 

I have taken the following steps thus far- 
-Have used autologger and av_z to fix and the pc this far. I am attaching the current logs.

I would appreciate help on:
A. if someone could give me an analysis of the progress and check the logs if any additional work needs to be done. 
B. if anyone can tell me from the logs what malware did this? 

 heck if all has been removed and what exactly was the malware that was in my pc. 
1. I need to know where and how to get rid of this malware from my pc I am the necessary logs. To start out with. Please tell me if I need to collect more extra information and please direct what I need to do to fix this. Thank you very much.

Welcome!
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Show us the required logs (for PC cure only):

  * Read carefully: "Ho
[info.txt](https://github.com/dragokas/hijackthis/files/10310108/info.txt)
[log.txt](https://github.com/dragokas/hijackthis/files/10310109/log.txt)
[virusinfo_syscheck.zip](https://github.com/dragokas/hijackthis/files/10310110/virusinfo_syscheck.zip)
[Check_Browsers_LNK.log](https://github.com/dragokas/hijackthis/files/10310111/Check_Browsers_LNK.log)
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/10310112/HiJackThis.log)
w to make a request for help in the PC cure section":
https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by "AutoLogger" tool:
http://tools.safezone.cc/drongo/test/AutoLogger-test.zip

### Step 2: Describe your problem in details:

1. What did you done before the problem occurs: _________________
2. What programs (browsers) affected by the problem: ________________
3. Steps to reproduce: _________________
5. Expected behavior: _________________
6. If applicable, add screenshots to help explain your problem.

**Comment by dragokas** [comment]
Closed as a duplicate.
