### ISSUE TITLE
Unexplained password theft

### ISSUE THREAD

**Issue by toborid** [dragokas/hijackthis#201]
First of all, please excuse my English. I had to use google translator

Hello Guys
About 2 weeks ago I noticed a strange behavior regarding the Twitter app.
Since I don't actually use Twitter anymore, I don't get any notifications on my cell phone anymore. But suddenly I got some messages. The profile pictures were always "pretty" ladies. I thought nothing further at first.
Until yesterday morning I had a message from Google on my cell phone that at 3:36 a.m. a "suspicious app" had been found "Origin of activity Windows: device with suspicious app" But no location or anything like that, as usual. I immediately changed my password in my Google accounts. Around noon, an unknown number called me with a foreign area code (UK). Of course I didn't answer and blocked the number. Shortly thereafter, a credit confirmation from Amazon for items not received by email. Then I was lured directly into the account because I suspected a scam. But I actually had credit. I had definitely received the items (2 games)
About 2 hours later another email from Amazon. An order confirmation via Apex Legend Coins (EUR 39.99) Then I immediately wrote to Amazon Support in the chat. I found that there was a chat beforehand that I didn't have. This one was about those 2 games. The writer reported to Amazon that he had only received an empty package. Insisted on a credit, but only as an Amazon credit. I informed the Amazon MA that this chat was not from me and from when. The MA immediately initiated a blocking of my account. I had already changed my password before, but I should do it again anyway. I have now changed my PWs everywhere and where possible also 2 phases Auth. activated. I searched the PC and mobile phone with desinfect or bitdefender. No results.  I absolutely cannot explain how he/she/it got my google and/or Amazon password. 
Therefore I ask you to check my system once. Many Thanks
[CollectionLog-2023.01.04-19.00.zip](https://github.com/dragokas/hijackthis/files/10346475/CollectionLog-2023.01.04-19.00.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

I didn't see obvious infection in logs so far.
You have Malwarebytes version 4.5.19.229 installed. Please do a full scan, save report to text file and attach it to your next post.

Then:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by toborid** [comment]
Hi, thank you in advance. Attached are the other logs

[FRST.txt](https://github.com/dragokas/hijackthis/files/10354820/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/10354821/Addition.txt)
[Malewarebytes_Scan.txt](https://github.com/dragokas/hijackthis/files/10354823/Malewarebytes_Scan.txt)

**Comment by Sandor-Helper** [comment]
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CloseProcesses:
SystemRestore: On
CreateRestorePoint:
HKLM\SOFTWARE\Microsoft\Windows Defender: [DisableAntiSpyware] Beschränkung <==== ACHTUNG
HKLM\SOFTWARE\Microsoft\Windows Defender: [DisableAntiVirus] Beschränkung <==== ACHTUNG
GroupPolicy: Beschränkung ? <==== ACHTUNG
Policies: C:\ProgramData\NTUSER.pol: Beschränkung <==== ACHTUNG
Task: {0862E1E8-2FB4-4C79-803D-142DF50FE4EE} - System32\Tasks\VideoStudioUpdater2022 => p:\Corel VideoStudio Ultimate 2022 v25.0.0.373\Corel VideoStudio 2022\VSNotification.exe /r (Keine Datei)
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\desktop.ini:B1DA6C571C [5154]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\adbLink2.lnk:5029469C55 [5154]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Acrobat.lnk:1FA7E99ECA [5154]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe After Effects 2022.lnk:F7B133A22A [5154]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Photoshop 2022.lnk:638138415C [5154]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\BlueStacks 5 Multi-Instance Manager.lnk:35C0D57199 [5154]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\BlueStacks 5.lnk:088221F38A [5154]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\desktop.ini:41964AA945 [5154]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Epic Games Launcher.lnk:BE32D07BC5 [5154]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Excel.lnk:B96E9B8455 [5154]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk:8096E45125 [4306]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\OneNote.lnk:60EC9648C0 [4954]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Outlook.lnk:5465085A2F [3314]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PowerPoint.lnk:1DC1525F34 [3314]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Project.lnk:3B7F7AA2C3 [3314]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RGBFusion.lnk:FCA7AEB286 [5154]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Uninstall Oculus.lnk:3E1FCB1CF0 [5154]
AlternateDataStreams: C:\Users\Public\Shared Files:VersionCache [8154]
Hosts:
FirewallRules: [{157FCCD5-1EC1-4C87-83A9-AAE89631244D}] => (Allow) LPort=9009
FirewallRules: [{9263C385-D45C-4FD0-98A6-86CFFA0A5C31}] => (Allow) LPort=9009
FirewallRules: [{23B6E756-EF9E-4C3C-B407-A494DA41DA8D}] => (Allow) LPort=9009
FirewallRules: [{232C7D80-B66A-4271-93C7-8697EA058E61}] => (Allow) LPort=9009
FirewallRules: [{19FB61B6-2FBC-43A8-AB2B-9CB1DF1C0B48}] => (Allow) LPort=9009
FirewallRules: [{74E489E7-DA30-4534-88F9-2AD3959C1E92}] => (Allow) LPort=9009
FirewallRules: [{081BF1C7-1EC4-41FC-8B8A-B91F5706B580}] => (Allow) LPort=9009
FirewallRules: [{9DDE03E7-E317-413B-A68D-05EB05064B10}] => (Allow) LPort=9009
FirewallRules: [{723F57FD-E93F-48B0-8292-74A5E24F1A31}] => (Allow) LPort=9009
FirewallRules: [{7C247E29-3132-41EE-94F7-225680585F3D}] => (Allow) LPort=9009
FirewallRules: [{CADE8F5D-9A34-43F6-9AB1-667A38A794B1}] => (Allow) LPort=9009
FirewallRules: [{87319063-5232-41C7-8CE9-DE7BDEDE82E5}] => (Allow) LPort=9009
FirewallRules: [{8942EC83-9337-454B-8152-D8FC86FD4AD5}] => (Allow) LPort=9009
FirewallRules: [{686B5013-F391-4228-B9C1-DB0E1F6063F6}] => (Allow) LPort=9009
FirewallRules: [{CD779AE3-D148-42C4-8838-1EFD4938D300}] => (Allow) LPort=9009
FirewallRules: [{40B88CDE-9D5E-4A53-AB3D-37A83B7E74FC}] => (Allow) LPort=9009
FirewallRules: [{14FDA285-9518-46E1-A8BC-AA616D789E18}] => (Allow) LPort=9009
FirewallRules: [{910B6FDD-0D99-452D-9286-C5E2811A559E}] => (Allow) LPort=9009
FirewallRules: [{56A9F2FE-E7ED-46BA-9093-17A087DDE04B}] => (Allow) LPort=9009
FirewallRules: [{5BDC8621-4ABD-4F9C-9560-9FFE2A43463E}] => (Allow) LPort=9009
FirewallRules: [{5839307C-14BB-45BB-86B8-2D0CEBE38C2A}] => (Allow) LPort=9009
FirewallRules: [{312236D8-B799-4114-AD5A-2A444BAA0BBA}] => (Allow) LPort=9009
FirewallRules: [{2E7E4670-BCCD-467E-B1B1-967B22302DB0}] => (Allow) LPort=9009
FirewallRules: [{E560BBC3-3C6B-4E5F-B041-B5F2A1B42371}] => (Allow) LPort=9009
FirewallRules: [{AF27D69C-F37F-439E-AE66-AA8BFB83883B}] => (Allow) LPort=9009
FirewallRules: [{EA94FFA4-E135-427D-9F13-48717EDF5C1F}] => (Allow) LPort=9009
FirewallRules: [{A30E4393-9C40-427B-975C-8D887C228EEC}] => (Allow) LPort=9009
FirewallRules: [{57F6CBAB-8215-4363-8257-5F266BCDDECB}] => (Allow) LPort=9009
FirewallRules: [{23A00BF8-53AC-4C62-A63A-AFE5D62C1576}] => (Allow) LPort=9009
FirewallRules: [{3F721ECE-D46D-4F67-91DE-87E5F53F31A8}] => (Allow) LPort=9009
FirewallRules: [{F788AE8C-5096-4684-99F5-B1F8521F88E4}] => (Allow) LPort=9009
FirewallRules: [{054DE7B3-D9A5-4435-AC4C-46A2DCC55490}] => (Allow) LPort=9009
FirewallRules: [{46D88992-D820-435F-8AB7-680A3047AFF5}] => (Allow) LPort=9009
FirewallRules: [{3BB2547F-DB27-4BE1-B798-6CFC76763055}] => (Allow) LPort=9009
FirewallRules: [{5151E03A-B99C-4450-AEE4-CA26E9318391}] => (Allow) LPort=9009
FirewallRules: [{A1F404C6-6E7E-4D38-853C-79D17C356AA1}] => (Allow) LPort=9009
FirewallRules: [{06E12C23-F053-4817-9E9E-BA99DFC67F61}] => (Allow) LPort=9009
FirewallRules: [{173E6128-7AD3-40C6-8E91-34BDF7DED358}] => (Allow) LPort=9009
FirewallRules: [{75336F4A-2DE0-4671-A35D-5C4FED98979C}] => (Allow) LPort=9009
FirewallRules: [{769BD54E-6893-4673-B45A-8C806BD29140}] => (Allow) LPort=9009
FirewallRules: [{5F5654B7-EA5A-4DF5-A41B-91E2C6A49DE2}] => (Allow) LPort=9009
FirewallRules: [{92E25AF6-1002-410D-8121-F40967AA81A0}] => (Allow) LPort=9009
FirewallRules: [{A123802A-6DD0-406D-A6BB-E3766632133E}] => (Allow) LPort=9009
FirewallRules: [{2141E283-09E7-4465-9F35-5607D6B3FA3D}] => (Allow) LPort=9009
FirewallRules: [{77DA7C60-5B99-482B-AE90-40A195F91019}] => (Allow) LPort=9009
FirewallRules: [{C3F3D450-D0F3-4E91-94BD-7226DBD1D472}] => (Allow) LPort=9009
FirewallRules: [{6B65CDB7-DB1C-4343-957F-C712E193CF41}] => (Allow) LPort=9009
FirewallRules: [{716E28CC-81DD-4C30-9945-69FF46FB35E0}] => (Allow) LPort=9009
FirewallRules: [{28FF9ACB-A414-45A1-BA55-CBAC10E51251}] => (Allow) LPort=9009
FirewallRules: [{BA22B8D5-3985-4F8E-96CB-FD66CEAA1FCC}] => (Allow) LPort=9009
FirewallRules: [{86314A87-9E97-4FB7-B5BD-AA03870BEEB8}] => (Allow) LPort=9009
FirewallRules: [{ACD98C9F-5630-4D04-BD53-AFE7D40A5FBD}] => (Allow) LPort=9009
FirewallRules: [{00E9DE12-0A50-4330-BC60-5D722CA359F2}] => (Allow) LPort=9009
FirewallRules: [{4244C0CF-AB0F-4F16-BE1B-5DA4579B1A51}] => (Allow) LPort=9009
FirewallRules: [{BEA5407F-C80F-4CD1-86C6-4317DFA14352}] => (Allow) LPort=9009
FirewallRules: [{8D82E87E-9FBD-4577-A337-9D949A55F743}] => (Allow) LPort=9009
FirewallRules: [{1FBAE041-CA07-4725-B99C-FED7BD233E69}] => (Allow) LPort=9009
FirewallRules: [{3D15BE86-C597-4475-97E2-35A6D532A44C}] => (Allow) LPort=9009
FirewallRules: [{1F2013A1-538C-4165-BC78-C3FE987D5114}] => (Allow) LPort=9009
FirewallRules: [{862FF5B2-2CCC-4A61-84C3-6561370729E4}] => (Allow) LPort=54925
FirewallRules: [{6571BF15-C306-4549-9015-969218155545}] => (Allow) LPort=8088
FirewallRules: [{E734D385-640B-4F66-819E-31F3FB9E4435}] => (Allow) LPort=8088
StartBatch:
  del /s /q "%userprofile%\AppData\Local\Google\Chrome\User Data\Default\Cache\*.*"
  del /s /q "%userprofile%\AppData\Local\Microsoft\Edge\User Data\Default\Cache\*.*"
  netsh winsock reset catalog
  netsh winsock reset catalog
  netsh int ipv4 reset reset.log
  netsh int ipv6 reset reset.log
  ipconfig /release
  ipconfig /renew
  ipconfig /flushdns
  ipconfig /registerdns
  netsh winhttp reset proxy
  bitsadmin /list /allusers
  bitsadmin /reset /allusers
EndBatch:
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

Please uninstall useless program

> Spybot - Search & Destroy

**Comment by toborid** [comment]
Spybot is uninstalled
fixlog attached

[Fixlog.txt](https://github.com/dragokas/hijackthis/files/10361999/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
That was good run, thank you.

Lets do another one scan with free anti-virus scanner:
Please download [Microsoft Safety Scanner](https://go.microsoft.com/fwlink/?LinkId=212732), run it.

In the **Scan Options** choose **FULL scan**.

Get a patience because scan could take a few hours (it depends of amount of files and system speed).
Wati for the end of scan.
Find the report **MSERT.log** in this folder C:\Windows\debug\msert.log

Attach it to your next post.

**Comment by toborid** [comment]
Here's the one msert.log

[msert.log](https://github.com/dragokas/hijackthis/files/10366209/msert.log)

**Comment by Sandor-Helper** [comment]
Ok, the utility has removed some activators that cause a lot of problems.
Do you still experience the same issues?

**Comment by toborid** [comment]
OK. Thats fine

The problem was that someone stole my amazon.de password and I couldn't explain how it happened. So I wanted to make sure I didn't have a virus / trojan on my pc. But now I am confident that my system is clean. Thanks a lot

**Comment by Sandor-Helper** [comment]
You can check the system for vulnerabilities and outdated critical software.
Please download [Security Check by glax24](https://www.safezone.cc/resources/security-check-by-glax24.25/download)
Run it with the parameter:
SecurityCheck.exe -! /htmllog
and wait for a while.

You'll get an html report with links in it.

**Comment by toborid** [comment]
hey thanks The scan didn't find anything suspicious. Everything looked fine. I almost think now, the password theft must have somehow happened through my cell phone. I have since reset that. Thank you for your great help

**Comment by Sandor-Helper** [comment]
Glad that everything is (or should be) fine! Good luck!
