### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by SynapseScribe** [dragokas/hijackthis#202]
can we get a new release. i see latest should be 2.10.24.0, but right now there is one from '21 2.10.10.0

**Comment by dragokas** [comment]
Hi, the latest is 2.10.0.24.
And you can always download it from the main page:
![image](https://user-images.githubusercontent.com/19956568/212113812-9d3964b0-df3d-42ed-ade0-1bc3ffb44a7b.png)
Links are static.

**Comment by dragokas** [comment]
Also, I added a notice in the Release section, so nobody may not confuse in the future
Pushing separate release for each little update is too hard for me, and I'm too lazy.
Considering that I already have to make updates to several other places, like at SafeZone.cc

**Comment by SynapseScribe** [comment]
i suppose you can use a github action to do it automatically

like this https://github.com/marketplace/actions/automatic-releases

**Comment by dragokas** [comment]
It doesn't support VB6 program language.

**Comment by dragokas** [comment]
btw, HJT supports automatic and manual updates, available under menus:
 * Help > Check for updates
 * File > Settings > Misc tools > Updates
 
 Program will check digital signature of downloaded program before attempt to replace it.
