### ISSUE TITLE
[CURE PC] Computer takes forever to open applications; runs at full FPS, however, icons in the bottom-right are glitchy

### ISSUE THREAD

**Issue by MontyMole98** [dragokas/hijackthis#203]
Hello! I have a computer that is only a couple years old and it takes absolutely forever to startup, get past the lock screen, and open applications (Windows Explorer doesn't take very long, but Google Chrome, for example, takes forever to open). Like said in the title, it runs at full FPS (Frames Per Second). In addition, the icons on the right end of the task-bar (the few icons just left of the time and date, not the pinned apps) are constantly moving left and right, making it almost impossible to, say, click the "Show Hidden Icons" button. I have also just followed a guide to speed up the PC with virus removal, and it did get rid of 15-20 malicious files, but it is still doing what I described above. Also, this PC supports touch screen, and a few months ago when I was using it, different parts of the screen were being touched almost constantly, even if I wasn't touching them. Somehow, the touch screen got disabled (something I am kind of happy about, since it was making it unusable when it was enabled) and when I tried to re-enable it, using the registry keys, and it said that it was already enabled. If this could be enabled again, of course working properly, it would be nice. I should also mention that AVG Secure Browser was maliciously installed, hijacking Google Chrome, but I got rid of it. Somehow, though, HiJackThis found AVG processes still running, something I removed after it told me. Below is the log created by the AutoLogger process. Thank you for any help given in advance.

[CollectionLog-2023.01.12-11.59.zip](https://github.com/dragokas/hijackthis/files/10405185/CollectionLog-2023.01.12-11.59.zip)

**Comment by Sandor-Helper** [comment]
Hello, welcome and thanks for the logs.

Please do another one scan with different tool:
Download [TDSSKiller.zip](http://media.kaspersky.com/utilities/VirusUtilities/RU/tdsskiller.zip) and extract it.
Run file TDSSKiller.exe.
Press "Start" button. Leave scan options by default.
Do not delete anything by yourself!
The tool will generate a report and place it to root directory of a system disk (usually C:).
Report name should be ToolName.Version_Time_Date
For example like this - C:\TDSSKiller.3.1.0.28_11.10.2020_15.52.14_log.txt

**Comment by MontyMole98** [comment]
Done. One threat was found and, as I was told, cleaning was skipped.

[TDSSKiller.3.1.0.28_13.01.2023_10.07.40_log.txt](https://github.com/dragokas/hijackthis/files/10413324/TDSSKiller.3.1.0.28_13.01.2023_10.07.40_log.txt)

**Comment by Sandor-Helper** [comment]
Thanks for the log.

You have Malwarebytes version 4.5.19.229 installed. Please run full scan, save report to text file and attach it here.

Lets get another one log.
Please download [Universal Virus Sniffer](https://www.safezone.cc/resources/universal-virus-sniffer-uvs.7/download) (uVS)
Extract it from zip.
Download [this file](https://disk.yandex.ru/d/vXrwEBMhYSbzrQ) (without extension) and copy it to new UVS folder.
Open UVS folder and run **start.exe**.
Choose "Start under the current user" and wait for a while.
When it finish analyzing go to File -> Save OS image with checking digital signatures - and save log named like _Computer_name_date_ to your Desktop.
Attach this log to your next post.

**Comment by MontyMole98** [comment]
Okay, I did the Malwarebytes scan. I have scanned with it before and it removed 15 malicious items (Unfortunately I don't have a log file of that one) so it's no surprise that this scan found nothing. Nonetheless, here's the log.
[Malwarebytes Scan.txt](https://github.com/dragokas/hijackthis/files/10418205/Malwarebytes.Scan.txt)
Unfortunately, when I opened the Universal Virus Sniffer, after allowing it administrator privileges, it gave a warning sign and when I clicked Ok, it just closed. So I don't have that log just yet. Do you know what is wrong with it? I also tried running it again and I put the other file (lclz) in the folder. It still isn't working, is this a common error?

**Comment by MontyMole98** [comment]
Have you seen anything within it, @Sandor-Helper ? Sorry, but it's been a while and I was wondering.

**Comment by MontyMole98** [comment]
Sorry to ask, but have you found anything, @Sandor-Helper ?  Sorry, but it's been a while since the last comment and I would like to know.

**Comment by Sandor-Helper** [comment]
I'm sorry for missing your last message.


> it gave a warning sign

Can you get me a screenshot of this warning, please?

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
