### ISSUE TITLE
My computer is running slow

### ISSUE THREAD

**Issue by LahcenGit** [dragokas/hijackthis#204]
Hello !
I need your help for this problem, 
My computer is so slow and it blocks for maby secondes when i using software like Adobe collections 
_________________________________________________________________

[CollectionLog-2023.01.16-09.55.zip](https://github.com/dragokas/hijackthis/files/10424126/CollectionLog-2023.01.16-09.55.zip)

**Comment by Sandor-Helper** [comment]
Hello and welcome,

Pleas uninstall PUPs via Contol Panel - Uninstall:
```
Bonjour
Driver Booster 8
Java(TM) 6 Update 27 (64-bit) - as an outdated version with a lot of vulnerabilities
Malwarebytes version 4.4.10.144 - also outdated version
```
Next:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by LahcenGit** [comment]
Thanks for your reply 
Done, attached you'll find ADWCleaner report
[AdwCleaner[C03].txt](https://github.com/dragokas/hijackthis/files/10437918/AdwCleaner.C03.txt)

**Comment by Sandor-Helper** [comment]
Thanks for the log.
Next step now:

Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by LahcenGit** [comment]
Thanks 
[FRST.txt](https://github.com/dragokas/hijackthis/files/10445410/FRST.txt)

**Comment by Sandor-Helper** [comment]
Thanks, but you forget to add second one - Addition.txt

**Comment by LahcenGit** [comment]
I'm sorry
[Addition.txt](https://github.com/dragokas/hijackthis/files/10446846/Addition.txt)

**Comment by Sandor-Helper** [comment]
Thank you.
I see in log signs of previous Avast installation (perhaps it was Avast VPN).
Please download [aswclear.exe](https://files.avast.com/files/eng/aswclear.exe), run it in Safe Mode and remove orphans.

After restart please uninstall useless program

> Bonjour

Next step.
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CloseProcesses:
SystemRestore: On
CreateRestorePoint:
GroupPolicy: Restriction ? <==== ATTENTION
Policies: C:\ProgramData\NTUSER.pol: Restriction <==== ATTENTION
HKLM\SOFTWARE\Policies\Mozilla\Firefox: Restriction <==== ATTENTION
HKLM\SOFTWARE\Policies\Microsoft\Internet Explorer: Restriction <==== ATTENTION
AlternateDataStreams: C:\WINDOWS\System32:tdsrinu.gfc [5882]
FirewallRules: [{4CE3D6F1-2AAE-4D3A-8E4E-04805578E2B0}] => (Allow) LPort=8299
FirewallRules: [{7D784D48-5E00-46A6-8BF6-EE5AE91209E3}] => (Allow) LPort=5130
FirewallRules: [{F9977BB5-2E2A-4C32-903C-B860614FCEE8}] => (Allow) C:\Program Files\Bonjour\mDNSResponder.exe (Apple Inc. -> Apple Inc.)
FirewallRules: [{BDD929DF-9FDC-4024-91BD-A70E91192EC2}] => (Allow) C:\Program Files\Bonjour\mDNSResponder.exe (Apple Inc. -> Apple Inc.)
FirewallRules: [{3C81B900-9219-4693-8F5D-C7E197577CE1}] => (Allow) C:\Program Files (x86)\Bonjour\mDNSResponder.exe (Apple Inc. -> Apple Inc.)
FirewallRules: [{3201F3D6-FF8B-494F-B889-A5566F39A8C3}] => (Allow) C:\Program Files (x86)\Bonjour\mDNSResponder.exe (Apple Inc. -> Apple Inc.)
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

The amount of free space at system disc is critically low:

> Drive c: () (Fixed) (Total:223.13 GB) (Free:5.59 GB)

It should be no less than 45 GB for your disk (20% from whole disk amount).

**Comment by LahcenGit** [comment]
Thank you
Ican't find this program

  //  Bonjour
 Attached  Fixlog.txt

[Fixlog.txt](https://github.com/dragokas/hijackthis/files/10528250/Fixlog.txt)

Free space at system disc // fixed

**Comment by Sandor-Helper** [comment]
That was good run, thank you.
Is there any more issues remains now?

**Comment by LahcenGit** [comment]
My computer is now much better than it was, thank you very much

**Comment by Sandor-Helper** [comment]
It's good to know it, thank you.

Ok, lets clean up our tools:
Start AdwCleaner, in Parameters tab scroll down and choose "Remove".
Next please rename file FRST64.exe -> uninstall.exe and run it. Reboot will be required.

All other tools and its folders you can simply delete.

Please download [Security Check by glax24](https://tools.safezone.cc/glax24/SecurityCheck/SecurityCheckH.zip), extract it from zip, run and wait some time. After a while you'll get an html report about some possible vulnerabilities and about outdated critical programs.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
