### ISSUE TITLE
Viruses - hacking on various platforms

### ISSUE THREAD

**Issue by RezerPL** [dragokas/hijackthis#205]
About a week ago, I decided to buy Microsoft Office. I decided to go the easy way and was looking for a free version of the program. Unfortunately, I failed to install Office, and the next day my various platforms were hacked. Google, Facebook, Instagram, Discord. I even lost some cash because I had a debit card linked to my Google account and the hackers took advantage of it. I scanned my computer with various antiviruses, but none found anything. What should I do?
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/10572195/HiJackThis.log)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
