### ISSUE TITLE
Next Level Evasive Malware Suspected 😅 PLS HALP!!!

### ISSUE THREAD

**Issue by gemeroni** [dragokas/hijackthis#206]
Hey All,

Big TIA if anyone can help, I could really do with guidance from someone who actually knows that they're doing 😅🙏🏻

I'm running MBAM on my 1.5yo mini PC (MSI Cubi5 Win11Pro / i7 / 32GB / SSD x2) but I've had odd PC behaviour since returning to 24/7 web access at the end of January after being away and largely offline for the month. 

I've been preoccupied and I'm a bit late to remediate, but I suspect something nasty, clever and extremely evasive has slipped through the cracks between getting back online and up to date.

I'm not in tech but I've managed a microscopic network for a small business for 15+ years and have picked up a bit about infected PC behaviour from the early days. Mine is looking, walking and quacking like the proverbial duck; BSOD attempts to auto repair on startup, app crashes, operation hangs, laggy performance, critical errors - the whole shebang 😩

I'd vaguely been thinking the BSOD auto repair attempts on startup were a Windows Update triggered hardware/system dummy spit about me treating my mini-pc like a laptop with regular relocations between home & work and no battery for quick startup behaviour at either end... which seems pretty dense of me now 🤦🏻‍♀️ When another workstation at the business began acting out I became much more suspicious.

No detections by MBAM. None via Windows Defender on demand. None via various other scans. I ran the portable edition of ClamWin last night and it took hours. There had been several detections by the time I went to bed with the scan still running; a Qbot Trojan, multiple Expiro, and a few more I can't recall... I'd counted on waking up to a detailed log of ClamWin's findings, but the results were curiously bland... Is it even possible for malware to somehow alter scan results that have detected it??? 

My installation is a mess and I'm starting to think a reset will be called for, but I'll attach my HJT scan results captured in Safe Mode w/ Networking. Will restart and run again in normal mode and attach my results from that shortly too. 

Many TIA for any assistance! 🙏🏻
[230219_1624 HiJackThis.log](https://github.com/dragokas/hijackthis/files/10776565/230219_1624.HiJackThis.log)

**Comment by gemeroni** [comment]
I've been getting this alert on startup for a couple of days, nothing that adds up.

![image](https://user-images.githubusercontent.com/125792723/219941548-195d7762-5922-433d-bdb6-3c03d455d363.png)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
