### ISSUE TITLE
professional virus

### ISSUE THREAD

**Issue by tnr20** [dragokas/hijackthis#207]
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/10835597/HiJackThis.log)
Welcome!
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Show us the required logs (for PC cure only):

  * Read carefully: "How to make a request for help in the PC cure section":
https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by "AutoLogger" tool:
http://tools.safezone.cc/drongo/test/AutoLogger-test.zip

### Step 2: Describe your problem in details:

1. What did you done before the problem occurs: _________________
2. What programs (browsers) affected by the problem: ________________
3. Steps to reproduce: _________________
4. Expected behavior: _________________
5. If applicable, add screenshots to h
[report1.log](https://github.com/dragokas/hijackthis/files/10835600/report1.log)
[report2.log](https://github.com/dragokas/hijackthis/files/10835601/report2.log)
elp explain your problem.
[CollectionLog-2023.02.27-03.30.zip](https://github.com/dragokas/hijackthis/files/10835599/CollectionLog-2023.02.27-03.30.zip)

**Comment by Sandor-Helper** [comment]
Hello and welcome,

You didn't describe what is the problem (Step 2). Please do it.

IObit Uninstaller 12 - refers to unwanted program so you should uninstall it.

In addition:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by tnr20** [comment]
[FRST.txt](https://github.com/dragokas/hijackthis/files/10878407/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/10878408/Addition.txt)


thanks sir.

**Comment by Sandor-Helper** [comment]
I'm asking you again to describe - what is the problem? Your system is slowing down or surfing troubles or something else?
I still do not see obvious signs of infection.

And why you still didn't uninstall PUP - IObit Uninstaller 12?

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
