### ISSUE TITLE
First Post I nee to look because

### ISSUE THREAD

**Issue by Zigeunski** [dragokas/hijackthis#211]
I had a brutal trojaner  or bot some months ago. 
I was live with him/them fighting to save passwords. The had a Keylogger and were faster .... new passsword, a minute later again.
some  Clown was watching later on me on the screen. He was very frightended because he moved his hand putting some gloves over them.. Thanks for my Handy i could restore my passwords. But olalala never ever live with a Good hacker who  infected your system and making live battles with Keyloggers, 1 Minute my Account + Email Passswords changed, I reccovered 99% because Movikle Verification  works. But later i have a feelingthey checked am not completlly brainless im not a beginner and try to test me a litttle . Bitcoin Passwort etc was changed. I could talk some days about this drama but very low data gone, had a backup and my passwords when not my E-Mail authentitanticate he done now i  cloned 2 of my emails they got the emails the first email get, he later does the same... Maybe Scareware+Botnet but really respect, i dont even know when and where i was infected i do not even open  a .exe file  in vm at first  +++ i didnt believe it woke up because that my wife , she says that' look like real; thought i was hallucinating.
In the End aber i swiped my whole Laptop and they left me with the work setting up every thing new . Man that was a Human(Clown) but the record was a few seconds live and were whole time loopping, it blocks my mouse . They had talent. later i found some a polisch txt. file likelie they dont even hide it good . <REMOVED> .I thought they want maybe me as end proxy. i think the second and craziest shit i saw. Now it's funny but i had so much anxiety Online banking, BTC Everything and ihow i couldnt themYou know i need internet to recover my password but they were/he were fast. A friend come helped me because i cant sleep. even when i had the internet off in the night, Showed me some They were pissed off if i shut down internet but i needed it too... weird autostarts i have and saw rescue what you can and swipe your disk. I had need to tell you the story   😃 

[report1.log](https://github.com/dragokas/hijackthis/files/11365543/report1.log)

[image](https://user-images.githubusercontent.com/88664449/235454849-10cdcf7a-7188-44ac-826f-255170e67898.png)

When i done something , wrong please tell me im new here and my english is training, not my native language. Interesting nice Community. It's my first post here :)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip)

  * Describe your problem in detail.

Also, do not mention prohibited substances in this topic! Your post is edited.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
