### ISSUE TITLE
Autoupdate ignores installation directory (if not default)

### ISSUE THREAD

**Issue by de-served** [dragokas/hijackthis#213]
Autoupdate caused by pressing Update when asked that version is newer than started ignores non default installation directory.

1. Install with /instDir
2. Run exe from "Start" by typing "Hijack" and click on found link
3. In my case error message popped up that started exe is newer than installed (? .exe installed are the same that was run, now I tried to start HJT to find a version to write at the bottom of this report and that message "version of HJT you just started are newer than installed" appeared again)
4. Exit program, check "Hijack" .lnk or check Installed Programs and find "Hijack", check installation directory - it is now default "Program Files..." but not the previous /instDir directory ("InstallLocation" in HKLM/.../Uninstall/HiJackThis Fork was ignored?)

Upgrade of installation must use the original directory.

 - HJT Version (Alpha version) 3.0.0.6

**Comment by dragokas** [comment]
hi,
thanks for report.

\# 3 - cannot reproduce, maybe some specific network troubles...
Could you try this special debug version: https://dragokas.com/tools/HiJackThis_dbg2.zip
Then, run it => Misc Tools => press "Check for updates online".
Close program, and attach HiJackThis_debug.log, or show exactly such lines from it:
```
Current version is: xxx
Query update URL: xxx
Update URL returned: xxx
Update URL content: xxx
Current version is (Long): xxx
 Latest version is (Long): xxx
```

\# 4 - Reproduced and will be fixed in the next version. Thanks.

**Comment by de-served** [comment]
"current version", "query update" в логе отсутствуют.
Буду далее на русском, поскольку посторонним всё это знать необязательно, осталось просто выловить и пофиксить.

Полагаю, что этот глюк проявляется строго при запуске HJT вне дефолтной директории.
Обязательно отсутствие HJT в директории по умолчанию. Уверен на 99.(9)%.
Вот почему:

1. Проверка апдейтов отключена:
```
- 16:10:21 - 1814,139 - SetStringVal - Begin | Software\TrendMicro\HiJackThisFork | CheckForUpdates | 0 | 
- 16:10:21 - 1814,139 - SetStringVal - Begin | Software\TrendMicro\HiJackThisFork | UpdateToTest | 0 | 
- 16:10:21 - 1814,139 - SetStringVal - Begin | Software\TrendMicro\HiJackThisFork | UpdateSilently | 0 | 
...
- 16:10:21 - 1814,141 - SetStringVal - Begin | Software\TrendMicro\HiJackThisFork | Version | 3.0.0.6 | 
```
2. Записи в логе, в которых упоминается проверка существования файлов и предполагается дальнейший переход к отключенной проверке версий, если вдруг она была бы включена.
```
- 16:10:10 - 1802,328 - FileExists - Begin | File: C:\Programs\___Security\HiJackThis | 
- 16:10:10 - 1802,328 - EnvironW - Begin | SrcEnv: C:\Programs\___Security\HiJackThis | 
- 16:10:10 - 1802,328 - EnvironW - End | C:\Programs\___Security\HiJackThis | 
- 16:10:10 - 1802,328 - FileExists - End | File: C:\Programs\___Security\HiJackThis | bUseWow64: False | Exists: False | 
- 16:10:10 - 1802,328 - FolderExists - Begin | Folder: C:\Programs\___Security\HiJackThis | bUseWow64: False | 
- 16:10:10 - 1802,328 - FolderExists - End | 
- 16:10:10 - 1802,329 - CheckForReadOnlyMedia - End | 
- 16:10:10 - 1802,329 - CheckForStartedFromTempDir - Begin | 
- 16:10:10 - 1802,329 - CheckForStartedFromTempDir - End | 
- 16:10:10 - 1802,330 - FormStart_Stage1 - End | 
- 16:10:10 - 1802,332 - frmEULA.Form_Load - End | 
- 16:10:10 - 1802,444 - FormStart_Stage2 - Begin | 
- 16:10:10 - 1802,444 - InstallUpdatedHJT - Begin | 
- 16:10:10 - 1802,444 - GetFilePropVersion - Begin | File: C:\Program Files (x86)\HiJackThis Fork\HiJackThis_dbg.exe | 
- 16:10:10 - 1802,444 - FileExists - Begin | File: C:\Program Files (x86)\HiJackThis Fork\HiJackThis_dbg.exe | 
- 16:10:10 - 1802,444 - EnvironW - Begin | SrcEnv: C:\Program Files (x86)\HiJackThis Fork\HiJackThis_dbg.exe | 
- 16:10:10 - 1802,444 - EnvironW - End | C:\Program Files (x86)\HiJackThis Fork\HiJackThis_dbg.exe | 
- 16:10:10 - 1802,444 - FileExists - End | File: C:\Program Files (x86)\HiJackThis Fork\HiJackThis_dbg.exe | bUseWow64: False | Exists: False | 
>>> - 16:10:10 - 1802,444 - C:\Program Files (x86)\HiJackThis Fork\HiJackThis_dbg.exe is not found. Err = 0 | 
- 16:10:20 - 1812,975 - InstallUpdatedHJT - End | 
```

Распаковал _dbg.exe в директорию, где установлен HJT (помним, что не по умолчанию).
Запускаю _dbg.exe - сообщение в аттаче выскакивает.
Закрываю его, нажав "Нет", закрываю программу, проверяю лог - части его в п.1 и п.2.
Удаляю лог, запускаю _dbg.exe снова, чтобы выявить последние строки в нём в момент появления всплывающего окна - первая "неприятность" - лог удерживается системой, причём не только на запись, а и на чтение (вероятно это тоже следует поправить? открывать лог на запись только в момент сохранения строк и сразу закрывать? по крайней мере я все свои логирования делаю только так много лет).
Поскольку лог блокирован даже на чтение, то не только открыть просмотр (напр, фаром), но и скопировать его в другое место не даёт. Остаётся вариант один - прибить процесс, что и делаю.
Заглядываю в лог, и последней строкой, как и предполагал выше - именно проверка наличия .exe в директории по умолчанию:
```- 16:17:55 - 2268,155 - C:\Program Files (x86)\HiJackThis Fork\HiJackThis_dbg.exe is not found. Err = 0 |```
Отсюда и косяки, видать.
![HiJackThis_dbg_230617_1617_CQyGfZXxmr](https://github.com/dragokas/hijackthis/assets/18093731/04472d60-74ae-4ee8-932d-b60b7d570cf6)

**Comment by de-served** [comment]
PS: можно добавить флаг в командную строку запуска, который включает логирование. На будущее, вдруг ещё понадобится - в этом случае не нужно будет дебаг-версию выпускать, а просто сказать пользователю, чтобы запустил с флагом, напр., "-dbg" или "--debug"

**Comment by dragokas** [comment]
Спасибо, воспроизвёл и исправил. Я изначально думал о совсем другой менюшке. Выйдёт в ближайшем обновлении.

/debug такой ключ уже есть, см. [Help](https://regist.safezone.cc/hijackthis_help/hijackthis.html#command-line_keys), или более актуальная инфа в самой программе: сис. меню Help - About - Keys. Или тоже самое, если просто переименовать файл утилиты.

**Comment by dragokas** [comment]
В вашей версии просто не было кода вывода сообщений в нужном месте там где идёт процесс обновления, поэтому пришлось собрать отдельную версию. А так всё это один и тот же файл, только работает в разных режимах в зависимости от ключей или постфикса в имени файла.

**Comment by de-served** [comment]
В таком случае всё чудесно. Закрываю.
Удачи!

PS: лок лога бы поправить ;)

**Comment by dragokas** [comment]
Блокировка лога сделана специально, чтобы в промежутки между записью не мог вклиниться антивирус со своими попытками прочитать файл и что-то там проверить. Уже бывали случаи отказа из-за этого.
