### ISSUE TITLE
Trojan download

### ISSUE THREAD

**Issue by jerebord** [dragokas/hijackthis#215]
Someone downloaded an apparently malicious file, and the computer got infected with viruses. Word files were encrypted and their file extension changed to ".gatz" now.
I used different antivirus and antimalware but I think it is still infected.

[1.log](https://github.com/dragokas/hijackthis/files/12267135/1.log)
[CollectionLog-2023.08.05-10.30.zip](https://github.com/dragokas/hijackthis/files/12267171/CollectionLog-2023.08.05-10.30.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hi,
Please zip a couple of encrypted files (with .gatz extention) along with the ransome note (if you have one) and attach it to your next post.
In addition:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by jerebord** [comment]
Encrypted files (with .gatz extention).
[Desktop.zip](https://github.com/dragokas/hijackthis/files/12275142/Desktop.zip)

Farbar Recovery Scan Tool files.
[FRST.txt](https://github.com/dragokas/hijackthis/files/12275145/FRST.txt)
[Shortcut.txt](https://github.com/dragokas/hijackthis/files/12275146/Shortcut.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/12275147/Addition.txt)

**Comment by Sandor-Helper** [comment]
Thanks for the logs.
Can you please also attach this file?

> C:\_readme.txt

**Comment by jerebord** [comment]
[_readme.txt](https://github.com/dragokas/hijackthis/files/12278849/_readme.txt)

**Comment by Sandor-Helper** [comment]
Type of ransome is STOP (Djvu). [Decryption](https://www.emsisoft.com/en/blog/34375/emsisoft-releases-new-decryptor-for-stop-djvu-ransomware/) for this encryptor was available only for early versions.

I see that you've already try to use it with no luck.
