### ISSUE TITLE
My notebook seems to be hacked, perhaps even with a keylogger

### ISSUE THREAD

**Issue by SydAcid** [dragokas/hijackthis#216]
Hello community,

since a few months I don't feel secure when I use my notebook.
Sometimes I can hear people from my neighbourhood talking about my passwords or contents of my emails, just as an example.

I have used Autologger to create the logs a few minutes ago.

Can somebody please have a look at them and tell me, how to make my OS secure?
[CollectionLog-2023.08.07-23.14.zip](https://github.com/dragokas/hijackthis/files/12285287/CollectionLog-2023.08.07-23.14.zip)

Please help me, I would really like to feel save while using my Toshiba Satellite P850.

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hi,
Please uninstall useless program

> Spybot Anti-Beacon

In addition please collect more logs:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Rename FRST64.exe to FRSTEnglish.exe
- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by SydAcid** [comment]
Hello again and thanks for your fast replies.
First I have uninstalled SpyBot Anti-Bacon and then I have used FRTS64.exe to create the 2 logs, which are atteched.
[Addition.txt](https://github.com/dragokas/hijackthis/files/12291133/Addition.txt)
[FRST.txt](https://github.com/dragokas/hijackthis/files/12291135/FRST.txt)

Is it correct, that only Registry, Services, Drivers, Scheduled Tasks, Processes, Internet, One month and Addition.txt are selected?

In addition here is a list of my opened ports on my FritzBox 7590 router:
[export.txt](https://github.com/dragokas/hijackthis/files/12291145/export.txt)

Perhaps somebody can have a look at this, too. 
I am not sure wether my WiFi or LAN are secure with those ports opened.

**Comment by Sandor-Helper** [comment]
Thanks, you've got logs correctly, with all checkmarks by default as it needed.
Now we'll do some kind of general cleaning.

Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CloseProcesses:
SystemRestore: On
CreateRestorePoint:
RemoveProxy:
BootExecute: autocheck autochk * sdnclean64.exe
GroupPolicy: Restriction ? <==== ATTENTION
Policies: C:\ProgramData\NTUSER.pol: Restriction <==== ATTENTION
HKLM\SOFTWARE\Policies\Mozilla\Firefox: Restriction <==== ATTENTION
HKLM\SOFTWARE\Policies\Google: Restriction <==== ATTENTION
HKLM\SOFTWARE\Policies\Microsoft\Edge: Restriction <==== ATTENTION
Tcpip\..\Interfaces\{897384e2-356c-48cc-ada7-6621a86e1a9a}: [NameServer] 127.0.2.2,127.0.2.3
Tcpip\..\Interfaces\{d6efd12e-5740-422f-88c3-5866422c72da}: [NameServer] 127.0.2.2,127.0.2.3
Tcpip\..\Interfaces\{db484304-db04-6aa0-a33d-7236836b364d}: [NameServer] 127.0.2.2,127.0.2.3
Tcpip\..\Interfaces\{e72fe63a-cc94-48cf-aa27-265421c90a31}: [NameServer] 127.0.2.2,127.0.2.3
AlternateDataStreams: C:\Users\Tobi Froh\Desktop\FRSTEnglish.exe:BDU [0]
AlternateDataStreams: C:\Users\Tobi Froh\Downloads\adwcleaner.exe:BDU [0]
AlternateDataStreams: C:\Users\Tobi Froh\Downloads\BraveBrowserSetup-BRV010.exe:BDU [0]
AlternateDataStreams: C:\Users\Tobi Froh\Downloads\Firefox Installer.exe:BDU [0]
AlternateDataStreams: C:\Users\Tobi Froh\Downloads\hijackthis.exe:BDU [0]
AlternateDataStreams: C:\Users\Tobi Froh\Downloads\ISO2USB.exe:BDU [0]
AlternateDataStreams: C:\Users\Tobi Froh\Downloads\PAssist_Std_20230808.6103951.exe:BDU [0]
AlternateDataStreams: C:\Users\Tobi Froh\Downloads\VMware-workstation-full-17.0.0-20800274.exe:BDU [0]
Hosts:
cmd: del /s /q "%userprofile%\AppData\Local\Google\Chrome\User Data\Default\Cache\*.*"
cmd: del /s /q "%userprofile%\AppData\Local\Microsoft\Edge\User Data\Default\Cache\*.*"
cmd: del /s /q "%userprofile%\AppData\Local\Opera Software\Opera Stable\Cache\Cache_Data\*.*"
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRSTEnglish.exe as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by SydAcid** [comment]
Thank you Sandor-Helper!
Here is the Fixlog.txt I just created right now..
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/12291887/Fixlog.txt)

PC has rebooted and I have turned my antivirus on again...

**Comment by Sandor-Helper** [comment]
Thank you, fix ran well.
Please watch the problem and tell us is it gone.

Did you install program

> Cloudflare WARP

by yourself?
If the problem is not solved try to uninstall Cloudflare WARP and see if it helps.

**Comment by SydAcid** [comment]
I have installed WARP by myself.
Will uninstall it now.

Did you also have a look on my opened ports log?
[export.txt](https://github.com/dragokas/hijackthis/files/12292362/export.txt)

Is there any port which should better be not open?

**Comment by dragokas** [comment]
The most dangerous are closed. Other - it's hard to tell without seen which software are using them.
Try get more detailed log using [System Informer](https://systeminformer.com/nightly.php) - Tab "Network", then press menu "Hacker" - Save... and attach the logfile.

**Comment by SydAcid** [comment]
Hello dragokas,
I have downloaded System Informer. I can see the Tab "Network", but I do not find any menu called hacker.
So I selected the tab "Network" and saved this as System Informer Network.txt
Here it is:
[System Informer Network.txt](https://github.com/dragokas/hijackthis/files/12295173/System.Informer.Network.txt)

Is this the log you meant or what do I have to do with this tool.
Could you explain how to find the menu Hacker?

Thanks for your fast reply!

**Comment by SydAcid** [comment]
Hello dragokas,I have installed System Informer and I also found the Tab "Network".
But I do not see any menu called hacker.

I just selected this "Network" tab and clicked "save as".
Here is a log called System Informer Network.txt:

[System Informer Network.txt](https://github.com/dragokas/hijackthis/files/12295629/System.Informer.Network.txt)
Hope I hae done it as you meant..

**Comment by dragokas** [comment]
I don't see anything suspicious in the network log. Most ports are related to BitDefender and its vpn service. All software mentioned are signed.

The only unsigned modules are:
```
() [File not signed] C:\Program Files (x86)\Samsung\Samsung Magician\ffmpeg.dll
() [File not signed] C:\Program Files (x86)\Samsung\Samsung Magician\libegl.dll
() [File not signed] C:\Program Files (x86)\Samsung\Samsung Magician\libglesv2.dll
() [File not signed] C:\Program Files (x86)\Samsung\Samsung Magician\resources\app\dist\magutils-napi.node
() [File not signed] C:\Program Files (x86)\Samsung\Samsung Magician\resources\app\dist\magvibrancy-napi.node
() [File not signed] C:\Program Files (x86)\Samsung\Samsung Magician\resources\app\dist\uimpewrapper-napi.node
() [File not signed] C:\Program Files (x86)\Samsung\Samsung Magician\vk_swiftshader.dll
() [File not signed] C:\Users\Tobi Froh\AppData\Local\Temp\.net\Cloudflare WARP\OYsOzuSzxdUVyovFTJxhXmR3VR0lVKo=\e_sqlite3.DLL
(Igor Pavlov) [File not signed] C:\Program Files\7-Zip\7-zip.dll
(Microsoft Corporation) [File not signed] C:\Windows\WinSxS\amd64_microsoft.vc80.atl_1fc8b3b9a1e18e3b_8.0.50727.6195_none_8a1dd9552ed7f8d8\ATL80.DLL

```
which, perhaps, normal. @Sandor-Helper may tell more about that part.

**Comment by Sandor-Helper** [comment]
I'm agree that there are no suspicious records were found in the log.
