### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mikerichdfdfd** [dragokas/hijackthis#217]
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/12395674/HiJackThis.log)

**Comment by dragokas** [comment]
Can't see an error.
Also, very outdated version.

**Comment by Mikerichdfdfd** [comment]
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/12396283/HiJackThis.log)
here a new version protokol

**Comment by dragokas** [comment]
What is the reason why you sent the log?
Do you want some assistance?

**Comment by dragokas** [comment]
BTW, this is also not the latest.
You can find the link at the "Releases" section: https://github.com/dragokas/hijackthis/releases/tag/v3%2B

**Comment by Mikerichdfdfd** [comment]
i cant find the possibility to analyse the file. hijackthis.de is not
available.



Am Mo., 21. Aug. 2023 um 15:18 Uhr schrieb Alex Dragokas <
***@***.***>:

**Comment by dragokas** [comment]
Hi,
automated analysis is not available anymore and is not planned.

We can provide direct manual assistance if you're suspecting that the PC is infected.
To do so:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip)

  * Describe your problem in detail.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
BTW, in the v3.x the digital signature signer name is implemented to be displayed directly in the log file, so it's much easy to make a decision about each item.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
