### ISSUE TITLE
Password Spy on my PC

### ISSUE THREAD

**Issue by greyhound1174** [dragokas/hijackthis#218]
Dear Community,
4 days ago my PC was probably hacked. The browser passwords were obviously read out and used. As a result, my Paypal account was misused to buy things for almost €20,000. Luckily I was able to stop this. My Amazon account was also spied on or an attempt was made to pay with my Amazon Pay. This was also blocked by Amazon in good time so that no damage was caused overall. Now, of course, I'm wondering whether the attack took place via my PC.
I have installed the Avast Antivirus as a test and it often shows me so-called brute force attacks via SMB. These always refer to an IP address from my network. After this terrible week I hope someone can see something in the log file and thanks in advance for any help.
[Check_Browsers_LNK.log](https://github.com/dragokas/hijackthis/files/12431244/Check_Browsers_LNK.log)
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/12431245/HiJackThis.log)
[info.txt](https://github.com/dragokas/hijackthis/files/12431246/info.txt)
[log.txt](https://github.com/dragokas/hijackthis/files/12431247/log.txt)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip)

Your attached list of files missing important logs such as:
 * virusinfo_syscheck.zip
 
(do not need to unpack the archive collection)

Some of our team members is at vocation at the moment, so you may expect more delay than usual. Our apologies.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
