### ISSUE TITLE
Directory Adding

### ISSUE THREAD

**Issue by Soulisss** [dragokas/hijackthis#219]
How do I add a directory to scan?

**Comment by dragokas** [comment]
Hi, and welcome.
It seems you misunderstood the concept.
It is not antivirus. HiJackThis is generally intended to show which software is set up to autorun in your system.
Nothing more. It has no signature scan mechanism.

If you're asking about a specific tool embedded in HiJackThis, please be more specific.

Kind regards,
Alex.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.

**Comment by Soulisss** [comment]
No, no. I was looking for HiJackthis to look for browser Hijaking, which is
what Hijackthis App use to be for PC

*Sent with Right Inbox <https://www.rightinbox.com/?utm_source=signature>*

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
09/12/23,
04:55:36 AM

**Comment by dragokas** [comment]
HiJackThis was used against browser hijackers 15 years ago. At that time it was specially developed for Internet Explorer only.
Browser anti-hijacker functionality wasn't updated since. None of modern browser support were added. We're just starting that part of task.
Atm HiJackThis+ is used to find other kind of malware, not browser related as well as diagnose specific OS issues.

To check for browser hijackers I suggest to use AdwCleaner by fr33tux.
You can find the most recent version at MalwareBytes site, which is the new owner of this software.

**Comment by Soulisss** [comment]
Thanks for the tip! And that is very sad. The app was amazing.
BTW HOw do I use Github? I have been trying to understand how do I use
github to organize my desktop icons?




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
09/12/23,
08:46:58 AM

*Sent with Right Inbox <https://www.rightinbox.com/?utm_source=signature>*

**Comment by dragokas** [comment]
> The app was amazing.

HiJackThis+ is very useful at current days too and it is used on some AV forums. However, not against malware abusing browsers. We give preference to AdwCleaner specifically tailored for this task. It's a huge work.
Also, you can refer to [short guide](https://dragokas.com/tools/help/hjt_tutorial.html), or the same in built-in menu "Help - About" to see effective areas of HiJackThis+ scan today.

> BTW HOw do I use Github? I have been trying to understand how do I use github to organize my desktop icons?

Sorry, I'm not sure about your question.

**Comment by dragokas** [comment]
Just a note, that you can also use HiJackThis+ to track changes in your system at boot up time.
Quote from general page:

... However, you can use it in form of boot-up automatical scanner in the following way:

 - Run the scanning by clicking "Do a system scan only"
 - Add all items in the ignore-list
 - Set up boot-up scan in menu "File" - "Settings" - "Add HiJackThis to startup"
 - Next time when user logged in, HiJackThis will silently scan your OS and display UI if only new records in your system has been found.

**Comment by Soulisss** [comment]
okay thank you.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
09/12/23,
04:51:25 PM

*Sent with Right Inbox <https://www.rightinbox.com/?utm_source=signature>*
