### ISSUE TITLE
HiJackThis Report - requires assistance

### ISSUE THREAD

**Issue by PcKid-GitHub** [dragokas/hijackthis#224]
Here's my report.

Kindly advise how can i proceed to make my computer better?

[v2.0.5 log removed]

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download)
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by PcKid-GitHub** [comment]
Thank you. I have attached the log files. Kindly take a look?




> Hi, If you need our assistance:
> 
> * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
> * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download)
> 
> **Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**
> 
> **Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any 
[report1.log](https://github.com/dragokas/hijackthis/files/13225762/report1.log)
[report2.log](https://github.com/dragokas/hijackthis/files/13225763/report2.log)
amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**
[report2.log](https://github.com/dragokas/hijackthis/files/13225757/report2.log)
[report1.log](https://github.com/dragokas/hijackthis/files/13225758/report1.log)

**Comment by Sandor-Helper** [comment]
Please be careful: we need a zip file called CollectionLog-date-time, not report.log

**Comment by dragokas** [comment]
@PcKid-GitHub also, describe what issues with PC do you experience?

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
