### ISSUE TITLE
Computer slows down randomly. Suspecting hidden malware. (Can it also affect voltage?)

### ISSUE THREAD

**Issue by M00NBEAST** [dragokas/hijackthis#225]
I've been having a lot of issues with my PC running hot for some reason, no matter what I do in my BIOS. I've also noticed weird entries in my Hijackthis report and felt there may be a lot going on that needs attention, and I'm hoping this will help take care of a lot of my issues.

[CollectionLog-2023.12.04-06.01.zip](https://github.com/dragokas/hijackthis/files/13545179/CollectionLog-2023.12.04-06.01.zip)

**Comment by Sandor-Helper** [comment]
Hello and welcome,

I didn't see obvious signs of infection so far.
But we have more steps to do. First of all I'd recommend to uninstall PUP (potentially unwanted programs) via Parametes - Programs:

> DriversCloud.com
> IObit Uninstaller 13

Restart your PC and next step is:
File **CheckBrowserLnk.log** from

> ...\AutoLogger\CheckBrowserLnk 

drag and drop onto [ClearLNK tool](http://dragokas.com/tools/ClearLNK.zip).

https://dragokas.com/tools/move.gif

Its report should be look like **ClearLNK-Date.log**. Attach it to your next post.


Third step:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
