### ISSUE TITLE
Hacked bad please confirm and help

### ISSUE THREAD

**Issue by sullenczu** [dragokas/hijackthis#228]
[CollectionLog-2023.12.20-12.44.zip](https://github.com/dragokas/hijackthis/files/13732455/CollectionLog-2023.12.20-12.44.zip)
I'm having serious issues with my computer. I know that it is infected but I can't seem to fix it. Everything I try doesn't work. Please confirm and help.

-Thank You

**Comment by dragokas** [comment]
Hi, sullenczu

Please, describe more detailed what kind of issues did you notice.

**Comment by sullenczu** [comment]
I cant update my bios, certain cmd commands aren't available, there are a ton of unrecognized devices in device manager, there seems to be two wifi radios when there should only be one. I feel like I have a bios or embedded corruption in my firmware. There are so many things to list. I have a bunch of third party drivers I cant uninstall or get rid of and there are tied to a networking and ip device that I cant find.

**Comment by sullenczu** [comment]
Sir I have had extreme corruption of my phones and computers the last year. I feel like I'll never get away from it. I feel like an extremely talented hacker is targeting me for some reason. I'm so frustrated. I have had multiple email accounts taken over and I've been locked out permanently. My Facebook account as well.

**Comment by dragokas** [comment]
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by sullenczu** [comment]
Okay thank you for your help.

**Comment by Sandor-Helper** [comment]
Hi,
I didn't see any obvious signs of infection so far. Lets look to some more logs:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by sullenczu** [comment]
Okay thank you. I will do that tomorrow.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
