### ISSUE TITLE
Не видит часть служб, при этом они существуют

### ISSUE THREAD

**Issue by de-served** [dragokas/hijackthis#232]
После первого сканирования системы в отчёте указано, что в зависимости группы присутствуют службы, которых нет, но они все существуют.
HJT самый свежий, 3.3.0.11
W10 x64 с самыми свежими обновлениями

![240106-Wi47](https://github.com/dragokas/hijackthis/assets/18093731/7af28731-4255-4a3c-8481-03507998099f)
![240106-nhF4](https://github.com/dragokas/hijackthis/assets/18093731/b20cea40-8710-41aa-b946-540bbd8feaf9)

**Comment by dragokas** [comment]
Неа, "contains unknown service" это неизвестная служба, а не "missing service".
Данному пункту соответствует эта часть справки:
```
HijackThis также проверяет наличие сторонних сервисов, которые включили себя в состав сервисной группы Microsoft.
```
По правде говоря мы подумывали убрать данный подвид проверки, но обычно там попадается сервисная группа NDIS, куда прописывают себя службы, которым необходимо взаимодействовать с сетью. Такое бывает полезно при диагностике проблем с сетью.
