### ISSUE TITLE
Недостаточно информации в списке, предлагаемые пути перехода неоднозначны

### ISSUE THREAD

**Issue by de-served** [dragokas/hijackthis#235]
В списке путь к реестру настолько сокращён, что без дополнительных усилий понять каков он, не представляется возможным - нужно запускать дополнительный софт, тот же RegWorkshop, и искать все вхождения.
Так же по ПКМ на таких строках в списке перехода к записи в реестре... присутствует множество записей помимо самих отсылок к сказанному в строке - оно-то понятно, тому кто в теме, что классы относятся к этой записи и пр., но именно то, что путь, о котором сказано в списке для проверки, в ПКМ к переходу находится совсем не на первом месте (не на первых местах) - затрудняет быстрое и взвешенное принятие решения в случае какой-то неизвестной программы, придётся ходить в принципе по всем записям, чтобы что-то понять или отредактировать при необходимости, хотя вполне возможно достаточно было бы перейти всего в одну запись из всех, если бы указанный в списке путь был первым в списке переходов.
Очень надеюсь более-менее доходчиво изъяснился. :|

![240106-cwgC9Szh](https://github.com/dragokas/hijackthis/assets/18093731/ee23dccf-1ba7-481d-bede-cd275df561ce)

**Comment by dragokas** [comment]
1. Сокращенный вид у некоторых элементов сделан с целью большей читаемости логов.
2. В подавляющем большинстве случаев в ПКМ - Прыжок - отображается именно всё то, что и будет фиксится. В данном случае с O21 - это не ошибка: всё, что указано в списке на скриншоте, подпадает под фикс всего лишь одного этого элемента. Все указанные записи ссылаются на конкретный dll файл и будут удалены одновременно. Сделано так опять же с целью более компактного лога. Обычно, таких ссылок бывает и по 10 штук и больше. Ранее, HiJackThis именно так и показывал - всё отдельными строчками, получался огромный лог. По факту, если требовался фикс, то исправляли все пункты сразу, ссылающиеся на один и тот же файл расширения оболочки.

**Comment by de-served** [comment]
Ну я-то фиксить ничего не собирался. Просто лазил по менюшкам/веткам, смотрел что да как и почему. В целом понял.
Может стоит сделать динамическое изменение формы отображения путей? Вот у меня окно это развёрнуто по ширине 1920 - программно мы же знаем размеры окна, как и длину текста в пикселях, при желании... Это, конечно, дополнительная возня в кодинге, однако было бы прекрасно, если строка целиком помещается в окно - то и не резать её. А если не помещается - то резать несущественное. А так получается я вижу только HKLM и конец. А в какую ветку пошло - сиди, думай... особенно если вариантов несколько Wow64 или нет, или ещё что. Такие дела.

**Comment by dragokas** [comment]
Понял о чем вы. Оставим такие плюшки для какого-нибудь коммерческого софта. Здесь достаточно возможности через контекстное меню сразу и увидеть всё, и скопировать в буфер, если вдруг нужно заюзать в другом софте, а не через стандартный редактор реестра.
