### ISSUE TITLE
Вылетает при ПКМ на Known Folder 

### ISSUE THREAD

**Issue by de-served** [dragokas/hijackthis#236]
Вылетает при ПКМ на этих двух директориях
![image](https://github.com/dragokas/hijackthis/assets/18093731/b05945cd-8a0f-47c2-990a-6590c329343d)

Дело в том, что они у меня не в стандартном расположении, и это отражено в реестре в т.ч.
Как переместить директории в нестандартное расположение?
Идём по пути стандартного Start Menu, в эксплорере ПКМ на Start Menu, вкладка "Расположение", выбираем другое место, применяем. Всё, старый путь более неактуален. А HJT ищет там. И что-то идёт "не в ту сторону" в этот момент и его нахлобучивает, он вылетает.
Дампы по-быстрому через WhoCrashed пиняют наmsvbvm60!_vbaStrl4+0x11F
![image](https://github.com/dragokas/hijackthis/assets/18093731/781fbbb2-7d00-4721-a4cf-bbae003749a9)

Все эти директории есть, все перенаправлены
![image](https://github.com/dragokas/hijackthis/assets/18093731/044124a2-fac9-4bdc-a85e-27f63d1b3361)

**Comment by dragokas** [comment]
Спасибо за развернутый отчет!
Исправлено в версии 3.4.0.2.
