### ISSUE TITLE
"Sign" characters in log file

### ISSUE THREAD

**Issue by githubuser00** [dragokas/hijackthis#239]
Are these characters valid?
![image](https://github.com/dragokas/hijackthis/assets/7738909/a065bfbd-5b3c-4b55-a849-11fe91f56887)

**Comment by dragokas** [comment]
@githubuser00, yes. It's a special hashing "signature" allowing everybody to check the integrity of logfile, which should be always FFFFFFFF (in CRC32).

**Comment by githubuser00** [comment]
so those logographic (asian characters) are translated to FFFFFFFF?

**Comment by dragokas** [comment]
It is random 4 bytes, not necessarily asian.
In real, the algorithm is much more complex, it is called "CRC32 recovery". Implementation is [here](https://github.com/dragokas/hijackthis/blob/bf811491be4edf578f84decd03eaeca3d55c5eb5/src/modHash.bas#L923).
Similar is used by Microsoft to protect Windows installation iso files.

You can use any application like WinRar, [OpenHashTab](https://github.com/namazso/OpenHashTab), [Md5Checker](https://www.safezone.cc/resources/md5checker.249/) etc. to verify the integrity of HJT logfile.
