### ISSUE TITLE
Problem still exists - Possibly being hacked through router

### ISSUE THREAD

**Issue by lisaoben45** [dragokas/hijackthis#245]
Many files are changed, RPC ports are being used, I believe someone is using my laptop remotely, possibly a neighbor.  I'm not sure but its a problem that continues after several months and after updating to Windows 11.

**Comment by lisaoben45** [comment]
[CollectionLog-2024.02.22-19.57.zip](https://github.com/dragokas/hijackthis/files/14380928/CollectionLog-2024.02.22-19.57.zip)

[FRST(1).txt](https://github.com/dragokas/hijackthis/files/14380917/FRST.1.txt)
[AutoLogger.zip](https://github.com/dragokas/hijackthis/files/14380920/AutoLogger.zip)
[HiJackThis_debug.log](https://github.com/dragokas/hijackthis/files/14380932/HiJackThis_debug.log)

**Comment by dragokas** [comment]
Do not open new topic. Please, use your own topic: https://github.com/dragokas/hijackthis/issues/244
