### ISSUE TITLE
hijack this told me to make create a topic

### ISSUE THREAD

**Issue by misty913** [dragokas/hijackthis#247]
im not sure what to say. my issue goes back over 10 years. every device i have is compromised. doesnt matter if its linux based or windows. or mac os. they take over all of them. iphone, android, ios doesnt matter.  updates stop working. i lose privelleges. its a kernel hack im sure. it sets up a bluetooth virtual network between all my devices. no antivirus has ever detected it. infact it takes over the virus software and rewrites the files to do what it wants. it constantly uploads audio and video. it infects every storage device and you cant tell. it loses a small percentage of space and you cant access that area with any kind of disk or partiion programs that i have found. I can go on and on but i dont have the vocabulary to explain to where anyone would understand. on my raspberry pi's it loads about 35000 modules into the kernel. windows, trusted user takes over. s-1-5-xxxxxxxx shows up in registry  somone logs in as NT AUTHORITY but its under my user name somehow. theres services that i cannot stop. files i cant take ownership of. hijack this is the first and only program that alerts to a problem. everyone thinks im crazy and that im not hacked but they havent experienced what i have and they are to dumb to know if they are hacked too. 
all windows files get writtern over and filled with some embedded os that you cannot kill or break. it fixes itself no matter what ive tried. i dont know much bout powershell or cmd but im learning more and more. 

im trying to follow the directons but i cannot stop windows defender or any thing else. i dont have access or authority. ill do the best i cant to follow directons. 
[CollectionLog-2024.03.15-01.40.zip](https://github.com/dragokas/hijackthis/files/14611351/CollectionLog-2024.03.15-01.40.zip)

**Comment by misty913** [comment]
i ran hijack this from the logger folder. i turned on mark all issues to be fixed. once i click fix it starts down the long list of things to fix and it stops working on: keyboard stopped working for a few minutes and i wasnt able to copy or screenshot where it hangs up at. it was like hkkey something msedge autorun i think

**Comment by misty913** [comment]
\<log got removed\>

**Comment by misty913** [comment]
\<log got removed\>

**Comment by misty913** [comment]
i tired to provide enough information. after the fix im sure ill have to reinstall windows. i install it every day almost so it might be a few days before the hacker will allow me to get back on line 

\<log got removed\>

ok i go to bed now. thank you for taking the time to try and help me. noone would help me for 12 years i deal with this. i throw away matbe 125 computers in the past. i cant afford to buy any more

**Comment by Sandor-Helper** [comment]
Hello,

> i turned on mark all issues to be fixed

Nothing worse could have been done. Windows re-install is the better decision in this case.
There are no obvious signs of infection in logs.

**Comment by misty913** [comment]
![IMG_3406](https://github.com/dragokas/hijackthis/assets/33387023/f0c86bff-3949-43a6-9eec-2bd484135917)

**Comment by dragokas** [comment]
@misty913 never ever mark all checkboxes in HiJackThis! It is not antivirus. You damaged OS. To recover the damage, you may try press "Main menu", "Backups" and restore everything.

We can't provide help if you're ignoring the instructions. First of all: don't do anything without suggestion of helper. It is written in our [general rules](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F). Also, we don't need extra logs which we didn't request.

**Comment by misty913** [comment]
I didn’t understand what it meant about mark something. The way I read it,
it supposed to mark it for me? There was nothing marked. That would explain
why I have to reinstall windows. I’ll try to find the instructions I read
and maybe you can clarify for me.
I will do exactly as you say but I need step by step instruction. I’ve
noticed in the past when following step by step instructions that my system
would differ from what I read and I can never complete the steps. Even when
copying and pasting command.

I appreciate you taking the time to look into my situation.

**Comment by dragokas** [comment]
The action you [did here](https://github.com/dragokas/hijackthis/issues/247#issuecomment-1999049681) - we didn't give you the instruction to do it.
To recover from what you did:
 - Run HiJackThis
 - Press button "Backups"
 - mark all checkboxes
 - Press "Restore" button.

Anyway, our helper said "There are no obvious signs of infection in logs.".
Also, according to your description it looks like the normal behaviour of Windows.
If you have a specific issue and it is suspected to be malware related, please, give us a screenshot.

**Comment by misty913** [comment]
Ok. I’ll try when I get home from work
Thank you

**Comment by misty913** [comment]
I usually reinstall couple times a week until my usb get corrupted. I’m not
allowed to down load windows 10 from my computer. Actually i’m not allowed
to even go to Microsoft website from my computer just shows a blank page so
I usually get a couple of new thumb drives and give them to a neighbor or a
friend to download the windows media creation tool or just the ISO file if
they can.
I’m actually impressed. I was able to download hijack this. I’m usually not
allowed to download any type of malware or antivirus or anything like
that.  If I do get lucky enough to slip it by At the very end of the
download for a very long time try to run it it will hang up. Actually
hijack this started doing that on my other computer. I threw away most of
my old computers, but I kept the hard drives. But somehow there’s no
information on them anymore. This nonsense started all over again. I
plugged one of the old hard drives into a reader.
I’m going to include a few pictures I took of my screen with my phone. Hard
to make out, but if you don’t mind, just look at a couple of them and see
if those are normal windows. I be really nosy during Windows XP, and I knew
every file and folder almost by on the computer but I’m lost after XP.
I do know that once I reload windows and it boots up for the first time not
much happens. Whatever this entity is, it’s set up in the task scheduler
and more and more things start happening every time it boots about the
third time it boots up you’ll hear the hard drive, just going crazy. I
don’t know if it’s installing racing changing files I don’t know, but it
just runs and runs and runs and runs. I know that it takes over windows
defender. It writes so many pages of rules in the firewall to allow so many
different connections. I wish I knew the terminology and had the vocabulary
to speak the language enough to you could understand what I’m saying. But I
promise you there is something going on with it and this something isn’t
your average normal run of the meal Trojan or a virus. It’s an attack at
the highest level. And it doesn’t matter if I blast this out and put Linux
on it. It does the same thing. You can’t update. It updates from Cash
memory and then after that, no matter what you do, you can’t through the
repository.
As soon as my windows boots up, you see for a split second a console window
pop-up then disappear the background.
Someone gave me a Windows XP computer two weeks ago and I messed around
with it for about a week and had it on my network. No issues whatsoever. As
an experiment put one of my SD cards in a card reader shoved it in the USB
slot and bam. It started doing its thing overwriting files taken away
privileges to where I couldn’t open different directories in File Manager
or command line. If you try to take ownership of that directory, which is
usually from trusted installer change to the owner then you try to open the
file or folder I mean it’ll tell you that you need to get permission from
to open it. It acts like there’s a virtual hard drive connected somehow.
You can go into the bios and make sure it’s turned off but it’ll be running
in services. Sometime c  drive will disappear. I don’t remember exactly
what it says reconnect it logged on or something I don’t remember. I will
be more than happy to box this thing up and ship it to you. I can ship you
one of these all in ones and you can play around with it if you want you
can keep it.
Long time ago, I had a friend named Richard that was a computer genius. We
weren’t very close, but we did some dealings in the past. He owed me some
money and partial payment. He gave me his super computer that he built. And
it was top-of-the-line back and its day.  He wrote and managed the firewall
for the NCIC  he also built the website for Gwinnett County detention
Center. This guy did nothing but play on his computer every day all day
long for many years and read books. Another friend of mine was in business
with him and they did computer repair. I think that’s how he managed to get
me. And may not knowing any better I managed to spread it to every device
I’ve ever had since then and that’s been about 10 between 10 and 15 years
ago. And I believe that he has improved his little software or program or
whatever you wanna call it  overtime and using me as a guinea pig. I have
kept every hard drive from every computer. I’ve kept one android and one
iPhone and one router unfortunately I have thrown away a truckload of
printers, computers tablets phones routers over the past 10 or 12 years.
I’ll be glad to send you , the hard drives they’re useless now. I don’t
know what he’s done but half of them don’t even work now and they were full
of information. That’s only important to me like music, family pictures,
personal files, etc. used to take over my email accounts as quick as I
could make them . One time I took a laptop apart, removed the wireless card
format. The hard drive repetition went to Micro Center and bought a brand
new copy of Windows XP Pro and also bought office security. That did up to
six computers couple of telephones and what not guaranteed to work. Install
windows, I prop my feet up on the coffee table and I said finally your son
of a bitch, created two accounts a user account and an admin account. I was
sitting there looking at the screen when it glitched and went back to the
sign on screen somehow so I typed in my password incorrect password OK
maybe a finger key let me slow down in again incorrect password. OK will
use my right index finger and I’m gonna punch the keys at a time incorrect,
OK flipped over to Admin account. Typed in my password for that. Incorrect
password. I politely picked it up off the coffee table open the front door
and threw it out in the yard. At one time I had three desktops and four
laptops of business, laser printer, and I don’t remember what else, I was
starting up a new company. DIVERSIFIED mechanical. Refrigeration had my
cards printed up. Got my license. Got all my computer set up. One laptop
was dedicated for karaoke karaoke studio in my basement for the kids. I can
recall it’s been a long time. About the time I had everything ready to go ,
when he started destroying things. He did some kind of password protection
to one of the hard drives and one of the laptops. And I don’t know how he
did this, but he took all the information off of, and it was coming up on
the other one except for I don’t know how to explain it, but it wasn’t the
same it was like, let’s say if it was a picture the picture would be like
half the size of what it was supposed to be. The desktop moved over to the
other. All the font would be jagged. It wouldn’t be smooth. It would
actually irritate you to look at it if that makes any sense , I mean
they’re so so much that I can say about this, but I don’t know if I can
properly convey the right information that would help you help me. If you
feel like it and have the time, maybe you could ask me some specific
questions and maybe I can give you some specific answers , but just go off
the top of my head and what it’s doing there’s not just what it’s doing.
It’s what it’s not doing.
I did notice before the first thing it did was install all kinds of
different languages. I couldn’t tell you where the location was, but I seen
with my own eyes and I don’t know what you call it. License files or key
files for just about every operating system ever made from every
manufacturer. It would always transmit Medad data to somewhere that was on
the old XP system like I say I was nosy and wanted to know how things work
and I knew every file in folder in XP it was in the middle of uploading a
whole bunch of metadata one time and I pulled the power cord and stopped it
in mid flight. Once it would transmit the file would get erased, but not
this time and I copied that file to a CD or DVD.
I will tell you this, one of those small, single antenna, cigarette lighter
plug signal jammers for jamming GPS If it’s sitting beside the computer, it
blocks whoever from getting in it
I used to flash new firmware in my Samsung galaxy after he would take it
over And it would kick him out for a little while and I’m not sure if he
got back in through NFC or it was probably dumb ass with infected SD cards
but he was in so it didn’t matter anyway. He figured out how to stop
flashing my phone.  I would try and I would try and I would try and just so
happens by accident. A guy worked with had one of those things he would
block his GPS signal on our work vans and go fool around with some married
girl and then when he would get home, he would turn it off. I haven’t
looked back at anything that I have written or spoke, but I will guarantee
you that most of it won’t make any sense because that is one of the things
that happens it changes words and it changes what I type and it also
changes what I say. You should see some of the notes that I enter at work
For some of the equipment that I repair knowing I typed it correctly the
first time and you go back and read it. It don’t make sense and I have
gotten to the point where I refuse to backspace constantly and change it
back to what I put it as to begin with  Anyway, Paul me his little GPS
blocker thing and wanted me to fix it so I sold the positive wire back onto
the board and temporarily connected a 9 V battery to it just to see if it
would work. It was on the table near my computer it came on and worked. I
don’t remember exactly why I decided to try to flash the computer. Maybe
maybe I noticed something changed on the desktop. I don’t recall if I said
anything I’d be lying, but I did try to flash Firm Oden worked like a champ
turn it off couldn’t do it. I’ve noticed that about a lot of things if you
do something new you get away with it for a while and it’s like it or he
learns how to stop you from doing what you’re doing.
I have 4 raspberry pi’s. 2 3B plus
4 w4 gig and a 4 w 2 gig.
Had them for several years got them for me and my kids so we could possibly
spend time with each other. Learning new things. Kids really weren’t
interested in them, but I have managed to become pretty Fluent in Linux.
I’m not completely lost with it.
Oh, let me back up. I got tired of all these windows PCs getting destroyed
so I bought the iMac one of the 28 inch iMac because they’re supposed to be
so much better security wise. That’s a freaking joke. He ended up
destroying the CD drive somehow then the hard drive. I had a lady with
Apple that was over whatever department it was that either Security or IT I
don’t remember and I don’t remember her name but what a sweet person she
tried her best to help me, and we ran a few reports before the hard drive
became mush and I was reading it out to her on the screen because she was
very interested in this, but I wasn’t able to print it out. We tried to
reload the operating system over the network, but it would not do it. It
would fail every time , there was two different ways. I think it was over
the network and then the I guess the recovery petition probably I don’t
know, but you wouldn’t allowed to recover either way just like windows. I
don’t care how many restore points you set you’re not allowed to restore.
And you cannot do startup repair will not work. You can go to a command
prompt and turn on default account. Turn on admin account when you reboot
it they’re not there.  Sfc Will not work DSM will not work CHKDSK will not
work. I guess I’ve rambled on long enough and I apologize but I was kind of
want to give you an idea of what I’ve been facing for the past 10 years
Eset Security got in my computer remotely the day that my passwords got
changed right after reloaded everything and they looked around for any type
of malware couldn’t find any. I have ran every virus scanner known to
mankind and it has never found anything because it’s not a virus now I Run
RK Hunter on my raspberry pies. It went crazy alerting me to every file in
the bend directory and user and user share bin. I’ve had a couple alert to
the registry in windows. I’ve noticed a couple of times it said something
about remote registry while I was in Rege edit. Anyway, I know I’m jumping
around just popping my head and I have to say it while I’m thinking about
it anyway thank you for taking the time to read this. I promise you that
this is real I promise you I’m not an idiot. I can’t make that promise. I
promise you that this has been happening to me and my kids For 12 years and
it’s every device I own I have threw them away several times over I have
moved and I thought I was over this. I haven’t even had a computer for the
past two or three years just for this reason I took it to a place to get
fixed , and they said throw it away because there’s no telling where
something like that may hide. Oh, let me say this one last thing before I
send you a couple of pictures and just look at those pictures. They may be
normal files for windows. I just don’t have the exposure to it so if you
tell me they’re normal then they’re normal. I had forgotten about my
friend. I haven’t seen him in 10 years. And it just popped in my head
Saturday morning about three weeks ago. I bet you it’s Richard . It’s not
the government I’m nobody. I got no money. I barely can afford to feed me
and the kids half the time so it’s not someone trying to steal from me ,
it’s somebody wanting to fuck with me and that is right up Richard alley. I
have a iPhone 13 that I know for a fact is compromised. I won’t go into all
the details but the only file that I have access to is something called.
cacert.pem
I assume it’s some kind of a certificate file granting access for some
program to have A access to a different area in the phone or what not edit
that file in a terminal window. It’s a bunch of key numbers just a bunch of
different digits and a whole bunch of them. I deleted them One morning and
I typed in in the place of the keys and I said hey Richard long time no
see. That was a pretty slick move. Give me that computer years ago. You got
me good. Have you any idea how much money you have cost me and my kids in
the past 10 years at bare minimum, I want a gaming computer For my son and
I want a new laptop for my daughter and I’ll be happy with any old piece of
junk computer without you in it. God is my witness, I got a text message
two hours later from a number and I’ll give you the number, that simply
said “I’m sorry?”
OK now, let me say this before I tell you where that number came from.
Richard back then wouldn’t have a cell phone. He had what looked like a
cell phone, but it was some kind of a voice wireless phone that he could
only use if it was around a wireless network. I don’t know why I never
thought about it. I thought it was strange but then again I thought Richard
was strange. Well I did a reverse look up on the number and guess what? Yes
it’s a voice over IP number that’s not traceable.  We have text
back-and-forth several times since then, but not much he don’t say much any
damn sure won’t say if it’s him or not but he tries to convince me that I
got the wrong number. He’s not who I think he is. I said yeah I guess
that’s normal to get a random text from a voice IP number, two after say
some shit in a file. Way more than coincidence
Isave the number is Richard Burman. I don’t know if it’s him or not, but
that’s what I saved it as.

Send a couple of pictures your way if you don’t mind take a look at them.
And if you’ll send me an address, I will ship one of these all in one
computers to you But please use with caution and don’t cross contaminate
anything of yours. Once you plug it in this computer, do not plug it into
anything else, please.
I’m gonna have to go into my pictures and then select them and then email
them so I’ll send them right after this again. I apologize for this long
ass email and I really appreciate you taking the time to read it if you
have any questions that you would like answered specifically please ask And
I will do my best to answer them.
Thank you and god bless.


Michael Stokes
4433 Toonigh rd
Acworth Ga 30101
7708624083

**Comment by misty913** [comment]
I sent, well tried to send some emails last night.  I just checked and they
are “too large “ so I don’t know if you got any of them or not.
I tried to remove the 4 or 5 pictures that I included but I can’t remove
them I guess.

I’ll send a few more now and then I’ll copy and paste the text later if I’m
allowed

**Comment by misty913** [comment]
I don’t think any of the messages I sent you were allowed to go through.
Oh well. Back to square one. If my hacker don’t like the emails I try to
send they will never make it.
