### ISSUE TITLE
Windows 10 Sleep Mode Malfunction 

### ISSUE THREAD

**Issue by alexouille77** [dragokas/hijackthis#248]
[CollectionLog-2024.04.07-23.06.zip](https://github.com/dragokas/hijackthis/files/14898981/CollectionLog-2024.04.07-23.06.zip)

Hello, 

For a while now, I've been encountering a persistent issue with my Windows 10 computer's sleep mode functionality. Whenever I attempt to initiate sleep mode, the system returns to the desktop after a brief moment, rendering the feature unusable. However, shutting down the computer operates normally.

Upon investigation using the command "powercfg \request," I've identified that certain processes, notably those ending with "svchost.exe," seem to be preventing the system from entering sleep mode. 

Thanks for any kind of help,

**Comment by Sandor-Helper** [comment]
Hello and welcome,

Please [fix in HiJackThis](https://github.com/dragokas/hijackthis/wiki/HJT:-How-to-'Fix-it'):
```
O1 - Hosts: Reset contents to default
O4 - MountPoints2: HKCU\..\{5754a75a-5b36-11eb-a117-309c23a7ad6c}\shell\AutoRun\command: (default) = D:\AutoRun.exe
O4 - Startup Global: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\‎    .scr    ->    (PE EXE) (not signed - Microsoft Corporation - 639E243BA1E4FBE8EA41CB0CDCA9C9A75203CF54)
```
Restart your system.

Next:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by alexouille77** [comment]
Hello, 
Thanks you for your answer. I joined the logs with this message.


[Addition.txt](https://github.com/dragokas/hijackthis/files/14908217/Addition.txt)
[FRST.txt](https://github.com/dragokas/hijackthis/files/14908219/FRST.txt)

**Comment by alexouille77** [comment]
Hello, 
Is there anything wrong ? I have not received any answers yet.

**Comment by Sandor-Helper** [comment]
Hello,
I'm very sorry for delay with my answer. Just missed your thread.

I didn't find any obvious signs of infections in logs.
Programs from IObit are known as PUP, so you can uninstall "IObit Uninstaller 13"
And I'm agree with @dragokas that in your case you have a System problem. Not virus-like one.

**Comment by dragokas** [comment]
Hi,
We only deal with malware-related issues. It is not likely the case.
For resolving general operating system or hardware issues, we suggest asking for help on the forums, like:
 - https://www.tenforums.com
 - https://www.bleepingcomputer.com/forums/f/229/windows-10-support/
 - https://answers.microsoft.com/
 - http://www.geekstogo.com/forum/forum/41-operating-systems/
