### ISSUE TITLE
Firefox and pc acting strange, long load times and loading wheel spinning

### ISSUE THREAD

**Issue by Opus-greybeard** [dragokas/hijackthis#249]
Tried the usual re install and clearing cookies, history cache and so on
But I have growing suspicion that my pc might be compromised
not sure ofc hence the much needed guidance
I hope I have followed the instructions correctly
[Check_Browsers_LNK.log](https://github.com/dragokas/hijackthis/files/14950819/Check_Browsers_LNK.log)
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/14950820/HiJackThis.log)
[info.txt](https://github.com/dragokas/hijackthis/files/14950821/info.txt)
[log.txt](https://github.com/dragokas/hijackthis/files/14950822/log.txt)
[virusinfo_syscheck.zip](https://github.com/dragokas/hijackthis/files/14950823/virusinfo_syscheck.zip)

**Comment by dragokas** [comment]
Hi, 
Next time please upload files in a single archive (CollectionLog.zip)

We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hi,
Logs show that system have a huge amount of process called AppleMobileDeviceProcess.exe running simultaneously.
Lets try to do this:
Uninstall two applications - `Apple Software Update` and `Bonjour`

Restart PC and tell us is there some changes in system behavior.

**Comment by Opus-greybeard** [comment]
Hi dragokas

I uninstalled, apple software update, Bonjour, Icloud for PC, Apple Music Player and the new Apple devices app for syncing phones
No more apple on the Pc

There is a significant improvement in lag, stutter and loading times
Is there a way to check that the huge amount of processes from apple have stopped running ?
A new autologger file ?

rgds

Med vennlig hilsen
Thomas Hiorth Kolstad

________________________________

**Comment by Sandor-Helper** [comment]
I'm Sandor :)

Yes, get new set of logs as CollectionLog.zip please.

**Comment by Opus-greybeard** [comment]
here you go !
thank you in advance Sandor :)
[CollectionLog-2024.04.12-15.27.zip](https://github.com/dragokas/hijackthis/files/14959361/CollectionLog-2024.04.12-15.27.zip)

**Comment by Sandor-Helper** [comment]
Thank you.
 - Did you set up DNS by yourself?
 - Did you install this software by yourself:  https://gamban.com/es/blog/what-is-gamban ?

Please get more logs.
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.
Please rename file FRST64.exe -> FRSTEnglish.exe

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by Opus-greybeard** [comment]
I did not setup DNS, dont know how 🙂 is that a bad or good thing ?
im getting the logs


Med vennlig hilsen
Thomas Hiorth Kolstad


________________________________

**Comment by Opus-greybeard** [comment]
[FRST.txt](https://github.com/dragokas/hijackthis/files/14961693/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/14961694/Addition.txt)

**Comment by Opus-greybeard** [comment]
has my DNS been hijacked, hacked ?

**Comment by dragokas** [comment]
1. Run HiJackThis:
 - press menu Tools - Uninstall manager - Save list, upload here the uninstall_list.txt file.

2. Please answer about:
 - Did you install this software by yourself: https://gamban.com/es/blog/what-is-gamban ? The description saying - it is intended to block gambling sites, it is also responsible for altering DNS for the same purposes.

**Comment by Opus-greybeard** [comment]
1. 
[uninstall_list.txt](https://github.com/dragokas/hijackthis/files/14965452/uninstall_list.txt)

2.Yes, or I didnt, but my brother when he was staying here, GAMBAN says its not possible to delete so have to keep it for a full year then it will unlock, but if you know how I can get it off my PC I would be happy, I cant even play the regular lottery because its banned and if thats the cause of all this mess I need it gone.
thx
thomas

**Comment by dragokas** [comment]
Sorry, the topic has stagnated. If you still need a help, please, let us know.
