### ISSUE TITLE
My computer seems to use almost 45% of my ram constantly and there is nothing in the task manager

### ISSUE THREAD

**Issue by Emalios** [dragokas/hijackthis#250]
Hello since few weeks I got a problem!
Every time my computer boots, I can see on the task manager that I only have 50% of my ram available (I have 16go in total). I am using windows but I don't think it can take that much RAM. The strange thing is that when I check on the task manager to see which program uses RAM i don't see anything that uses a lot of RAM.
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/15310194/HiJackThis.log)
![strange2](https://github.com/dragokas/hijackthis/assets/35004924/0e27d29f-1c63-4089-ab65-b8318980c657)
![strange1](https://github.com/dragokas/hijackthis/assets/35004924/f9ed1863-a2cd-4972-992d-0c7bbe0e8b18)
 
Thanks you in advance!

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download)
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Committing up to 10 GB. (without 3rd-party program to be running) is a normal behaviour for nowadays Windows OS.
In your case ~ 5 GB. is used by system. You can see more info on "Details" tab. All other memory (not visible there) is utilised by core (drivers).
