### ISSUE TITLE
startup_str_36.vbs not found

### ISSUE THREAD

**Issue by ukiyo3000** [dragokas/hijackthis#251]
Can not find script file
"C:\Windows\System32\StartupCheck.vbs".

I tried to add an StartupCheck.vbs with "WScript.Quit" to the System32-Folder but that didn't work. I scanned my PC with Malwarebytes multiple times but it doesn't fix it. Could someone help me out here? 
[CollectionLog-2024.06.19-18.48.zip](https://github.com/user-attachments/files/15903887/CollectionLog-2024.06.19-18.48.zip)

**Comment by Sandor-Helper** [comment]
Hi and welcome,

Please uninstall PUP

> Bonjour

It doesn't needed at Windows systems.

Close all running programs, **temporarily** unload antivirus and other protecting software.

[Run a script in AVZ](https://github.com/dragokas/hijackthis/wiki/AVZ:-How-to-execute-script) (File - Run script):

```
begin
 ExecuteFile('net.exe', 'stop tcpip /y', 0, 15000, true);
 ClearQuarantineEx(true);
 QuarantineFile('C:\Users\Huy\AppData\Roaming\startup_str_36.vbs', '');
 DeleteSchedulerTask('RuntimeBroker_startup_36_str');
 DeleteFile('C:\Users\Huy\AppData\Roaming\startup_str_36.vbs', '64');
 CreateQurantineArchive(GetAVZDirectory + 'quarantine.zip');
ExecuteSysClean;
 ExecuteRepair(22);
 ExecuteWizard('SCU', 2, 3, true);
RebootWindows(true);
end.

```

Computer will _reboot_. 


For _secondary_ diagnostics please run AutoLogger again. 
Attach new CollectionLog to your post.

**Comment by ukiyo3000** [comment]
[CollectionLog-2024.06.20-15.18.zip](https://github.com/user-attachments/files/15914488/CollectionLog-2024.06.20-15.18.zip)

**Comment by Sandor-Helper** [comment]
That was good run. I think that mentioned issue was gone.
But lets see another set of logs:

Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by ukiyo3000** [comment]
[Addition.txt](https://github.com/user-attachments/files/15929590/Addition.txt)
[FRST.txt](https://github.com/user-attachments/files/15929592/FRST.txt)

**Comment by Sandor-Helper** [comment]
Bonjour is still in apps list, uninstall it.

Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CloseProcesses:
SystemRestore: On
CreateRestorePoint:
HKU\S-1-5-21-4272423960-3751217700-1585560764-1001\SOFTWARE\Policies\Google: Beschränkung <==== ACHTUNG
AlternateDataStreams: C:\ProgramData\AMDAutoUpdate.log:5AFFBDE7FB [4298]
AlternateDataStreams: C:\ProgramData\AMDAutoUpdate.log:B5D3D35FA8 [4298]
AlternateDataStreams: C:\ProgramData\unins000.exe:4C9C1A119A [4298]
AlternateDataStreams: C:\ProgramData\unins000.exe:8A5F68F8C0 [4298]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\desktop.ini:B1DA6C571C [4298]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Custom Curve LE.lnk:95F3D5BA1C [4298]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\desktop.ini:41964AA945 [4298]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Epic Games Launcher.lnk:BE32D07BC5 [4298]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk:8096E45125 [4298]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Malwarebytes.lnk:C5D586BE93 [4298]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Microsoft Edge.lnk:E77773B271 [4298]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Netmarble Launcher.lnk:CD5AEA454C [4298]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\TeamSpeak 3 Client.lnk:F208FC6732 [4298]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\TechPowerUp GPU-Z.lnk:718E15FDE8 [4298]
AlternateDataStreams: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Windows Sandbox.lnk:285A51F556 [4298]
AlternateDataStreams: C:\Users\Huy\Desktop\FRST64.exe:MBAM.Zone.Identifier [193]
AlternateDataStreams: C:\Users\Public\Shared Files:VersionCache [5830]
AlternateDataStreams: C:\Users\Public\Desktop\BstShm_5.21.100.1011_nxt:AF90CD8CCE [4298]
AlternateDataStreams: C:\Users\Public\Documents\BstShm_5.21.100.1011_nxt:1BB2FC7B05 [4298]
FirewallRules: [{185CE210-6996-4CE6-A4EC-74CCE6852382}] => (Allow) LPort=26822
FirewallRules: [{BD62234B-DB85-4161-9705-A4CC9802437A}] => (Allow) LPort=32683
FirewallRules: [{15AD703E-872B-4F0D-885E-2FD0D04EA3DC}] => (Allow) C:\Program Files\Bonjour\mDNSResponder.exe (Apple Inc. -> Apple Inc.)
FirewallRules: [{71DCA118-2142-419A-A3D7-5AE59F386D57}] => (Allow) C:\Program Files\Bonjour\mDNSResponder.exe (Apple Inc. -> Apple Inc.)
FirewallRules: [{2E081097-EB2E-46C6-8682-161EF40621E8}] => (Allow) C:\Program Files (x86)\Bonjour\mDNSResponder.exe (Apple Inc. -> Apple Inc.)
FirewallRules: [{92982328-0DD3-48CF-96B4-ED3F3D2A206E}] => (Allow) C:\Program Files (x86)\Bonjour\mDNSResponder.exe (Apple Inc. -> Apple Inc.)
FirewallRules: [{CF5E1ACA-33A3-44BF-B829-F0388C8EAEC6}] => (Allow) LPort=32682
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by ukiyo3000** [comment]
[Fixlog.txt](https://github.com/user-attachments/files/15936602/Fixlog.txt)
 I still need Bonjour so I can move things from the PC to my iPhone.

**Comment by Sandor-Helper** [comment]
This program is only needed for Apple TV.

Fix ran well, so do you still have some issue?

**Comment by ukiyo3000** [comment]
I don't have any issues anymore. Thank you very much!
May I know the cause of the Problem? Was it malware or just a misfunction?

**Comment by Sandor-Helper** [comment]
I think that there were only traces from previous potential infection.

Good.
Rename FRST.exe (FRST64.exe) to **uninstall.exe** and run it. PC will reboot.
This will clean all of FRST folders. Other cureing tools you can sipmly delete.

Here some [Tips to help protect from infection](https://forums.malwarebytes.com/topic/258363-tips-to-help-protect-from-infection/)

**Comment by ukiyo3000** [comment]
Okay I understand, thank you very much!
