### ISSUE TITLE
Possible Malware or virus I'm not sure I've tried and tried so I'm finally asking for help 

### ISSUE THREAD

**Issue by nikkimarie31** [dragokas/hijackthis#252]
[CollectionLog-2024.06.20-09.02.zip](https://github.com/user-attachments/files/15916884/CollectionLog-2024.06.20-09.02.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.

We'll return to you as soon as possible.

Meanwhile, please describe in details what are the signs of infection did you notice?

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hi,
I do not see any obvious signs of infection so far. Waiting for your description.
And please do these logs:

Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by nikkimarie31** [comment]
Thank you so much for helping me. After my son used my computer, I started getting random pop up without anything even being open. I would just shut everything down with the task manager and then all of a sudden multiple ads would pop up. I thought I had stopped them by uninstalling some applications I didn't recognize and then another one popped up the other day while I was working on my computer. I attached the two files you requested. Thank you again for your time.
________________________________

**Comment by Sandor-Helper** [comment]
Please attach these log to your next message (lik you already did in your first post here) rather than inserting them.

**Comment by nikkimarie31** [comment]
[Addition.txt](https://github.com/user-attachments/files/15963673/Addition.txt)
[FRST.txt](https://github.com/user-attachments/files/15963675/FRST.txt)


Also I just had something pop up which I didn't download anything so it seems odd to me and when it popped up I also went and checked to see if my computer is up to date and it is but the notification says restart required you PC needs to be restarted to finish setting up this device: killer wireless-n/a/ac 1435 wireless network adapter. 
and like I said I haven't updated or downloaded anything at all today. I just turned on my computer an hour ago and this is popping up.

**Comment by Sandor-Helper** [comment]
Please show me a screenshot (or shapshot) of such pop up window.

**Comment by nikkimarie31** [comment]
![Screenshot 2024-06-25 004232](https://github.com/dragokas/hijackthis/assets/108557772/28fbad49-5051-416c-a1f6-7becd83cdb94)

**Comment by dragokas** [comment]
Please, clarify, do you mean system notification with "Restart required message"?
That's a normal behaviour. However, if you have constantly see exactly the same message, e.g. about wi-fi adapter installation and despite you already tried to reboot PC, it still appearing again, that's means some issues with drivers or device, not malware related.

To solve too much distraction of such system messages, you can follow this instruction:
https://www.howtogeek.com/349829/how-to-use-focus-assist-do-not-disturb-mode-on-windows-10/
to set "Focus Assist" settings to value: "Alarms Only". This way, most system messages will remain silent.

**Comment by nikkimarie31** [comment]
![Screenshot 2024-06-29 014701](https://github.com/dragokas/hijackthis/assets/108557772/762480de-ea6c-40bc-92ab-96c1abfd60a1)

i also just got this. everytime i try to download something into the program files it says im not the admin when this is my computer and it shows im the admin. speaking of the notification ive never seen one like that before on any of my computers thats why it concerned me. The virus concern is due to random ads popping up when im not even clicking on anything or have anything opened

**Comment by dragokas** [comment]
It is correct behaviour due to specific of Windows 10 security design.
Normally, you are not allowed to save files into "Program Files" directory even if your user account is assigned into Administrator group. It is a part of protection, related to UAC. Why are you trying to save files there? By default, "Downloads" folder (which is C:\Users\nikkimarie\OneDrive\Downloads) is intended to temporarily store files downloaded from internet.

If you have random ads pop-up, please attach a screenshot of such window. We don't see any signs of it so far.
I hope, you figured out how to set up "Focus Assist" mentioned before, which is system notification, not ads.

**Comment by dragokas** [comment]
Closed.
Reason: It seems, help is no more required. 2 weeks left.
If you still need our help, please, execute the last steps, requested by a helper.

**Comment by nikkimarie31** [comment]
everytime i try to login to github it instantly shuts down chrome i
havent been able to do much on my computer and im not sure why so i
havent been able to respond but i remembered that i could write you back in
gmail when i got your email

**Comment by dragokas** [comment]
Please, prepare new CollectionLog according to initial [rules](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F).

**Comment by nikkimarie31** [comment]
Okay I will

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
