### ISSUE TITLE
[Feature] HydraDragonAntivirus Website Signature Check To Find Any Tracker, Spam, Scam, Malware, Botnet, PUP etc.

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [dragokas/hijackthis#253]
**Is your feature request related to a problem? Please describe.**
No it's new

**Describe the solution you'd like**
https://github.com/HydraDragonAntivirus/HydraDragonAntivirus
A cloud solution to host these HydraDragonAntivirus website signatures then check these things at tracker cookies or active connections etc.

**Describe alternatives you've considered**
Another solution is local solution. Create different version of HijackThis to check for malware.
**Additional context**
,https://github.com/HydraDragonAntivirus/HydraDragonAntivirus/blob/main/website/Domains.7z Here is the website list.

**Comment by dragokas** [comment]
HiJackThis+ does not use signatures.
Cookies or active connections check is not implemented.
Please, read description of the project before suggesting such enhancements. Thank you.

**Comment by dragokas** [comment]
Also, I don't see a Cloud or any clear documentation about API.
Are you suggesting to host own Windows Server Cloud?
This goes against the specifics of the project, which is open source and free.
Hosting personal Cloud require monetary costs that will not be covered by anything.

BTW, project looks like a scam. No references or anything. Who are you?

**Comment by HydraDragonAntivirus** [comment]
hm okay it probably detects malware with looking suspicious changes on executables right?

**Comment by dragokas** [comment]
It behaves much like Autoruns with digital signature check. The operator is required to verify is it suspicious. In most cases they use own whitelists.
Also, there is VirusTotal integration, though not so handy as in Autoruns, single file submission is supported through context menu.
