### ISSUE TITLE
Minecraft

### ISSUE THREAD

**Issue by DominatinDorito** [dragokas/hijackthis#254]
Welcome!
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Show us the required logs (for PC cure only):

  * Read carefully: "How to make a request for help in the PC cure section":
https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F

  * Attach 'Collection-[Date].zip' log created by "AutoLogger" tool:
https://www.safezone.cc/resources/autologger-regist-drongo.59/download

### Step 2: Describe your problem in details:

1. What did you done before the problem occurs: _________________
2. What programs (browsers) affected by the problem: ________________
3. Steps to reproduce: _________________
4. Expected behavior: _________________
5. If applicable, add screenshots to help explain your problem.

**Comment by dragokas** [comment]
Hi, @DominatinDorito.

What's up?

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
