### ISSUE TITLE
HJT log

### ISSUE THREAD

**Issue by Brufolo** [dragokas/hijackthis#26]
Welcome !
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Are you in the right place?

  * Do you need assistance in PC cure from viruses?
  * Or would you like to report a bug or propose a feature for HiJackThis?

If yes, see the next step.

### Step 2: Show us required logs (for PC cure):

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details:

1. What did you done before the problem occurs: Nothing_________________
2. What programs (browsers) affected by the problem: Google Chrome
[HiJackThis log.txt](https://github.com/dragokas/hijackthis/files/1826775/HiJackThis.log.txt)
________________
3. Steps to reproduce: _________________

**Comment by dragokas** [comment]
Hi, Brufolo !

If you need help with curing your PC:

1) Describe your problem in details.
2) Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)
3) Read carefully [our conditions and rules](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F).

**Comment by Brufolo** [comment]
Hi.
I'm affecting by lifestion.info....many annoying banners. I'm using Google Chrome. I attach the log created by Autologger. Thank you.
[CollectionLog-2018.03.20-17.27.zip](https://github.com/dragokas/hijackthis/files/1830255/CollectionLog-2018.03.20-17.27.zip)

**Comment by Sandor-Helper** [comment]
Hello,


Fix in HijackThis [https://github.com/dragokas/hijackthis/wiki/HJT:-How-to-'Fix-it'](url) (some of records could be absent):

```
O2-32 - HKLM\..\BHO: (no name) - {02478D38-C3F9-4efb-9B51-7695ECA05670} - (no file)
O9 - Button: HKLM\..\{7815BE26-237D-41A8-A98F-F7BD75F71086} - (no name) - (no file)
O22 - Task (Job): (Ready) EasyAddOns.job - c:\programdata\{18790732-e396-5f70-1879-90732e391ccb}\5699612918318267615b.exe --startup=1 --single
O22 - Task (Job): (Ready) EasyTools.job - c:\programdata\{9647a88f-2846-a40c-9647-7a88f284a23c}\9089012741855757907b.exe --startup=1 --single
O22 - Task (Job): (Ready) FoodSpy.job - c:\programdata\{ede8535e-9152-8802-ede8-8535e9154d7a}\7856491903853659354b.exe --startup=1 --single
O22 - Task (Job): (Ready) GameGo.job - c:\programdata\{63f3f7df-e405-f968-63f3-3f7dfe40df7f}\4098369885605254422b.exe --startup=1 --single
O22 - Task (Job): (Ready) GymExercise.job - c:\programdata\{a66885af-a176-9ec2-a668-885afa1716be}\2473179576826625361b.exe --startup=1 --single
O22 - Task (Job): (Ready) PocketSheets.job - c:\programdata\{0f915f9a-b0ca-6018-0f91-15f9ab0c7e6a}\shydoll1995_cutedoll1995_1...eecams.exe --startup=1 --single
O22 - Task (Job): (Ready) PrivateFiles.job - c:\programdata\{c1912438-0d6a-8f5f-c191-124380d690e0}\6888831321419175283b.exe --startup=1 --single
O22 - Task (Job): (Ready) SniperHit.job - c:\programdata\{656c435a-2701-6b71-656c-c435a2700d68}\3468113712850561286b.exe --startup=1 --single
O22 - Task (Job): (Ready) VidMustSee.job - c:\programdata\{134cc319-69f3-c26f-134c-cc31969f0c65}\212138134468403297b.exe --startup=1 --single
O22 - Task: EasyAddOns - c:\programdata\{18790732-e396-5f70-1879-90732e391ccb}\5699612918318267615b.exe --startup=1 --single (file missing)
O22 - Task: EasyTools - c:\programdata\{9647a88f-2846-a40c-9647-7a88f284a23c}\9089012741855757907b.exe --startup=1 --single (file missing)
O22 - Task: FoodSpy - c:\programdata\{ede8535e-9152-8802-ede8-8535e9154d7a}\7856491903853659354b.exe --startup=1 --single (file missing)
O22 - Task: GameGo - c:\programdata\{63f3f7df-e405-f968-63f3-3f7dfe40df7f}\4098369885605254422b.exe --startup=1 --single (file missing)
O22 - Task: GymExercise - c:\programdata\{a66885af-a176-9ec2-a668-885afa1716be}\2473179576826625361b.exe --startup=1 --single (file missing)
O22 - Task: LifeChatTask - C:\Program Files\Microsoft LifeChat\LifeChat.exe (file missing)
O22 - Task: PocketSheets - c:\programdata\{0f915f9a-b0ca-6018-0f91-15f9ab0c7e6a}\shydoll1995_cutedoll1995_1...eecams.exe --startup=1 --single (file missing)
O22 - Task: PrivateFiles - c:\programdata\{c1912438-0d6a-8f5f-c191-124380d690e0}\6888831321419175283b.exe --startup=1 --single (file missing)
O22 - Task: SniperHit - c:\programdata\{656c435a-2701-6b71-656c-c435a2700d68}\3468113712850561286b.exe --startup=1 --single (file missing)
O22 - Task: VidMustSee - c:\programdata\{134cc319-69f3-c26f-134c-cc31969f0c65}\212138134468403297b.exe --startup=1 --single (file missing)
O26 - IFEO: HKLM\..\sethc.exe: [Debugger] = C:\Windows\system32\systray.exe
O26 - IFEO: HKLM\..\utilman.exe: [Debugger] = C:\Windows\system32\systray.exe
```


For secondary diagnostics please run AutoLogger again. 
Attach new CollectionLog to your post.

> many annoying banners

In which browser you see it? Please check, is it appears in Internet Explorer?

**Comment by Brufolo** [comment]
I've fix it. The browsers are Chrome and IE.
This is a new log by Autologger
[CollectionLog-2018.03.22-07.44.zip](https://github.com/dragokas/hijackthis/files/1836384/CollectionLog-2018.03.22-07.44.zip)

**Comment by Sandor-Helper** [comment]
> I've fix it

**Comment by Sandor-Helper** [comment]
>I've fix it.

Yes, new log looks much better.
>browsers are Chrome and IE

My question was: is that annoying banners appears in IE also?

Please download [AdwCleaner](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) run it and do a Scan. Attach C:\AdwCleaner\AdwCleaner[Sx].txt log (x - means any number).

**Comment by Brufolo** [comment]
Browsers (affected) are Chrome and IE
[AdwCleaner[S0].txt](https://github.com/dragokas/hijackthis/files/1839013/AdwCleaner.S0.txt)

**Comment by Brufolo** [comment]
I only use Google Chrome but, for a try, i had a chance with I.E. 
The banners appears in I.E. too... and still don't stop...

**Comment by Sandor-Helper** [comment]
Please run AdwCleaner again, do Scan and then do Clean. PC should reboot after clean. Attach appropriate log - C:\AdwCleaner\AdwCleaner[Cx].txt

Also, Uninstall MyFreeCodec.

**Comment by Brufolo** [comment]
Hi. This is the last AdwCleaner log.
[AdwCleaner[S3].txt](https://github.com/dragokas/hijackthis/files/1869151/AdwCleaner.S3.txt)

**Comment by Sandor-Helper** [comment]
I'm sorry for missing your post.
Please attach **clean** log (which contents symbol [Cx] in name where x - any number).

**Comment by Brufolo** [comment]
Hi. Here the requested logs:
[AdwCleaner[C2].txt](https://github.com/dragokas/hijackthis/files/1899718/AdwCleaner.C2.txt)

**Comment by Sandor-Helper** [comment]
HitmanPro 3.8 - it's better to uninstall it.

**Comment by Brufolo** [comment]
Here the last log
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/1910409/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
Please describe - what problems are remains now?

**Comment by Brufolo** [comment]
No more problem...thanks a lot to everybody...
