### ISSUE TITLE
PC Help - Runs like a Sloth

### ISSUE THREAD

**Issue by Octoberkayne** [dragokas/hijackthis#262]
I have a Windows 10 PC that I can run CCleaner & Malwarebytes on to clean up, but within a week, it reverts back to the speed of a sloth. I'm hoping someone might be able to offer some suggestions on what might be going on and get me on the right track.
[CollectionLog-2024.11.10-02.51.zip](https://github.com/user-attachments/files/17690943/CollectionLog-2024.11.10-02.51.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

Please turn off any anti-virus while getting logs or executing scripts.

1. Start Malwarebytes, do a full scan, export its result to text file and attach it to your next message.
2. 
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
