### ISSUE TITLE
Laptop opens programs, windows and files independently

### ISSUE THREAD

**Issue by Hatdatnit** [dragokas/hijackthis#263]
Hi All,
My new Dell Laptop opens programs, windows and files independently. Shutting down and restart helps fixing it. But when the Laptop wakes up after it went sleeping (becauise of not using it) the mass starts again. McAffee could not find a virus.

*Text log has been deleted by moderator*

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip)

  * Describe your problem more detailed: what do you mean by "opens independently"? Can you provide program name or screenshot of the issue?

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
