### ISSUE TITLE
Need for help/ Potential Malware in here ? 

### ISSUE THREAD

**Issue by Gundalf187** [dragokas/hijackthis#266]
Since the 17.11. My PC performance declined drastically. (potentially due to some downloads of some Minceraft mods AND AMD Driver Update). My System was already checked with Malwarebyte, HitmanPro, Adwcleaner, Microsoft Defender, RKill, where 2 or 3 suspicious files were found and deleted. Problem wasn´t solved, the performance is still extremely slow but i got some time windows like now where I can almost use it like before. 

I did a Hijackthis scan and i need someone to "encrypt" the log and tell me what can I do. 
Sry for my lack of english skills. 

[HiJackThis.log](https://github.com/user-attachments/files/17873834/HiJackThis.log)

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download)
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
