### ISSUE TITLE
Can somebody check these logs for me?

### ISSUE THREAD

**Issue by LIKATNO** [dragokas/hijackthis#268]
Hi there,
may somebody look at my case? I'm not sure if there is something suspicious.
Thanks

[CollectionLog-2024.12.07-12.09.zip](https://github.com/user-attachments/files/18048162/CollectionLog-2024.12.07-12.09.zip)

**Comment by dragokas** [comment]
Hi,
If you need our assistance:

 * Please, describe in details do your have any issues with PC

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hi.
I didn't find any obvious signs of infections in these logs so far.
You should uninstall useless
> Spybot - Search & Destroy
> Spybot Anti-Beacon

After that do a whole system scan with Malwarebytes, save its log as text file and attach it to your next post.

Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

Also please describe in details what kind of issues you have seen.

**Comment by LIKATNO** [comment]
First of all thanks for your help and respond. I appreciate this.

> You should uninstall useless
> 
> > Spybot - Search & Destroy
> > Spybot Anti-Beacon

It's done, is this program dangerous in some way? I know that people can use these kind of apps to easy access to pc without host's knowledge. Anyway, here's mentioned logs by you.

[Malwarebytes Raport 2024-12-11 003822.txt](https://github.com/user-attachments/files/18087945/Malwarebytes.Raport.2024-12-11.003822.txt)

[Addition.txt](https://github.com/user-attachments/files/18087968/Addition.txt)
[FRST.txt](https://github.com/user-attachments/files/18087970/FRST.txt)

May I talk to you in private message? I wanna describe my worries in more details, but I don't want to make it on the forum. I have some questions if u doesn't mind. How can we hook up?

**Comment by Sandor-Helper** [comment]
> is this program dangerous in some way?

These programs intends to unwanted or even scareware. It could for example "find" some viruses in your system (no matter that system is clean) but to cure them it will ask you to bye license. Something like that. So it's better to stay away from that kind of programs.

Malwarebytes didn't find any suspicious and it is good.

Lets do some general clean fix in Farbar.

Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CloseProcesses:
SystemRestore: On
CreateRestorePoint:
HKLM\SOFTWARE\Policies\Microsoft\Windows Defender: Ograniczenia <==== UWAGA
BootExecute: autocheck autochk * sdnclean64.exe
HKLM\SOFTWARE\Policies\Mozilla\Firefox: Ograniczenia <==== UWAGA
HKLM\SOFTWARE\Policies\Google: Ograniczenia <==== UWAGA
HKLM\SOFTWARE\Policies\Microsoft\Edge: Ograniczenia <==== UWAGA
S2 SpybotAntiBeaconInterceptor; C:\Program Files (x86)\Safer-Networking Ltd\Spybot Anti-Beacon\x64\Spybot3AntiBeaconService.exe --run [X]
2024-12-07 11:16 - 2024-12-07 11:16 - 000000000 ____D C:\Windows\system32\Tasks\Safer-Networking
2024-12-07 11:15 - 2024-12-09 09:40 - 000000000 ____D C:\ProgramData\Spybot - Search & Destroy
AlternateDataStreams: C:\Users\Trox1\Dane aplikacji:00e481b5e22dbe1f649fcddd505d3eb7 [394]
AlternateDataStreams: C:\Users\Trox1\AppData\Roaming:00e481b5e22dbe1f649fcddd505d3eb7 [394]
FirewallRules: [{3002E888-8F9C-4FF2-A381-9911FDB734C2}] => (Block) LPort=135
FirewallRules: [{1ED7D8D5-4A5B-4F6A-929D-91F81B105760}] => (Block) LPort=445
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.



> May I talk to you in private message?

Yes, you can write me to sandor@safezone,cc

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
