### ISSUE TITLE
malware

### ISSUE THREAD

**Issue by rino254** [dragokas/hijackthis#27]
Welcome !
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Are you in the right place?

  * Do you need assistance in PC cure from viruses?
  * Or would you like to report a bug or propose a feature for HiJackThis?

If yes, see the next step.

### Step 2: Show us required logs (for PC cure):

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details:

1. What did you done before the problem occurs: browser open inaspectately pages
2. What programs (browsers) affected by the problem: chrome - edge
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/2065162/HiJackThis.log)

**Comment by dragokas** [comment]
Hi, rino254 !

Thank you for the log.
Do you need any assistance?
If so:
  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Comment by dragokas** [comment]
No answer for 10 days. Closed.
If you still need our help, please, post new CollectionLog.
