### ISSUE TITLE
Second issue - Malicious IP's blocked by ISP 

### ISSUE THREAD

**Issue by Corliss-82** [dragokas/hijackthis#270]
This recently started again yesterday, here is a link to the previous issue - https://github.com/dragokas/hijackthis/issues/264
I don't believe I ever visit high risk sites, I don't accept cookies from sites I don't know.  I have included a screenshot of what my ISP sends me. 

[CollectionLog-2024.12.14-03.46.zip](https://github.com/user-attachments/files/18135179/CollectionLog-2024.12.14-03.46.zip)
![Screenshot_20241214-034310](https://github.com/user-attachments/assets/a861872a-edbe-430c-82b8-e1603f2d897f)

**Comment by Sandor-Helper** [comment]
Hi,
For some reason there is no logs from AVZ in the pack, I suppose you didn't turn off your Norton while starting Autologger. In its folder you can find logs called report, please attach them to your next post.
How your connection to the Net is organized? Do you use router? If so, is it only one connection to it or maybe more PC or phones are connected?

Lets see more logs:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by Corliss-82** [comment]
Thought I had it disabled, I see two logs, both attached.
I connect through a router/modem combo with two hard wired connections, and 10-11 wifi devices. 
One of my hard drives is from a laptop I had from 2008 that still has a windows 7 installation on it.
[report1.log](https://github.com/user-attachments/files/18135724/report1.log)
[report2.log](https://github.com/user-attachments/files/18135725/report2.log)
[Addition.txt](https://github.com/user-attachments/files/18135726/Addition.txt)
[FRST.txt](https://github.com/user-attachments/files/18135727/FRST.txt)

**Comment by Sandor-Helper** [comment]
> two hard wired connections, and 10-11 wifi devices

Does this issue appears on other devices?

You have a lot of notifications turned on in Chrome:

> CHR Notifications: Default -> hxxps://hibid.com; hxxps://member.igv.com; hxxps://messages.google.com; hxxps://www.g2a.com; hxxps://www.govplanet.com; hxxps://www.igv.com

You can edit this option [this way](https://support.google.com/chrome/answer/3220216?hl=en&co=GENIE.Platform%3DDesktop) or we can turn them off by script.

**Comment by Corliss-82** [comment]
It's only this hard wired device, I will manually disable the notifications

**Comment by Sandor-Helper** [comment]
Ok, lets do some kind of general clean of the system and then get more scan.

Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CloseProcesses:
SystemRestore: On
CreateRestorePoint:
HKLM\SOFTWARE\Policies\Mozilla\Firefox: Restriction <==== ATTENTION
2024-11-15 18:46 - 2024-11-13 11:17 - 000000000 ____D C:\ProgramData\Avast Software
FirewallRules: [{31139B12-B739-4C0E-AA26-FD3186ABE7B6}] => (Allow) C:\Users\richa\AppData\Local\Temp\Ins9F7\Setup.exe => No File
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

Next:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

Please try to find out - in which situation the issue appears:
- by surfing (if so, what exactly browser is running)?
- by playing a game?
- nothing is started?

Is the issue appears when system running in Safe Mode with networking?

**Comment by Corliss-82** [comment]
I have not been successful in getting safe mode with networking, it keeps telling me I have no network adapters. 

[Addition.txt](https://github.com/user-attachments/files/18170023/Addition.txt)
[Fixlog.txt](https://github.com/user-attachments/files/18170025/Fixlog.txt)
[FRST.txt](https://github.com/user-attachments/files/18170029/FRST.txt)
[AdwCleaner[S00].txt](https://github.com/user-attachments/files/18170050/AdwCleaner.S00.txt)

**Comment by Sandor-Helper** [comment]
You didn't answer my questions.

OK, AdwCleaner find nothing and it's good.

Please download [Microsoft Safety Scanner](https://go.microsoft.com/fwlink/?LinkId=212732) and run it.

In the **Scan Options** choose **FULL scan**.

Please get a lot of patience cause the scan may take several hours (it depends from the PC speed and amount of files).
Wait until it ends.
Find log named **MSERT.log** in this folder C:\Windows\debug\msert.log

Attach it to your next post.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
