### ISSUE TITLE
Can someone check this log

### ISSUE THREAD

**Issue by najmihamdin** [dragokas/hijackthis#272]
Hi there,
may somebody look at my case? I'm not sure if there is something suspicious.
Thanks

[CollectionLog-2024.12.18-09.33.zip](https://github.com/user-attachments/files/18173454/CollectionLog-2024.12.18-09.33.zip)

**Comment by Sandor-Helper** [comment]
Hi and welcome,

I didn't find any suspicious signs in logs. What kind of issue you suspect?
Unless some records from previous Comodo installation have been seen. You can run [this tool](https://download.comodo.com/cis/download/installs/ciscleanuptool/ciscleanuptool_x64.exe) to clean them.

**Comment by najmihamdin** [comment]
I found this pc always want to remote same network. Almost got 2k access has been blocked. Like using AI. I will try using this tool to clean up Comodo. Thanks for replying

**Comment by Sandor-Helper** [comment]
Where exactly you get this 2k access?

Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
