### ISSUE TITLE
2025 Malware Infects Hardware & Can Modify Windows During Setup (No matter how many times SSD is erased/sanitized))

### ISSUE THREAD

**Issue by Tackett132** [dragokas/hijackthis#273]
All this Malware is using fake Microsoft signatures to sneak through the cracks.
I have been using Lite versions and the SuperLite version broke the malware from growing as it has most features removed. But using any Windows with regular features & Microsoft Store included this malware can use Internet Explorer to execute Javascript and install more malware. I've found millions of malware directories I even posted a video of the mile long directories on facebook. I know about 75% of what I'm looking at when I use Hijack This+. I Just need someone to look at my complete log I made to make sure I'm not crazy. Because it seems as if it also makes hidden profiles that I cant see, but I can find all their directories.

[HiJackThis+ Complete Scan.txt](https://github.com/user-attachments/files/18174775/HiJackThis%2B.Complete.Scan.txt)

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download)
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
