### ISSUE TITLE
Security Fixes & Protection Center

### ISSUE THREAD

**Issue by dragokas** [dragokas/hijackthis#30]
Welcome, contributors!

Here is new "work in progress" module (see comments in [frmSecurity.frm file](https://github.com/dragokas/hijackthis/blob/devel/src/frmSecurity.frm)).

![security](https://user-images.githubusercontent.com/19956568/42345308-8e0cf8a0-80a7-11e8-983a-41de2e9e5c86.png)

Purpose of the center:
 - increase system security by individual user wish;
 - optimization for the best performance.

You can:
 - Help with writing the code and pull request;
 - Suggest something new, suitable for this center.
 - Say some objections and wishes about already planned features.

Thanks,
Stanislav.

**Comment by beerisgood** [comment]
It already exist such a project for security: https://github.com/securitywithoutborders/hardentools
Maybe work together instead of start from scratch?

**Comment by dragokas** [comment]
Hi,
Thank you for letting me know about that project.
Pretty interesting discussions there. I'll, maybe, use something for the basic scan engine.

So it's even better that there is already such a tool.
I will have time to concentrate on more important tasks and drop idea of such tool inside HJT.

**Comment by dragokas** [comment]
Closed and removed from HJT, because there is a better alternative.
