### ISSUE TITLE
HiJackThis Logfile - maybe an virus on system?

### ISSUE THREAD

**Issue by ReCoNtY** [dragokas/hijackthis#34]
HiJackThis Logfile - is there a keylogger or Virus?
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/2238050/HiJackThis.log)

**Comment by dragokas** [comment]
Hi, @ReCoNtY !

Please,
  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648) and prepare new CollectionLog.
