### ISSUE TITLE
task host window stop closing pc

### ISSUE THREAD

**Issue by usamaAlsadany** [dragokas/hijackthis#35]
i frstly download pycharm and setup it . the desktop was like picture 1
![picture 1](https://user-images.githubusercontent.com/41965557/43473158-aae3b4ee-94ef-11e8-8dda-336fde1abcc1.png)  
after restating pc , desktop becomes 
![picture 2](https://user-images.githubusercontent.com/41965557/43473461-7d03f95c-94f0-11e8-81f1-eea28b395b05.png)
if I rearrange the icons and restart pc the arrangement will change again to be next to some of them like picture 2 
then I uninstall pycharm this action doesn't occur again but if i use program on desktop and close the program i find its place changes _ that occurs these days

after some days when shutting down pc i find message " task host window stop closing Pc " 

the hijack report :: 
[hijackthis.log](https://github.com/dragokas/hijackthis/files/2246289/hijackthis.log)

this installed programs report 
[InstallList.txt](https://github.com/dragokas/hijackthis/files/2246334/InstallList.txt)

if you please , i want to what makes programs' places change and stop " task host window stop closing Pc " 

Thanks in advance.

**Comment by dragokas** [comment]
Hi, @usamaAlsadany !

Please, notice, that this section is intended for helping with cure malware infection.
For resolving system problems it's better to ask help on Windows specific forums, like https://www.tenforums.com

If you suspect that your machine is infected and you need our assistance, please:
  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Comment by usamaAlsadany** [comment]
Hi, @dragokas .
I hope you are fine ,
thanks for reply ..
I think the problem is malware infection 
this is autologger log
[CollectionLog-2018.08.05-22.08.zip](https://github.com/dragokas/hijackthis/files/2260675/CollectionLog-2018.08.05-22.08.zip)

**Comment by usamaAlsadany** [comment]
Hi, @dragokas <https://github.com/dragokas> .
I hope you are fine ,
thanks for reply ..
I think the problem is malware infection
this is autologger log
CollectionLog-2018.08.05-22.08.zip
<https://github.com/dragokas/hijackthis/files/2260675/CollectionLog-2018.08.05-22.08.zip>


‫في الثلاثاء، 31 يوليو 2018 في 8:15 م تمت كتابة ما يلي بواسطة ‪Stanislav
Polshyn‬‏ <‪notifications@github.com‬‏>:‬

**Comment by Sandor-Helper** [comment]
Hi, @usamaAlsadany,

I didn't find any malicious records in logs.
Try this:
Right-click on empty space of the Desktop. Switch **off** checkmark at View -> Organize icons automatically (or something like that).

**Comment by dragokas** [comment]
Hi, @usamaAlsadany.
Since it's not a malware issue, we recommend you to ask help on one of the forums that provide assistance in resolving general operation system issues, like:
 - https://answers.microsoft.com/
 - https://www.tenforums.com/
 - http://www.geekstogo.com/forum/forum/41-operating-systems/

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, type something in this topic.
