### ISSUE TITLE
Chrome LAG on text fields

### ISSUE THREAD

**Issue by gspitman** [dragokas/hijackthis#37]
Welcome !
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Are you in the right place?

  * Do you need assistance in PC cure from viruses?
  * Or would you like to report a bug or propose a feature for HiJackThis?

If yes, see the next step.

### Step 2: Show us required logs (for PC cure):

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details:

1. What did you done before the problem occurs: Click on any text entry field in Chrome
2. What programs (browsers) affected by the problem: Chrome
3. Steps to reproduce: Click on a text entry field, there will be clocking for about 3 seconds then text can be entered.
[CollectionLog-2018.08.10-09.55.zip](https://github.com/dragokas/hijackthis/files/2278356/CollectionLog-2018.08.10-09.55.zip)

**Comment by dragokas** [comment]
Thank you for the log.
Please:
  * Describe your problem in more details.
  * Do you have another signs of infection?

We'll return to you as soon, as we have a free time.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Comment by gspitman** [comment]
No other infection signs, just a clocking of about 3 seconds when clicking
drop down or text entry areas in chrome. Even in the address/search bar.

**Comment by Sandor-Helper** [comment]
Hello and welcome!

Please do following additional steps:

Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by gspitman** [comment]
# -------------------------------
# Malwarebytes AdwCleaner 7.2.2.0
# -------------------------------
# Build:    07-17-2018
# Database: 2018-08-13.2
# Support:  https://www.malwarebytes.com/support
#
# -------------------------------
# Mode: Scan
# -------------------------------
# Start:    08-15-2018
# Duration: 00:00:30
# OS:       Windows 10 Pro
# Scanned:  41819
# Detected: 2


***** [ Services ] *****

No malicious services found.

***** [ Folders ] *****

No malicious folders found.

***** [ Files ] *****

No malicious files found.

***** [ DLL ] *****

No malicious DLLs found.

***** [ WMI ] *****

No malicious WMI found.

**Comment by akokSZ** [comment]
Greetings

Try downloading the portable version of Chrome. Check if there will be a problem again

**Comment by gspitman** [comment]
Same problem with Portable.

**Comment by Sandor-Helper** [comment]
In logs I see that **DotNetBrowser Chromium** is running. Do you know about it? Perhaps it was installed along with some software.

**Comment by gspitman** [comment]
No, I'm not aware of this. Should I remove it?

**Comment by Sandor-Helper** [comment]
Yes, you can try. Though I didn't find it in installed programs list.

Additionally lets see FRST logs:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.


- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please do not copy and paste the logs back here, but attach them as you did in first your post.

**Comment by gspitman** [comment]
My company's malware blocker won't allow that tool to execute.

**Comment by dragokas** [comment]
Hi, @gspitman.

Please, try again. It was a broken link. Sorry.

**Comment by gspitman** [comment]
The broken link wasn't the issue. I found the file, it's just prohibited
here.

**Comment by Sandor-Helper** [comment]
@gspitman, can you ask your company's administrator to temporarily unlock this tool? It is well-known tool and it used very widely to cure system and malware problems. Or it'll be better to add it to exclusion of your anti-virus.

**Comment by gspitman** [comment]
Thank you all for your help.  I just decided to re-image instead of hunting
down the bug.

**Comment by dragokas** [comment]
Good luck!
