### ISSUE TITLE
Endless "The shell stopped unexpectedly and explorer.exe was restarted."

### ISSUE THREAD

**Issue by VulcanTourist** [dragokas/hijackthis#38]
Welcome !
Thank you for joining the section of VIRUSNET association support.

  * Describe your problem in details:

1. What did you done before the problem occurs:
Beginning two days ago, beginning with system boot and as long as the Windows (Explorer) Shell is active, it repeatedly continually fails and restarts every few seconds to minutes (just happened now as I was typing this).  It's apparently freezing or hanging, and certain actions like right-clicking on the Desktop will elicit an immediate crash and restart, but otherwise some watchdog eventually kicks in and does the deed.

After one of these events, the Shell will be momentarily functional - e.g. Desktop right-click context menu works - but only briefly.  (Another restart just happened.)  The restarts grab focus away from every other process and that primary Shell instance of explorer.exe also seems to permanently hog one CPU core as long as it is active (25% utilization of a 4-core Core i5-3570K CPU), making the system largely unusable as long as the Shell is active.  Killing the primary explorer.exe process provides some relief, AND Explorer then continues to function normally as a file manager.  

2. What programs (browsers) affected by the problem:
Everything is affected, obviously.

3. Steps to reproduce:
Boot the system and wait....

In addition to attaching the requested Autologger log file, I am attaching a Zip file containing an .evtx Event Viewer file containing a filtered view of some of the recorded APPCRASH and BEX64 Application log events.

[CollectionLog-2018.08.22-18.34.zip](https://github.com/dragokas/hijackthis/files/2312595/CollectionLog-2018.08.22-18.34.zip)
[BEX64 explorer.exe crashes.evtx.zip](https://github.com/dragokas/hijackthis/files/2312596/BEX64.explorer.exe.crashes.evtx.zip)

**Comment by dragokas** [comment]
Thank you for the log.
We'll return to you as soon, as we have a free time.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Comment by dragokas** [comment]
Hi, VulcanTourist!

It's rather problem with installed software or due to the tweaks, not a virus related.
Since we are providing virus cure help only, we recommend you to ask about your case on forum, such as: https://www.tenforums.com

The only suspicious object is:
`C:\Program Files (x86)\Privoxy\privoxy.exe`
Is it familiar to you?

**Comment by VulcanTourist** [comment]
Privoxy is a well-known and respected HTTP proxy filter, similar to the obsolete Proxomitron.  I will continue looking for answers elsewhere.  I found an alternative shell - seems to be just one available now - and it sidestepped the problem but it wasn't refined enough to be usable.

**Comment by dragokas** [comment]
Sometimes well-known tools used by intruders to redirect you on another site/show adware.
You have many 3rd-party loaded libraries in explorer + tweaks. The usual way is to disable one by one and see what's happen. But, it's better to ask concrete steps and algorithm on profile forum.
Good luck.

Topic is closed.
Reason: non-malware related issue.
