### ISSUE TITLE
I suspect I am infected with a nasty Rootkit or a stealthy Trojan Horse

### ISSUE THREAD

**Issue by joshsprings** [dragokas/hijackthis#42]
Hello,

Thank you for taking the time to read my post. As the title states, I suspect I am infected with some sort of Rootkit (or possibly a Trojan Horse). Prior to the infection, there was a person skilled in computers and programming that had physical access to my computer. I was informed by others that he had infected my PC. Upon learning this, I did some looking around, but did not find much. However, at this point I didn't know what was true and what wasn't, so I didn't dig very deep.

Approximately a week and a half later, I spoke with this individual and he/she in so many words threatened to "hack" me / do damage to my computer. Approximately 12-16 hours after the threat was made, I was working on my computer when I noticed it started to run hard and fast. My PC fan sped up and I had sensed that various resources on my PC had increased so I opened Task Manager and saw that my Antivirus program was taking up a high percentage of my Disk Usage (I cannot remember the exact percentage/number, but it was high enough to cause concern). I wanted to rule out that it may be my Antivirus simply downloading a definitions update, so I opened the main GUI and saw that it wasn't downloading anything.

I decided to restart my PC to see if any of the issues I've described so far would continue after a reboot, and they did. Therefore, I proceeded to run a netstat command and when I did so I noticed...I would estimate ~250-300 remote ports that were present in some form of state. Most of the ports were random 5-digit ports that were in sets of sequential numbers. For example: 48270, 48271, 48272, 48273, etc. and then they would skip ~50 numbers and pick back up in a sequential format, like so: 48220, 48221, 48222, 48223, etc.

I immediately unplugged my Ethernet cable out from the back of my PC tower and started doing some serious investigating on my PC. I found out that a rule had been added to my Antivirus Firewall that essentially rendered the firewall useless without actually disabling it (considering I would have noticed if it was disabled almost immediately). The rule that was added allowed any network, application, protocol, port, etc. full access to my PC. I also noticed that Developer Options in Windows 10 Pro had been enabled, as well as Microsoft's new implementation of their SSH Server. I now knew that this was very bad, and very serious.

Moving on, this actually happened two or three months ago so I'm not going to go into great detail about all of the symptoms I have experienced since the initial infection unless requested to do so (I'd rather have the logs examined before I list things that may not even be of any relevance or importance). However, I think it's important to note that my primary Email address was compromised about 2 hours after the initial infection. A day or two later I found out that whatever was dropped and executed on my PC had spread throughout my entire LAN, infecting the 4 other PCs that connect to / reside on it because the same symptoms that started appearing on the original computer that was infected also started appearing on my other computers (along with some new / different symptoms).

The AutoLogger log file attached below was generated on a laptop running Windows 7 Pro SP1 (64-bit). The original PC that was infected was running Windows 10 Pro (64-bit). At the moment, the original PC that was initially infected is no longer booting properly. However, I created a WinPE on a USB Stick and I downloaded AVZ v4 directly from the creator's website and was able to configure my own settings and run a full scan. It detected A LOT. I cannot be sure if what it detected is any type of real threat (although it sure appears to be), but I am going to include that log as well due to the fact that I personally feel that the default settings within AVZ (when it is launched by AutoLogger) are nowhere near sufficient enough to detect everything thats on my PCs (namely kernel hooks/intercepts and a whole lot more).

As you will see in the Windows 10 Pro (64-bit) log file, it appears that whatever has apparently infected my computer is residing in my Recycle Bin (I know it sounds weird, I'll let you look at the logs and tell me if its anything malicious or not) as well as my Windows folder (and some of its important subfolders). The last thing I'll say in an attempt not to have this post end up being over 50,000 characters long is that I have ran various programs such as Malwarebytes' AdwCleaner since the initial infection. On another PC running Windows 10 Home (64-bit) AdwCleaner will detect 7 registry keys and one service as being malicious. It will successfully move these item to Quarantine, it'll have me reboot, I'll delete them from the Quarantine section, and then scan again to make sure nothing was missed and the same exact registry keys and the one service are detected all over again. It seems any progress I've been able to make at any given time is quickly erased once the PC in question is rebooted.

Thank you very much for your time and your patience. I have received permission to place the logs in a zip file that is password protected. Whichever helper is assigned to look over this can obtain the password from Mr. Alex.

**NOTE:** If I was not supposed to include an additional log and/or if the helper assigned to my case is not allowed to view or take it into account, please forgive me and simply ignore it. I just really, really feel it may be of some importance being that it provides so much more than when AVZ is simply launched from AutoLogger.

[My_Collection_Logs.zip](https://github.com/dragokas/hijackthis/files/2385276/My_Collection_Logs.zip)

**Comment by dragokas** [comment]
Thank you for the log.
We'll return to you as soon, as we have a free time.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Comment by joshsprings** [comment]
dragokas,

Sure thing. Thank you for your response.

**Comment by Sandor-Helper** [comment]
Hello,
lets concentrate on this PC where you got the CollectionLog. (About other PC we'll talk a bit later).
You have Malwarebytes version 3.5.1.2522 installed.
Please do a whole scan, do not delete anything by yourself, save the results by pressing "Save in text file" button and attach the result file.

**Comment by joshsprings** [comment]
Hello Sandor,

I am very sorry for my delayed response but the good news is I know why it happened (due to a misconfiguration within my Email Notifications) and I will make sure I check this Issue at least once per day.

Yes, I do have Malwarebytes installed and although I'm not sure if this matters, I just upgraded to their latest version: v3.6.1 (I have a legal, licensed copy). I have Malwarebytes scheduled to scan my computer every 24 hours (I have enabled for it to detect rootkits) so I am confident it will not detect anything, but then again it never has been able to do so from the start.

However, of course I will happily follow your instructions. After I submit this post, I am going to close my browser (as well as any other running programs and do a Full Threat Scan. Once it's finished, I will return and post the log file.

Thanks in advance!

**Comment by joshsprings** [comment]
Hello Sandar,

Here is the Malwarebytes log. Considering Malwarebytes came back with no detections, I'm going to paste about 40 lines of hidden directories/files below that came from log of the program Show Hidden that I downloaded from Bleeping Computer. I'm in no way suggesting you think I am not infected, but unless I have some pretty advanced/stealthy malware on my computer, everyone knows Malwarebytes should have detected something. So I'm pasting these lines so you'll see that although Malwarebytes cannot and has not been able to detect anything from the time of the initial infection, there is some type of malware on my computer that can hide itself very well. I'm hoping this will further give you an idea of what I may be infected with (I already have my suspicions).

>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\History\History.IE5
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Feeds Cache
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\History\History.IE5
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Feeds Cache
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Internet Explorer\DOMStore
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Internet Explorer\EmieSiteList
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Internet Explorer\EmieUserList
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\3FLHNI0D
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\6K4LGNMK
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\7HWRRNDQ
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\9U3I3CY4
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\9U3I3CY4\1
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\V1NNRZQY
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\YQ4Y0IRH
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\Burn\Burn
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\History
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\History\History.IE5
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\WebCache
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\WebCache.old
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Temporary Internet Files\Content.IE5
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\History\History.IE5
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\History\History.IE5\MSHist012018091920180920
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Device Metadata\dmrccache\downloads
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Feeds\{5588ACFD-6436-411B-A5CE-666AE6A92D3D}~
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Feeds Cache
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Internet Explorer\DOMStore
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Internet Explorer\DOMStore\V91MQYPT
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Internet Explorer\EmieBrowserModeList
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Internet Explorer\EmieSiteList
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Internet Explorer\EmieUserList
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\3FLHNI0D
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\6K4LGNMK
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\7HWRRNDQ
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\9U3I3CY4
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\9U3I3CY4\1
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\V1NNRZQY
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\AppCache\YQ4Y0IRH
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\Burn\Burn
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\History
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\History\History.IE5
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\Temporary Internet Files
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\Temporary Internet Files\Content.IE5
>  * C:\Documents and Settings\<Redacted>\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Microsoft\Windows\WebCache

The following 8 lines are _always_ removed by Malwarebytes' Junk Removal Tool (I know it is no longer being developed but AdwCleaner doesn't detect and remove these directories so I still run JRT as well). When I say they are always removed when I run JRT, what I mean is I can run JRT right now, they'll be removed, then run it an hour later without restarting, and they'll be present _again_ and be removed.

> File System: 8 
> 
> Successfully deleted: C:\Users\<Redacted>\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.IE5\04BO3WIS (Temporary Internet Files Folder) 
> Successfully deleted: C:\Users\<Redacted>\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.IE5\0ZHXXPLX (Temporary Internet Files Folder) 
> Successfully deleted: C:\Users\<Redacted>\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.IE5\JL0LXL2R (Temporary Internet Files Folder) 
> Successfully deleted: C:\Users\<Redacted>\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.IE5\NDDESB2Q (Temporary Internet Files Folder) 
> Successfully deleted: C:\windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.IE5\04BO3WIS (Temporary Internet Files Folder) 
> Successfully deleted: C:\windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.IE5\0ZHXXPLX (Temporary Internet Files Folder) 
> Successfully deleted: C:\windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.IE5\JL0LXL2R (Temporary Internet Files Folder) 
> Successfully deleted: C:\windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.IE5\NDDESB2Q (Temporary Internet Files Folder)
> Successfully deleted: C:\windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.IE5\NDDESB2Q (Temporary Internet Files Folder)

Thanks again!

[mwbytes.txt](https://github.com/dragokas/hijackthis/files/2399795/mwbytes.txt)

**Comment by Sandor-Helper** [comment]
> about 40 lines of hidden directories/files

All of them are normal.

> following 8 lines are _always_ removed by Malwarebytes' Junk Removal Tool

As you've notice, this tool is no longer supported and as a result - it have a very high level of false positives.
Nothing malicious at all.

**Comment by joshsprings** [comment]
Hello Sandar,

Thanks for your response. I had no idea so many hidden application folders inside of application folders inside of application folders existed. Thanks for letting me know. However, I'm wondering when you said "Nothing malicious at all," does that mean my case/issue is considered closed?

The reason I ask is because as I stated in my original post, I have a ton of evidence that is far more damning than these hidden lines that I wrongfully suspected were malicious that I can show you on demand...anytime you'd like. I also noticed you didn't ask me to run any further scans or do anything else.

Thanks again, and I will be eagerly awaiting your response.

**Comment by Sandor-Helper** [comment]
> you didn't ask me to run any further scans or do anything else

Autologger collects logs from 4 different tools. Furthermore I asked you to do MBAM scan. None of mentioned didn't find (or show) anything suspicious.
Perhaps your problem is system-depended (not virus-like). If so, @dragokas will move your topic to appropriate location.

**Comment by dragokas** [comment]
Hi, joshsprings.
Since your problem is not malware-related, we recommend you to ask help on the forums that provide assistance in resolving general operation system issues, like:
 - https://www.sevenforums.com/
 - https://answers.microsoft.com/
 - http://www.geekstogo.com/forum/forum/41-operating-systems/

**Comment by joshsprings** [comment]
Hello Sandor and Dragokas,

I am ready to post some additional logs generated while running AutoLogger, but this time I ran it on a different PC which is running Windows 10 Home (64-bit). I also have some screenshots that I think are of great importance. With that said, it is possible that the Windows 7 PC may have not been the best PC to post scan logs of because whatever that I personally believe has infected my computer seems to cause the most damage on Window 10.

So, I'm wondering if I should open an entire new Issue in order to cover this second PC and its logs, or can I post the logs here as well? I think I remember Dragokas saying each PC had to be a separate Issue, although I am unsure. While I wait for an answer to that question, I would like to show you two screenshots. One is a screenshot I took of Autoruns launched on this Windows 10 PC and the other is a screenshot I took from the following link: [https://www.dell.com/support/article/us/en/04/sln292746/how-to-identify-and-repair-malware-or-virus-infected-systems?lang=en#Detection](url)

**Note:** I do not own any Delll computers. It was simply by chance that I found this guide hosted by Dell.com while I was searching the web.

**Dell's Autoruns Example:**
![dell_example](https://user-images.githubusercontent.com/43278215/45925160-df643d00-bed5-11e8-9bfa-ef733df93d62.png)

**My Actual Autoruns:**
![autoruns_infected](https://user-images.githubusercontent.com/43278215/45925169-028eec80-bed6-11e8-8f24-6ccdb3ff772f.png)

Given that those two screenshots are of course not the exact same, they have enough similarities for me to conclude there is a problem that needs to be cleaned up and I'm sure when I post the AutoLogger logs, this problem will be evident within the logs.

I also wanted to mention that although I'm no professional in this arena, if I am not infected and it's nothing but system issues, why did the four other computers that use/connect to my LAN all of sudden start having these same system issues very shortly after the original PC was (I believe) infected? I'm honestly wondering, I am not being sarcastic. For all I know this is not uncommon.

I will be patiently awaiting a response. Please, take your time. I appreciate everything both of you have done for me thus far.  =)

Cheers.

**Comment by dragokas** [comment]
Sorry for late reply.
I see only 2 files not passed signature verification for some reason. You can archive them, set password "virus" and send to email: quarantine < at > safezone.cc (provide the link to this topic in the title of email).
All another files are legit.
There are no another signs of infection.

**Comment by dragokas** [comment]
> I'm wondering if I should open an entire new Issue in order to cover this second PC and its logs

Yes. But, are there some real reason to suspect it is infected?
