### ISSUE TITLE
Virus From Persistent Hacker

### ISSUE THREAD

**Issue by FinallyFree03022018** [dragokas/hijackthis#46]
Welcome !
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Are you in the right place?

  * Do you need assistance in PC cure from viruses?
  * Or would you like to report a bug or propose a feature for HiJackThis?
[HiJackThis2.log](https://github.com/dragokas/hijackthis/files/2476440/HiJackThis2.log)

If yes, see the next step.

### Step 2: Show us required logs (for PC cure):

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details:

1. What did you done before the problem occurs: _______Nothing: Unable to view content on webpages and experiencing rogue access points affecting my internet connection at home, also from infiltrating code running on iPhone and work Android phone, and when using Verizon Jetpack. Network showing NetBotx , someone monitoring Iot items in home and multiple rogue access points using Linux Ubantu, Citrix, and multiple Raspberry PIs, etc.
2. What programs (browsers) affected by the problem: ___Every browser I use: Edge, Internet Explorer, Firefox, K-Melon. Multiple .exe files and new users created impersonating my user id and Microsoft Apps being downloaded by Remote Computer with forced sharing.___________
3. Steps to reproduce: ______Monitoring source code on every web page in every browser and using SysAdmin apps to monitor daily changes on PC including configuration changes and changes made to Registry Editor to deny access to information.  I am not an IT Professional or a developer.  I am learning on my own.________

**Comment by dragokas** [comment]
Hi,
please
  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648) and prepare new CollectionLog.
