### ISSUE TITLE
*BUG REPORT* Run-time error while verifying process signature after running a StartUpList scan

### ISSUE THREAD

**Issue by Hostn4me** [dragokas/hijackthis#48]
Hello,

I noticed an Email earlier today notifying me that there had been a new version of HijackThis uploaded to the GitHub repo. I immediately downloaded it and decided (for whatever reason) to run a StartUpList scan.

As you can see from the screenshot of the Run-time error I have inserted below, I had been right-clicking on each of the running processes at the time the error actually occurred. I want to say I was able to successfully verify at least a minimum of 15 processes successfully without any issues before I tried to verify the process that actually threw the error ("armsvc.exe").

I just ran another StartUpList scan and I was able to verify the "armsvc.exe" process without any issues at all. Considering the error occurred because HijackThis was having trouble opening my clipboard, I'm thinking it's possible the reason behind me receiving the error may not be related to HijackThis at all, but instead my computer and/or its clipboard at the time. With that said, if Dragokas would like, he can add specific error handling for this type of particular error and (assuming my theory is correct) that is one of the reasons why I decided to go ahead and post this as a bug report.

![hijackthis_bug](https://user-images.githubusercontent.com/30291292/47274043-81874b80-d58e-11e8-9210-57fd60b44b2d.png)

**Comment by dragokas** [comment]
Hi, @Hostn4me!

Thank you for report.
Can you please clarify. Does error happen right after clicking right mouse button, or you choosed "Copy node text to clipboard" item from context menu?

**Comment by dragokas** [comment]
Also, please, keep in mind that StartupList has a "lazy" support. That's mean main updates focused on main HJT function: it's "**Do a system scan**" button in main menu. No new features or improvements for StartupList is planned.

**Comment by dragokas** [comment]
Should be fixed in v2.9.0.2+
