### ISSUE TITLE
The phone number is inserted from the clipboard +79131992773

### ISSUE THREAD

**Issue by hirednguyen** [dragokas/hijackthis#51]
When copying from the clipboard, the phone number is inserted +79131992773 instead of pictures
This only applies to copying pictures, pictures and vector images (including the Print Screen function does not work - also when inserting a phone number).
I have used many programs, but have not found them.
Please help me.
Thank you very much!
[CollectionLog-2018.11.04-23.04.zip](https://github.com/dragokas/hijackthis/files/2545987/CollectionLog-2018.11.04-23.04.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

Please go to Control Panel - Programs and uninstall an unwanred programs:

> Advanced SystemCare Ultimate 11
> Driver Booster 6
> IObit Uninstaller 8

Close all running programs, **temporarily** unload antivirus and other protecting software.

[Run a script in AVZ](https://github.com/dragokas/hijackthis/wiki/AVZ:-How-to-execute-script) (File - Run script):

``` 
begin
 ExecuteFile('schtasks.exe', '/delete /TN "Microsoft\Windows\SMB\UninstallSMB1ClientTask" /F', 0, 15000, true);
 ExecuteFile('schtasks.exe', '/delete /TN "Microsoft\Windows\SMB\UninstallSMB1ServerTask" /F', 0, 15000, true);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1001', 1);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1004', 3);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1201', 3);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1804', 1);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '2201', 3);
RebootWindows(false);
end.
```

Computer will _reboot_. 

Run again [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) (it should be run by right-clicking **as Administrator**).
Go to Settings and switch on:
> Reset IE policies
> Reset Chrome policies

Go to Dashboard, press **Scan now** and after scan ends press **Clean & Repair**.
System should be restarted.
After restart log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Cxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by hirednguyen** [comment]
Please check and help me!
I'm very grateful to your actions.
Thank you very much!
[AdwCleaner[C02].txt](https://github.com/dragokas/hijackthis/files/2549930/AdwCleaner.C02.txt)

**Comment by Sandor-Helper** [comment]
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by hirednguyen** [comment]
Please check and help me!
Thank you very much!
[FRST.txt](https://github.com/dragokas/hijackthis/files/2550006/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/2550007/Addition.txt)

**Comment by Sandor-Helper** [comment]
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CreateRestorePoint:
BHO: ExplorerWnd Helper -> {10921475-03CE-4E04-90CE-E2E7EF20C814} -> C:\Program Files (x86)\IObit\IObit Uninstaller\UninstallExplorer.dll => No File
FF user.js: detected! => C:\Users\Admin\AppData\Roaming\Mozilla\Firefox\Profiles\4oh503a6.default\user.js [2018-10-21]
2018-11-04 21:10 - 2018-11-04 21:10 - 000000000 ____D C:\Users\Default\AppData\Roaming\IObit
2018-11-04 21:10 - 2018-11-04 21:10 - 000000000 ____D C:\Users\Default User\AppData\Roaming\IObit
ContextMenuHandlers1: [IObitUnstaler] -> {836AB26C-2DE4-41D3-AC24-4C6C2699B960} => C:\Program Files (x86)\IObit\IObit Uninstaller\IUMenuRight.dll -> No File
ContextMenuHandlers6: [IObitUnstaler] -> {836AB26C-2DE4-41D3-AC24-4C6C2699B960} => C:\Program Files (x86)\IObit\IObit Uninstaller\IUMenuRight.dll -> No File
HKU\S-1-5-21-50933356-2206160036-1467846541-1001\...\StartupApproved\Run: => "Advanced SystemCare Ultimate"
EmptyTemp:
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by hirednguyen** [comment]
Please check and help me!
Regards.

[Fixlog.txt](https://github.com/dragokas/hijackthis/files/2550061/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
Start your system in Safe mode and check the problem. Tell us about result.

**Comment by hirednguyen** [comment]
I don't know how to check the problem. Can you guide me?

**Comment by Sandor-Helper** [comment]
[How to boot in Safe mode](https://support.microsoft.com/en-us/help/12376/windows-10-start-your-pc-in-safe-mode).
Go there and try to copy/paste any picture. See what happens.

**Comment by hirednguyen** [comment]
Hi
I did so. But the problem remains unresolved :(

**Comment by Sandor-Helper** [comment]
Please clarify - when system running in Safe mode problem with clipboard also remains?

**Comment by hirednguyen** [comment]
In Safe mode no error occurred. But when booting to normal mode after a while the error still occurs :(

**Comment by Sandor-Helper** [comment]
OK, then please carefully read [this article](https://support.microsoft.com/en-us/help/929135/how-to-perform-a-clean-boot-in-windows) and try to identify guilty file or service.
Tell us the result.

**Comment by hirednguyen** [comment]
I do not know about information technology. I send you pictures. Can you help me!

**Comment by hirednguyen** [comment]
Hi.
I would like to ask when reinstalling the operating system, my bug has been removed.

Thank you very much

**Comment by Sandor-Helper** [comment]
> I send you pictures

Where did you send them?

**Comment by Sandor-Helper** [comment]
> when reinstalling the operating system

You don't have to do this. You just in one step from solving the problem, but it takes a time to spent.
Do the error appears when boot in clean mode (described in mentioned above article)?
If not, you have to turn on half of turned off programs or services, reboot and check error again. So, step by step you could find out what the program is doing this.

**Comment by hirednguyen** [comment]
Hi.
I installed a new operating system. but the error still occurs. I'm sad because I do not know how to handle the problem :(

**Comment by Sandor-Helper** [comment]
It's because of problem is not in system, but in one of installed programs.
Read carefully [this instruction](https://support.microsoft.com/en-us/help/929135/how-to-perform-a-clean-boot-in-windows) again and try to find out.

**Comment by hirednguyen** [comment]
Hi,
I have disabled following your instructions. But the problem has not been resolved
Please help me.
Thank so much!

**Comment by Sandor-Helper** [comment]
Earlier you've said that


> In Safe mode no error occurred

Check it now after re-install system, please.

**Comment by hirednguyen** [comment]
Hi.
when running safe mode. I did not detect the error. But then the error occurred me I do not know the reason why it came from

**Comment by Sandor-Helper** [comment]
Go to section - How to perform a clean boot - in mentioned above instruction.
You should carefully check in three modes:
1. Safe mode
2. Clean boot
3. Normal mode

Please describe in which mode the error appearing?

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog and write what problems remained.
