### ISSUE TITLE
issue win7 starting fortnite

### ISSUE THREAD

**Issue by mindissue** [dragokas/hijackthis#53]
Welcome !
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Are you in the right place?

  * Do you need assistance in PC cure from viruses?
  * Or would you like to report a bug or propose a feature for HiJackThis?

If yes, see the next step.

### Step 2: Show us required logs (for PC cure):

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details:

1. What did you done before the problem occurs: _________________
2. What programs (browsers) affected by the problem: ________________
3. Steps to reproduce: _________________

Logfile of HiJackThis Fork (Beta) by Alex Dragokas v.2.8.0.4

Platform:  x64 Windows 7 (Home Premium), 6.1.7601.24263, Service Pack: 1
Time:      10.11.2018 - 05:02 (UTC+01:00)
Language:  OS: German (0x407). Display: German (0x407). Non-Unicode: German (0x407)
Elevated:  Yes

Default: "C:\Program Files\Mozilla Firefox\firefox.exe" -osint -url "%1" (Firefox)

Boot mode: Normal

Running processes:
Number | Path
   1  C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win64\EpicGamesLauncher.exe
  29  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
   1  C:\Program Files (x86)\Google\Update\1.3.33.17\GoogleCrashHandler.exe
   1  C:\Program Files (x86)\Google\Update\1.3.33.17\GoogleCrashHandler64.exe
   1  C:\Program Files (x86)\HiJackThis Fork\HiJackThis.exe
   1  C:\Program Files (x86)\RocketDock\RocketDock.exe
   1  C:\Program Files (x86)\TeamViewer\TeamViewer_Service.exe
   1  C:\Program Files\AMD\CNext\CNext\RadeonSettings.exe
   1  C:\Program Files\AMD\CNext\CNext\amddvr.exe
   1  C:\Program Files\AMD\CNext\CNext\amdow.exe
   1  C:\Program Files\CCleaner\CCUpdate.exe
   1  C:\Program Files\Common Files\Apple\Mobile Device Support\AppleMobileDeviceService.exe
   1  C:\Program Files\Common Files\Microsoft Shared\Windows Live\WLIDSVC.EXE
   1  C:\Program Files\Common Files\Microsoft Shared\Windows Live\WLIDSVCM.EXE
   1  C:\Program Files\DAEMON Tools Lite\DTShellHlp.exe
   1  C:\Program Files\DAEMON Tools Lite\DiscSoftBusServiceLite.exe
   7  C:\Program Files\Mozilla Firefox\firefox.exe
   1  C:\Program Files\Mozilla Firefox\plugin-container.exe
   1  C:\Program Files\Realtek\Audio\HDA\RAVCpl64.exe
   1  C:\Program Files\Windows Media Player\wmpnetwk.exe
   1  C:\Users\worthtoot\Downloads\FRST64.exe
   1  C:\Windows\System32\SearchIndexer.exe
   1  C:\Windows\System32\alg.exe
   1  C:\Windows\System32\audiodg.exe
   2  C:\Windows\System32\csrss.exe
   1  C:\Windows\System32\dwm.exe
   1  C:\Windows\System32\lsass.exe
   1  C:\Windows\System32\lsm.exe
   1  C:\Windows\System32\notepad.exe
   1  C:\Windows\System32\services.exe
   1  C:\Windows\System32\smss.exe
   1  C:\Windows\System32\spoolsv.exe
  14  C:\Windows\System32\svchost.exe
   1  C:\Windows\System32\taskeng.exe
   1  C:\Windows\System32\taskhost.exe
   1  C:\Windows\System32\wininit.exe
   1  C:\Windows\System32\winlogon.exe
   1  C:\Windows\explorer.exe

O2 - HKLM\..\BHO: (no name) - {761497BB-D6F0-462C-B6EB-D4DAF1D92D43} - (no file)
O2 - HKLM\..\BHO: Windows Live ID Sign-in Helper - {9030D464-4C02-4ABF-8ECC-5164760863C6} - C:\Program Files\Common 

Files\Microsoft Shared\Windows Live\WindowsLiveLogin.dll
O2-32 - HKLM\..\BHO: Microsoft-Konto-Anmelde-Hilfsprogramm - {9030D464-4C02-4ABF-8ECC-5164760863C6} - C:\Program Files 

(x86)\Common Files\Microsoft Shared\Windows Live\WindowsLiveLogin.dll
O4 - HKCU\..\Run: [CCleaner Smart Cleaning] = C:\Program Files\CCleaner\CCleaner64.exe /MONITOR
O4 - HKCU\..\Run: [EpicGamesLauncher] = C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries

\Win64\EpicGamesLauncher.exe -silent
O4 - HKCU\..\Run: [RocketDock] = C:\Program Files (x86)\RocketDock\RocketDock.exe
O4 - HKLM\..\Run: [RTHDVCPL] = C:\Program Files\Realtek\Audio\HDA\RAVCpl64.exe -s
O4 - MSConfig\startupreg: AdobeBridge [command] = (no file) (HKCU) (2018/11/05)
O4 - MSConfig\startupreg: AwesomeMiner [command] = C:\Program Files (x86)\Awesome Miner\AwesomeMiner.exe /minimized 

(file missing) (HKCU) (2018/08/04)
O4 - MSConfig\startupreg: DAEMON Tools Lite Automount [command] = C:\Program Files\DAEMON Tools Lite\DTAgent.exe -

autorun (HKCU) (2018/11/05)
O4 - MSConfig\startupreg: Steam [command] = C:\Program Files (x86)\Steam\steam.exe -silent (HKCU) (2018/08/13)
O4 - MSConfig\startupreg: uTorrent [command] = C:\Users\worthtoot\AppData\Roaming\uTorrent\uTorrent.exe /MINIMIZED 

(HKCU) (2018/11/05)
O9-32 - Button: HKLM\..\{219C3416-8CB2-491a-A3C7-D9FCDDC9D600} - In Blog veröffentlichen - C:\Program Files 

(x86)\Windows Live\Writer\WriterBrowserExtension.dll
O9-32 - Tools menu item: HKLM\..\{219C3416-8CB2-491a-A3C7-D9FCDDC9D600} - In &Blog in Windows Live Writer 

veröffentlichen - C:\Program Files (x86)\Windows Live\Writer\WriterBrowserExtension.dll
O10 - Unknown file in Winsock LSP: C:\Windows\system32\PrxerDrv.dll
O10 - Unknown file in Winsock LSP: c:\windows\system32\prxernsp.dll
O15 - Trusted Zone: HKCU - *.localhost
O17 - DHCP DNS 1: 192.168.43.1
O22 - Task: (disabled) {FCAB38F3-AC64-483D-8256-9C9755D41B97} - C:\Windows\system32\pcalua.exe -a C:\Users\worthtoot

\Downloads\setup.exe -d C:\Users\worthtoot\Downloads
O22 - Task: (telemetry) \Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser - C:\Windows

\system32\CompatTelRunner.exe (Microsoft)
O22 - Task: (telemetry) \Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser - C:\Windows

\system32\compattel\DiagTrackRunner.exe /UploadEtlFilesOnly (Microsoft)
O22 - Task: (telemetry) \Microsoft\Windows\Application Experience\ProgramDataUpdater - C:\Windows

\system32\compattelrunner.exe -maintenance (Microsoft)
O22 - Task: Adobe Flash Player NPAPI Notifier - C:\Windows\SysWOW64\Macromed\Flash\FlashUtil32_31_0_0_122_Plugin.exe -

check plugin
O22 - Task: Adobe Flash Player Updater - C:\Windows\SysWOW64\Macromed\Flash\FlashPlayerUpdateService.exe
O22 - Task: CCleaner Update - C:\Program Files\CCleaner\CCUpdate.exe
O22 - Task: CCleanerSkipUAC - C:\Program Files\CCleaner\CCleaner.exe $(Arg0)
O22 - Task: GoogleUpdateTaskMachineCore - C:\Program Files (x86)\Google\Update\GoogleUpdate.exe /c
O22 - Task: GoogleUpdateTaskMachineUA - C:\Program Files (x86)\Google\Update\GoogleUpdate.exe /ua /installsource 

scheduler
O22 - Task: MSIAfterburner - C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe /s (file missing)
O22 - Task: StartCN - C:\Program Files\AMD\CNext\CNext\cncmd.exe startwithdelay
O22 - Task: StartDVR - C:\Program Files\AMD\CNext\CNext\dvrcmd.exe
O22 - Task: \Microsoft\Windows Live\SOXE\Extractor Definitions Update Task - {3519154C-227E-47F3-9CC9-12C3F05817F1} - 

(no file)
O22 - Task: {9008A083-84D4-48B7-B059-F89CF679428E} - C:\Windows\system32\pcalua.exe -a C:\Users\worthtoot\Downloads

\avm_fritz_wlan_usb_stick_x64_05.04.31.exe -d C:\Users\worthtoot\Downloads
O23 - Service R2: Apple Mobile Device Service - C:\Program Files\Common Files\Apple\Mobile Device Support

\AppleMobileDeviceService.exe
O23 - Service R2: Diagnostics Tracking Service - (DiagTrack) - C:\Windows\System32\svchost.exe -k utcsvc; "ServiceDll" = 

C:\Windows\system32\diagtrack.dll
O23 - Service R2: TeamViewer 13 - (TeamViewer) - C:\Program Files (x86)\TeamViewer\TeamViewer_Service.exe
O23 - Service R2: Windows Defender - (WinDefend) - C:\Windows\System32\svchost.exe -k secsvcs; "ServiceDll" = C:\Program 

Files\Windows Defender\mpsvc.dll
O23 - Service R2: Windows Live ID Sign-in Assistant - (wlidsvc) - C:\Program Files\Common Files\Microsoft Shared\Windows 

Live\WLIDSVC.EXE
O23 - Service R3: Disc Soft Lite Bus Service - C:\Program Files\DAEMON Tools Lite\DiscSoftBusServiceLite.exe
O23 - Service S2: Google Update-Dienst (gupdate) - (gupdate) - C:\Program Files (x86)\Google\Update\GoogleUpdate.exe 

/svc
O23 - Service S3: Adobe Flash Player Update Service - (AdobeFlashPlayerUpdateSvc) - C:\Windows\SysWOW64\Macromed\Flash

\FlashPlayerUpdateService.exe
O23 - Service S3: EasyAntiCheat - C:\Program Files (x86)\EasyAntiCheat\EasyAntiCheat.exe
O23 - Service S3: Google Update-Dienst (gupdatem) - (gupdatem) - C:\Program Files (x86)\Google\Update\GoogleUpdate.exe 

/medsvc
O23 - Service S3: Mozilla Maintenance Service - (MozillaMaintenance) - C:\Program Files (x86)\Mozilla Maintenance 

Service\maintenanceservice.exe
O23 - Service S3: Steam Client Service - C:\Program Files (x86)\Common Files\Steam\SteamService.exe /RunAsService

--
End of file - Time spent: 4 sec. - 16210 bytes, CRC32: FFFFFFFF. Sign: �
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/2568090/HiJackThis.log)

**Comment by dragokas** [comment]
Hi,
thank you for the log.

Please, note that this forum is intended to solve virus infections, not system problems.

If you are suspecting virus infection and you need our assistance:
  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by mindissue** [comment]
[CollectionLog-2018.11.10-22.15.zip](https://github.com/dragokas/hijackthis/files/2568787/CollectionLog-2018.11.10-22.15.zip)
[report1.log](https://github.com/dragokas/hijackthis/files/2568788/report1.log)
[report2.log](https://github.com/dragokas/hijackthis/files/2568789/report2.log)

**Comment by mindissue** [comment]
when running fortnite on win7 [INFO] Blocked loading of file: "C:\Windows\System32\PrxerDrv.dll".

**Comment by Sandor-Helper** [comment]
Hello,

Please uninstall an unwanted program via Control Panel - Programs:

> Spybot - Search & Destroy

Could you please show the screenshot of this:


> when running fortnite on win7 [INFO] Blocked loading of file: "C:\Windows\System32\PrxerDrv.dll".

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog and write what problems remained.
