### ISSUE TITLE
doubtful mail in google: "I'm crack..."

### ISSUE THREAD

**Issue by wba2** [dragokas/hijackthis#55]
Hello just by chance I found a doubtful mail in my spam folder. Just to be completely sure I'd like to get my hijackthis logfile analized. Could you be so kind?

[HiJackThis.log](https://github.com/dragokas/hijackthis/files/2592056/HiJackThis.log)

**Comment by Sandor-Helper** [comment]
Hello and welcome,

I didn't find any malicious records in log. But to be sure you'd better collect a complete logs pack using [this instruction](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F).

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog and write what problems remained.
