### ISSUE TITLE
PC Running Erratically and Slow. 

### ISSUE THREAD

**Issue by A1Protocol** [dragokas/hijackthis#56]
Hi Everyone !

I am trying to fix a co-worker's pc. Her laptop is running slow and pop-ups, processes are appearing while browsing online. I already ran a Ccleaner scan and registry cleanup. 

Also checked the startup processes, nothing abnormal.

Autologger and HijackThis scans ran. 
[CollectionLog-2018.12.12-23.12.zip](https://github.com/dragokas/hijackthis/files/2674701/CollectionLog-2018.12.12-23.12.zip)

  * Describe your problem in details:

1. What did you do before the problem occurs: She was browsing streaming websites I believe. 
2. What programs (browsers) affected by the problem: Chrome, Chromium and Edge. 
3. Steps to reproduce: N/A

Thank you for your help!

**Comment by Sandor-Helper** [comment]
Hello and welcome!

Please uninstall PUP
> Chromium

Then:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by A1Protocol** [comment]
Hi !

Thank you ! Here is attached the scan. 
[AdwCleaner[S00].txt](https://github.com/dragokas/hijackthis/files/2678664/AdwCleaner.S00.txt)

**Comment by Sandor-Helper** [comment]
1. 
Run again [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) (it should be run by right-clicking **as Administrator**).
Go to Settings and switch on:
> Reset IE policies
> Reset Chrome policies

Go to Dashboard, press **Scan now** and after scan ends press **Clean & Repair**.
System should be restarted.
After restart log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Cxx].txt** (where **x** is any digit).
Attach it to your next post here.

2. 
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
