### ISSUE TITLE
Could you check those logs?

### ISSUE THREAD

**Issue by zenekklocek** [dragokas/hijackthis#59]
[CollectionLog-2018.12.26-14.26.zip](https://github.com/dragokas/hijackthis/files/2710327/CollectionLog-2018.12.26-14.26.zip)

Please could anyone analyze those logs, I'm afraid that my computer could be infected.

I noticed sometimes coursor is moving by itself and I have other weird stuff going on. 
I started to have  a problem with overheating some time ago, fans was cleaned and thermal paste was changed. 

I would be thankful if someone could verify my paranoic mode  xD

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

Close all running programs, **temporarily** unload antivirus and other protecting software.

[Run a script in AVZ](https://github.com/dragokas/hijackthis/wiki/AVZ:-How-to-execute-script) (File - Run script):

```
begin
 ExecuteFile('net.exe', 'stop tcpip /y', 0, 15000, true);
 ClearQuarantineEx(true);
 StopService('HWiNFO32');
 QuarantineFile('C:\Users\dariu\AppData\Local\Temp\HWiNFO64A.SYS', '');
 DeleteFile('C:\Users\dariu\AppData\Local\Temp\HWiNFO64A.SYS', '64');
 DeleteService('HWiNFO32');
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1001', 1);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1004', 3);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1201', 3);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1804', 1);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '2201', 3);
 CreateQurantineArchive(GetAVZDirectory + 'quarantine.zip');
ExecuteSysClean;
 ExecuteWizard('SCU', 2, 3, true);
RebootWindows(true);
end.

```

Computer will _reboot_. 



File **quarantine.zip** from extracted AVZ folder please send using [this form](http://dragokas.com/virusnet/) or (if archive size exceeds the 8 MB) to this mailbox: **quarantine at safezone.cc** (change _at_ to _@_) and specify your forum link in e-mail subject and password: **virus** in message body.


For _secondary_ diagnostics please run AutoLogger again. 
Attach new CollectionLog to your post.

**Comment by zenekklocek** [comment]
I disabled antivirus, run script in AVZ, PC rebooted, but file quarantine.zip is empty.
[quarantine.zip](https://github.com/dragokas/hijackthis/files/2729789/quarantine.zip)

**Comment by Sandor-Helper** [comment]
OK, then please do a secondary diagnostics.

> run AutoLogger again.
> Attach new CollectionLog to your post.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
