### ISSUE TITLE
Commandline /silentautolog

### ISSUE THREAD

**Issue by ChrisKdevelopment** [dragokas/hijackthis#6]
Building hijack this into an Incident Response HTA right now for automation.... one thing I've noticed is that  even with the /silentautolog enabled - the following warning will appear and still require interaction from the user:

HijackThis appears to have been started from a temporary folder.  Since temp folders tend to be emptied regularly, it's wise to copy HijackThis.exe to a folder of its own, for instance C:\Program Files\HijackThis.
This way, any backups that will be made of fixed items won't be lost.

Please quit HijackThis and copy it to a separate folder first before fixing any items

The obvious work around is to just create a folder which we will do ... but silentautolog as a switch should still not prompt this error.

thanks guys - great work.

**Comment by dragokas** [comment]
Hi, Unity88!

Thank you for the feedback.
Please, notice that you are using very old version. Current developer binaries stored [here](https://github.com/dragokas/hijackthis) under ./binary/ folder.
However, in this version you will also be denied launching from %temp%.
We will think about adding opportunity for silent run from %temp%.
If you very need HJT with this feature in nearest time, let me know and I'll inlude it in the next test binary on my FTP.

P.S. Official release will be only for HJT v3 with reworked backup system and full testings for safe. I almost completed it. ~ date of release is before New Year.

**Comment by dragokas** [comment]
Fixed in 2.7.0.13 dev build.
