### ISSUE TITLE
Could you check those logs? v2

### ISSUE THREAD

**Issue by zenekklocek** [dragokas/hijackthis#63]
I created new post as [last one](https://github.com/dragokas/hijackthis/issues/59) was closed.

I get some new symptoms of infection like, chrome browser trying to open pushwhy.com site (blocked by antivirus). When I was writing this post suddenly phraese "testtesttesttest" was pasted without my action. This text wasn't in clipboard for sure.

New log attached.
[CollectionLog-2019.02.20-23.20.zip](https://github.com/dragokas/hijackthis/files/2886722/CollectionLog-2019.02.20-23.20.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

As about "test" phrase, it is a part of our analysis engine.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,


> chrome browser trying to open

Could you please check is the same problem appears in other browsers including IE and Edge?



> "testtesttesttest" was pasted without my action

Don't worry, you've had to wait until log collecting is ended and do nothing while collecting. It is AVZ's check for keylogger.

**Comment by zenekklocek** [comment]
> It is AVZ's check for keylogger.

haha My bad

**Comment by zenekklocek** [comment]
Do I need to worry about smth? Attached collection are clean?

**Comment by Sandor-Helper** [comment]
It depends from your answer on my question:

> Could you please check is the same problem appears in other browsers including IE and Edge?

**Comment by zenekklocek** [comment]
Nope Edge is working fine, I actually tried to follow some online guides to clean pushwhy.com malware from chrome and installed ublock and ghostery addon, and chrome stopped trying to redirect me to that page.

**Comment by Sandor-Helper** [comment]
Lets do some more diagnostic.
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by zenekklocek** [comment]
Nope Edge is working fine, I actually tried to follow some online guides to clean pushwhy.com malware from chrome and installed ublock and ghostery addon, and chrome stopped trying to redirect me to that page.
