### ISSUE TITLE
Computer mouse cursor problem/think its a malware/virus/worm infection.

### ISSUE THREAD

**Issue by Evilkarn** [dragokas/hijackthis#66]
Welcome !
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Are you in the right place?

  * Do you need assistance in PC cure from viruses?
  * Or would you like to report a bug or propose a feature for HiJackThis?

If yes, see the next step.

### Step 2: Show us required logs (for PC cure):

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger]
[CollectionLog-2019.03.27-07.00.zip](https://github.com/dragokas/hijackthis/files/3011745/CollectionLog-2019.03.27-07.00.zip)
(https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details:

1. What did you done before the problem occurs: 
I have been around the web searching for drivers and pictures, movies and so on as the web offers many bad sites and good sites to view, and all of a sudden a few days ago since last windows update it began failing in the world of Warcraft game with the mouse cursor having its own life, likely as in it clicks right button by itself, and moves fast as if i changed the dpi the same time i was moving, but one would be foolish to do so, because the point in playing the game is to use one setup before entering the game to the mouse cursor speed on the screen, and therefor not change the speed volume of the dpi on the mouse when i am online in a game._________________
2. What programs (browsers) affected by the problem: ________________
World of Warcraft only.
3. Steps to reproduce:  
Mouse cursor moves by itself and clicks, when double pressing hold down mouse left and right in world of Warcraft, it makes the Charecter run/fly on mount and then stops working after a few seconds. it returns to as Im not holding both the mouse buttons down at the same time. 
It comes with the double pressed down left and right mouse click buttons, one is to hold down the two buttons to make a Charecter run or walk/fly in world of Warcraft, but when i hold down the upkept down pressed mouse buttons, left and right, it goes back to if i had released the right button and makes me run straight ahead in game, instead of letting me controle the actual Charecter movement, as in moving left and right with the movement on the mouse left and right button, the issue i am having is similiar to some sort of worm infection i believe, and i would rather not take any risks, as i cant afford loosing the hobby of my whole computer rig's gaming, to loosing my world of Warcraft account, but since it only shows in world of Warcraft where the mouse As earlier told, it would have its own life, and later on seeing it as a fraud, where i loose my charecters or something like that. I hope you can solve the puzzle and see through my HiJackThis Log and auto logger zip file. let me know if you find anything sucpisious.  _________________
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/3011747/HiJackThis.log)

**Comment by Sandor-Helper** [comment]
Hello and welcome!

Close all running programs, **temporarily** unload antivirus and other protecting software.

[Run a script in AVZ](https://github.com/dragokas/hijackthis/wiki/AVZ:-How-to-execute-script) (File - Run script):

```
begin
 DeleteSchedulerTask('Microsoft\Windows\SMB\UninstallSMB1ClientTask');
 DeleteSchedulerTask('Microsoft\Windows\SMB\UninstallSMB1ServerTask');
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1001', 1);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1004', 3);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1201', 3);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1804', 1);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '2201', 3);
RebootWindows(false);
end.

```

Computer will _reboot_. 

This script will close some vulnerabilities in system.


For _secondary_ diagnostics please run AutoLogger again. 
Attach new CollectionLog to your post.

Please clarify - does the problem you described above appears **only** in mentioned game?
And does your mouse works well in standard apps or when browsing?

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog and write what problems remained.
