### ISSUE TITLE
Please help 

### ISSUE THREAD

**Issue by vanpajms** [dragokas/hijackthis#69]
Hi I need help with analyzing logs, I'm afraid my PC got infected. 
 l
[CollectionLog-2019.04.28-20.22.zip](https://github.com/dragokas/hijackthis/files/3125349/CollectionLog-2019.04.28-20.22.zip)

Thanks

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

I didn't find any malicious record in logs.
Please describe more detailed - what kind of problems you've experienced?

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
