### ISSUE TITLE
 hijackthis analyzer

### ISSUE THREAD

**Issue by beeebz** [dragokas/hijackthis#73]
Logfile of HiJackThis Fork by Alex Dragokas v.2.9.0.19

Platform:  x64 Windows 10 (Pro), 10.0.17763.557 (ReleaseId: 1809), Service Pack: 0
Time:      23.06.2019 - 23:35 (UTC+03:00)
Language:  OS: English (0x809). Display: Arabic (0x401). Non-Unicode: English (0x809)
Elevated:  Yes
Ran by:    Alageel	(group: Administrator) on DESKTOP-1TNDD48, FirstRun: no

Chrome:  75.0.3770.100
Edge:    11.0.17763.557
Internet Explorer: 11.0.17763.1
Default: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" -- "%1" (Google Chrome)

Boot mode: Normal

Running processes:
Number | Path
  11  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
   1  C:\Program Files (x86)\Google\Update\1.3.34.11\GoogleCrashHandler.exe
   1  C:\Program Files (x86)\Google\Update\1.3.34.11\GoogleCrashHandler64.exe
   1  C:\Program Files\McAfee\Agent\macmnsvc.exe
   1  C:\Program Files\McAfee\Agent\masvc.exe
   1  C:\Program Files\McAfee\Agent\x86\UpdaterUI.exe
   1  C:\Program Files\McAfee\Agent\x86\macompatsvc.exe
   1  C:\Program Files\McAfee\Agent\x86\mctray.exe
   1  C:\Program Files\McAfee\Agent\x86\mfemactl.exe
   1  C:\Program Files\Microsoft Office\Office15\MSOSYNC.EXE
   1  C:\Program Files\Realtek\Audio\HDA\RtkNGUI64.exe
   1  C:\Program Files\WinRAR\WinRAR.exe
   1  C:\Program Files\WindowsApps\Microsoft.WindowsStore_11905.1001.4.0_x64__8wekyb3d8bbwe\WinStore.App.exe
   1  C:\Program Files\WindowsApps\Microsoft.YourPhone_1.19053.13.0_x64__8wekyb3d8bbwe\YourPhone.exe
   1  C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.1905.4-0\MsMpEng.exe
   1  C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.1905.4-0\NisSrv.exe
   1  C:\Users\Alageel\AppData\Local\Microsoft\OneDrive\OneDrive.exe
   1  C:\Users\Alageel\Desktop\HiJackThis\HiJackThis.exe
   1  C:\Windows\ImmersiveControlPanel\SystemSettings.exe
   1  C:\Windows\Microsoft.NET\Framework64\v3.0\WPF\PresentationFontCache.exe
   1  C:\Windows\System32\ApplicationFrameHost.exe
   1  C:\Windows\System32\DriverStore\FileRepository\cui_dch_comp.inf_amd64_c8e108d4a62c59d5\igfxCUIService.exe
   1  C:\Windows\System32\DriverStore\FileRepository\cui_dch_comp.inf_amd64_c8e108d4a62c59d5\igfxEM.exe
   1  C:\Windows\System32\DriverStore\FileRepository\iigd_dch_base.inf_amd64_b95c9a044993331b\IntelCpHDCPSvc.exe
   1  C:\Windows\System32\DriverStore\FileRepository\iigd_dch_base.inf_amd64_b95c9a044993331b\IntelCpHeciSvc.exe
   1  C:\Windows\System32\MicrosoftEdgeCP.exe
   1  C:\Windows\System32\MicrosoftEdgeSH.exe
   6  C:\Windows\System32\RuntimeBroker.exe
   1  C:\Windows\System32\SearchFilterHost.exe
   1  C:\Windows\System32\SearchIndexer.exe
   2  C:\Windows\System32\SearchProtocolHost.exe
   1  C:\Windows\System32\SecurityHealthService.exe
   1  C:\Windows\System32\SecurityHealthSystray.exe
   1  C:\Windows\System32\SgrmBroker.exe
   1  C:\Windows\System32\audiodg.exe
   1  C:\Windows\System32\browser_broker.exe
   2  C:\Windows\System32\csrss.exe
   1  C:\Windows\System32\ctfmon.exe
   2  C:\Windows\System32\dllhost.exe
   1  C:\Windows\System32\dwm.exe
   2  C:\Windows\System32\fontdrvhost.exe
   1  C:\Windows\System32\lsass.exe
   1  C:\Windows\System32\notepad.exe
   1  C:\Windows\System32\services.exe
   1  C:\Windows\System32\sihost.exe
   1  C:\Windows\System32\smartscreen.exe
   1  C:\Windows\System32\smss.exe
   1  C:\Windows\System32\spoolsv.exe
  65  C:\Windows\System32\svchost.exe
   1  C:\Windows\System32\taskhostw.exe
   1  C:\Windows\System32\wbem\WmiPrvSE.exe
   1  C:\Windows\System32\wininit.exe
   1  C:\Windows\System32\winlogon.exe
   1  C:\Windows\SystemApps\InputApp_cw5n1h2txyewy\WindowsInternal.ComposableShell.Experiences.TextInput.InputApp.exe
   1  C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe
   1  C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
   1  C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe
   1  C:\Windows\explorer.exe

O4 - HKCU\..\Run: [OneDrive] = C:\Users\Alageel\AppData\Local\Microsoft\OneDrive\OneDrive.exe /background (Microsoft)
O4 - HKLM\..\Run: [SecurityHealth] = C:\Windows\system32\SecurityHealthSystray.exe
O4 - User Startup: C:\Users\Alageel\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Send to OneNote.lnk    ->    C:\Program Files (x86)\Microsoft Office\root\Office16\ONENOTEM.EXE /tsr
O4 - User Startup: C:\Users\Alageel\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\System32Cli.lnk    ->    E:\System32Clientghj\System32Clientnt.exe
O4 - User Startup: C:\Users\Alageel\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\مراقبة تنبيهات الحبر - HP Officejet 7610 series.lnk    ->    C:\WINDOWS\system32\RunDll32.exe "C:\Program Files\HP\HP Officejet 7610 series\bin\HPStatusBL.dll",RunDLLEntry SERIALNUMBER=CN66F3R23Y064N;CONNECTION=USB;MONITOR=1;
O4-32 - HKLM\..\Run: [McAfeeUpdaterUI] = C:\Program Files\McAfee\Agent\x86\UpdaterUI.exe /StartedFromRunKey
O17 - DHCP DNS 1: 192.168.0.1
O22 - Task (.job): (disabled) (Not scheduled) CreateExplorerShellUnelevatedTask.job - C:\Windows\explorer.exe /NOUACCHECK
O23 - Service R2: Intel(R) Content Protection HDCP Service - (cplspcon) - C:\Windows\System32\DriverStore\FileRepository\iigd_dch_base.inf_amd64_b95c9a044993331b\IntelCpHDCPSvc.exe
O23 - Service R2: Intel(R) HD Graphics Control Panel Service - (igfxCUIService2.0.0.0) - C:\Windows\System32\DriverStore\FileRepository\cui_dch_comp.inf_amd64_c8e108d4a62c59d5\igfxCUIService.exe
O23 - Service R2: McAfee Agent Common Services - (macmnsvc) - C:\Program Files\McAfee\Agent\macmnsvc.exe /ServiceStart
O23 - Service R2: McAfee Agent Service - (masvc) - C:\Program Files\McAfee\Agent\masvc.exe /ServiceStart
O23 - Service R3: Intel(R) Content Protection HECI Service - (cphs) - C:\Windows\System32\DriverStore\FileRepository\iigd_dch_base.inf_amd64_b95c9a044993331b\IntelCpHeciSvc.exe
O23 - Service R3: McAfee Agent Backwards Compatibility Service - (McAfeeFramework) - C:\Program Files\McAfee\Agent\x86\macompatsvc.exe
O23 - Service S2: خدمة Google Update (gupdate) - (gupdate) - C:\Program Files (x86)\Google\Update\GoogleUpdate.exe /svc
O23 - Service S3: Google Chrome Elevation Service - (GoogleChromeElevationService) - C:\Program Files (x86)\Google\Chrome\Application\75.0.3770.100\elevation_service.exe
O23 - Service S3: Office 64 Source Engine - (ose64) - C:\Program Files\Common Files\Microsoft Shared\Source Engine\OSE.EXE
O23 - Service S3: خدمة Google Update (gupdatem) - (gupdatem) - C:\Program Files (x86)\Google\Update\GoogleUpdate.exe /medsvc

--
End of file - Time spent: 16.6 sec. - 13468 bytes, CRC32: FFFFFFFF. Sign: 䁕ᝋ

**Comment by Sandor-Helper** [comment]
Hello and welcome,

If you need help please read carefully and do simple steps from [this message](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F).

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog and write what problems remained.
