### ISSUE TITLE
can you please analize mi log?

### ISSUE THREAD

**Issue by Mysioll** [dragokas/hijackthis#74]
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/3366350/HiJackThis.log)
Welcome !
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Are you in the right place?

  * Do you need assistance in PC cure from viruses?
  * Or would you like to report a bug or propose a feature for HiJackThis?

If yes, see the next step.

### Step 2: Show us required logs (for PC cure):

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details:

1. What did you done before the problem occurs: _________________
2. What programs (browsers) affected by the problem: ________________
3. Steps to reproduce: _________________

**Comment by Sandor-Helper** [comment]
Hello,

Please describe your problem, collect and attach log from step2.

**Comment by Mysioll** [comment]
I have no problem yet
But somebody trying to steal my facebook account with a text message sent on my phone
So I'll like to know if my pc is clean
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/3366860/HiJackThis.log)

**Comment by Sandor-Helper** [comment]
For deep research we need CollectionLog.zip created by Autologger (Step2 from your first message).

**Comment by Mysioll** [comment]
> 
> 
> For deep research we need CollectionLog.zip created by Autologger (Step2 from your first message).

malwarebytes is blocking the download...
I'll try tomorrow, if I can

**Comment by Sandor-Helper** [comment]
> malwarebytes is blocking the download

Turn in off before restart.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog and write what problems remained.
