### ISSUE TITLE
Analisi del log Hijackthis

### ISSUE THREAD

**Issue by redevilr76** [dragokas/hijackthis#80]
Buongiorno a tutti , un saluto per la mia prima apparizione in questo forum.
_________________________________________________________________
Avrei bisogno, molto gentilmente, di una mano per analizzre il log di HiJackThis, non ho nessun problema in particolare e solo un analisi di controllo. Grazie
_________________________________________________________________

Logfile of HiJackThis Fork by Alex Dragokas v.2.9.0.18

Platform:  x64 Windows 7 (Ultimate), 6.1.7601.24468, Service Pack: 1
Time:      09.12.2019 - 22:58 (UTC+01:00)
Language:  OS: Italian (0x410). Display: Italian (0x410). Non-Unicode: Italian (0x410)
Elevated:  Yes
Ran by:    redevilr76	(group: Administrator) on ERCOLE, FirstRun: yes

Opera:   65.0.3467.62
Chrome:  78.0.3904.108
Internet Explorer: 11.0.9600.19377
Default: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" -- "%1" (Google Chrome)

Boot mode: Normal

Running processes:
Number | Path
   1  C:\Program Files (x86)\AOMEI Backupper\ABService.exe
   1  C:\Program Files (x86)\ASUS\AXSP\1.02.00\atkexComSvc.exe
   1  C:\Program Files (x86)\ATI Technologies\HydraVision\HydraDM.exe
   1  C:\Program Files (x86)\ATI Technologies\HydraVision\HydraDM64.exe
   1  C:\Program Files (x86)\Avira\Antivirus\avgnt.exe
   1  C:\Program Files (x86)\Avira\Antivirus\avguard.exe
   1  C:\Program Files (x86)\Avira\Antivirus\avshadow.exe
   1  C:\Program Files (x86)\Avira\Antivirus\sched.exe
   1  C:\Program Files (x86)\Avira\Launcher\Avira.ServiceHost.exe
   1  C:\Program Files (x86)\Avira\Launcher\Avira.Systray.exe
  40  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
   2  C:\Program Files (x86)\HDDGURU LLF Tool\LLFTOOL.EXE
   1  C:\Program Files (x86)\IObit\Advanced SystemCare\ASCService.exe
   1  C:\Program Files (x86)\IObit\Advanced SystemCare\ASCTray.exe
   1  C:\Program Files (x86)\IObit\IObit Malware Fighter\IMF.exe
   1  C:\Program Files (x86)\IObit\IObit Malware Fighter\IMFCore.exe
   1  C:\Program Files (x86)\IObit\IObit Malware Fighter\IMFTips.exe
   1  C:\Program Files (x86)\IObit\IObit Malware Fighter\IMFsrv.exe
   1  C:\Program Files (x86)\IObit\IObit Uninstaller\Pub\PubMonitor.exe
   1  C:\Program Files (x86)\IObit\IObit Uninstaller\UninstallMonitor.exe
   1  C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL\Jhi_service.exe
   1  C:\Program Files (x86)\Spybot - Search & Destroy 2\SDFSSvc.exe
   1  C:\Program Files (x86)\Spybot - Search & Destroy 2\SDUpdSvc.exe
   1  C:\Program Files (x86)\Spybot - Search & Destroy 2\SDWSCSvc.exe
   1  C:\Program Files\Bonjour\mDNSResponder.exe
   1  C:\Program Files\Common Files\Apple\Mobile Device Support\AppleMobileDeviceService.exe
   1  C:\Program Files\Common Files\Microsoft Shared\Windows Live\WLIDSVC.EXE
   1  C:\Program Files\Common Files\Microsoft Shared\Windows Live\WLIDSVCM.EXE
   1  C:\Program Files\HP\HP OfficeJet Pro 8710\Bin\ScanToPCActivationApp.exe
   1  C:\Program Files\Realtek\Audio\HDA\RtkNGUI64.exe
   1  C:\Program Files\Windows Media Player\wmpnetwk.exe
   1  C:\ProgramData\MEGAsync\MEGAsync.exe
   1  C:\Users\redevilr76\AppData\Local\Videostream\app-0.3.6\Videostream.exe
   2  C:\Users\redevilr76\AppData\Local\Videostream\app-0.3.6\videostream-native\videostream-

native.exe
   1  C:\Users\redevilr76\Desktop\HijackThis.exe
   1  C:\Users\redevilr76\Desktop\Nuova cartella (3)\HiJackThis (2).exe
   1  C:\Windows\Microsoft.NET\Framework64\v3.0\Windows Communication Foundation\infocard.exe
   1  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\SMSvcHost.exe
   1  C:\Windows\SysWOW64\notepad.exe
   1  C:\Windows\System32\SearchFilterHost.exe
   1  C:\Windows\System32\SearchIndexer.exe
   1  C:\Windows\System32\SearchProtocolHost.exe
   2  C:\Windows\System32\WUDFHost.exe
   1  C:\Windows\System32\alg.exe
   1  C:\Windows\System32\atieclxx.exe
   1  C:\Windows\System32\atiesrxx.exe
   1  C:\Windows\System32\conhost.exe
   2  C:\Windows\System32\csrss.exe
   1  C:\Windows\System32\dllhost.exe
   1  C:\Windows\System32\lsass.exe
   1  C:\Windows\System32\lsm.exe
   1  C:\Windows\System32\services.exe
   1  C:\Windows\System32\smss.exe
   1  C:\Windows\System32\spoolsv.exe
  16  C:\Windows\System32\svchost.exe
   1  C:\Windows\System32\wininit.exe
   1  C:\Windows\System32\winlogon.exe
   2  C:\Windows\explorer.exe

R0 - HKCU\Software\Microsoft\Internet Explorer\Main: [Search Bar] = https://%66%65%65%64.

%73%6F%6E%69%63-%73%65%61%72%63%68.%63%6F%6D/?

p=mKO_AwFzXIpYRaHdGKBRHOjYN9_5EdL7qPpMxk4QqOkRJK_wvxpQl910wLxq6AjuXCkJ_13vV-

by_ab7nmKRrQDZY0DSsNSYs3dbG3XfenVpDdpJHtjvY9wMpSugcbE7g8ye__LdZDS9hYQpX1boACT-5IHy-

Ck0dgYg1Q2ABNjojR3lEi8NTbrFcqLvjUAjVdu8BEyz-Ko,&q={searchTerms}
R0 - HKCU\Software\Microsoft\Internet Explorer\Main: [Search Page] = https://%66%65%65%64.

%73%6F%6E%69%63-%73%65%61%72%63%68.%63%6F%6D/?

p=mKO_AwFzXIpYRaHdGKBRHOjYN9_5EdL7qPpMxk4QqOkRJK_wvxpQl910wLxq6AjuXCkJ_13vV-

by_ab7nmKRrQDZY0DSsNSYs3dbG3XfenVpDdpJHtjvY9wMpSugcbE7g8ye__LdZDS9hYQpX1boACT-5IHy-

Ck0dgYg1Q2ABNjojR3lEi8NTbrFcqLvjUAjVdu8BEyz-Ko,&q={searchTerms}
R0 - HKCU\Software\Microsoft\Internet Explorer\Search: [Default_Search_URL] = https://

%66%65%65%64.%73%6F%6E%69%63-%73%65%61%72%63%68.%63%6F%6D/?

p=mKO_AwFzXIpYRaHdGKBRHOjYN9_5EdL7qPpMxk4QqOkRJK_wvxpQl910wLxq6AjuXCkJ_13vV-

by_ab7nmKRrQDZY0DSsNSYs3dbG3XfenVpDdpJHtjvY9wMpSugcbE7g8ye__LdZDS9hYQpX1boACT-5IHy-

Ck0dgYg1Q2ABNjojR3lEi8NTbrFcqLvjUAjVdu8BEyz-Ko,&q={searchTerms}
R1 - HKCU\Software\Microsoft\Internet Explorer\Main: [SearchAssistant] = https://

%66%65%65%64.%73%6F%6E%69%63-%73%65%61%72%63%68.%63%6F%6D/?

p=mKO_AwFzXIpYRaHdGKBRHOjYN9_5EdL7qPpMxk4QqOkRJK_wvxpQl910wLxq6AjuXCkJ_13vV-

by_ab7nmKRrQDZY0DSsNSYs3dbG3XfenVpDdpJHtjvY9wMpSugcbE7g8ye__LdZDS9hYQpX1boACT-5IHy-

Ck0dgYg1Q2ABNjojR3lEi8NTbrFcqLvjUAjVdu8BEyz-Ko,&q={searchTerms}
R4 - SearchScopes: HKCU\Software\Microsoft\Internet Explorer\SearchScopes\{5A108EB8-8172-4934

-9FBC-46C6A34AD31A}: [URL] = https://www.google.com/search?q={searchTerms} - Google
R4 - SearchScopes: HKCU\Software\Microsoft\Internet Explorer\SearchScopes\{CE0FCCE4-FA2B-

47EF-873D-3ABC7CC7AB1E}: [URL] = http://www.google.it/#hl=it&source=hp&q={searchTerms}

&aq=f&aqi=g10&aql=&oq=&gs_rfai=&fp=9fca69c98b5d77d7 - Google Italia
O1 - Hosts: Reset contents to default
O1 - Hosts: 127.0.0.1 75.126.120.203
O1 - Hosts: 127.0.0.1 46.4.58.71
O1 - Hosts: 127.0.0.1 46.4.62.150
O1 - Hosts: 127.0.0.1 46.4.28.80
O1 - Hosts: 127.0.0.1 idb.iobit.com
O1 - Hosts: 127.0.0.1 asc55.iobit.com
O1 - Hosts: 127.0.0.1 is360.iobit.com
O1 - Hosts: 127.0.0.1 asc.iobit.com
O1 - Hosts: 127.0.0.1 pf.iobit.com
O1 - Hosts: 127.0.0.1 98.129.229.186
O1 - Hosts: 127.0.0.1 www.iana.org
O1 - Hosts: 127.0.0.1 iana.org# ::1 localhost
O2 - HKLM\..\BHO: ExplorerWnd Helper - {10921475-03CE-4E04-90CE-E2E7EF20C814} - C:\Program 

Files (x86)\IObit\IObit Uninstaller\UninstallExplorer.dll
O2 - HKLM\..\BHO: Windows Live ID Sign-in Helper - {9030D464-4C02-4ABF-8ECC-5164760863C6} - 

c:\Program Files\Common Files\Microsoft Shared\Windows Live\WindowsLiveLogin.dll
O2-32 - HKLM\..\BHO: IObit Surfing Protection - {BA0C978D-D909-49B6-AFE2-8BDE245DC7E6} - C:

\Program Files (x86)\IObit\Advanced SystemCare\Surfing Protection\BrowerProtect

\ASCPlugin_Protection.dll
O2-32 - HKLM\..\BHO: Java(tm) Plug-In 2 SSV Helper - {DBC80044-A445-435b-BC74-9C25C1C588A9} - 

C:\Program Files (x86)\Java\jre1.8.0_191\bin\jp2ssv.dll
O2-32 - HKLM\..\BHO: Java(tm) Plug-In SSV Helper - {761497BB-D6F0-462C-B6EB-D4DAF1D92D43} - 

C:\Program Files (x86)\Java\jre1.8.0_191\bin\ssv.dll
O4 - Global User Startup: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\SELPHY 

Photo Print Launcher.lnk.CommonStartup
O4 - HKCU\..\Run: [Advanced SystemCare] = C:\Program Files (x86)\IObit\Advanced SystemCare

\ASCTray.exe /Auto
O4 - HKCU\..\Run: [HP OfficeJet Pro 8710 (NET)] = C:\Program Files\HP\HP OfficeJet Pro 

8710\Bin\ScanToPCActivationApp.exe -deviceID "CN7C3BT2F8:NW" -scfn "HP OfficeJet Pro 8710 

(NET)" -AutoStart 1
O4 - HKCU\..\Run: [HydraVisionDesktopManager] = C:\Program Files (x86)\ATI Technologies

\HydraVision\HydraDM.exe
O4 - HKCU\..\Run: [Videostream] = C:\Users\redevilr76\AppData\Local\Videostream\app-

0.3.6\Videostream.exe startup
O4 - HKLM\..\Run: [RTHDVCPL] = C:\Program Files\Realtek\Audio\HDA\RtkNGUI64.exe -s
O4 - HKLM\..\Session Manager: [BootExecute] = C:\Windows\system32\SmartDefragBootTime.exe
O4 - HKLM\..\Session Manager: [BootExecute] = C:\Windows\system32\autochk.exe /p \??\L:
O4 - HKLM\..\Session Manager: [BootExecute] = autocheck autochk * (file missing)
O4 - MSConfig\startupfolder: C:^ProgramData^Microsoft^Windows^Start 

Menu^Programs^Startup^SELPHY Photo Print Launcher.lnk [backup] =  (2017/03/04) (no file)
O4 - MSConfig\startupreg: Plex Media Server [command] = (HKCU) (2014/09/06) (no file)
O4 - User Startup: C:\Users\redevilr76\AppData\Roaming\Microsoft\Windows\Start Menu\Programs

\Startup\MEGAsync.lnk    ->    C:\ProgramData\MEGAsync\MEGAsync.exe
O4-32 - HKLM\..\Run: [Avira SystrayStartTrigger] = C:\Program Files (x86)\Avira\Launcher

\Avira.SystrayStartTrigger.exe
O4-32 - HKLM\..\Run: [IObit Malware Fighter] = C:\Program Files (x86)\IObit\IObit Malware 

Fighter\IMF.exe /autostart
O7 - Taskbar policy: HKCU\..\Explorer\Advanced: [Start_ShowRun] = 0
O10 - Unknown file in Winsock LSP: C:\Program Files (x86)\Bonjour\mdnsNSP.dll
O17 - DHCP DNS 1: 208.67.222.222 (Well-known DNS: Cisco OpenDNS)
O17 - DHCP DNS 2: 208.67.220.220 (Well-known DNS: Cisco OpenDNS)
O17 - HKLM\System\CCS\Services\Tcpip\..\{12830DF3-2A05-43F1-A154-777EDC998346}: [NameServer] = 

208.67.220.220 (Well-known DNS: Cisco OpenDNS)
O17 - HKLM\System\CCS\Services\Tcpip\..\{12830DF3-2A05-43F1-A154-777EDC998346}: [NameServer] = 

208.67.222.222 (Well-known DNS: Cisco OpenDNS)
O17 - HKLM\System\CCS\Services\Tcpip\..\{606ACE02-F761-4479-A51E-B41C4206A57F}: [NameServer] = 

208.67.220.220 (Well-known DNS: Cisco OpenDNS)
O17 - HKLM\System\CCS\Services\Tcpip\..\{606ACE02-F761-4479-A51E-B41C4206A57F}: [NameServer] = 

208.67.222.222 (Well-known DNS: Cisco OpenDNS)
O17 - HKLM\System\ControlSet002\Services\Tcpip\..\{12830DF3-2A05-43F1-A154-777EDC998346}: 

[NameServer] = 208.67.220.220 (Well-known DNS: Cisco OpenDNS)
O17 - HKLM\System\ControlSet002\Services\Tcpip\..\{12830DF3-2A05-43F1-A154-777EDC998346}: 

[NameServer] = 208.67.222.222 (Well-known DNS: Cisco OpenDNS)
O17 - HKLM\System\ControlSet002\Services\Tcpip\..\{606ACE02-F761-4479-A51E-B41C4206A57F}: 

[NameServer] = 208.67.220.220 (Well-known DNS: Cisco OpenDNS)
O17 - HKLM\System\ControlSet002\Services\Tcpip\..\{606ACE02-F761-4479-A51E-B41C4206A57F}: 

[NameServer] = 208.67.222.222 (Well-known DNS: Cisco OpenDNS)
O18 - HKLM\Software\Classes\Protocols\Handler\wlpg: [CLSID] = {E43EF6CD-A37A-4A9B-9E6F-

83F89B8E6324} - C:\Program Files (x86)\Windows Live\Photo Gallery

\AlbumDownloadProtocolHandler.dll
O20-32 - HKLM\..\Winlogon\Notify\SDWinLogon: [DllName] = SDWinLogon.dll (file missing)
O20-32 - HKLM\..\Winlogon\Notify\mmtlock: [DllName] = (no file)
O21 - HKLM\..\ShellIconOverlayIdentifiers\ MEGA (Pending):  MEGA (Pending) - {056D528D-CE28

-4194-9BA3-BA2E9197FF8C} - C:\ProgramData\MEGAsync\ShellExtX64.dll
O21 - HKLM\..\ShellIconOverlayIdentifiers\ MEGA (Synced):  MEGA (Synced) - {05B38830-F4E9-

4329-978B-1DD28605D202} - C:\ProgramData\MEGAsync\ShellExtX64.dll
O21 - HKLM\..\ShellIconOverlayIdentifiers\ MEGA (Syncing):  MEGA (Syncing) - {0596C850-

7BDD-4C9D-AFDF-873BE6890637} - C:\ProgramData\MEGAsync\ShellExtX64.dll
O21 - HKLM\..\ShellIconOverlayIdentifiers\                    IMFSafeBox: (no name) - 

{0BB81440-5F42-4480-A5F7-770A6F439FC8} - (no file)
O21 - HKLM\..\ShellIconOverlayIdentifiers\00asw: (no name) - {472083B0-C522-11CF-8763-

00608CC02F24} - (no file)
O21-32 - HKLM\..\ShellIconOverlayIdentifiers\ MEGA (Pending):  MEGA (Pending) - {056D528D-

CE28-4194-9BA3-BA2E9197FF8C} - C:\ProgramData\MEGAsync\ShellExtX32.dll
O21-32 - HKLM\..\ShellIconOverlayIdentifiers\ MEGA (Synced):  MEGA (Synced) - {05B38830-

F4E9-4329-978B-1DD28605D202} - C:\ProgramData\MEGAsync\ShellExtX32.dll
O21-32 - HKLM\..\ShellIconOverlayIdentifiers\ MEGA (Syncing):  MEGA (Syncing) - {0596C850-

7BDD-4C9D-AFDF-873BE6890637} - C:\ProgramData\MEGAsync\ShellExtX32.dll
O23 - Service R2:  Servizio Bonjour - (Bonjour Service) - C:\Program Files\Bonjour

\mDNSResponder.exe
O23 - Service R2: AMD External Events Utility - C:\Windows\system32\atiesrxx.exe
O23 - Service R2: AOMEI Backupper Scheduler Service - (Backupper Service) - C:\Program Files 

(x86)\AOMEI Backupper\ABService.exe
O23 - Service R2: ASUS Com Service - (asComSvc) - C:\Program Files (x86)\ASUS\AXSP

\1.02.00\atkexComSvc.exe
O23 - Service R2: Advanced SystemCare Service 13 - (AdvancedSystemCareService13) - C:\Program 

Files (x86)\IObit\Advanced SystemCare\ASCService.exe
O23 - Service R2: Apple Mobile Device Service - C:\Program Files\Common Files\Apple\Mobile 

Device Support\AppleMobileDeviceService.exe
O23 - Service R2: Avira Pianificatore - (AntiVirSchedulerService) - C:\Program Files 

(x86)\Avira\Antivirus\sched.exe
O23 - Service R2: Avira Protezione in tempo reale - (AntiVirService) - C:\Program Files 

(x86)\Avira\Antivirus\avguard.exe
O23 - Service R2: Avira Service Host - (Avira.ServiceHost) - C:\Program Files (x86)\Avira

\Launcher\Avira.ServiceHost.exe
O23 - Service R2: Diagnostics Tracking Service - (DiagTrack) - C:\Windows\System32\svchost.exe 

-k utcsvc; "ServiceDll" = C:\Windows\system32\diagtrack.dll
O23 - Service R2: IMF Service - (IMFservice) - C:\Program Files (x86)\IObit\IObit Malware 

Fighter\IMFsrv.exe
O23 - Service R2: Intel(R) Dynamic Application Loader Host Interface Service - (jhi_service) - 

C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL\jhi_service.exe
O23 - Service R2: Spybot-S&D 2 Scanner Service - (SDScannerService) - C:\Program Files 

(x86)\Spybot - Search & Destroy 2\SDFSSvc.exe
O23 - Service R2: Spybot-S&D 2 Security Center Service - (SDWSCService) - C:\Program Files 

(x86)\Spybot - Search & Destroy 2\SDWSCSvc.exe
O23 - Service R2: Spybot-S&D 2 Updating Service - (SDUpdateService) - C:\Program Files 

(x86)\Spybot - Search & Destroy 2\SDUpdSvc.exe
O23 - Service S2: Avira Protezione email - (AntiVirMailService) - C:\Program Files 

(x86)\Avira\Antivirus\avmailc7.exe
O23 - Service S2: Avira Protezione web - (AntiVirWebService) - C:\Program Files (x86)\Avira

\Antivirus\avwebg7.exe
O23 - Service S2: IObit Uninstaller Service - (IObitUnSvr) - C:\Program Files (x86)\IObit

\IObit Uninstaller\IUService.exe
O23 - Service S2: Intel(R) Management and Security Application Local Management Service - 

(LMS) - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\LMS\LMS.exe
O23 - Service S2: Servizio Google Update (gupdate) - (gupdate) - C:\Program Files 

(x86)\Google\Update\GoogleUpdate.exe /svc
O23 - Service S3: Adobe Flash Player Update Service - (AdobeFlashPlayerUpdateSvc) - C:

\Windows\SysWOW64\Macromed\Flash\FlashPlayerUpdateService.exe
O23 - Service S3: Alcohol Virtual Drive Auto-mount Service - (AxAutoMntSrv) - C:\Program Files 

(x86)\Alcohol Soft\Alcohol 52\AxAutoMntSrv.exe
O23 - Service S3: Google Chrome Elevation Service - (GoogleChromeElevationService) - C:

\Program Files (x86)\Google\Chrome\Application\78.0.3904.108\elevation_service.exe
O23 - Service S3: InstallDriver Table Manager - (IDriverT) - C:\Program Files (x86)\Common 

Files\InstallShield\Driver\1050\Intel 32\IDriverT.exe
O23 - Service S3: Intel(R) Capability Licensing Service Interface - C:\Program Files\Intel

\iCLS Client\HeciServer.exe
O23 - Service S3: Intel(R) Capability Licensing Service TCP IP Interface - C:\Program Files

\Intel\iCLS Client\SocketHeciServer.exe
O23 - Service S3: Intel(R) Content Protection HECI Service - (cphs) - C:\Windows

\SysWow64\IntelCpHeciSvc.exe
O23 - Service S3: Intel(R) Rapid Storage Technology - (IAStorDataMgrSvc) - C:\Program Files

\Intel\Intel(R) Rapid Storage Technology\IAStorDataMgrSvc.exe
O23 - Service S3: Macromedia Licensing Service - C:\Program Files (x86)\Common Files

\Macromedia Shared\Service\Macromedia Licensing.exe
O23 - Service S3: NeMeSys Service - (Nemesys) - C:\Program Files (x86)\Nemesys\dist

\Nemesys.exe
O23 - Service S3: Servizio Google Update (gupdatem) - (gupdatem) - C:\Program Files 

(x86)\Google\Update\GoogleUpdate.exe /medsvc
O23 - Service S3: Servizio iPod - (iPod Service) - C:\Program Files\iPod\bin\iPodService.exe
O23 - Service S3: StarWind AE Service - (StarWindServiceAE) - C:\Program Files (x86)\Alcohol 

Soft\Alcohol 52\StarWind\StarWindServiceAE.exe
O23 - Service S3: Wondershare Application Framework Service - (WsAppService) - C:\Program 

Files (x86)\Wondershare\WAF\2.4.3.237\WsAppService.exe

--
End of file - Time spent: 14,7 sec. - 32828 bytes, CRC32: FFFFFFFF. Sign: ꕂ僩
[hijackthis1.log](https://github.com/dragokas/hijackthis/files/3941970/hijackthis1.log)
[hijackthis1.log](https://github.com/dragokas/hijackthis/files/3941974/hijackthis1.log)

**Comment by dragokas** [comment]
Hi,
thank you for the log.

Note, that we provide asssistance on English and Russian languages only.

If you need our assistance:
  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog and write what problems remained.
