### ISSUE TITLE
Ignore List Corrupted

### ISSUE THREAD

**Issue by hkier** [dragokas/hijackthis#82]
Not sure if this is a bug or some other problem.  I recently scanned my computer with HJT and discovered a slew of programs were modified which was unexpected.  A closer look at the situation showed the Ignore List seems to have been corrupted.  Every entry there shows up as ??????? where I expected to see the text for the ignored entry.  

I do have about 3 weeks of backups on my computer so we can attempt to see when the problem occurred, but I have no idea what to look for.

**Comment by Sandor-Helper** [comment]
Hi, and welcome
If you need our assistance:

* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)
* Describe your problem in details.

**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Hi, hkier and welcome!

This is more like a bug.

1. Please, make export of this registry key:
`HKEY_LOCAL_MACHINE\SOFTWARE\TrendMicro`
pack and attach it to your next post.

Instruction:
How to Export and Import Registry Keys in Windows
https://www.tenforums.com/tutorials/125696-export-import-registry-keys-windows.html

2. Also, make export of registry key:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion`
pack and attach it to your next post.

3. Run HiJackThis Fork, press **"Do a system scan and save a log file"**, attach HiJackThis.log

Thank you.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in HiJackThis topics. 
Ignore any recommendations given by other users, including PM !!!**

**Comment by hkier** [comment]
Here are the files you requested.  I hope the .txt version of the registry is sufficient as that seems to be the only export file type of regedit which is supported by Github upload.

[hijackthis scanlog.txt](https://github.com/dragokas/hijackthis/files/4060775/hijackthis.scanlog.txt)
[trendmicro regedit.txt](https://github.com/dragokas/hijackthis/files/4060790/trendmicro.regedit.txt)
[currentversion regedit.txt](https://github.com/dragokas/hijackthis/files/4060791/currentversion.regedit.txt)

**Comment by dragokas** [comment]
Nope, 
HKEY_LOCAL_MACHINE\SOFTWARE\TrendMicro
needs to be in .reg format.

Please, pack it to .zip archive and attach.
Thank you.

**Comment by hkier** [comment]
Here is the zip file as requested.

[registry files.zip](https://github.com/dragokas/hijackthis/files/4061758/registry.files.zip)

**Comment by hkier** [comment]
Here's a screen shot of the ignore list.

![HJT Ignore list](https://user-images.githubusercontent.com/28713997/72412383-cfa7e200-3732-11ea-9e59-d68716aa4be3.jpg)

**Comment by dragokas** [comment]
Hi,
sorry for late reply.

Looks like Windows Update broke encryption seed.
To confirm that, I need additional logs:

Please,
run command line ( Win + R key combination -> type CMD and press OK )
paste this command and press enter:
`
wmic qfe list /format:csv > updates.txt& explorer /select,.\updates.txt
`
Attach updates.txt file to your next reply.

**Comment by hkier** [comment]
I get the feeling that is not the only thing the Windows Update may have broken.  I also seem to remember I did allow a Windows Update to install on my computer around the same time.  In fact, that may have been why I was running HJT, to verify what may have changed.

[updates.txt](https://github.com/dragokas/hijackthis/files/4101293/updates.txt)

**Comment by dragokas** [comment]
**WARNING. This fix is intended specially for user 'hkier'. Do not try to apply it to your PC. You can harm it.**

I decrypted it. This is temporal fix. You can download this file: [currentversion_solution.zip](https://github.com/dragokas/hijackthis/files/4101298/currentversion_solution.zip)

unpack, doule-click reg file in it, and apply to your PC. This will revert your ignore list to normal, until I publish new HiJackThis update, or until Microsoft publish new update and brake it again :)

**Comment by hkier** [comment]
Problem fixed.  But I seriously think Microsoft broke more than just this one thing.... ;-(

**Comment by dragokas** [comment]
Great.
This thread will be opened until fresh HiJackThis update been released.
So, you can receive notification.

If you need further assistance, note that:
our section is intended to cure malware only.
If you think your PC is infected feel free to open new issue.

If you have other problems with your PC, we recommend you to ask help on the forums that provide assistance in resolving general operation system issues, like:
 - https://www.tenforums.com
 - https://answers.microsoft.com/
 - http://www.geekstogo.com/forum/forum/41-operating-systems/

Good luck!

**Comment by hkier** [comment]
For your information:

Bad news and Good news....

Bad news, Microsoft corrupted the record again with another update.  Good news, the previous fix worked to resolve the problem....

**Comment by dragokas** [comment]
Yeah, I still working on other project, dunno when I had time.
Thanks for info.

**Comment by dragokas** [comment]
Fixed in the Nightly build v.2.9.0.23.
