### ISSUE TITLE
Mi ordenador va extremadamente lento ¿Lo podeis mirar por favor?

### ISSUE THREAD

**Issue by ancestro** [dragokas/hijackthis#83]
Registro de Hijackthis
Logfile of HiJackThis Fork by Alex Dragokas v.2.9.0.18

Platform:  x64 Windows 8.1 (Home), 6.3.9600.19599, Service Pack: 0
Time:      28.01.2020 - 20:51 (UTC+01:00)
Language:  OS: Spanish (0xC0A). Display: Spanish (0xC0A). Non-Unicode: Spanish (0xC0A)
Elevated:  Yes
Ran by:    equipo1	(group: Administrator) on EQUIPO, FirstRun: no

Chrome:  79.0.3945.130
Internet Explorer: 11.0.9600.19036
Default: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" -- "%1" (Google Chrome)

Boot mode: Normal

Running processes:
Number | Path
   1  C:\Program Files (x86)\Common Files\Adobe\ARM\1.0\armsvc.exe
   1  C:\Program Files (x86)\Common Files\VMware\USB\vmware-usbarbitrator64.exe
  19  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
   1  C:\Program Files (x86)\Google\Update\1.3.35.422\GoogleCrashHandler.exe
   1  C:\Program Files (x86)\Google\Update\1.3.35.422\GoogleCrashHandler64.exe
   1  C:\Program Files (x86)\IObit\Advanced SystemCare\ASCService.exe
   1  C:\Program Files (x86)\IObit\IObit Uninstaller\UninstallMonitor.exe
   4  C:\Program Files (x86)\Microsoft\Skype for Desktop\Skype.exe
   1  C:\Program Files (x86)\Qualcomm Atheros\Bluetooth Suite\ActivateDesktop.exe
   1  C:\Program Files (x86)\Qualcomm Atheros\Bluetooth Suite\BtvStack.exe
   1  C:\Program Files (x86)\VMware\VMware Workstation\vmware-authd.exe
   1  C:\Program Files (x86)\VMware\VMware Workstation\vmware-hostd.exe
   1  C:\Program Files (x86)\VMware\VMware Workstation\vmware-tray.exe
   1  C:\Program Files (x86)\VMware\VMware Workstation\vmware-unity-helper.exe
   1  C:\Program Files (x86)\VMware\VMware Workstation\vmware.exe
   1  C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx.exe
   1  C:\Program Files\AVAST Software\Avast\AvastSvc.exe
   2  C:\Program Files\AVAST Software\Avast\AvastUI.exe
   1  C:\Program Files\AVAST Software\Avast\afwServ.exe
   1  C:\Program Files\AVAST Software\Avast\aswidsagent.exe
   1  C:\Program Files\Common Files\microsoft shared\ClickToRun\AppVShNotify.exe
   1  C:\Program Files\Common Files\microsoft shared\ClickToRun\OfficeClickToRun.exe
   2  C:\Program Files\Microsoft Office\Office16\WINWORD.EXE
   1  C:\Users\equipo1\Downloads\HiJackThis.exe
   1  C:\Windows\SysWOW64\vmnat.exe
   1  C:\Windows\SysWOW64\vmnetdhcp.exe
   1  C:\Windows\System32\RuntimeBroker.exe
   1  C:\Windows\System32\audiodg.exe
   2  C:\Windows\System32\csrss.exe
   1  C:\Windows\System32\dasHost.exe
   1  C:\Windows\System32\dwm.exe
   1  C:\Windows\System32\lsass.exe
   1  C:\Windows\System32\services.exe
   1  C:\Windows\System32\smss.exe
   1  C:\Windows\System32\spoolsv.exe
  14  C:\Windows\System32\svchost.exe
   1  C:\Windows\System32\taskhost.exe
   1  C:\Windows\System32\taskhostex.exe
   1  C:\Windows\System32\wbem\unsecapp.exe
   1  C:\Windows\System32\wininit.exe
   1  C:\Windows\System32\winlogon.exe
   1  C:\Windows\explorer.exe

R0 - HKCU\Software\Microsoft\Internet Explorer\Main: [Search Bar] = https://www.google.com/?trackid=sp-006
R0 - HKCU\Software\Microsoft\Internet Explorer\Main: [Search Page] = https://www.google.com/search?trackid=sp-006&q={searchTerms}
R0 - HKCU\Software\Microsoft\Internet Explorer\Main: [Start Page] = https://www.msn.com/?PC=UF01
R0-32 - HKLM\Software\Microsoft\Internet Explorer\Main: [Search Bar] = https://www.google.com/?trackid=sp-006
R0-32 - HKLM\Software\Microsoft\Internet Explorer\Main: [Search Page] = https://www.google.com/search?trackid=sp-006&q={searchTerms}
R0-32 - HKLM\Software\Microsoft\Internet Explorer\Main: [Start Page] = https://www.google.com/?trackid=sp-006
R4 - SearchScopes: HKCU\Software\Microsoft\Internet Explorer\SearchScopes\{E9410C70-B6AE-41FF-AB71-32F4B279EA5F}: [SuggestionsURLFallback] = http://clients5.google.com/complete/search?q={searchTerms}&hl={language}&gl={language}&client=ie8&mw={ie:maxWidth}&sh={ie:sectionHeight}&rh={ie:rowHeight}&inputencoding={inputEncoding}&outputencoding={outputEncoding} - Google
R4 - SearchScopes: HKCU\Software\Microsoft\Internet Explorer\SearchScopes\{E9410C70-B6AE-41FF-AB71-32F4B279EA5F}: [URL] = https://www.google.com/search?trackid=sp-006&q={searchTerms} - Google
R4 - SearchScopes: HKCU\Software\Microsoft\Internet Explorer\SearchScopes\{EC15F353-4992-46C9-A763-CB70A2595E76}: [URL] = http://www.goal-es.com/search?q={searchTerms} - Buscar
O1 - Hosts: 23.74.24.114 l3cdn.riotgames.com
O1 - Hosts: 0.0.0.0 adclick.g.doublecklick.net
O1 - Hosts: 0.0.0.0 googleads.g.doubleclick.net
O1 - Hosts: 0.0.0.0 http://www.googleadservices.com
O1 - Hosts: 0.0.0.0 pubads.g.doubleclick.net
O1 - Hosts: 0.0.0.0 securepubads.g.doubleclick.net
O1 - Hosts: 0.0.0.0 pagead2.googlesyndication.com
O1 - Hosts: 0.0.0.0 spclient.wg.spotify.com
O1 - Hosts: 0.0.0.0 audio2.spotify.com
O2 - HKLM\..\BHO: ExplorerWnd Helper - {10921475-03CE-4E04-90CE-E2E7EF20C814} - C:\Program Files (x86)\IObit\IObit Uninstaller\UninstallExplorer.dll
O4 - HKCU\..\RunOnce: [Uninstall C:\Users\equipo1\AppData\Local\Microsoft\OneDrive\17.3.6386.0412\amd64] = C:\Windows\system32\cmd.exe /q /c rmdir /s /q "C:\Users\equipo1\AppData\Local\Microsoft\OneDrive\17.3.6386.0412\amd64"
O4 - HKCU\..\StartupApproved\Run: [GoogleDriveSync] = C:\Program Files\Google\Drive\googledrivesync.exe /autostart (2019/12/14)
O4 - HKCU\..\StartupApproved\Run: [Speech Recognition] = C:\Windows\Speech\Common\sapisvr.exe -SpeechUX -Startup (2019/12/17)
O4 - HKLM\..\Policies\Explorer\Run: [BtvStack] = C:\Program Files (x86)\Qualcomm Atheros\Bluetooth Suite\BtvStack.exe
O4 - HKLM\..\Run: [AvastUI.exe] = C:\Program Files\AVAST Software\Avast\AvLaunch.exe /gui
O4 - HKLM\..\StartupApproved\Run32: [vmware-tray.exe] = C:\Program Files (x86)\VMware\VMware Workstation\vmware-tray.exe (2019/11/26)
O10 - Unknown file in Winsock LSP: C:\Windows\system32\vsocklib.dll
O15 - Trusted Zone: https://amazon.es
O17 - DHCP DNS 1: 8.8.8.8 (Well-known DNS: Google)
O17 - DHCP DNS 2: 8.8.4.4 (Well-known DNS: Google)
O17 - HKLM\System\CCS\Services\Tcpip\..\{4E71CC8A-ED8D-4C70-B6B1-6D6B655E8C9D}: [NameServer] = 8.8.4.4 (Well-known DNS: Google)
O17 - HKLM\System\CCS\Services\Tcpip\..\{4E71CC8A-ED8D-4C70-B6B1-6D6B655E8C9D}: [NameServer] = 8.8.8.8 (Well-known DNS: Google)
O21 - HKLM\..\ShellIconOverlayIdentifiers\  GoogleDriveBlacklisted: Google Drive Shell extension - {81539FE6-33C7-4CE7-90C7-1C7B8F2F2D42} - C:\Program Files\Google\Drive\googledrivesync64.dll
O21 - HKLM\..\ShellIconOverlayIdentifiers\  GoogleDriveSynced: Google Drive Shell extension - {81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40} - C:\Program Files\Google\Drive\googledrivesync64.dll
O21 - HKLM\..\ShellIconOverlayIdentifiers\  GoogleDriveSyncing: Google Drive Shell extension - {81539FE6-33C7-4CE7-90C7-1C7B8F2F2D41} - C:\Program Files\Google\Drive\googledrivesync64.dll
O21 - HKLM\..\ShellIconOverlayIdentifiers\ ACloudSynced: ACloudSynced Class - {5CCE71FA-9F61-4F24-9CD1-98D819B40D68} - C:\Program Files (x86)\Acer\shellext\x64\shellext_win.dll
O21 - HKLM\..\ShellIconOverlayIdentifiers\ ACloudSyncing: ACloudSyncing Class - {C1E1456F-C2D8-4C96-870D-35F1E13941EE} - C:\Program Files (x86)\Acer\shellext\x64\shellext_win.dll
O21 - HKLM\..\ShellIconOverlayIdentifiers\ ACloudToBeSynced: ACloudToBeSynced Class - {307523FA-DDC0-4068-983F-2A6B34627744} - C:\Program Files (x86)\Acer\shellext\x64\shellext_win.dll
O21 - HKLM\..\ShellIconOverlayIdentifiers\###MegaShellExtSyncing: (no name) - {0596C850-7BDD-4C9D-AFDF-873BE6890637} - (no file)
O21 - HKLM\..\ShellIconOverlayIdentifiers\00asw: avast - {472083B0-C522-11CF-8763-00608CC02F24} - C:\Program Files\AVAST Software\Avast\ashShell.dll
O21 - HKLM\..\ShellIconOverlayIdentifiers\00avast: avast - {472083B0-C522-11CF-8763-00608CC02F24} - C:\Program Files\AVAST Software\Avast\ashShell.dll
O21-32 - HKLM\..\ShellIconOverlayIdentifiers\ SkyDrivePro1 (ErrorConflict): Microsoft SkyDrive Pro Icon Overlay 1 (ErrorConflict) - {8BA85C75-763B-4103-94EB-9470F12FE0F7} - C:\Program Files (x86)\Microsoft Office\Office16\GROOVEEX.DLL (file missing)
O21-32 - HKLM\..\ShellIconOverlayIdentifiers\ SkyDrivePro2 (SyncInProgress): Microsoft SkyDrive Pro Icon Overlay 2 (SyncInProgress) - {CD55129A-B1A1-438E-A425-CEBC7DC684EE} - C:\Program Files (x86)\Microsoft Office\Office16\GROOVEEX.DLL (file missing)
O21-32 - HKLM\..\ShellIconOverlayIdentifiers\ SkyDrivePro3 (InSync): Microsoft SkyDrive Pro Icon Overlay 3 (InSync) - {E768CD3B-BDDC-436D-9C13-E1B39CA257B1} - C:\Program Files (x86)\Microsoft Office\Office16\GROOVEEX.DLL (file missing)
O21-32 - HKLM\..\ShellIconOverlayIdentifiers\###MegaShellExtSyncing: (no name) - {0596C850-7BDD-4C9D-AFDF-873BE6890637} - (no file)
O22 - Task: \Microsoft\Windows\ApplicationData\CleanupTemporaryState - C:\Windows\system32 (file missing)
O23 - Service R2: Adobe Acrobat Update Service - (AdobeARMservice) - C:\Program Files (x86)\Common Files\Adobe\ARM\1.0\armsvc.exe
O23 - Service R2: Advanced SystemCare Service 13 - (AdvancedSystemCareService13) - C:\Program Files (x86)\IObit\Advanced SystemCare\ASCService.exe
O23 - Service R2: Avast Antivirus - (avast! Antivirus) - C:\Program Files\AVAST Software\Avast\AvastSvc.exe
O23 - Service R2: Avast Firewall Service - (avast! Firewall) - C:\Program Files\AVAST Software\Avast\afwServ.exe
O23 - Service R2: Diagnostics Tracking Service - (DiagTrack) - C:\Windows\System32\svchost.exe -k utcsvc; "ServiceDll" = C:\Windows\system32\diagtrack.dll
O23 - Service R2: Servicio Hacer clic y ejecutar de Microsoft Office - (ClickToRunSvc) - C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe /service
O23 - Service R2: VMware Authorization Service - (VMAuthdService) - C:\Program Files (x86)\VMware\VMware Workstation\vmware-authd.exe
O23 - Service R2: VMware DHCP Service - (VMnetDHCP) - C:\Windows\SysWOW64\vmnetdhcp.exe
O23 - Service R2: VMware NAT Service - C:\Windows\SysWOW64\vmnat.exe
O23 - Service R2: VMware USB Arbitration Service - (VMUSBArbService) - C:\Program Files (x86)\Common Files\VMware\USB\vmware-usbarbitrator64.exe
O23 - Service R2: VMware Workstation Server - (VMwareHostd) - C:\Program Files (x86)\VMware\VMware Workstation\vmware-hostd.exe -u "C:\ProgramData\VMware\hostd\config.xml"
O23 - Service R3: aswbIDSAgent - C:\Program Files\AVAST Software\Avast\aswidsagent.exe
O23 - Service S2: Origin Web Helper Service - C:\Program Files (x86)\Origin\OriginWebHelperService.exe
O23 - Service S2: Servicio de Google Update (gupdate) - (gupdate) - C:\Program Files (x86)\Google\Update\GoogleUpdate.exe /svc
O23 - Service S3: BattlEye Service - (BEService) - C:\Program Files (x86)\Common Files\BattlEye\BEService.exe
O23 - Service S3: Google Chrome Elevation Service - (GoogleChromeElevationService) - C:\Program Files (x86)\Google\Chrome\Application\79.0.3945.130\elevation_service.exe
O23 - Service S3: Office 64 Source Engine - (ose64) - C:\Program Files\Common Files\Microsoft Shared\Source Engine\OSE.EXE
O23 - Service S3: Origin Client Service - C:\Program Files (x86)\Origin\OriginClientService.exe
O23 - Service S3: Servicio de Google Update (gupdatem) - (gupdatem) - C:\Program Files (x86)\Google\Update\GoogleUpdate.exe /medsvc
O23 - Service S3: VirtualBox system service - (VBoxSDS) - C:\Program Files\Oracle\VirtualBox\VBoxSDS.exe

Debug information:

- 28.01.2020 20:50:50 - CryptCATAdminCalcHashFromFileHandle - #0 LastDllError = 193 (%1 no es una aplicación Win32 válida.) TRUST_E_NOSIGNATURE: Not signed File:  C:\Windows\system32 

--
End of file - Time spent: 27 sec. - 23200 bytes, CRC32: FFFFFFFF. Sign: ᶛ礞

No me acuerdo de lo que hice antes de que se ralentizase, llevo mucho tiempo así
Es todo el ordenador el que está afectado, me va demasiado lento y tiene una gráfica que no está conectada, ¿puede ser la gráfica?, tendria dos graficas, pero una al parecer se desconectó desde dentro y no lo he abierto todavia para conectarla

**Comment by dragokas** [comment]
Hi,
thank you for the log.
If you need our assistance:
  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog and write what problems remained.
