### ISSUE TITLE
Accessibility pre-login startups

### ISSUE THREAD

**Issue by macxcool** [dragokas/hijackthis#84]
Enhancement:
In HKLM:\Software\Microsoft\Windows NT\Accessibility there are settings that allow things to start up during the login prompt. This might be another place to scan. It doesn't look like this is currently scanned and listed.

**Comment by dragokas** [comment]
Thank you.
This will be added to the next release.
I'll close issue for now to prevent people actively use this method by reading fresh opened issues.
