### ISSUE TITLE
Got Attacked By REHA VIRUS. Need to decrypt ALL my files.

### ISSUE THREAD

**Issue by edeekaeve** [dragokas/hijackthis#85]
[CollectionLog-2020.01.31-21.20.zip](https://github.com/dragokas/hijackthis/files/4140169/CollectionLog-2020.01.31-21.20.zip)

1. What did you done before the problem occurs: Try to activated Office software with KMSPico.
2. What programs (browsers) affected by the problem: All my files got decrypted with addition ".reha" as an file extension.
3. Steps to reproduce: After reha virus attacked my files, I scanned my laptop with various AV softwares and recovered my files with EaseUS Data Recovery Wizard, but nothing happened.

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hi,
Please attach 2-3 encrypted files along with ransom note (if you have it) zipped in your next post.

In addition:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by edeekaeve** [comment]
[encrypted_by_ reha_virus.zip](https://github.com/dragokas/hijackthis/files/4141190/encrypted_by_.reha_virus.zip)

Please help me. Thanks :)

**Comment by edeekaeve** [comment]
[log files by farbar recovery scan tool.zip](https://github.com/dragokas/hijackthis/files/4141240/log.files.by.farbar.recovery.scan.tool.zip)

**Comment by Sandor-Helper** [comment]
Unfortunately, type of ransom is "STOP (Djvu)". And this version has online ID, decryption is impossible.

We can only help in cleaning some of its steps and traces.

Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CreateRestorePoint:
HKLM\SOFTWARE\Policies\Microsoft\Windows Defender: Restriction <==== ATTENTION
GroupPolicy: Restriction ? <==== ATTENTION
2020-01-31 18:03 - 2020-01-31 18:03 - 000000000 _____ C:\Windows\system32\reha.exe
Folder: C:\Windows\Wget
Folder: C:\Windows\curl
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

**Comment by edeekaeve** [comment]
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/4145342/Fixlog.txt)

**Comment by Sandor-Helper** [comment]
You could mannually delete these folders with its contents:

> C:\Windows\Wget
> C:\Windows\curl

Change your important passwords especially for RDP.

**Comment by roussafi-omar** [comment]
the same is here i have been attacked too all my files exrypted to .reha

**Comment by dragokas** [comment]
@roussafi-omar 

Hi !
Please, don't hijack other people's threads.

If you need our assistance:
  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
