### ISSUE TITLE
Virus infection ?

### ISSUE THREAD

**Issue by sbmkvirus** [dragokas/hijackthis#86]
Hi everyone

Have a virus/malware i cant seem to find noted anywhere online.

Keyboard and mouse hijacked on start up.

caps lock goes on by itself
Mouse makes same circular movement every 5 seconds
messages typed into any text box thats on a focused window such as
"your computer has been hacked" "your history has been uploaded to facebook" among others

I can see three mouse and keyboards in device mananger - if i delete/disable two of each the system becomes stable and useable

collection log attached

thanks for any assistance

[CollectionLog-2020.02.17-13.55.zip](https://github.com/dragokas/hijackthis/files/4211630/CollectionLog-2020.02.17-13.55.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hi,

Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by sbmkvirus** [comment]
Hi
Attached log from adwcleaner as requested
[AdwCleaner[S00].txt](https://github.com/dragokas/hijackthis/files/4216691/AdwCleaner.S00.txt)

**Comment by Sandor-Helper** [comment]
1.
Run again [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) (it should be run by right-clicking **as Administrator**).
Go to Settings and switch on:
> Reset IE policies
> Reset Chrome policies

Go to Dashboard, press **Scan** and after scan ends press **Quarantine**.
System should be restarted.
After restart log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Cxx].txt** (where **x** is any digit).
Attach it to your next post here.

2.
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by sbmkvirus** [comment]
Hi

logs as requested

thanks

[FRST.txt](https://github.com/dragokas/hijackthis/files/4222185/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/4222186/Addition.txt)
[AdwCleaner[S01].txt](https://github.com/dragokas/hijackthis/files/4222194/AdwCleaner.S01.txt)
[AdwCleaner[C01].txt](https://github.com/dragokas/hijackthis/files/4222195/AdwCleaner.C01.txt)

**Comment by Sandor-Helper** [comment]
Do you still have described above problems?
If so, run system in Safe mode and check is the problem exist.

**Comment by sbmkvirus** [comment]
yes

**Comment by Sandor-Helper** [comment]
[Start your PC in safe mode in Windows 10](https://support.microsoft.com/en-us/help/12376/windows-10-start-your-pc-in-safe-mode) and check.
Tell us result.

**Comment by sbmkvirus** [comment]
i try to start in safe mode... when i get to "trouble shoot" ... pc closes down ;/

**Comment by sbmkvirus** [comment]
GOT IT INTO SAFE MODE ... NO CHANGE ... STILL THE SAME PROBLEM

**Comment by Sandor-Helper** [comment]
Is it PC or notebook?

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog and write what problems remained.
