### ISSUE TITLE
Logfile of HiJackThis

### ISSUE THREAD

**Issue by eisieisbrecher** [dragokas/hijackthis#87]
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/4277092/HiJackThis.log)

**Comment by dragokas** [comment]
Hi,
thank you for the log.
If you need our assistance:
  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog and write what problems remained.
