### ISSUE TITLE
Pc cure- I might have a malware help

### ISSUE THREAD

**Issue by Marco571** [dragokas/hijackthis#88]
Hello, I am here because I am afraid I could have a malware, these are the logs collecions from "automatic log collector" thanks in advance for the help
[CollectionLog-2020.03.09-13.48.zip](https://github.com/dragokas/hijackthis/files/4306692/CollectionLog-2020.03.09-13.48.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Marco571** [comment]
Thanks a lot, feel free to take all the time you need.

**Comment by Sandor-Helper** [comment]
Hi,
At brief look there is no malicious records in logs.
Please describe more detailed - what kind of problems you have?

**Comment by Marco571** [comment]
No problems, I just used to download a lot from the pirate bay (now I've stopped) and I was afraid I got some malware, thanks for the help

**Comment by Sandor-Helper** [comment]
You're welcome.
