### ISSUE TITLE
Unable to upload bios, stops internet connection and antivirus

### ISSUE THREAD

**Issue by wilkoszenator** [dragokas/hijackthis#91]
Welcome !
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Are you in the right place?

  * Do you need assistance in PC cure from viruses?
  * Or would you like to report a bug or propose a feature for HiJackThis?

If yes, see the next step.

### Step 2: Show us required logs (for PC cure):
I am unable to attach or paste the logs. I can open them on my laptop, but I cannot paste them anywhere (not only on this page). When I try to add them using the bar at the bottom of this window, they do not show in my folder. I attach pictures showing that the logs are there (View 2), and what I see when I try to add them (View 1). I tried to see, if I could add them to an email, but they don't show either. Is there any way this can be solved?

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

  * Describe your problem in details:
I get the message that BIOS is updating and then this pops up: C:\WINDOWS\TEMP\RarSFX7\install.vbs
System Windows cannot get access to a specific device, path or file. You may not have access rights to the element.

Note: In the message above RarSFX... numbers are different, not always 7.

I am also 
![view 1](https://user-images.githubusercontent.com/63824764/80643695-ce43c080-8a68-11ea-9933-3dbb412b9b61.JPG)
![view 2](https://user-images.githubusercontent.com/63824764/80643697-cf74ed80-8a68-11ea-8f4c-c33bd2a91042.JPG)

very often unable to browse the Internet. Even though the WI-FI is connected (I can talk via Skype), the browser I use (chrome) stops loading pages. I checked on different browsers, and it also doesn't work. When it happens, the antivirus I use, Comodo Internet Security switches off. This lasts from several seconds to several minutes. I can start browsing the Internet, but the antivirus remains off. 

1. What did you done before the problem occurs: I don't know.
2. What programs (browsers) affected by the problem: Comodo Internet Security, Chrome
3. Steps to reproduce: _________________

**Comment by dragokas** [comment]
Hi and welcome!
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,
Did you get zip file called CollectionLog? If so, attach it to your next post.

**Comment by wilkoszenator** [comment]
Thank you for your reply. 
I did get it but I am unable to attach it to the post. Dragging and dropping doesnt't work. When I try to add the file by clicking on the bottom of this window, the file does not show in its location.
I can ONLY see Collection...zip right after AutoLogger has finished working and I press the button to open the file location. I can't attach the file though. I can unzip it ant open the files inside, but I cannot attach the files or copy and paste them either.
I could take screenshots of the logs. Would that be of any use?

**Comment by Sandor-Helper** [comment]
OK, can you upload it to any cloud storage and post here download link?

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog and write what problems remained.
