### ISSUE TITLE
Ransomware. Help with Log Analysis

### ISSUE THREAD

**Issue by frakman1** [dragokas/hijackthis#93]
### Step 1: Are you in the right place?

  * I need assistance to PC cure from viruses?

### Step 2: Show us required logs (for PC cure):

  * AutoLogger log: [CollectionLog-2020.06.12-09.05.zip](https://github.com/dragokas/hijackthis/files/4770989/CollectionLog-2020.06.12-09.05.zip)

  * Describe your problem in details:

Problem occured after exposing an admin account via RDP overnight. In the morning, almost all files files are encrypted in the form `myfile.extension.id-xxxx.[openpgp@foxmail.com].pgp`. Also all files in USB attached drive and network shared drives were encrypted.

Some things still run. I can get into Safe Mode with Networking and install SpyBot, Maylware Bytes etc but they didn't help.

I already had a PGP Desktop tool which could contribute to why when I try and open some files, I get this popup:

![image](https://user-images.githubusercontent.com/5826484/84506826-e9bc0100-ac8d-11ea-8f64-f34169e0f9fe.png)

1. What did you done before the problem occurs: Admin RDP login account exposed overnight.
2. What programs (browsers) affected by the problem: All files are encrypted with .pgp extension
3. Steps to reproduce: N/A

HijackThis log: [HiJackThis.log](https://github.com/dragokas/hijackthis/files/4771020/HiJackThis.log)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.
We'll return to you as soon as possible.

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by Sandor-Helper** [comment]
Hello,

1. A couple of encrypted documents along with C:\Recovery.txt file zip in archive and attach to your next post.
2. Do you edit Hosts file mannually?

3. Uninstall Spybot - Search & Destroy as PUP.

4. Close all running programs, **temporarily** unload antivirus and other protecting software.

[Run a script in AVZ](https://github.com/dragokas/hijackthis/wiki/AVZ:-How-to-execute-script) (File - Run script):

```
begin
 ExecuteFile('net.exe', 'stop tcpip /y', 0, 15000, true);
 ClearQuarantineEx(true);
 QuarantineFile('C:\WINDOWS\System32\svhost.exe', '');
 DeleteFile('C:\WINDOWS\System32\svhost.exe', '64');
 RegKeyParamDel('HKEY_LOCAL_MACHINE', 'Software\Microsoft\Windows\CurrentVersion\Run', 'svhost.exe');
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '2201', 3);
 CreateQurantineArchive(GetAVZDirectory + 'quarantine.zip');
ExecuteSysClean;
RebootWindows(true);
end.
```

Computer will _reboot_. 



5. File **quarantine.zip** from extracted AVZ folder please send using [this form](http://dragokas.com/virusnet/) or (if archive size exceeds the 8 MB) to this mailbox: **quarantine at safezone.cc** (change _at_ to _@_) and specify your forum link in e-mail subject and password: **virus** in message body.



6. For _secondary_ diagnostics please [this version](http://tools.safezone.cc/drongo/test/AutoLogger-test.zip) and run AutoLogger again. 
Attach new CollectionLog to your post.

**Comment by frakman1** [comment]
1- Before and After Encryption:
[BeforeEncryption.zip](https://github.com/dragokas/hijackthis/files/4775144/BeforeEncryption.zip)
[AfterEncryption.zip](https://github.com/dragokas/hijackthis/files/4775146/AfterEncryption.zip)

`C:\Recovery.txt` is an empty text file

2- Yes, I edited hosts file with a few local computers on `192.168.86.x` subnet. Everything else was added by SpyBot which is a trusted anti-malware program, which I just uninstalled as per your instructions.

3- Done

4- Done.

5- After reboot, `quarantine.zip` file is an empty zip archive (size 22 bytes).

6- [CollectionLog-2020.06.13-14.56.zip](https://github.com/dragokas/hijackthis/files/4775253/CollectionLog-2020.06.13-14.56.zip)

Note that I am rebooting into Safe Mode with Networking in case there is still malware on my system.

**Do you know if there is a known decryption tool for these files yet?**

**Comment by Sandor-Helper** [comment]
It's a pity, but there is no known method for decrypt Dharma (.cezar Family). See link:
https://www.bleepingcomputer.com/forums/t/632389/dharma-ransomware-id-idemaildharmawalletarena-support-topic/

[Fix in HijackThis](https://github.com/dragokas/hijackthis/wiki/HJT:-How-to-'Fix-it'):
```
O1 - Hosts: Reset contents to default
O4 - HKCU\..\Run: [SpybotPostWindows10UpgradeReInstall] = C:\Program Files\Common Files\AV\Spybot - Search and Destroy\Test.exe  (file missing)
```

This will clear Hosts file and you can edit it again looking at Hijackthis.log if needed.

> in case there is still malware on my system

No it is not. To be sure do following in Normal mode:
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by frakman1** [comment]
[FRST.txt](https://github.com/dragokas/hijackthis/files/4776741/FRST.txt)
[Addition.txt](https://github.com/dragokas/hijackthis/files/4776742/Addition.txt)

Since the type of encryption is known, is there a tool that I can use to try and brute-force guess the private key used for encryption? I know it could take forever but at least I could try. Who knows? If it works, it could help others with the same problem.

**Comment by Sandor-Helper** [comment]
Unfortunately the encryption is very strong and there is no tool to get a key. And key is unique for every victim.
Sometimes ransomers public keys by themselves, but it happens very rarely.

Temporarily turn off any antivirus.
Highlight following code:

```
Start::
CreateRestorePoint:
GroupPolicy: Restriction ? <==== ATTENTION
Task: {0046A336-C924-46B1-9620-56F9D6319BB1} - System32\Tasks\Safer-Networking\Spybot - Search and Destroy\Check for updates => C:\Program Files (x86)\Spybot - Search & Destroy 2\SDUpdate.exe
Toolbar: HKU\S-1-5-21-4116590725-976107385-1013477746-1001 -> No Name - {47833539-D0C5-4125-9FA8-0819E2EAAC93} -  No File
AlternateDataStreams: C:\ProgramData\Reprise:wupeogjxlctlfudivq`qsp`28hfm [0]
AlternateDataStreams: C:\Users\Frak\Documents\.DS_Store:AFP_AfpInfo [122]
FirewallRules: [{C0B1EFFE-AA57-47DB-8A0A-52E26C1EE566}] => (Allow) LPort=22
Reboot:
End::
```


Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press **Fix** button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.

You have to change the password to RDP connection.

**Comment by frakman1** [comment]
Why is Port 22 (ssh) enabled and allowed in the Firewall rules?
Does that line in the script delete it from the Registry?

**Comment by frakman1** [comment]
Ever since I booted normally, i can no longer get online via a browser. I can still ping google.com from the command line though.

**Comment by Sandor-Helper** [comment]
>Program will create (Fixlog.txt). Attach it to the next post

Still waiting.

>Ever since I booted normally, i can no longer get online via a browser

In which browser?

**Comment by frakman1** [comment]
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/4781635/Fixlog.txt)
I had to boot into SafeMode with Networking to get online again.

> In which browser?


Any browser (chrome, IE, Firefox)

**Comment by dragokas** [comment]
Temporarily turn off any antivirus.
Highlight following code:

```
Start::
RestoreFromBackup: system
Reboot:
End::
```
Copy highlighted text (right click - Copy).
Run FRST (FRST64) as Administrator.
Press Fix button once and wait. Program will create (Fixlog.txt). Attach it to the next post.

PC will reboot.
Please, report if you still have a problem with internet connection from browsers in normal boot mode.

**Comment by frakman1** [comment]
There is still a problem connecting to the internet in normal boot mode. The Fixlog.txt file says:
```
RestoreFromBackup: system => Error: The restore operation should be done in the recovery mode.
```

The malware destroyed any system restore points so when I originally booted in to recovery mode and tried to restore from a backup, it couldn't find one.

**Comment by dragokas** [comment]
Please, follow this instruction:
[HJT: How to recover from system backup (ABR)](https://github.com/dragokas/hijackthis/wiki/HJT:-How-to-recover-from-system-backup-(ABR))

Note: you can find HiJackThis within AutoLogger's folder: ...\Autologger\HijackThis\HijackThis.exe

**Comment by frakman1** [comment]
Thanks. Which one? The first `Autologger` or the second `Autologger_test`?

**Comment by dragokas** [comment]
Any.

**Comment by frakman1** [comment]
I tried the most recent one `Autologger_test` and after the reboot it said "Preparing Automatic Repair" -> "Diagnosing PC" then it came up with a message saying that it failed to Repair. I then tried to boot normally, but it keeps going to the "Automatic Repair: Your PC did not start correctly". Attempts to "Restart" always return to the same page. If I then go to Advanced Options and select Safe with Networking Boot (option 5), it still does the same thing and goes back to the Automatic Repair page.

It seems the Hijack This 'restore from backup' feature broke it and is preventing the laptop from booting into Windows anymore.

**Comment by frakman1** [comment]
I also attempted the 'Fix Problems Preventing Windows From Starting Option' but it booted into the screen "Startup Repair couldn't repair your PC" Log file: `C:\WINDOWS\System32\Srt\SrtTrail.txt`

**Comment by dragokas** [comment]
Apologies for this. That's never happened before.

Try follow guide from this video: https://dragokas.com/tools/img/abr.mp4

Note:
 - each command is applied by pressing "ENTER" button.
 - notepad is required to found the right one drive letter (other than X:) where "Windows" folder is located.
 - you have to use same letter when you apply 
```
restore DRIVE:
```
command.

**Comment by frakman1** [comment]
Thank you for the video. For me, my windows drive is C. I performed the restore from the command line and it completed without errors. However, after exiting and continuing to Windows 10, I got into the same error condition:
Preparing Automatic Repair -> Diagnosing PC -> Did not start correctly

I tried to find the logfile `SrtTrail.txt` form within notepad but there was no `Srt` folder inside `c:\Windows\System32`

**Comment by dragokas** [comment]
Are you sure your windows drive is C: ?
In most cases under Recovery Environment C: drive is changed by higher letter.

**Comment by dragokas** [comment]
In recovery environment, open command prompt, run notepad.
Enter in its window:
```
RestoreFromBackup: system
RestoreFromBackup: software
```
Save this file as "fixlist.txt" and place it next to the FRST.exe file.
Run FRST.exe and press "Fix" button.
Close all windows and reboot PC.

**Comment by frakman1** [comment]
> Are you sure your windows drive is C: ?

Yes, I double checked. `X:` had the recovery environment, `C:` had Windows with all my familiar files and `D:` was a built-in recovery partition I think Lenovo makes.

I was able to run the FRST.exe `fixlist.txt` script, the logfile indicated that it completed successfully. After a reboot, I was able to boot into normal windows again. This time internet connectivity **_was working_** again via the browser.

I guess that's what that message was trying to tell me earlier:

```
RestoreFromBackup: system => Error: The restore operation should be done in the recovery mode.
```

**Comment by frakman1** [comment]
By the way, what is the difference between the first and second version of Autologger tool? `http://tools.safezone.cc/drongo/test/AutoLogger-test.zip`

**Comment by Sandor-Helper** [comment]
Second one contains very fresh versions of AVZ and HJT.

>This time internet connectivity was working again via the browser.

Can you say that system is working well now (except encrypted files of course)?

**Comment by frakman1** [comment]
Yes. One of the first things I did was to delete the newly created `admin` account that was compromised. Most likely the root ransomware files were in those folders. 

Almost all files in the computer are encrypted with the exception to the Downloads and Documents folder.

Do you recommend I reinstall windows/restore my system from scratch? Or should I just re-install apps on top of my already encrypted/installed ones one by one?

**Comment by Sandor-Helper** [comment]
>delete the newly created admin account

That's right. And do not forget to change account's and RDP passwords.

>Or should I just re-install apps

I think this is good idea.
Following script will help to close possible vulnerabilities.
Run script in AVZ while Internet is **connected**:
```
var
LogPath : string;
ScriptPath : string;

begin
 LogPath := GetAVZDirectory + 'log\avz_log.txt';
 if FileExists(LogPath) Then DeleteFile(LogPath);
 ScriptPath := GetAVZDirectory +'ScanVuln.txt';

  if DownloadFile('http://dataforce.ru/~kad/ScanVuln.txt', ScriptPath, 1) then ExecuteScript(ScriptPath) else begin
    if DownloadFile('http://dataforce.ru/~kad/ScanVuln.txt', ScriptPath, 0) then ExecuteScript(ScriptPath) else begin
       ShowMessage('It is impossible to download AVZ script for finding vulnerability!');
       exit;
      end;
  end;
 if FileExists(LogPath) Then ExecuteFile('notepad.exe', LogPath, 1, 0, false)
end.
```

After script ends and if it find vulnerabilities file avz_log.txt will be open in the Notepad and there'll be download links in it. 
First of all it depends to browsers, Java, Adobe Acrobat/Reader and Adobe Flash Player.
You should download and install needful programs if they exist in avz_log.txt

Reboot your PC.
Run script again to ensure that all vulnerabilities gone.

**Comment by frakman1** [comment]
Thank you for your support.
Cheers

**Comment by dragokas** [comment]
To help improve our tools please make a log of Windows updates list:

In Search field of Start menu enter:
```
cmd
```
right mouse click on it => Run as Administrator
input in cmd console (or copy & paste):
```
wmic qfe list > %UserProfile%\desktop\upd.txt
```
press ENTER. 

Attach to your next post a file upd.txt from Desktop.
