### ISSUE TITLE
Unwanted and automatic key operation

### ISSUE THREAD

**Issue by Vanishhh** [dragokas/hijackthis#97]
For a long time, my computer began to behave strangely, namely: how it performs a certain action, e.g. writing a message on Facebook, keyboard keys do not work as they should, writing a message immediately returns me to the beginning of the message or I cannot use the "C" or " H "and sometimes throws me straight to the desktop or blocks me by the letter" L "to the login screen.

I enclose Logg with HiJackThis for optional help in the problem.

Running processes:
Number | Path
   1  C:\Program Files (x86)\ASUS\ASUS Smart Gesture\AsTPCenter\x64\AsusTPCenter.exe
   1  C:\Program Files (x86)\ASUS\ASUS Smart Gesture\AsTPCenter\x64\AsusTPHelper.exe
   1  C:\Program Files (x86)\ASUS\ASUS Smart Gesture\AsTPCenter\x64\AsusTPLoader.exe
   1  C:\Program Files (x86)\AVG\Antivirus\AVGSvc.exe
   5  C:\Program Files (x86)\AVG\Antivirus\AVGUI.exe
   1  C:\Program Files (x86)\AVG\Antivirus\afwServ.exe
   1  C:\Program Files (x86)\AVG\Antivirus\aswEngSrv.exe
   1  C:\Program Files (x86)\AVG\Antivirus\aswidsagent.exe
   1  C:\Program Files (x86)\AVG\Antivirus\wsc_proxy.exe
   1  C:\Program Files (x86)\Common Files\Adobe\ARM\1.0\armsvc.exe
  25  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
   1  C:\Program Files (x86)\Google\Update\1.3.35.452\GoogleCrashHandler.exe
   1  C:\Program Files (x86)\Google\Update\1.3.35.452\GoogleCrashHandler64.exe
   3  C:\Program Files\AMD\CNext\CNext\RadeonSettings.exe
   1  C:\Program Files\AMD\Performance Profile Client\AUEPLauncher.exe
   1  C:\Program Files\AMD\Performance Profile Client\AUEPMaster.exe
   1  C:\Program Files\AMD\Performance Profile Client\AUEPUF.exe
   1  C:\Program Files\AVG\TuneUp\TuneupSvc.exe
   1  C:\Program Files\Focusrite\Focusrite Control\Server\ControlServer.exe
   1  C:\Program Files\Microsoft Mouse and Keyboard Center\MKCHelper.exe
   1  C:\Program Files\Microsoft Mouse and Keyboard Center\ipoint.exe
   1  C:\Program Files\Microsoft Mouse and Keyboard Center\itype.exe
   2  C:\Program Files\Realtek\Audio\HDA\RAVBg64.exe
   1  C:\Program Files\Realtek\Audio\HDA\RAVCpl64.exe
   1  C:\Program Files\rempl\sedsvc.exe
   1  C:\Users\DjOptimus\Desktop\HiJackThis.exe
   1  C:\Windows\ImmersiveControlPanel\SystemSettings.exe
   1  C:\Windows\System32\ApplicationFrameHost.exe
   1  C:\Windows\System32\DriverStore\FileRepository\c0342855.inf_amd64_e2ef814e68f7dc8c\B342717\atieclxx.exe
   1  C:\Windows\System32\DriverStore\FileRepository\c0342855.inf_amd64_e2ef814e68f7dc8c\B342717\atiesrxx.exe
   2  C:\Windows\System32\RuntimeBroker.exe
   1  C:\Windows\System32\SystemSettingsBroker.exe
   1  C:\Windows\System32\audiodg.exe
   1  C:\Windows\System32\conhost.exe
   2  C:\Windows\System32\csrss.exe
   1  C:\Windows\System32\ctfmon.exe
   1  C:\Windows\System32\dasHost.exe
   1  C:\Windows\System32\dllhost.exe
   1  C:\Windows\System32\dwm.exe
   2  C:\Windows\System32\fontdrvhost.exe
   1  C:\Windows\System32\lsass.exe
   1  C:\Windows\System32\schtasks.exe
   1  C:\Windows\System32\services.exe
   1  C:\Windows\System32\sihost.exe
   1  C:\Windows\System32\smss.exe
   1  C:\Windows\System32\spoolsv.exe
  56  C:\Windows\System32\svchost.exe
   1  C:\Windows\System32\taskhostw.exe
   1  C:\Windows\System32\wbem\WmiPrvSE.exe
   1  C:\Windows\System32\wbem\unsecapp.exe
   1  C:\Windows\System32\wininit.exe
   1  C:\Windows\System32\winlogon.exe
   1  C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe
   1  C:\Windows\explorer.exe
   1  D:\02.Programy\DAEMON Tools Pro\DTShellHlp.exe
   1  D:\02.Programy\DAEMON Tools Pro\DiscSoftBusService.exe
   1  D:\League of Legends\LeagueClient.exe
   1  D:\League of Legends\LeagueClientUx.exe
   2  D:\League of Legends\LeagueClientUxRender.exe
   1  D:\League of Legends\LeagueCrashHandler.exe
   1  D:\Riot Games\Riot Client\RiotClientCrashHandler.exe
   1  D:\Riot Games\Riot Client\RiotClientServices.exe

O1 - Hosts: 127.0.0.1 live.virtualdj.com
O4 - HKCU\..\Run: [CCleaner Smart Cleaning] = C:\Program Files\CCleaner\CCleaner64.exe /MONITOR
O4 - HKCU\..\StartupApproved\Run: [AceStream] = C:\Users\DjOptimus\AppData\Roaming\ACEStream\engine\ace_engine.exe (2019/11/09)
O4 - HKCU\..\StartupApproved\Run: [DAEMON Tools Pro Agent] = D:\02.Programy\DAEMON Tools Pro\DTAgent.exe -autorun (2018/06/22)
O4 - HKCU\..\StartupApproved\Run: [Discord] = C:\Users\DjOptimus\AppData\Local\Discord\app-0.0.306\Discord.exe (2019/11/09)
O4 - HKCU\..\StartupApproved\Run: [Steam] = C:\Program Files (x86)\Steam\steam.exe -silent (2019/11/11)
O4 - HKCU\..\StartupApproved\Run: [TSMApplication] = D:\World of warcraft Global\World of Warcraft\Interface\TradeSkillMaster Application\app\TSMApplication.exe (2019/11/09)
O4 - HKLM\..\Run: [AVGUI.exe] = C:\Program Files (x86)\AVG\Antivirus\AvLaunch.exe /gui
O4 - HKLM\..\Run: [TuneupUI.exe] = C:\Program Files\AVG\TuneUp\TuneupUI.exe /nogui
O4 - HKLM\..\Session Manager: [BootExecute] = C:\Windows\system32\icarus_rvrt.exe
O4 - HKLM\..\StartupApproved\Run32: [GrooveMonitor] = C:\Program Files (x86)\Microsoft Office\Office12\GrooveMonitor.exe (2018/05/25)
O4 - HKLM\..\StartupApproved\Run32: [XboxStat] = C:\Program Files (x86)\Microsoft Xbox 360 Accessories\XboxStat.exe silentrun (2019/08/16)
O4 - HKU\.DEFAULT\..\Run: [CCleaner Smart Cleaning] = C:\Program Files\CCleaner\CCleaner64.exe /MONITOR
O8 - Context menu item: HKCU\..\Internet Explorer\MenuExt\Add to Google Photos Screensa&ver: (default) = C:\Windows\system32\GPhotos.scr (file missing)
O8 - Context menu item: HKU\S-1-5-19\..\Internet Explorer\MenuExt\Add to Google Photos Screensa&ver: (default) = C:\Windows\system32\GPhotos.scr (file missing)
O8 - Context menu item: HKU\S-1-5-20\..\Internet Explorer\MenuExt\Add to Google Photos Screensa&ver: (default) = C:\Windows\system32\GPhotos.scr (file missing)
O17 - DHCP DNS 1: 192.168.1.1
O21 - HKLM\..\ShellIconOverlayIdentifiers\00avg: (no name) - {472083B0-C522-11CF-8763-00608CC02F24} - (no file)
O21-32 - HKLM\..\ShellExecuteHooks: [{B5A7F190-DDA6-4420-B3BA-52453494E6CD}] - Groove GFS Stub Execution Hook - C:\Program Files (x86)\Microsoft Office\Office12\GrooveShellExtensions.dll (disabled)
O21-32 - HKLM\..\ShellIconOverlayIdentifiers\Groove Explorer Icon Overlay 1 (GFS Unread Stub): Groove Explorer Icon Overlay 1 (GFS Unread Stub) - {99FD978C-D287-4F50-827F-B2C658EDA8E7} - C:\Program Files (x86)\Microsoft Office\Office12\GrooveShellExtensions.dll
O21-32 - HKLM\..\ShellIconOverlayIdentifiers\Groove Explorer Icon Overlay 2 (GFS Stub): Groove Explorer Icon Overlay 2 (GFS Stub) - {AB5C5600-7E6E-4B06-9197-9ECEF74D31CC} - C:\Program Files (x86)\Microsoft Office\Office12\GrooveShellExtensions.dll
O21-32 - HKLM\..\ShellIconOverlayIdentifiers\Groove Explorer Icon Overlay 2.5 (GFS Unread Folder): Groove Explorer Icon Overlay 2.5 (GFS Unread Folder) - {920E6DB1-9907-4370-B3A0-BAFC03D81399} - C:\Program Files (x86)\Microsoft Office\Office12\GrooveShellExtensions.dll
O21-32 - HKLM\..\ShellIconOverlayIdentifiers\Groove Explorer Icon Overlay 3 (GFS Folder): Groove Explorer Icon Overlay 3 (GFS Folder) - {16F3DD56-1AF5-4347-846D-7C10C4192619} - C:\Program Files (x86)\Microsoft Office\Office12\GrooveShellExtensions.dll
O21-32 - HKLM\..\ShellIconOverlayIdentifiers\Groove Explorer Icon Overlay 4 (GFS Unread Mark): Groove Explorer Icon Overlay 4 (GFS Unread Mark) - {2916C86E-86A6-43FE-8112-43ABE6BF8DCC} - C:\Program Files (x86)\Microsoft Office\Office12\GrooveShellExtensions.dll
O23 - Service R2: AMD External Events Utility - C:\Windows\System32\DriverStore\FileRepository\c0342855.inf_amd64_e2ef814e68f7dc8c\B342717\atiesrxx.exe
O23 - Service R2: AMD User Experience Program Launcher - (AUEPLauncher) - C:\Program Files\AMD\Performance Profile Client\AUEPLauncher.exe
O23 - Service R2: AVG Antivirus - C:\Program Files (x86)\AVG\Antivirus\AVGSvc.exe /runassvc
O23 - Service R2: AVG Firewall Service - (AVG Firewall) - C:\Program Files (x86)\AVG\Antivirus\afwServ.exe
O23 - Service R2: AVG TuneUp - (CleanupPSvc) - C:\Program Files\AVG\TuneUp\TuneupSvc.exe
O23 - Service R2: Adobe Acrobat Update Service - (AdobeARMservice) - C:\Program Files (x86)\Common Files\Adobe\ARM\1.0\armsvc.exe
O23 - Service R2: AvgWscReporter - C:\Program Files (x86)\AVG\Antivirus\wsc_proxy.exe /runassvc /rpcserver
O23 - Service R2: Focusrite Control Server - C:\Program Files\Focusrite\Focusrite Control\Server\ControlServer.exe service
O23 - Service R2: Windows Remediation Service - (sedsvc) - C:\Program Files\rempl\sedsvc.exe
O23 - Service R3: Disc Soft Bus Service - D:\02.Programy\DAEMON Tools Pro\DiscSoftBusService.exe
O23 - Service R3: avgbIDSAgent - C:\Program Files (x86)\AVG\Antivirus\aswidsagent.exe
O23 - Service S2: Origin Web Helper Service - D:\02.Programy\Origin\OriginWebHelperService.exe
O23 - Service S2: Usługa Google Update (gupdate) - (gupdate) - C:\Program Files (x86)\Google\Update\GoogleUpdate.exe /svc
O23 - Service S3: BattlEye Service - (BEService) - C:\Program Files (x86)\Common Files\BattlEye\BEService.exe
O23 - Service S3: EasyAntiCheat - C:\Program Files (x86)\EasyAntiCheat\EasyAntiCheat.exe
O23 - Service S3: Google Chrome Elevation Service - (GoogleChromeElevationService) - C:\Program Files (x86)\Google\Chrome\Application\83.0.4103.116\elevation_service.exe
O23 - Service S3: Microsoft Office Diagnostics Service - (odserv) - C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE12\ODSERV.EXE
O23 - Service S3: Microsoft Office Groove Audit Service - C:\Program Files (x86)\Microsoft Office\Office12\GrooveAuditService.exe
O23 - Service S3: Origin Client Service - D:\02.Programy\Origin\OriginClientService.exe
O23 - Service S3: Steam Client Service - C:\Program Files (x86)\Common Files\Steam\SteamService.exe /RunAsService
O23 - Service S3: Uncheater for BattleGroundsLite_SE - (uncheater_bgl) - C:\Program Files\Common Files\Uncheater\uncheater_bgl.exe
O23 - Service S3: Usługa Google Update (gupdatem) - (gupdatem) - C:\Program Files (x86)\Google\Update\GoogleUpdate.exe /medsvc

--
End of file - Time spent: 29,9 sec. - 20470 bytes, CRC32: FFFFFFFF. Sign: 브

**Comment by dragokas** [comment]
Hi,
thank you for the log.
If you need our assistance:
  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648)

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond in PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge at our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave a feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute tha last steps, requested by helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog and write what problems remained.
