### ISSUE TITLE
Slow system.

### ISSUE THREAD

**Issue by qzx61** [dragokas/hijackthis#98]
Hello!

I have a problem with lagging system. Music-creation program works fine, but browser (Opera) and system generally definitely suffers because of some issue. I don't know what couse this.

I will attach log from HijackThisFork and AVZ.

If something is wrong - sorry.
If anyone help - thanks!
[CollectionLog-2020.07.17-05.39.zip](https://github.com/dragokas/hijackthis/files/4935634/CollectionLog-2020.07.17-05.39.zip)
[HijackThis log.log](https://github.com/dragokas/hijackthis/files/4935635/HijackThis.log.log)

**Comment by Sandor-Helper** [comment]
Hello,

Too many antiviruses :)
You have to leave one (I suggest it'll be Avast Free Antivirus) and unistall others:

> adaware antivirus
> AdAwareInstaller
> AdAwareUpdater
> AntimalwareEngine
> McAfee WebAdvisor

Please also uninstall PUP programs via Parameters - Programs:

> Chromium
> Web Companion

Next:
Download [AdwCleaner (by Malwarebytes)](https://toolslib.net/downloads/viewdownload/1-adwcleaner/) and save it to **Desktop**.
Run (it should be run by right-clicking **as Administrator**), press **"Scan"** and wait.
At the end of the scan log will be found at: 
**C:\AdwCleaner\Logs\AdwCleaner[Sxx].txt** (where **x** is any digit).
Attach it to your next post here.

**Comment by qzx61** [comment]
thanks, I will proceed and write after changes

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog, and write what problems remained.
