### ISSUE TITLE
checksums of some binaries indicated infection from virustotal, which led me to hijackthis by way of PortableApps

### ISSUE THREAD

**Issue by ScientificMethodist** [dragokas/hijackthis#99]
Welcome!
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Are you in the right place?

  * Do you need assistance in PC cure from viruses?
  * Or would you like to report a bug or propose a feature for HiJackThis?

If yes, see the next step.

### Step 2: Show us the required logs (for PC cure):
[CollectionLog-2020.07.25-20.59.zip](https://github.com/dragokas/hijackthis/files/4974889/CollectionLog-2020.07.25-20.59.zip)
[report2.log](https://github.com/dragokas/hijackthis/files/4974890/report2.log)

  * Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)

  * Attach 'Collection-[Date].zip' log created by [AutoLogger](http://tools.safezone.cc/drongo/test/AutoLogger-test.zip)

  * Describe your problem in details:

1. What did you done before the problem occurs: _I ran a few unsigned binaries.
2. What programs (browsers) affected by the problem: None as far as I can tell.HiJackThis quarentined MANY files before I got a newer version. I should post the logs from that initial run, perhaps. 
3. Steps to reproduce: VLC was so slow that it couldn't play movies.  So I took a peak with ProcessExplorer64, and Task Manager- and found a bunch of new services. I unplugged my USB media and came here as a result. Thank you for helping me!  =)

**Comment by Sandor-Helper** [comment]
Hello and welcome,

Close all running programs, **temporarily** unload antivirus and other protecting software.

[Run a script in AVZ](https://github.com/dragokas/hijackthis/wiki/AVZ:-How-to-execute-script) (File - Run script):

```
begin
 DeleteSchedulerTask('Microsoft\Windows\SMB\UninstallSMB1ClientTask');
 DeleteSchedulerTask('Microsoft\Windows\SMB\UninstallSMB1ServerTask');
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1001', 1);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1004', 3);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1201', 3);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '1804', 1);
 RegKeyIntParamWrite('HKCU', 'Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\', '2201', 3);
 ExecuteRepair(13);
RebootWindows(false);
end.
```

Computer will _reboot_. 



For _secondary_ diagnostics please run AutoLogger again. 
Attach new CollectionLog to your post.

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download?version=648), prepare new CollectionLog, and write what problems remained.
